### ISSUE TITLE
Brainstorming: Looking at Repetition Patterns

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#101]
I am going through the process of adding a new event.

User clicks the Add Event.
User fills in various information, and then wants to add another event associated with the current event.
Selects to use "Repetition Pattern" 

Activates the "Repetition Pattern" example adds Daily, weekdays only until 2021-07-31

Publishes.

Goes to events page. Opens one of the events. Sees this:

Scheduled dates for this event

![Screen Shot 2021-07-16 at 16 48 36](https://user-images.githubusercontent.com/5323259/125966593-d5ef5faa-d109-4183-bd62-fe494b27ed44.png)

"Editing a single date of an event changes only that date. Editing the root event changes all events in the series."

These are associated to the Repetition Pattern seen below which lists the current pattern.

![Screen Shot 2021-07-16 at 16 52 18](https://user-images.githubusercontent.com/5323259/125966983-af1bbfc0-6ad2-44de-bdd0-0dfe107e44e0.png)

Entering any of these repeated dates will likely show the "Repetition Pattern" as seen above. I assume that changing the "Repetition Pattern" in any of these dates will also change all the other dates.
---> In a repeated date there is a root date. It is not clear which is the root date. The root date should stand out more compared to the other dates. All "child" events/dates not the "parent" root date should perhaps not have the Repetition Pattern area available? As the Repetition Pattern should only be changed in the root date/event.

Clicking "Edit" button for any of these dates will likely go to the event. If one changes the date then it goes from being a Pattern to an occurrence.

I am starting to think about the "parent" (top container) and the "child/inner blocks" inside Gutenberg.
As the original event should likely have more options compared to scheduled dates.
I am finding this somewhat complex as this can touch upon how events are seen in the Events page. Having a kind of hierarchy similar to Pages in WordPress. Where there is a parent and there are sub pages.

![Screen Shot 2021-07-16 at 17 02 10](https://user-images.githubusercontent.com/5323259/125968339-d112bcbe-4fc1-4b9e-a0d8-febdf2ece32b.png)

I will think more about this later on.

**Comment by joedolson** [comment]
FYI, this has been redesigned. Some points of clarification:

- Repetition settings can't be changed & aren't visible when editing a single event date.
- It's not a root 'date', it's the root 'event'. None of the dates are the root event; but I can definitely add a link to the root event when editing a specific date. 
- If you edit a specific instance, it splits the parent event into different sets of recurring events. So those relationships aren't necessarily permanent.
- There can be hundreds or thousands of individual dates for any event, so displaying them in the main event navigation is not advisable.

**Comment by joedolson** [comment]
I should clarify - if you edit the content of a specific date, it splits the parent event. You can change the date and time of an instance without splitting the parent.

**Comment by joedolson** [comment]
Relevant changes: https://github.com/joedolson/my-calendar/commit/07aaf96c228d4579a95717afaeb2f6a4b24b6556, https://github.com/joedolson/my-calendar/commit/82a191985a6015ce01247598e221baa5e6c224bf

**Comment by joedolson** [comment]
I think that I've addressed most of the issues in this issue that aren't already represented in other issues, so I'm closing this out. Feel free to break anything remaining out into a new issue if I've overlooked it.
