### ISSUE TITLE
Events page: Archiving events does not update the Published/Drafts text number links

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#103]
In the My Events page.
I clicked "Check all" and Archived all of the events as I wanted to start over with a fresh Events screen.

As the 33 events that were published and 4 events that were in draft were moved to Archived. It should now just say Published and Drafts without a number beside it.
Below it still says Published (33) and Drafts (4).

Archiving should remove the numbers beside Published and Drafts. As the number is duplicated in the Archived page.

![Screen Shot 2021-07-18 at 11 03 40](https://user-images.githubusercontent.com/5323259/126061774-354801c4-7b26-4cdb-bc07-76c0e55a5ae8.png)

This becomes confusing when having an event in the Events page. Seeing that there are now 34 Published events and just 1 is seen in the Published screen.

![Screen Shot 2021-07-18 at 11 17 06](https://user-images.githubusercontent.com/5323259/126062032-f36906af-e7fe-499d-adf7-c6b12e33c9a2.png)

**Comment by joedolson** [comment]
There's some kind of bug in this, for sure. I think it's a cache busting problem. Will explore.

**Comment by joedolson** [comment]
Although this is *not* the bug. The issue here is that 'archived' is not exclusive of being published. An archived event is still published; it's just removed from those views. But this has created quite a few problems. I do, however, need a method for moving old events out of the main list without removing them from the calendar. If you have any ideas for a better UX for that, I'm glad to hear it.

**Comment by paaljoachim** [comment]
Archive is the place where one moves any event out of the Published and Drafts flow. As these events should be moved and not duplicated into the archive page. It should not affect the frontend, as the "Archived" page is just meant for the backend, as I understand it. (I have a feeling there is something I am not fully understanding from your comment.)

I see there is also an All text link. I believe the All text link can be removed. All seems to show what is in the Published, Drafts and Trash pages.

**Comment by joedolson** [comment]
After thinking this over, as much as it's *technically* true that archived events are also published, when it comes to filtering events, that's flat out confusing. So I'm changing the counts so that published only gives the events that are published and *not* archived.

**Comment by paaljoachim** [comment]
Going through what it looks like after the change.

![Screen Shot 2021-07-31 at 13 56 41](https://user-images.githubusercontent.com/5323259/127739148-ea42800f-f55c-4784-b027-ffb6d7d4c7b8.jpg)


What we see from the above screenshot.
Published 3.
Drafts 1.
Trash 1.
Archived 7.
All shows no number as it should show what is located in all the screens.

Shows what has been published, trashed and drafts. It does not show Archived events.
I will add a new issue for archived events not showing in the All screen.
