### ISSUE TITLE
My Events page: Remove bottom "View Archived Events" (?) text link

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#104]
At the bottom of the My Events page is a link: "View Archived Events" which is the same as "Archived" link just above it.
I am wondering why it is there. As it creates a duplication of the Archived link.

Can/should it be removed?
"View Archived Events" text link is not seen on the top, only the bottom of the My Events page.

![Screen Shot 2021-07-18 at 11 36 51](https://user-images.githubusercontent.com/5323259/126062483-cd4c06c1-8549-4622-8f4c-fd24ac50bf5e.png)

**Comment by joedolson** [comment]
Pretty sure that's just leftover from before I implemented the event status navigation bar. So, yeah, definitely remove.
