### ISSUE TITLE
My Events page: Move buttons into a Bulk actions drop down

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#105]
Regarding the buttons:
Delete events
Trash events
Publish events
Archive events.

![Manage-Events](https://user-images.githubusercontent.com/5323259/126064178-0231d841-57e9-4eb1-be2d-7335cbd4d193.jpg)

What about moving these into a bulk select drop down similar to All Pages or All Posts screen in WordPress?

![Screen Shot 2021-07-18 at 12 03 10](https://user-images.githubusercontent.com/5323259/126063258-d5a3f917-0860-44a4-9a5c-f29f3308fb79.png)

![Screen Shot 2021-07-18 at 12 03 30](https://user-images.githubusercontent.com/5323259/126063183-4c1c101e-9ab8-4d7c-b2ab-2e98bc05fbdb.png)

It could look something like this:
![My-Events-with-Bulk-actions-drop-down](https://user-images.githubusercontent.com/5323259/126064344-6d44554a-61c1-41d6-8bca-c19422d14129.jpg)

**Comment by joedolson** [comment]
Closed in https://github.com/joedolson/my-calendar/commit/74428baa293c86885cecddfc4980f7b5a27c2113

**Comment by paaljoachim** [comment]
Great! I am testing out the drop down to see that each selection works.

**Comment by paaljoachim** [comment]
This is what the Bulk actions drop down looks like in the Events screen. (I do so for most closed issues so that we can see the adjustment that was made.)
![Screenshot 2021-09-11 at 17 32 11](https://user-images.githubusercontent.com/5323259/132953145-59238350-1e59-4b8a-a615-4756e065ff56.jpg)
