### ISSUE TITLE
Event Groups: Manage Events title seen in the sidebar. (Bug)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#107]
I clicked the Event Groups tab and happen to notice this:

![My-Calendar-Event-Groups](https://user-images.githubusercontent.com/5323259/126064810-9ab26dfb-1423-4444-877e-0b6c09ee507b.jpg)

(Check the right sidebar area. Notice the Manage Events title etc.)

**Comment by paaljoachim** [comment]
Additionally below the Create/Modify Groups is the My Events section.
Identical My Events as seen in the My Events tab.

This should be removed. It will then also fix the above problem.
![Screen Shot 2021-07-18 at 13 07 56](https://user-images.githubusercontent.com/5323259/126064876-be0227b8-3e77-4fef-a685-77279008772f.png)

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar/commit/1d09325e2996bc93d76f1301b6bbb7a8b02b1c7f
