### ISSUE TITLE
Print search results

### ISSUE THREAD

**Issue by joseffallman** [joedolson/my-calendar#11]
Hi.
I'm thinking of a future to make it easy to print search results. I want them to be on calender default print page.

I have done this before, by saving the return from "mc_get_search_results( $search );" i $_session and make my_calendar() to use that if the variable $_GET['searched'] is set.

I could make a pr with that approach but i don't know if its a good way to solve it or if only events id should be saved in the session or as a cookie and reload them when from db when rendering printpage.
One advantage of that would be that it could be easy to implement a select function so you could select which event you want to print. 

What do you think?

**Comment by joedolson** [comment]
It doesn't seem like the best possible choice to me; I'm not thrilled with the idea of using the global session variables to hold that.  Might be workable, though.

It has the downside that it prevents having a separate print and view template, but I don't think that's a serious issue. 

It has the plus that it doesn't require any re-rendering or new DB fetches. 

Go ahead and do a PR to start on this; I can always roll it back if needed. I won't approve the PR until after my next release, however, as I have a release I need to do in the next couple days.

**Comment by joedolson** [comment]
This is now merged and updated. I've modified the print view CSS so that the event details in search views are better. I also changed the session key to disambiguate for other plugins. Still need to update the headings in the print view so that they show the search results info instead of the period originally intended for display.

**Comment by joedolson** [comment]
I'm closing this issue with the merge.
