### ISSUE TITLE
Scheduled dates for this event shows time and dates differently.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#112]
An example is that I set the start time at 15:00.

Scheduled dates for this event shows it at 3:00 pm.

In the following example shows time and dates differently.
It would be good to keep a similar time and date as is used in the above Date and Time area.

![Screen Shot 2021-07-19 at 12 37 29](https://user-images.githubusercontent.com/5323259/126147744-455def40-b3fa-4693-8e24-0fdd50928b1b.png)

I assume that it shows a default time and date method and not what the user has selected for their WordPress site.

**Comment by joedolson** [comment]
The time shown in the scheduled dates is configured in settings; it's the time format setting. The time shown in the input field is provided by the browser. I'm going to consider this a wontfix. I could do some kind of detection of the user's language setting, identify the date format for that language, and insert a format based on that, but from a practical stand point I don't think it's worth it.
