### ISSUE TITLE
Removing Template from the top menu items in Edit event (?)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#115]
Looking at the top menu:
Delete - View - Template - Manage events - Update - Publish

![Screen Shot 2021-07-19 at 14 24 34](https://user-images.githubusercontent.com/5323259/126159637-85edc373-2c03-4ecf-811a-86adee588554.png)

What is the reasoning for having the Template link here? Can we remove it? As the user can go to the Template Editor and find the needed information. 

Something like this:
![Edit-Event-top-menu-items-removing-template](https://user-images.githubusercontent.com/5323259/126160241-a13b23a0-9e87-467f-93d6-635613c12d8a.jpg)

**Comment by joedolson** [comment]
Yeah, I've been fuzzy about that, too. The template link does show what the template shows for *this* event, as opposed to generic data on the template editor screen. But I have doubts that it's a very useful link, definitely. It may be that I still want to provide the link, but maybe not in such a prominent location.

**Comment by paaljoachim** [comment]
What about adding a Template section below the Event Location that shows a kind of most used Template information? For additional information the user clicks a link which takes one over to the Template tags area.

**Comment by joedolson** [comment]
Hmm. And if I loaded it in an iframe, I could also pull in front-end styles for it, which might be helpful.

**Comment by paaljoachim** [comment]
That sounds really helpful!
