### ISSUE TITLE
Deleting a single create occurrence form -bug-

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#116]
I noticed when clicking "Add another occurrence" and then changing my mind, and clicking Delete that this happened:

https://user-images.githubusercontent.com/5323259/126164223-827e7de6-563e-4df6-a52f-2655bc5e68f2.mp4

Deleting the occurrence should remove it so it goes back to what it looked like before clicking the "Add another occurrence" accordion. There should not be a restore option as it is easy to fill out time and date if one made an error deleting an occurrence.

**Comment by joedolson** [comment]
Honestly, I think that this would be a rarely used feature. The most probably case I imagine would be somebody adds a dozen or more dates, then realizes they want to remove one that's incorrect. I added the restore option just as protection against removing the wrong instance, to make it easy to put back.

Might want to have a second click option to remove completely, though. I'll think about it.

**Comment by paaljoachim** [comment]
Great! 
There is now added an option to "Restore" or "Remove".
That is helpful if the user changes one mind and decides not to use Occurrences.

![Screen Shot 2021-07-25 at 01 22 47](https://user-images.githubusercontent.com/5323259/126883190-8ebd8f59-d856-4db4-944b-c0497754fa91.png)
