### ISSUE TITLE
Help text for "Add another occurrence" and "Repetition Pattern"

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#117]
Before the user clicks the "Add another occurrence" or "Repetition Pattern" it would be helpful to explain what it is.

![Screen Shot 2021-07-19 at 15 11 35](https://user-images.githubusercontent.com/5323259/126165733-5111b1b9-a6c5-4a1a-8b11-1bf4bafc63c9.png)

Perhaps having a tooltip a user can click or hover over. I added the help text directly to each area. It does not look that great, but I believe it would be helpful to clearly explain the difference between the two.

![Occurrences-Repetition-Pattern-help-text](https://user-images.githubusercontent.com/5323259/126166776-d63f3baa-823e-4885-b636-957bc985c74d.jpg)

Included a tooltip

![Occurrences-Repetition-Pattern-tool-tip](https://user-images.githubusercontent.com/5323259/126167073-43381574-7a40-45f8-bd98-c4ddf4bc1030.jpg)

**Comment by joedolson** [comment]
I'll think about this. Adding a simple disclosure widget for text isn't too much to do, although I'll need to avoid over-using it, if I want to avoid adding too much translator burden.

**Comment by paaljoachim** [comment]
This is actually the first place I have found a need to add some additional context. To explain the difference between Add another occurrence and repetition pattern.

**Comment by joedolson** [comment]
Calling this closed. There are details to work out for individual help modals, but the overall feature is implemented.
