### ISSUE TITLE
Events -> Event Groups: seeing events here but not in any other location.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#118]
---> This needs retesting to figure out what happened. 

I deleted a bunch of events or so I thought.
I believe I trashed them and then emptied the trash.

Going to Event Groups. I could see a lot of events that I had earlier trashed.

Example:
![Screen Shot 2021-07-19 at 20 22 02](https://user-images.githubusercontent.com/5323259/126208372-21d79618-a211-4805-87eb-ae94b4b94deb.png)

Summer rain many events. Dates: July 31, August 6, August 13, August 20.

Frontend calendar:
![Screen Shot 2021-07-19 at 20 22 58](https://user-images.githubusercontent.com/5323259/126208499-b1c27ab5-a828-42d4-ae89-e172561ace8c.png)

A weird one here. Which I need to track down.

**Comment by joedolson** [comment]
In https://github.com/joedolson/my-calendar/commit/aefc7375235e5cda6b61d8485d6879b5c31fca02, I've just changed the default event list for event groups to exclude trashed events. However, this seems like it's more than just that issue, so I'm leaving it open for now.

**Comment by paaljoachim** [comment]
This comment is associated: 
https://github.com/joedolson/my-calendar/issues/121#issuecomment-882895283

**Comment by joedolson** [comment]
See also commit references on #121

**Comment by joedolson** [comment]
Closing this. I think the essential issue is resolved, and we should watch for any oddities with events showing up in odd places in the future.
