### ISSUE TITLE
Event Groups: Not able to select all events 

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#121]
The Manage Event Groups page is missing the Check all (checkbox). This means I am not able to select all the events listed in this screen, but have to select one event at a time to delete it.

Manage Events Groups screen

![Manage-Event-Groups-screen](https://user-images.githubusercontent.com/5323259/126224270-129c945c-46a6-40fc-b21c-ebefb2d60840.jpg)

Manage Events screen

![Screen Shot 2021-07-19 at 22 41 27](https://user-images.githubusercontent.com/5323259/126224548-4464e624-33d6-4234-9eb2-fbf68e6254ee.png)

Btw
Here it would also be helpful to trash any event by having a trash button etc.

**Comment by joedolson** [comment]
But you can delete the events from the Manage Events screen. Why would you also need to do that here?

**Comment by paaljoachim** [comment]
This is a zoomed out view.
I assume that My Events is supposed to show all the events (also grouped events). There is a glitch here so that I am getting many more events in the Manage Event Groups screen compared to what I see in the My Events screen.

Because this is what my Mange Events screen looks like:

![Screen Shot 2021-07-20 at 00 02 57](https://user-images.githubusercontent.com/5323259/126233387-161cb4dc-0cf6-42c5-b4dd-31ddac1e21a5.png)


This is what the Event Groups screen looks like:

![Event-Groups-many-events](https://user-images.githubusercontent.com/5323259/126233684-949b1290-2b3e-4119-815b-3fc92adbc44c.jpg)

I assume that I can go to Settings and click to remove all plugin data and then delete the plugin. Then upload the plugin again. So that it clears out the Event Groups screen.

**Comment by joedolson** [comment]
Are those events trashed or archived? If neither, let me know what you can about them. 

Grouped events is only supposed to be for managing event groups, and not so much about managing the events themselves except where editing the shared event fields. I definitely do not want to duplicate any functionality in the grouped events interface that isn't absolutely necessary.

**Comment by paaljoachim** [comment]
Here is a video:

https://user-images.githubusercontent.com/5323259/126235012-d1023435-0268-4c4f-89d8-29ecf30cf5c7.mp4

**Comment by joedolson** [comment]
Hmm. That's definitely a little odd. Seems like they may be invalidated events due to a partial deletion (the date information deleted, but not the core event?)

Will have to try and figure out how those were created; it's definitely a bug that will need exploring, but probably better to do a reset at this point, then start over, specifically trying to pay attention to whether this is happening. I'll also try and recreate it in my own dev.

**Comment by paaljoachim** [comment]
I went to the Published page.
Trashed one of the published events.
Went to The Trash screen and noticed this:

![Screen Shot 2021-07-24 at 12 28 45](https://user-images.githubusercontent.com/5323259/126865709-dbfea853-b5a9-4076-a236-98e7ca2e62a4.png)


https://user-images.githubusercontent.com/5323259/126865778-c4c6fad9-3e57-4765-9f3d-2761060d096b.mp4


I uninstalled the plugin (I noticed I also have the pro version installed).


https://user-images.githubusercontent.com/5323259/126865970-48b5a87e-3b5d-484b-a0e0-9e2aa4e94cc4.mp4


I downloaded the newest plugin version from this repo. Took out the Src and made that into the plugin. Uploaded but noticed that the same numbers were seen, but this time no events where seen in the Published screen.

![Screen Shot 2021-07-24 at 12 41 46](https://user-images.githubusercontent.com/5323259/126866043-11cd6901-344d-403d-9221-a6fe8a89cc18.png)

I tried it again a few times. Hard refreshing the site. I also deleted the Pro version.

**Comment by joedolson** [comment]
Did you delete the plug-in data when you deleted the plug-in?

**Comment by joedolson** [comment]
Noting that the status count data is apparently not registered for uninstall, so if you *did* delete data, that would have been kept. Fixing that now.

**Comment by joedolson** [comment]
The event count numbers are only based on a count of items in the main events table. There seems to be a bug somewhere causing occurrences to be deleted without also deleting the relevant event, and that creates a situation where an event is invalid, but is still counted. I can transform the event counts so that they account for invalid data, but I'd rather figure out where the data is becoming invalidated, so I'm going to leave them for now.

**Comment by paaljoachim** [comment]
Yes, I clicked to "Drop MySQL tables on uninstall".

I will keep the following in the back of my mind:

> There seems to be a bug somewhere causing occurrences to be deleted without also deleting the relevant event, and that creates a situation where an event is invalid, but is still counted.

This time when I clicked to "Drop MySQL tables on uninstall" and uninstalled and deleted the plugin. Downloaded the newest update from this Github repo and uploaded it to the test site. I received this screen:

![Screen Shot 2021-07-25 at 01 14 39](https://user-images.githubusercontent.com/5323259/126883088-77d121c2-02aa-465d-8d3f-c85bf448b4ee.png)

Should there be a message that says: "There are no events in the database meeting your current criteria."
What about removing the message and just keeping it blank? As it seems pretty natural that when all the screens show 0 that there are no events to show. One could perhaps change it to "Create an event" or something to that affect.

**Comment by joedolson** [comment]
When you're filtering events, it's useful to have a message that specifies nothing was found. But for initial installation, when there are no events, I do like the idea of having a link to add a new event. Not super important, but it makes more sense than this message, in that context.

**Comment by joedolson** [comment]
This issue has wandered around a lot, and I think I'm going to close it. Many items in here are resolved, but any further issues should be opened separately.
