### ISSUE TITLE
Manage Events: Not able to click some checkboxes in the ID column.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#122]
I noticed that in the Manage Event Groups screen that I can only click a checkbox next to an ungrouped event.
As there are other checkboxes next to grouped events that are greyed out.

![Screen Shot 2021-07-19 at 22 45 53](https://user-images.githubusercontent.com/5323259/126225142-ebe6d47d-4612-45cf-8af1-a7f841b8b463.png)

Here it would be helpful to click any checkbox.

**Comment by joedolson** [comment]
The only use for the checkbox is to group events; if an event is already grouped, then you can't group it again. Not sure what the benefit would be to this change.

**Comment by paaljoachim** [comment]
I think there is a glitch here with the events seen in the Manage Event Groups. After cleaning up this glitch then I can look at it again. For now I will close this issue.
