### ISSUE TITLE
Merging Style Editor, Script Manager and Template Editor into one screen with multiple tabs. (?)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#124]
The Style Editor, Script Manager and Template Editor.

Can one merge these into one WP left sidebar menu item called "Editor"?

----

Another option.

Merging Style Editor and Template Editor into one screen with two tabs. - Calling these pages for Editor in the left WP menu.

Moving the Script Manager into the settings screen into a "Script" tab. 

Current:
![Screen Shot 2021-07-19 at 23 21 15](https://user-images.githubusercontent.com/5323259/126229096-6de4b4a4-4c49-4f86-90ec-0a869e909e56.png)

Suggestion:
![My-Calendar-adjusting-WP-left-menu-items](https://user-images.githubusercontent.com/5323259/126229761-0385c7e8-10c5-4a47-8b35-0193709c3546.jpg)

**Comment by joedolson** [comment]
I'm not sure about 'Editor', I worry that would convey a sense that it would be a much richer editing experience than it is. Maybe 'Design'. 

There'd also be an argument that a lot of the Output settings could be shifted out of settings and into this section. I think it's a good idea; I'm not sure I've got the bandwidth to do it in this release, but definitely worth looking at.

**Comment by paaljoachim** [comment]
It seems like something we can circle back to at a later time.

**Comment by paaljoachim** [comment]
Changes made:

![Consolidating-sidebar-links-into-design-link](https://user-images.githubusercontent.com/5323259/136911498-68d1f36e-6075-4876-aba7-6e090c6bde39.jpg)

Consolidated: Style Editor, Script Manager and Template Editor into Design screen with multiple tabs.
![My Calendar Design screen](https://user-images.githubusercontent.com/5323259/136911771-770cec88-55b4-4937-bd38-015ede4aad69.jpg)
