### ISSUE TITLE
Autofill of minutes inside Start Time and End Time?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#125]
One thing that comes up when adding times to events is that most will start at the top of an hour. 
Examples 17, 18, 19 hour, and minutes 00.

Can we if the user does not fill out minutes have an auto insert of 00?
For the main event and various Occurrences?

![Screen Shot 2021-07-25 at 01 26 59](https://user-images.githubusercontent.com/5323259/126883235-81d251e5-878a-4684-b5c6-9fbf71c0d88b.png)

**Comment by joedolson** [comment]
You mean have it be optional to insert the minutes? I could only do that by either just using a text input or by creating a complete custom time input. Neither of those are good options; using a standard input, I'm dependent on however the browser implements it, but creating custom inputs is an enormous amount of work & using a text input is just inviting fuzzy data.

**Comment by joedolson** [comment]
I can set a default start time, however, when the field is created.

**Comment by paaljoachim** [comment]
I assume we could use a 00:00 default time. 
...or just leave it as it is today.
