### ISSUE TITLE
Deleting an event. Adding a No button?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#126]
I am testing Occurrences, and the various menu items.
Testing Delete option.

Let's say that I happen to press the wrong button and now I am seeing:
![Screen Shot 2021-07-25 at 01 32 45](https://user-images.githubusercontent.com/5323259/126883309-d9db6e70-1a30-40cf-9e35-800e00cb0906.png)

I then wonder if there is a No button to where I can change my mind. (Personally I assume I can probably just change to another screen and the message goes away. Yep that it did.)

Should there be a No option?

**Comment by joedolson** [comment]
I think not. That feels like unnecessary UI to me.
