### ISSUE TITLE
Followup on moving template menu item to a Template section inside the Events page.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#128]
As Template has been removed from the top menu items. It feels cleaner. 
There is now instead a Preview Template Output at the bottom.
Like so:

![Screen Shot 2021-07-25 at 02 09 54](https://user-images.githubusercontent.com/5323259/126883752-25fa8bd7-9400-427c-85c1-95a4454e7899.png)

A few things.
The Delete - View - Manage events and Update button should be below this new Preview Template Output section.

Should there be a sentence or two that explains what this section does/is? If one has not used templates yet, one will very likely wonder what can be done with the template tags.

**Comment by joedolson** [comment]
I'm OK with a short explanation of use, but I'd rather keep the Delete/View/Update buttons above the preview. The preview is a completely optional section; there's no particular *need* to see the preview before taking an action.
