### ISSUE TITLE
Date/Time display for multiday events does not reflect stored data

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#13]
Should correct display to match the database representation.

https://wordpress.org/support/topic/end-time-last-day/

**Comment by joedolson** [comment]
Data is now organized correctly as of https://github.com/joedolson/my-calendar/commit/9ee3dcc12ea3012dd40e3eec400e035fff68207c; display will need some updating, still.

**Comment by paaljoachim** [comment]
Hey @joedolson 
I am checking in.
Is this issue still valid?

**Comment by joedolson** [comment]
This is improved in 3.3.0. This will include some breaking changes, but I think it was necessary. 

In https://github.com/joedolson/my-calendar/commit/99c587503648ee0c9b8fa01164f9579a71efab10#diff-4723475894e3b6f5796ad369082533f0c31d01d775cb6335af9c9f61d4fd1437
