### ISSUE TITLE
Thank you for creating with WordPress and Version 5.8 not on the bottom - bug -

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#132]
I happen to notice this:

![Screen Shot 2021-07-25 at 16 09 25](https://user-images.githubusercontent.com/5323259/126902130-6c651d3c-22d2-446b-8062-5c0aae85e2ad.png)

Check out the Thank you for creating with WordPress and Version 5.8

Btw Another thing...
The sidebar items needs some padding adjustment. Compare to the My Events page sidebar.

**Comment by joedolson** [comment]
This is all one issue; it's a nesting problem from an extra close div.
