### ISSUE TITLE
My Calendar Styles: Selecting my-calendar.css in drop down.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#135]
I went to My Calendar Styles and in the right drop down I selected my-calendar.css
and clicked Choose Style.

I noticed the notification that says:
There have been updates to the stylesheet.  Compare Your Stylesheet with latest installed version of My Calendar.

![Screen Shot 2021-07-25 at 16 48 14](https://user-images.githubusercontent.com/5323259/126903349-44ade14c-ff41-430a-ac93-96be4a475dab.png)

Clicked the link " Compare Your Stylesheet with latest installed version of My Calendar."

Noticed this:
![Screen Shot 2021-07-25 at 16 49 14](https://user-images.githubusercontent.com/5323259/126903385-5cd6d0d4-e185-4fe4-856c-7ebdfbf00588.png)

I tested the dark.css and it shows similar to as was seen above with my-calendar.css. 
The page becomes very very long and shows the CSS in one column.

**Comment by joedolson** [comment]
Ha! That's actually ironic. That's directly caused by a commit I made to WordPress core fixing a problem with textdiff rendering, which I'd reported when I originally wrote this - because I was using a workaround to make it work right, which no longer works.

**Comment by paaljoachim** [comment]
Yeah that is ironic!..:)
It is nice to see that the fix has been added to WordPress core and now the work around can be removed from the plugin.
