### ISSUE TITLE
Template Editor: errors

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#137]
I happen to notice that there is also a very long scrollbar in the Template Editor.
Scrolling down below the Template Tags section I noticed this:

![Screen Shot 2021-07-25 at 17 12 17](https://user-images.githubusercontent.com/5323259/126904093-68afc69e-e552-4fd3-bcc3-3708d822a603.jpg)

**Comment by joedolson** [comment]
Do you have any events? First guess is this is happening because there are no events in the database. I can fix it without knowing for sure, but if you *do* have events then it's a different root problem.

**Comment by joedolson** [comment]
Never mind! It was a typo. Just a typo...
