### ISSUE TITLE
Settings -> General: "Use Pretty Permalinks for Events". Should this be removed?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#139]
I am wondering about the setting: "Use Pretty Permalinks for Events" seen in the Settings -> General section.

As WordPress by default uses pretty permalinks. Should the setting remain in My Calendar or should it be removed?

![Screen Shot 2021-07-25 at 17 41 10](https://user-images.githubusercontent.com/5323259/126904953-a282405c-8855-4e3d-9674-ad53c740ed5d.png)

**Comment by joedolson** [comment]
See #43 - pending additional debugging.

**Comment by joedolson** [comment]
Closing along with #43. Not removing this setting, because I'm not comfortable forcing sites that aren't currently using this option to use it, but I am changing the default.
