### ISSUE TITLE
Edit Event Group: "Remove checked events ..." button greyed out even when event is selected - bug -

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#140]
Edit Event Group:
Even when selecting individual checkboxes the button is still greyed out (non clickable).

![Screen Shot 2021-07-26 at 00 16 00](https://user-images.githubusercontent.com/5323259/126915126-20c0211e-2c1c-4515-b719-344783d9fa21.png)

When the Check/Uncheck all is selected the button becomes clickable.

![Screen Shot 2021-07-26 at 00 17 48](https://user-images.githubusercontent.com/5323259/126915155-cd607e7d-6691-4304-aff8-2196a4e7da79.png)

**Comment by joedolson** [comment]
Well, *that's* not right...

**Comment by paaljoachim** [comment]
Yeah. Kinda thought so.... I was not fully certain as there might be some magic word to make the button actionable..:)
