### ISSUE TITLE
Manage Event Groups: Rephrasing "The group editable fields for the events...." 

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#141]
I am looking at:

![Screen Shot 2021-07-26 at 00 24 57](https://user-images.githubusercontent.com/5323259/126915355-58b57175-2e3c-4de8-858d-aa62e14e0ea9.png)

The sentence:
"The group editable fields for the events in this group match."
(I find this sentence confusing.)

As I have selected an event that is a part of a group. So I would expect that these have the same information.
Here I am to understand that I can click which event(s) that I would like to modify by changing the various fields.

Rephrasing ideas: 
Select which group events to change.
Select which events to make changes to.
Here you can select which events to change.
Modify the various fields and select which events to apply the changes to.

**Comment by joedolson** [comment]
Editing a group does *not* mean that the fields match. You can group any set of events, in which case editing the group will force every event to share the information from the event you selected in the Manage Groups list.

**Comment by joedolson** [comment]
I think I'm going to 'wontfix' this. We can reopen later if needed.

But I think the terminology 'apply' in bulk editing contexts is pretty common in WordPress, and I'm going to stick with the current phrasing for now.
