### ISSUE TITLE
Manage Event Groups: Merging two single events.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#143]
In the Manage Event Groups screen

I have two single events selected. The button "Group checked events for bulk editing" is active.

![Screen Shot 2021-07-26 at 00 43 19](https://user-images.githubusercontent.com/5323259/126915689-0821cc9f-20b3-4fb4-8808-b933c27f9128.png)

There is too much information in the button. I have selected two single events to group these because I want these to use some common information. At this stage I would know that, or else I would not group these.

I would suggest changing the button text to something simpler such as "Group events" or "Group events for bulk editing" (no need to have the word checked.)

**Comment by joedolson** [comment]
Yes, I think this has become more clear now that the button is only active if items are checked. Before, it was a bit more abstract.
