### ISSUE TITLE
Rephrasing: Warning: The group editable fields for the events in this group do not match

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#146]
Manage Event Groups
I have grouped two single events.

![Screen Shot 2021-07-26 at 01 11 49](https://user-images.githubusercontent.com/5323259/126916482-a1203ea9-b994-4389-9a77-958e3bd1a601.png)

Selected to Edit Event Group. I then see this:

The top area shows the two Single events which I merged (Group 1). 
Below I see other grouped events (Group 2).

![Screen Shot 2021-07-26 at 01 17 55](https://user-images.githubusercontent.com/5323259/126916576-0640e24e-167e-4c69-8ae8-069ef128a0cb.png)

I did not expect to see two different event groups. As I only expected to see Group 1 the Single event group and not have Group 2 included.

**Comment by joedolson** [comment]
That's weird. I'll have to explore this; I don't know why the two lists would show different events. Is this on a version that's more recent than https://github.com/joedolson/my-calendar/commit/501c422820703c204acfdfa9b3b685b0c570fb77?

**Comment by paaljoachim** [comment]
I went ahead and downloaded the newest build. Removed the older plugin and uploaded and installed this one.
I went to existing events that I had grouped and noticed the same result as is shown in the screenshot above.

This time I will go to Settings and select to "Drop MySQL tables on uninstall" and uninstall and delete the plugin. Then a hard refresh. Upload and reinstall the plugin again. 

-----

Another test. I grouped two single events. Then went to edit one of the events. Here is the result.

![Screen Shot 2021-07-26 at 23 17 20](https://user-images.githubusercontent.com/5323259/127060478-d5be2017-3510-4b75-8c8b-8691fb8ac115.png)

I am seeing the "Warning: The group editable fields for the events in this group do not match" (NB needs a punctuation.)

I assume the warning is there because of the two events have different times. (I have only filled out the date and time for these events.)

**Comment by joedolson** [comment]
The titles are different - that's noted specifically in the label for the title field.

**Comment by paaljoachim** [comment]
I assume that grouped events will show a red text beside all fields that are not similar. In addition to the extra warning.

"Warning: The group editable fields for the events in this group do not match"
The word group is mentioned twice. I am looking at some alternatives.

Rephrasing:
Warning: Events editable fields in this group do not match.
Warning: Grouped events have editable fields that do not match.
Warning: Grouped events have different editable fields that do not match.
**Warning: Editable fields for the events in this group do not match.**
