### ISSUE TITLE
Rephrasing the message: "There are no events in the database meeting the current limits."

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#148]
The phrase:
"There are no events in the database meeting the current limits."
Is confusing. As I am wondering what it means with the current limits. 

It is seen in the My Events (Published, Drafts, Trash, Archived and All)

As well as in 
Event Groups
Grouped Events, Ungrouped Events and All.

A simpler phrase would be something like:

"There are no events in the database."
"There are no events."

Or no message at all. Just having a blank page. As one will see that the page is blank. In the My Events page there is also a 0 next to each menu item link.

**Comment by joedolson** [comment]
Perhaps "no events found". The case "no events" is already handled - if there are no limits posed, then they'll see the invitation to create an event. If there are limits imposed on the selection - e.g., search results, category filters, author filters, etc., then it's not accurate to see "no events".

**Comment by paaljoachim** [comment]
> Perhaps "no events found". 

Yes, that would be helpful and easy to understand!

**Comment by paaljoachim** [comment]
Taking a look.

When clicking the Events sidebar menu item it enters the **All** screen.

https://user-images.githubusercontent.com/5323259/127739654-3756f900-942a-4855-acf9-4a9ffdef12d3.mp4

The above "No events found" is very helpful!
One thing I began wondering about..... The All screen has the "Create an event" button. The various other screens have the message "No events found". Should example the Published screen also have the button?
