### ISSUE TITLE
Moving ID so it does not take as much visual space (?)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#151]
At the moment the ID is taking a lot of visual space. I am not sure yet how important it is to show the ID numbers.

![Screen Shot 2021-07-27 at 19 06 44](https://user-images.githubusercontent.com/5323259/127197505-ce676c2b-b236-4fbd-81c4-bd7d8c484eff.jpg)

This is how WooCommerce shows the ID:
![Screen Shot 2021-07-27 at 19 09 12](https://user-images.githubusercontent.com/5323259/127197875-e2768f67-86a7-4abf-97a1-d58bdda20b07.jpg)

Here is another suggestion. 
![Moving-ID-colum-to-Title](https://user-images.githubusercontent.com/5323259/127199008-0a783bce-0afc-47d9-be5c-8c216ed44d5d.jpg)

Moving the ID number to the quick edit bar (Similar to WooCommerce).
![Moving-ID-into-Quick-Edit-bar](https://user-images.githubusercontent.com/5323259/127199892-0ac48cf9-5991-4238-a96f-2c0964bc6e62.jpg)

**Comment by paaljoachim** [comment]
Btw Manage Locations also show a very prominent ID column.
![Screen Shot 2021-07-27 at 22 10 57](https://user-images.githubusercontent.com/5323259/127221353-2b21c37b-3283-4208-92e7-c9f47bbaec97.jpg)

I assume this issue is something to circle back to at a later time.

**Comment by joedolson** [comment]
In my view, ID numbers are critical and I *loathe* the fact that WordPress core has chosen to hide them. I make heavy use of them myself. So, in keeping with my general principle of "don't make UI choices I'll hate", I'm definitely going to keep that present and prominent; I wouldn't want to have to interact with the screen to be able to see that information. 

It might be reasonable to narrow the space reserved for it, but it's not a priority.

**Comment by paaljoachim** [comment]
> So, in keeping with my general principle of "don't make UI choices I'll hate", I'm definitely going to keep that present and prominent; 

LOL!
Main reason why I added the issue is that ID numbers are usually not as prominent or much used, but that might be a bit different with My Calendar plugin.
