### ISSUE TITLE
My Events: Removing the word "events" in the text buttons.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#153]
The various buttons all use the word "events"
Like so:

![Screen Shot 2021-07-27 at 19 32 04](https://user-images.githubusercontent.com/5323259/127202012-bd76fce7-ac10-4c15-b7e6-ad9807075ce8.jpg)

What if we shortened the buttons to become:
![Shorter-buttons-text-My-Events](https://user-images.githubusercontent.com/5323259/127202056-a8402b7a-a45f-48dc-ae8c-6ef1ad5401c5.jpg)

It feels tighter and cleaner and takes less space.

**Comment by joedolson** [comment]
Although if I'm going to possibly switch these to a select input with an 'apply' button, that will be irrelevant. So I'm not going to commit one way or the other just yet... ;)

**Comment by paaljoachim** [comment]
Issue is closed as these buttons are removed and a Bulk actions drop down has been added instead. See: 
My Events page: Move buttons into a Bulk actions drop down
https://github.com/joedolson/my-calendar/issues/105
