### ISSUE TITLE
Host: selecting none (?)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#156]
Under Event Details.
Host: -drop down to select an existing user. -

A host = an existing WordPress user.

![Screen Shot 2021-07-27 at 20 16 43](https://user-images.githubusercontent.com/5323259/127212578-570267c0-c2b7-4e4f-845e-025872e1c53c.jpg)

What about adding a checkbox that says do not show Host? 
Yes. One can go to Settings -> Output and turn off "Author's name" which I assume is the same as Host. But that is in general for all events. It would be nice to have a way to turn off Host name.

Perhaps something like:
![Do-not-show-host-name](https://user-images.githubusercontent.com/5323259/127213112-6c2cd278-345a-49ce-b80d-764139ba70c4.jpg)

When active:
![Do-not-show-host-name-active](https://user-images.githubusercontent.com/5323259/127213397-9be5b4ff-9781-4dcd-bd4e-401794164066.jpg)

**Comment by joedolson** [comment]
Since host is currently not shown at all by default, I think I'll close this. However, the note on clarifying this - and possibly adding a method to show the host information in the default event template - is definitely taken.
