### ISSUE TITLE
Quirkiness with selecting beginning and ending date. Not showing up correctly. - bug -

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#158]
I added an event that is to begin 2021-08-11 and the end date 2021-08-13
All day event.

I saved it as a draft and tried to preview it on the frontend in the Calendar but as the message said in the backend draft events can not be previewed in the calendar. I then published it.

![Screen Shot 2021-07-27 at 21 29 09](https://user-images.githubusercontent.com/5323259/127216035-4cdfb407-973c-4c5d-9fc2-193f9861ac49.jpg)

Checked the frontend calendar.

![Screen Shot 2021-07-27 at 21 30 19](https://user-images.githubusercontent.com/5323259/127216135-ab61b523-3ee0-491c-ab99-40d044d653fb.jpg)

It showed todays date.

I will create another event and see if I can repeat the bug.

**Comment by paaljoachim** [comment]
I tried another but this time it showed the dates correctly.

**Comment by joedolson** [comment]
Yeah, I can't seem to reproduce this. Let me know if you reproduce it again, though.

**Comment by paaljoachim** [comment]
This was a tricky one. I will post if/when the error shows up again.

**Comment by paaljoachim** [comment]
Closing for now. I can always reopen it again.
