### ISSUE TITLE
Overview of Calendar Style Options.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#164]
I will be looking at the various default stylesheets mentioned in the drop drop down. Focus on the frontend visual styles.

![Screen Shot 2021-07-27 at 23 04 07](https://user-images.githubusercontent.com/5323259/127227669-feafc732-f882-4cf6-b6f4-666dac90f98f.jpg)

### dark.css

![Screen Shot 2021-07-27 at 23 05 24](https://user-images.githubusercontent.com/5323259/127227329-e927b80f-d02c-4045-81a1-6401f256c419.jpg)

### inherit.css

![Screen Shot 2021-07-27 at 23 06 05](https://user-images.githubusercontent.com/5323259/127227398-160328ba-0b1a-4cf7-a4fc-ce1c463ab9a7.jpg)

### light.css

![Screen Shot 2021-07-27 at 23 06 38](https://user-images.githubusercontent.com/5323259/127227754-3269f4f7-155c-4666-81ff-df45e1a3462d.jpg)

### my-calendar.css

![Screen Shot 2021-07-27 at 23 09 55](https://user-images.githubusercontent.com/5323259/127227827-a3e40eb6-9907-454d-ad6c-dfadf7039e99.jpg)

### refresh.css

![Screen Shot 2021-07-27 at 23 10 36](https://user-images.githubusercontent.com/5323259/127227927-95004001-af96-410c-8dfe-bde5cbe1c0cf.jpg)

### twentyeighteen.css

![Screen Shot 2021-07-27 at 23 11 32](https://user-images.githubusercontent.com/5323259/127228046-247433e7-8498-428f-8971-0542d38f93fa.jpg)

### twentyfifteen.css

![Screen Shot 2021-07-27 at 23 12 24](https://user-images.githubusercontent.com/5323259/127228157-a2061591-e315-47d4-9554-9cdc4ba19629.jpg)

### twentyfourteen.css

(Zoomed out to 75%.)

![Screen Shot 2021-07-27 at 23 13 46](https://user-images.githubusercontent.com/5323259/127228328-1c56bbe3-5a35-4de9-a391-6dae967a58d4.jpg)

### twentytwenty.css

![Screen Shot 2021-07-27 at 23 15 18](https://user-images.githubusercontent.com/5323259/127228445-5954295b-d788-4162-85c9-0de8feb2d63a.jpg)

**Comment by joedolson** [comment]
So you have some important context on these, you should know that any changes to these stylesheets will only be applied on new installations. Any changes or fixes in the stylesheet would only be merged if the site admin chooses to integrate them.

**Comment by paaljoachim** [comment]
Ahh gotcha!

**Comment by paaljoachim** [comment]
I am adding in the default twentytwentyone.css here.

![Screenshot 2021-12-02 at 09 04 56](https://user-images.githubusercontent.com/5323259/144381970-069b052a-f3d8-4989-98ca-de07bb321030.jpg)

I am also creating a new issue for explorations of the new included stylesheet.
https://github.com/joedolson/my-calendar/issues/389
