### ISSUE TITLE
Calendar Style Settings: closing current stylesheet.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#165]
It would be nice to be able to close the current stylesheet.

Current page:
![Screen Shot 2021-07-27 at 23 34 04](https://user-images.githubusercontent.com/5323259/127230574-133a33ff-8dbd-47e0-b7ac-c527c748adac.jpg)

Perhaps something like this:
Open.
![Style-Settings-Close-current-Stylesheet](https://user-images.githubusercontent.com/5323259/127231044-6948fcf5-fb5f-4e35-afe0-f59dd7878a8c.jpg)

Closed:
![Style-Settings-closed](https://user-images.githubusercontent.com/5323259/127231359-c9237f97-eb8b-4e46-ab08-7360e06bb003.jpg)

The reason is that one should be able to create a new stylesheet below the current one. Closing the current to work on ones one stylesheet.

**Comment by joedolson** [comment]
Are you recommending that I should add a section for people to add a second stylesheet? Otherwise, I'm not sure I see the point of this.

**Comment by paaljoachim** [comment]
Yes.

**Comment by paaljoachim** [comment]
That means people can choose a pre existing stylesheet or create their own. Save it so it gets added to the drop down.

**Comment by paaljoachim** [comment]
They can load in current stylesheets can copy CSS from it to a new stylesheet they create further down. I can create a mockup.

**Comment by joedolson** [comment]
Hmm. So they could create a different stylesheet without disabling the existing one? Would that be additive, or an alternative?

I can see something like that working, but practically speaking I think that most people who create custom stylesheets will use one of the many other existing methods for that - adding them to their theme or custom calendar data folder, using the customizer to handle additional CSS, etc. I don't see a value to doing much to add yet another way to customize styles.

**Comment by paaljoachim** [comment]
(The mockup is not great but it is meant to give some ideas.)

![Create-a-new-stylesheet](https://user-images.githubusercontent.com/5323259/127233561-39c50311-5709-4b2f-aa84-5307fc133e59.jpg)


![Style-Settings-create-new-stylesheet](https://user-images.githubusercontent.com/5323259/127233250-74d07550-dab4-458e-848f-d3a0acd76bf8.jpg)

The point is not to overwrite any existing styles.
Which means one needs to make ones own stylesheet. 
Opening up a current selected stylesheet in the top and copying CSS classes etc into a bottom new stylesheet. User saves the new stylesheet. (Needs to give it a name.) The newly saved stylesheet will then be added to the "Select My Calendar Theme" drop down. 

**So instead of all this there could be a mention of Add your own stylesheet through the customizer. Etc. **

Which means. "Disable My Calendar Stylesheet" could be
Disable My Calendar Stylesheet and create your own stylesheet through the customizer or add the CSS tags to the current themes stylesheet.

-------

My main reason to add this issue is to gather My Calendar CSS in one screen.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue.
