### ISSUE TITLE
My Calendar Styles - Stylesheet section - Adding a View Style button.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#166]
Related: My Calendar Styles - moving Select Stylesheet into the main content area.
https://github.com/joedolson/my-calendar/issues/163
(Not happening)

---------

As a user selects a style it would be nice with a view button to see the new CSS styled calendar on the frontend.

As the select Stylesheet will continue in the top right section. Perhaps we should add a View button next to the "Choose Style"

Perhaps something like this:

![Select-Stylesheet-View-Style-button](https://user-images.githubusercontent.com/5323259/127235876-d6c5f8c0-e6a4-4d2f-9cce-1117cc27656c.jpg)

Clicking "View Style" will then open the main Calendar page.

**Comment by joedolson** [comment]
That's should definitely be doable.

**Comment by joedolson** [comment]
Closed by https://github.com/joedolson/my-calendar/commit/098414bcdbab43859b67e46cc76ba84fbfd460f2

**Comment by paaljoachim** [comment]
This is very helpful!
Switching to another CSS stylesheet through the drop down a "Preview Stylesheet" text link is seen.

![Screen Shot 2021-08-02 at 12 26 43](https://user-images.githubusercontent.com/5323259/127847278-2a8bf662-89e6-4fe6-8ffe-74064e04869a.jpg)
