### ISSUE TITLE
Manage Events - All screen does not add Archived events.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#168]
![Screen Shot 2021-07-31 at 14 03 19](https://user-images.githubusercontent.com/5323259/127739284-44eb401a-29a1-495d-a7f8-8864e6c279d2.jpg)

What we see from the above screenshot.
Published 3.
Drafts 1.
Trash 1.
Archived 7.
All shows no number as it should show what is located in all the screens.

**All** shows what has been published, trashed and drafts. It does not show Archived events.

**Comment by joedolson** [comment]
"All" screen will not add archived events. I'm happy to make it more clear that archived events will not be shown in other lists, but they will *not* appear in other lists. That's the whole point of archiving events: so that they are out of the way.

**Comment by joedolson** [comment]
I do think it's questionable how valuable 'All' is. The main events screen shows Published & Draft; you can isolate published, draft, trash, or archived. All shows published, draft, and trash. Is there any real benefit to seeing that combination of events?

The core WordPress 'All' filter excludes posts in the Trash, so an "All" link that doesn't actually show everything has precedent in WordPress, for better or for worse. That's more equivalent to the My Calendar default view. 

I'm not convinced that either of these are a great model...

**Comment by joedolson** [comment]
Made some changes to improve this. Also added a Help tab that defines event statuses users might see.

**Comment by paaljoachim** [comment]
> I do think it's questionable how valuable 'All' is. The main events screen shows Published & Draft; you can isolate published, draft, trash, or archived. All shows published, draft, and trash. Is there any real benefit to seeing that combination of events?

I do agree with you on this. As the Published, Drafts and Trash are already isolated, and "All" just shows the combination of all three. I too am wondering how valuable it is, and have thought a few times about suggesting to remove it. 
It is of course a way to just view three screens in one place.

**Comment by paaljoachim** [comment]
I just checked the Help tab.

![Screen Shot 2021-08-15 at 20 15 05](https://user-images.githubusercontent.com/5323259/129488342-83fef84b-5e0d-4618-8e1d-d8efdc9b5209.jpg)

It gives a nice overview of different states an event can have! Nice!

**Comment by joedolson** [comment]
For now, I'm going to consider this complete. It's definitely a lot clearer, at any rate.
