### ISSUE TITLE
Mini Calendar: displaying categories if needed in columns?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#169]
This issue is related to: https://github.com/joedolson/my-calendar/issues/94

Here is a nice example of being able to click which of the various categories to display in the Mini Calendar.
![Screen Shot 2021-07-31 at 14 09 09](https://user-images.githubusercontent.com/5323259/127739467-6528ac15-7e17-4bbd-84f1-d5c694efedb3.jpg)

If there are a lot of categories should these after a specific count be added as columns? Like so:
![Mini-Calendar-showing-categories-in-columns](https://user-images.githubusercontent.com/5323259/127739514-d8a5035f-b137-4ad0-b58a-3d3cc340457f.jpg)

**Comment by joedolson** [comment]
Not sure how easily I can break 'all' into a separate group, but yes, this is definitely reasonable.

**Comment by joedolson** [comment]
Practically speaking, I didn't see a pressing reason to make this conditional on the number of categories.

**Comment by paaljoachim** [comment]
> Practically speaking, I didn't see a pressing reason to make this conditional on the number of categories.

I see no need to do so.

This works very well:

![Screen Shot 2021-08-02 at 12 24 36](https://user-images.githubusercontent.com/5323259/127846978-86f7c343-285b-4fa9-b962-bc0c5260df4b.jpg)
