### ISSUE TITLE
Manage Events List

### ISSUE THREAD

**Issue by dstevray** [joedolson/my-calendar#17]
It would be nice to have a way to automatically delete (or archive) all events older than x days in order to keep the Manage Events list at a reasonable length.

**Comment by joedolson** [comment]
In https://github.com/joedolson/my-calendar/commit/b4497e73f8a230352d823be390cb22d5a39d3e07, added three actions that occur when an event is tested for its relationship to the current time. 

These three actions can be used to automatically transition events, but I don't think I'm going to add these as a core feature in the plug-in. I'll write an example for my add-on library showing usage, but I think this is an edge case need.
