### ISSUE TITLE
Remove underline for Default Location

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#170]
Remove underline for right Default Location pencil and Opsal Gard.

![Screen Shot 2021-07-31 at 14 27 38](https://user-images.githubusercontent.com/5323259/127739851-821a1cd8-46bd-4d83-8219-e00cb412e988.jpg)
 
Because the main Location table does not use underline for the same titles.

**Comment by joedolson** [comment]
Links in the sidebar are underlined, so I'm going to leave the underline. However, I'll remove it on the pencil itself, to fix that broken underline.

**Comment by paaljoachim** [comment]
That helped!

![Screen Shot 2021-08-02 at 12 21 32](https://user-images.githubusercontent.com/5323259/127846590-e9ab1212-87e0-4a2f-b097-591b8c04759a.jpg)
