### ISSUE TITLE
Creating a new category inside the Event screen?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#171]
As I was creating a new event I noticed that I had not yet made any new categories.

Should there be a way to create new categories inside the new event screen? 
(Anyhow something to perhaps think about for a later time.)

**Comment by joedolson** [comment]
I thought you'd already suggested this somewhere, but I'm not finding it, if so. It's definitely a consideration. There's already an internal system for creating categories when saving an event, used when importing from CSV, so the back-end pieces are already done.

**Comment by paaljoachim** [comment]
I made a search as well, and could not find it.
