### ISSUE TITLE
Saved as Draft and now change to publish. Button still says update. It should say Publish.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#172]
I saved an event as a Draft. Switching over to Publish the button still says Update. It should say Publish.

Update - Draft (drop down).
Switching through drop down to Publish.
Update - Publish (drop down).
Switching through drop down back to Draft.
Save Draft - Draft (drop down).

It should be
Update - Draft (drop down).
Switching through drop down to Publish.
NB: **Publish** - Publish (drop down).
Switching through drop down back to Draft.
Save Draft - Draft (drop down).

https://user-images.githubusercontent.com/5323259/127740238-4356e0bd-7699-4388-af1c-d31b9c879bf5.mp4

**Comment by paaljoachim** [comment]
Btw I switched it over to Trash and notice the button also says Update there.
Perhaps the button text should say "Move to Trash" instead of Update.

**Comment by joedolson** [comment]
So, I think that the switch between 'Publish' and 'Save Draft' should only happen when adding a new event. When editing an event, it should always say 'Update', and shouldn't be switching based on status. You're always updating something that's already saved if you're editing.

**Comment by paaljoachim** [comment]
That sounds reasonable.
I will go ahead and close the issue.
