### ISSUE TITLE
Underline or not to underline.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#174]
I am wondering about the underline. When it is to be used or not.

The calendar view. I have modified it with CSS to this stage:
By default.
List, Month, Week, Day, Go, left, right arrows, Categories, Print are not underlined.
On hover these become underlined.

The only item that is underlined by default is the event title.

![Screen Shot 2021-07-31 at 23 38 32](https://user-images.githubusercontent.com/5323259/127753003-0d282908-248c-468e-a801-35c959a35a11.jpg)

Clicking the event title. We see this popup card.
Here we see multiple items which by default are underlined.
External links: Opsal Gard, Map,  Opsal Gard, biomangfold og levende fortelling and Google Calendar.
iCal downloads an ics calendar.
Read more goes to the event.

![Screen Shot 2021-07-31 at 23 41 09](https://user-images.githubusercontent.com/5323259/127753046-c15290bc-12a7-4cce-a452-49f7eddc0a33.jpg)

Having the three icons and text by default underlined then we need to make adjustments. The above has actually been adjusted by adjustments I made here:  Hover over calendar icon + List text shows uneven underline.
Linking to my latest comment: https://github.com/joedolson/my-calendar/issues/54#issuecomment-890405493

But these three iCal, Google Calendar and Read more need some additional tiny adjustments, so we get the underlines aligned with each other.

**Comment by joedolson** [comment]
If you set up the underlines using border-bottom instead of text-decoration, that'll work. It may require higher specificity, depending on theme.
