### ISSUE TITLE
Direct rephrasing and translation labels.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#175]
I am looking at the Time Label. What is nice here is that one can use words in any language as a direct translation or for adjusting the phrase in English. 

![Screen Shot 2021-08-01 at 00 18 55](https://user-images.githubusercontent.com/5323259/127753647-33932d61-193c-4acd-b0b3-3db5f0e3f145.jpg)

There are two more fields that could use direct rephrasing/translation as well.

![Screen Shot 2021-08-01 at 00 21 32](https://user-images.githubusercontent.com/5323259/127753702-e77f0a34-edc6-44e3-8104-39f1143e1814.jpg)

The frontend will show:

![Screen Shot 2021-08-01 at 00 22 32](https://user-images.githubusercontent.com/5323259/127753715-4aeaf837-b47b-4460-be19-529f9b614286.jpg)

Being able to adjust "Hosted by" and "More information" can be very useful. As one might want to phrase it differently and also use a direct translation.

![Event-Details-additional-labels](https://user-images.githubusercontent.com/5323259/127753911-0b706ff3-9148-4d72-9030-8e45b2beb7c9.jpg)

As one more want to use For more information go to this external link instead of "More information".
One might want to say Faciliated by instead of "Hosted by". 
Etc.

**Comment by joedolson** [comment]
Closing this for now; I've implemented most cases, can re-open or create new issues if others come up.

**Comment by paaljoachim** [comment]
Ahhh one thing I just discovered a few days ago is that I can change Hosted by, Posted by and More information as well as various other phrases directly in the Settings -> Text.

Like so:
Text Setting.
![Screenshot 2021-09-19 at 21 48 58](https://user-images.githubusercontent.com/5323259/133941000-119aa91a-4aa3-445c-9835-f49e791cc2e1.jpg)

Frontend:
![Screenshot 2021-09-19 at 21 49 09](https://user-images.githubusercontent.com/5323259/133941005-285e294d-7646-4377-ba32-58efa53c3a6b.jpg)

So that really takes care of phrases/language etc, as the user can rename various output directly in the Text Settings.
