### ISSUE TITLE
Taking a closer look at the Template Editor

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#176]
As one enters the Template Editor.
This is what a user sees:

![Screen Shot 2021-08-06 at 18 56 11](https://user-images.githubusercontent.com/5323259/128545649-25fb57df-9e4e-45de-a999-4911312afef0.jpg)

Edit Template

A link to Template Help (this becomes a bit hidden away because of the huge code window below.)

Starting from the most basic.
I go to the Template Editor because I want to use a template for a specific screen.

I expect to see a nice overview of the Template options I have at the top. Selecting which template I want to look closer at and activating. A smaller code window that can be resized if needed, so that I can see the Update Template button without scrolling. Here is another suggestion (I made one in https://github.com/joedolson/my-calendar/issues/138 as well.)

![Template-Editor-redesigned](https://user-images.githubusercontent.com/5323259/128553873-e29905d0-97a7-4f55-a01d-729e7ac9dec5.jpg)

Added the templates in a list above the template code.
Clicking the checkbox activates the template.
Clicking the template name shows it below. Here one can click "Use this template" to activate the template. A checkmark will also be added to the active column.
I added a Preview Template button next to the Update Template button. 
I added the Add New Template above on the right side of the code section. Could perhaps be moved below next to Preview Template instead.
I added a red triangle to show that the code section can be extended, as it should start out smaller than what we see today. (The red color was just to have it stand out in the mockup.)
I added a text link bottom right to the Templates Help area.

**Comment by joedolson** [comment]
Added template previews; CodeMirror being resizable is something I'm not going to pursue further at this point.

**Comment by paaljoachim** [comment]
This is what it looks like right now.
![Screenshot 2021-09-25 at 10 41 55](https://user-images.githubusercontent.com/5323259/134765454-8b18b68c-3f4f-438e-a907-f4b66677638f.jpg)

![Screenshot 2021-09-25 at 10 43 46](https://user-images.githubusercontent.com/5323259/134765472-da2c66a4-a10b-439e-af44-49ab247da33c.jpg)

I was thinking a way to just view the template in use on the frontend. A preview text link close to the Core Templates area. Having a preview which then opens a new tab that goes to the frontend and the specific area it affects.

**Comment by paaljoachim** [comment]
I believe we need to reopen this issue.

**Comment by joedolson** [comment]
There are a lot of barriers to making that work; and I'm not sure how it's different from just opening an event page in a separate tab and refreshing it when you make an edit. Seems like a lot of work on my end to accomplish very little. 

The unrendered {image} tag is due to an error in the template (my error in the default); it should have a closing curly brace instead of a terminal semicolon.

**Comment by joedolson** [comment]
If you want to reopen any issue, go ahead.

**Comment by paaljoachim** [comment]
I am not able to to so in this repo, but can only do so in the Pro repo.

**Comment by joedolson** [comment]
I hadn't actually invited you as a collaborator to this repository, but had completely forgotten that, since it's a public repository, so anybody can comment. Invited now!
