### ISSUE TITLE
Adding a calendar view for admin navigation of events

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#183]
Hey Joe

I am bringing the feature over from this now closed issue:
https://github.com/joedolson/my-calendar/issues/179

About integrating the admin calendar view.

![WP-Event-Calendar-Calendar-screen](https://user-images.githubusercontent.com/5323259/131183062-590832db-2691-4e01-85f8-c5ef6a4ef29f.jpeg)

**Comment by joedolson** [comment]
This was a complicated addition. There may be bugs with it; open those as new issues.

**Comment by paaljoachim** [comment]
How interesting!

I went to Events and there I suddenly noticed the Grid View and List View options.

![Screen Shot 2021-08-29 at 23 59 12](https://user-images.githubusercontent.com/5323259/131266677-50e5f77b-2886-4dd2-84b8-614528299fc2.jpg)

Heck it looks better on the backend than on the frontend.
New issue coming up...:)

**Comment by joedolson** [comment]
It's a *lot* easier to implement design on the backend...
