### ISSUE TITLE
Brushing up the frontend calendar

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#187]
It would be nice to brush up the frontend calendar.

Here is one example of the current calendar.
![Screenshot 2021-09-09 at 00 59 15](https://user-images.githubusercontent.com/5323259/132596689-63c6d344-dd36-4d91-8a38-17c324925912.jpg)

The new backend calendar.
![Screenshot 2021-09-09 at 00 56 15](https://user-images.githubusercontent.com/5323259/132597476-57509895-694a-4c86-a4c7-e4451c8819c8.jpg)

Some suggestions.
Adding Month, Week and Day into a drop down. So the user can choose the time frame.
Adjusting < > to become similar to the new backend calendar < Previous l Next > as can be seen in the backend.
The Go drop down area is also similar to backend.

![Readjusting-Frontend-Calendar](https://user-images.githubusercontent.com/5323259/132660321-d38485a8-13f9-4a16-9dcb-6809fe160b15.jpg)

Associated:
https://github.com/joedolson/my-calendar/issues/183

**Comment by paaljoachim** [comment]
Ahh yes this would also affect the Settings -> Output section.

![Screenshot 2021-09-09 at 13 10 12](https://user-images.githubusercontent.com/5323259/132675631-88409f79-943b-4619-b484-421ef4bce046.jpg)

**Comment by joedolson** [comment]
The appearance of the prev/next link is just styles; different stylesheets set those up differently. Text is already there, just hidden as screen reader text in some stylesheets.

Making format into a dropdown is not readily feasible unless I just added two options for showing timeframe, e.g. 'timeframe (links)' and 'timeframe (dropdown)'. 

I can do that, but it's not a priority for this release, I think. As I've mentioned, the next release is where I want to target more front-end changes.

**Comment by joedolson** [comment]
I am shipping an updated stylesheet in 3.4.0; but not other larger styles. The big change that's relevant here is that I added a tool to migrate CSS into custom directories, so I'll be able to stop supporting old versions of CSS files.

**Comment by paaljoachim** [comment]
Adding a screenshot of the Migrate CSS information.
![Screenshot 2022-12-22 at 01 04 09](https://user-images.githubusercontent.com/5323259/209067945-1aa3f058-4ab5-4653-bf8d-796b783dfeaf.jpg)
