### ISSUE TITLE
Feature: Adding additional frontend views

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#188]
At the moment we have the List and Grid view of the calendar.

It would be natural to add a kind of Card view where one can define a certain amount cards in a row. As it if was a typical blog preview showing a post preview with a title, featured image, excerpt and a read more.

Another is a kind of Map view showing events on a map.

These are complex features that we can circle back to for 3.4. Perhaps to be added to the Pro version.

**Comment by joedolson** [comment]
Yes, prefer adding front-end features in Pro only at this point, definitely. 

The rewrite of the map JS that I did set up the possibility of doing maps with multiple points; that wasn't supported before.

Please raise those as two separate issues in the My Calendar Pro repository - thanks!

**Comment by paaljoachim** [comment]
Feature: Adding additional frontend Card view. 
https://github.com/joedolson/my-calendar-pro/issues/11

Feature: Adding additional frontend Map view.
https://github.com/joedolson/my-calendar-pro/issues/12
