### ISSUE TITLE
Adjusting the tabs 

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#190]
Here are some suggestions on adjusting the tabs style. 

This is what it currently looks like:
![Screenshot 2021-09-09 at 12 38 01](https://user-images.githubusercontent.com/5323259/132674085-0d968c2d-82a8-4a6a-a2d9-d5a2074eb786.jpg)

Adjustment 1. Just adding grey lines to the small downward arrow.
![Adjusting-the-tabs](https://user-images.githubusercontent.com/5323259/132674181-3c153ee2-cbe3-4591-a3ec-0c07050ee399.jpg)

Adjustment 2. Removing the bottom grey lines in the active tab.
![Tabs-adjustment-2](https://user-images.githubusercontent.com/5323259/132674261-2c8094f1-9600-42a4-a622-751cc71ea9c3.jpg)

Adjustment 3. Pushes the links closer to the content and removes the downward arrow. 
![Tabs-adjustment-3](https://user-images.githubusercontent.com/5323259/132674298-70192677-b007-48d7-94af-c027a274cca3.jpg)

Here is an example from WooCommerce.
![Screenshot 2021-09-09 at 13 02 17](https://user-images.githubusercontent.com/5323259/132674654-8deaf017-00c2-452e-8975-870cc9ef1f50.jpg)

Example from editing a Multisite site.
![Screenshot 2021-09-09 at 13 06 08](https://user-images.githubusercontent.com/5323259/132675123-63642f8d-b268-4c72-a969-08ef41691ed6.jpg)

Btw do also check out how Github issue tabs look like.

https://wordpress.stackexchange.com/questions/127493/wordpress-settings-api-implementing-tabs-on-custom-menu-page

**Comment by joedolson** [comment]
The distance between the tabs and the content controlled is a structural problem, and it would be a major restructuring to address that...which isn't going to happen in this release, for sure. 

Adjustment 1 is a perfectly good option. I have some idea that I tried to do that and ran into a problem, but I no longer remember the context for that, so I'll look at it again.

**Comment by paaljoachim** [comment]
Yes. That looks better!

![Screenshot 2021-09-13 at 11 23 40](https://user-images.githubusercontent.com/5323259/133059081-ede498f8-9d9d-49c9-8d0d-eb73020f7d5b.jpg)
