### ISSUE TITLE
Some confusion: Output and Input event manager vs Single Event Details

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#191]
Settings

Here is my initial response when I view these options.

### Input

Calendar Input Fields

Show in event manager (Event Manager - capital letters?)

![Screenshot 2021-09-09 at 13 12 28](https://user-images.githubusercontent.com/5323259/132675952-4c89a013-cf8e-4862-81e7-6983ed9b17e3.jpg)

and we also have...

### Output

Output Settings

Single Event Details

![Screenshot 2021-09-09 at 13 24 07](https://user-images.githubusercontent.com/5323259/132677467-f86f1bef-b857-416c-944d-06a1bc88f12b.jpg)

It seems like the above two screens overlap.

Here I will also assume that Input (going inward) is more focused on the backend, and Output (going outward) is more focused on the frontend. In general we need to make it clear which area is for the frontend and which area is the backend.

I also find it a bit confusing having in the Input screen - Show in event manager a checkbox for: "Administrators see all input options" As I assume the admin would be the one to adjust what is seen on the frontend or not.

**Comment by joedolson** [comment]
Yes, input is "the input fields visible in event creation" and output is "the event fields shown on the site". 

Admin see all input options means that an admin can restrict the fields available to other users, but still see everything themselves.

**Comment by paaljoachim** [comment]
It would be nice to add some better clarity to these features.
I will look closer into it and probably add new issues.

**Comment by joedolson** [comment]
I think that this is basically resolved, or at least progressed in related issues. Closing.

**Comment by paaljoachim** [comment]
I am seeing differences in between Output settings - Single Event Details VS Input settings - Calendar Input Fields.
I assume we are handling these in other issues. (If not I can always circle back at another time.)

**Comment by joedolson** [comment]
I'm not sure there can be a complete 1:1 match between those - some fields, for example, are auto generated (e.g. Link to single event iCal download), and have no input correlation. But yes, there's room for some improvement.

**Comment by joedolson** [comment]
I'm feeling that I really need to create multiple settings configurations for output; at *least* one for the pop-up and one for the single event page. I think that's a barrier for many people; not understanding clearly when these will or won't be used.

**Comment by paaljoachim** [comment]
That sounds like a good idea.
I would be cleaner and easier to understand when the various options/fields are located under the subheading these belong in. Something like:

Single Event Details
--- fields ---

Pop-up Card Details
--- fields ---

Grid Options 

List Options

Mini Calendar Options

**Comment by joedolson** [comment]
Needs checking to verify that all options display as expected. This was a pretty major change.
