### ISSUE TITLE
Adjusting the Settings -> Permissions screen

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#192]
At the moment I have a few plugins installed into the test site such as BuddyPress, bbPress and WooCommerce. All bring along new users. This means that the Permissions screen looks like this (at 75% zoom)

![Screenshot 2021-09-09 at 13 53 28](https://user-images.githubusercontent.com/5323259/132681118-8bc8ea27-ccb9-4102-bfc8-73adc138aa63.jpg)

An alternative is doing something like so:
![Adjusting-Permissions-screen](https://user-images.githubusercontent.com/5323259/132681176-d1dac296-b97a-4ceb-a9b4-b217950a40e4.jpg)

User clicks a Role or clicks the checkbox and one clicks the various checkboxes for a specific role. (Could even hightlight the selected role to easier see which role one is adjusting.)

**Comment by joedolson** [comment]
This screen hasn't been a high priority because - in theory - people should only very rarely need to tweak it. But it could stand some tweaking, for sure. 

Maybe just a secondary set of tabs (possibly organized vertically, since the number of user roles can get pretty large.)

**Comment by paaljoachim** [comment]
Ahhh yes.. This looks a LOT better!

![Screenshot 2021-09-13 at 11 13 46](https://user-images.githubusercontent.com/5323259/133057621-79866bd0-1a6f-445a-80fa-088cfc190efc.jpg)
