### ISSUE TITLE
Settings -> Notifications

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#193]
Calendar Email Settings

Email Notifications

![Screenshot 2021-09-09 at 13 58 49](https://user-images.githubusercontent.com/5323259/132681777-9981b9a4-3756-40f2-b6d8-a5a96c6909dc.jpg)

" Send Email Notifications when new events are scheduled or drafted." ---> What about sending a notification when an event is published?

**Comment by joedolson** [comment]
I think "new events are scheduled" means "new events are published", but I agree that reads confusingly. Probably should be rephrased for clarity. (After verifying that yes, that is actually what it means...)

**Comment by paaljoachim** [comment]
Yes. This is better!

![Screenshot 2021-09-13 at 11 17 06](https://user-images.githubusercontent.com/5323259/133058084-e293ec84-c2a0-42d7-b5ca-5837befb5714.jpg)

One thing...
The sentence form: "Send Email Notifications when new events are added." ---> Should this be: Send email notifications when new events are added. (Small s and small e. Because it is a part of a sentence?)
