### ISSUE TITLE
Viewing event on frontend - No top bar edit event link.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#194]
Viewing an event on the frontend there is not Edit event link in the top admin black bar.

Event seen on the frontend:
![Screenshot 2021-09-09 at 14 23 30](https://user-images.githubusercontent.com/5323259/132685074-74ec2e7a-2018-4ff8-ba57-1b43fd0c0cbb.jpg)

Compared to seeing a page on the frontend:
![Screenshot 2021-09-09 at 14 24 16](https://user-images.githubusercontent.com/5323259/132685182-7839f94d-a0d1-40b0-baa4-9300a3cc434f.jpg)

There are various edit links below the event.
![Screenshot 2021-09-09 at 14 25 21](https://user-images.githubusercontent.com/5323259/132685352-d99e1e71-3587-48e7-8cb7-c855a2f8b6be.jpg)

It would be helpful to add Edit Event (which goes to the specific top/parent event.)
![Frontend-Edit-Event](https://user-images.githubusercontent.com/5323259/132685807-45ccc3d2-5d12-477e-a27f-f949e7fea32f.jpg)

**Comment by joedolson** [comment]
The admin bar can get so cluttered, and there are, as you note, already links to edit the event on the page. I'll think about it, but it's not a priority.
