### ISSUE TITLE
Opening and closing each section as an accordion?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#196]
I am wondering if an accordion should be added to each section, so we can open and close each depending on what one needs.

75% zoom.

![Screenshot 2021-09-09 at 14 37 07](https://user-images.githubusercontent.com/5323259/132687043-2f9aa022-d274-4610-a0e0-e83ad1388110.jpg)

**Comment by joedolson** [comment]
I'd rather not. I can appreciate the desire, but personally not something I like in an interface; I find it to just be a hassle.
