### ISSUE TITLE
Manage Locations: Quickly changing Default Location

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#198]
Here I expect to easily switch which location is the Default Location.

![Screenshot 2021-09-09 at 14 50 46](https://user-images.githubusercontent.com/5323259/132688973-f36795b1-7f13-4142-8b32-f4804d166f16.jpg)

Perhaps on a Default location checkbox next to Check all or a quick edit hover over the place and see a make default link.
![Screenshot 2021-09-09 at 14 50 53](https://user-images.githubusercontent.com/5323259/132689098-682842fb-d91f-43d7-9afd-2540852a854d.jpg)

![Make-default](https://user-images.githubusercontent.com/5323259/132689534-26e1fb51-a2cb-4bfe-9c6e-8970308c8771.jpg)

**Comment by joedolson** [comment]
Certainly easy enough to do. If so, I'd want to mirror that change in Categories, as well.

**Comment by paaljoachim** [comment]
Great! Having "Set as Default" added to the quick edit menu is very helpful.

![Screenshot 2021-09-13 at 12 08 01](https://user-images.githubusercontent.com/5323259/133065696-294fc5ed-4fa2-432b-be21-07bd86035771.jpg)
