### ISSUE TITLE
Calendar Input Field setting fields vs Add Event fields

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#204]
I am comparing field names used in the Settings -> Input (Screen Options) vs Add Event fields. These names should be identical.

I am also seeing a bunch of small case letters which should be capital letters.

-------

Settings -> Input screen.

### Calendar Input Field settings.

![Screenshot 2021-09-13 at 15 52 49](https://user-images.githubusercontent.com/5323259/133096288-7e500d4b-df05-4aff-82cc-cdb0645e76fc.jpg)

Accessibility
Category
Description
Host
Image
Link
Location fields ( Should be Location **F**ields - adjust to become capital F.) 
Location Selector
Registration options (Should be Registration **O**ptions - adjust to become capital O.) 
Recurrence Options
Excerpt
Special Scheduling options (Should be Special Scheduling **O**ptions - adjust to become capital 0.)
Administration see all input options

### Add Event fields 

Event Title
Content
Excerpt
Categories vs Category
Date and Time
Repetition Pattern
Featured Image
Event Details
-- Host
-- External Link
Event Access
Event Registration Settings
Event Location
Special Scheduling options (Should be Special Scheduling **O**ptions - adjust to become capital O.)

-----------------

Let us be sure that fields in Input (+ Screen Options) and Add Event screen use the same field names, so that we do not cause confusion.

### Add Event fields vs Calendar Input fields

Event Location vs Location Selector
Excerpt vs Excerpt
Blank (no name - content area) vs Description (Perhaps add the field name Description somewhere around the content field area? 
Categories vs Category
Featured Image vs Image
External Link vs Link
Repetition Pattern vs Recurrence Options
Event Registration Settings vs Registration options (Options with a capital **O**)
Event Location vs Location fields (Fields with a capital **F**)
Special scheduling options vs  Special Scheduling options (Capital **S** and Capital **O**)
Accessibility ? (Not sure where this is...)

**Comment by joedolson** [comment]
I'm not sure these can be 100% identical, but they could certainly be more similar than they are. The output is just the output; but the input fields include input mode, e.g. inputting locations through the selector or via location fields. 

Accessibility correlates to Event Access.

**Comment by joedolson** [comment]
Also, there are some issues in that 'Categories' is only the label if you have multiple categories enabled...but I'd like to encourage that, so I'm comfortable with changing that label. Tricky, though.

**Comment by joedolson** [comment]
I think this has been resolved, as well.

**Comment by paaljoachim** [comment]
Yeah I also believe this has been fixed.

Input Fields now look like this:
![Screenshot 2021-09-27 at 11 08 51](https://user-images.githubusercontent.com/5323259/134879136-d82f93d7-fb40-41d8-bc41-67ffd6af72e6.jpg)
