### ISSUE TITLE
Bulk actions drop down order of items

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#205]
Associated issue:
https://github.com/joedolson/my-calendar/issues/203

![Screenshot 2021-09-13 at 21 08 42](https://user-images.githubusercontent.com/5323259/133142861-b85e28fd-ea71-45d6-927d-ad5b9b3ec93e.jpg)

Bulk actions - drop down items.
Publish
Delete
Trash
Switch to Draft
Archive

Bulk actions (should this be Bulk **A**ctions?)
New order of items. By the following logic. Publish is the main item. Next would be switching a published event back to draft. Then trash (event moved to trash). Archive (event moved to Archive tab). Last is Delete which totally removes the event.

Publish 
Switch to Draft
Trash
Archive
Delete

**Comment by joedolson** [comment]
'Bulk actions' with lowercase "a" matches WordPress core.

**Comment by paaljoachim** [comment]
Great! This is what it looks like.

![Screenshot 2021-09-14 at 10 19 49](https://user-images.githubusercontent.com/5323259/133222280-15fad507-510c-4467-a0d9-dd61e15fae04.jpg)

One last comment which I will add here even though this issue is closed.
The quick edit bar shows a red colored Delete text. Should we do the same in the Bulk action drop down?

![Screenshot 2021-09-14 at 10 20 42](https://user-images.githubusercontent.com/5323259/133222408-70fdcae9-3025-4b97-875a-3f761d664614.jpg)
