### ISSUE TITLE
Add red color to Delete text in Bulk action drop down.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#206]
We have cleaned up the Bulk action drop down.
So it now looks like this:
![Screenshot 2021-09-14 at 10 19 49](https://user-images.githubusercontent.com/5323259/133224289-7e501c78-383d-423c-b1fc-0d38aadd9dda.jpg)

One thing I noticed earlier in the quick edit is that the word Delete is in red.
![Screenshot 2021-09-14 at 10 20 42](https://user-images.githubusercontent.com/5323259/133224340-4e233416-ee38-4d74-b14c-a48db72bfd7e.jpg)

Should we also add red to the Delete word in the Bulk action drop down?

**Comment by joedolson** [comment]
Options in a select dropdown are completely controlled by the browser; it's not an option to style their color or background.

**Comment by paaljoachim** [comment]
Alrighty!
