### ISSUE TITLE
Input tab fields and Add Event screen options. (order of names)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#207]
Hey

Input tab Calendar Input Fields.

![Screenshot 2021-09-14 at 10 25 44](https://user-images.githubusercontent.com/5323259/133223603-e040a08d-cbac-4929-87d8-d2020062737d.jpg)

Add Event Screen Options.

![Screenshot 2021-09-14 at 10 30 30](https://user-images.githubusercontent.com/5323259/133223771-ace8fd04-b859-4c7f-aca2-0cb4318080ce.jpg)

Having the names correspond was mentioned in this issue https://github.com/joedolson/my-calendar/issues/204.

I am now looking at keeping the same order of names in the Input Fields and the Screen Options. Which can correspond to the order these are seen in the Add Event screen.

Description
Excerpt
Categories
Repetition Pattern
Featured Image (in Screen Options and Input Fields tab is says "Image". It would be helpful to add the word Featured. As Image is such a broad term.)
Host
External Link (in Screen Options and Input Fields tab it says "Link". It would be helpful to add the word External. As link is such a broad term.)
Accessibility
Registration Settings
Location Selector
Location Fields 
Special scheduling options (Needs to be changed to using capital letters. As can be seen in Screen Options and Input Fields tab.)

**Comment by joedolson** [comment]
Sheesh, so picky. It's like you want me to be consistent or something! ;)

I'm not sure that these should correspond to the order in the add event screen, but they should definitely have the same order as each other. My inclination would be alphabetical order, for findability.

**Comment by paaljoachim** [comment]
This is a lot better and very helpful! It gives a much better clarity to the options seen!

![Screenshot 2021-09-16 at 10 49 53](https://user-images.githubusercontent.com/5323259/133582126-69c48f71-b6be-4f9a-869f-6d834e3f7f9f.jpg)

![Screenshot 2021-09-16 at 10 50 21](https://user-images.githubusercontent.com/5323259/133582145-f56025b3-ab00-4de5-975e-63c6ad144a96.jpg)
