### ISSUE TITLE
Create demo content

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#208]
For new users, it might be beneficial to start with demo content: a demo location & a demo event that work well with default templates, so they can see how things will work. I could conceivably store that content in a way that could be used in preview layouts, as well.

**Comment by paaljoachim** [comment]
Good idea! I was thinking about it as well when I started fresh earlier today.

**Comment by paaljoachim** [comment]
It would be great to use demo content for screenshot purposes to use in documentation.
I will add some suggestions very soon.

**Comment by joedolson** [comment]
Closing this. The content & layout could use some massaging, but the basic implementation is done.

**Comment by paaljoachim** [comment]
Are you thinking the frontend content & layout? Or are you thinking about the Event Description content?
