### ISSUE TITLE
Using Gutenberg in the docs site?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#210]
Hey Joe

Can we use the Block Editor/Gutenberg in the docs site?
https://docs.joedolson.com/my-calendar

**Comment by joedolson** [comment]
Yes, certainly.

**Comment by paaljoachim** [comment]
I just tested and notice that Gutenberg is active but I assume the Classic Editor is also network activated because I am not seeing Gutenberg active in the posts or pages. As I am also thinking of redoing the My Calendar: Table of Contents page in Gutenberg and adding these into lists inside columns.

**Comment by joedolson** [comment]
Are you not able to enable it in your profile?

**Comment by paaljoachim** [comment]
I looked but could not see any setting in my user profile to enable the Block editor
![Screenshot 2021-09-20 at 08 25 42](https://user-images.githubusercontent.com/5323259/133963477-34679ad6-943a-42a3-8185-f0cc45e018c3.jpg)


![Screenshot 2021-09-20 at 08 24 38](https://user-images.githubusercontent.com/5323259/133963514-3d847fe6-c856-40fa-aab9-89e9ab79f19f.jpg)

**Comment by paaljoachim** [comment]
https://wordpress.org/plugins/classic-editor/
I noticed this in the FAQ.

**Default settings for network installation**
There are two options:

- When network-activated this plugin will set the classic editor as default and prevent site administrators and users from changing editors.
The settings can be changed and default network-wide editor can be selected on the Network Settings screen.

- When not network-activated each site administrator will be able to activate the plugin and choose options for their users.

**Comment by joedolson** [comment]
Tried it activated in the individual site, and that also seems to not allow users to switch settings. Disabled it.

**Comment by paaljoachim** [comment]
Hey Joe

I tested the Classic Editor on a multisite testing environment I have. I made this post in the support forum for the Classic Editor plugin: https://wordpress.org/support/topic/rephrasing-updating-the-faq-for-network-installations/

I figure out by networking activating the plugin. That I could go to Settings, and scroll to the bottom and click the checkbox for "Allow site admins to change settings". Then go to a sub site and Settings -> Writing and select the default editor for the specific Sub site.

**Comment by paaljoachim** [comment]
Btw
I am not seeing a few options that are added to the Gutenberg plugin. Can you network enable the Gutenberg plugin?

**Comment by joedolson** [comment]
It is already network activated.

**Comment by paaljoachim** [comment]
Great!
Btw I am working on the documentation site right now.
