### ISSUE TITLE
Event screen: Move Event Location just under Event Details section.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#211]
I am thinking we should move the Event Location just below the Event Details section.
So it becomes like so:
Featured Image
Event Details
Event Location
Accessibility
Registration Settings
Special scheduling options (Capital S and O)

Because after Event Details it would be natural to have Event Location. After selecting the location then one can fill out the Accessibility section. Move on to Registration Settings and Special Scheduling Options.

**Comment by joedolson** [comment]
Mixed feelings about this. When the location fields are enabled, that's a pretty long form, which leaves a lot of scrolling to those other fields. But as a select field, much more reasonable. But, what I *can* do, is add an expansion toggle when both features are enabled. Then this only impacts people who aren't using the location selector.

**Comment by joedolson** [comment]
As I work on this, I'm now thinking that I'll reduce this to a single option, and always have both fields & selector grouped together. With the toggle to hide the field by default, there's no pressing reason not to have both, and it allows me to do a lot of code simplifications...

**Comment by joedolson** [comment]
This is functionally done; will do more work on the look, but closing the issue, anyway.

**Comment by paaljoachim** [comment]
That is a very good idea!
A user can toggle to open and close to Add a location.
