### ISSUE TITLE
Event Location - blank drop down - Add new location similar to Add new category

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#212]
I have started fresh thinking about the first experience a user will have with the event screen.

Add new category has been added to the event screen which helps a log in quickly adding a new category.

![Screenshot 2021-09-16 at 13 15 03](https://user-images.githubusercontent.com/5323259/133602572-c89737b0-7c9a-4789-a374-07c5fe2b8918.jpg)

We should do the same with Event Location. (Hmm I wonder if we already have an issue for this... I was not able to locate it.) Perhaps something similar to this:

![Event-Add-new-location](https://user-images.githubusercontent.com/5323259/133603072-b9598e5c-2021-4851-a74e-a2b1f18ff268.jpg)

Clicking the checkbox. Will open up the most used alternatives in a similar way as "Add new category" does today.
This way one can quickly add a location (less fields compared to going to the Locations tab). At the bottom there could be some info about for additional fields go to the Locations tab.

------------

An alternative instead of the same approach as categories would be to have an option in the drop down to create a new location.

**Comment by joedolson** [comment]
I'm not sure this is super necessary; it's already possible to have both the selector and the event input fields in place, and most of the fields are optional, anyway. So if this is a workflow somebody needs, they can basically already do it. I'll think about it, though.

**Comment by paaljoachim** [comment]
Ahhh yes. I had likely hidden the Location Fields as I have been working in the Input fields lately.
As Add Event has a way to already add a new location.
It is fine as it is (for now anyway).
Closing this issue. We can always reopen if/when it is needed.
