### ISSUE TITLE
Beginning to fill out an event and leaving the screen does not automatically save the event as draft.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#213]
I began to fill out event information and left when I was halfway done. There was no prompt asking me to save and no autosaving of the event into a draft event.

This means leaving an event it will disappear and one will not be able to find it again, and will have to start over.

**Comment by joedolson** [comment]
No autosaving, but I added a listener that prompts to save.

**Comment by paaljoachim** [comment]
That works nicely! Thanks!

![Screenshot 2021-09-19 at 21 31 35](https://user-images.githubusercontent.com/5323259/133940520-bc20a6c9-9719-4ba2-a555-b4e72369261a.jpg)
