### ISSUE TITLE
Settings > General "Use Pretty Permalinks for Events"

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#215]
I am going through the General settings screen.

"Use Pretty Permalinks for Events" is automatically clicked by default.
The URL looks like this: https://wp-5-8.dev.cc/my-calendar/?mc_id=2

Unclicking "Use Pretty Permalinks for Events" (I am also doing a hard refresh)
The URL looks like this: https://wp-5-8.dev.cc/my-calendar/?mc_id=2

Going to Permalink page I see this:
![Screenshot 2021-09-16 at 13 41 18](https://user-images.githubusercontent.com/5323259/133605936-be209008-08f7-4391-abfd-1cc08446d3a7.jpg)

I would assume that the above Event links would look a little different from each other. There is something that is just not clear for me...

**Comment by paaljoachim** [comment]
From the My-Calendar pdf documentation:
Use Pretty Permalinks for Events
By default, My Calendar uses event details links that look something like this:
http://yourdomain.com/my-calendar/?mc_id=24

If you enable pretty permalinks, you can have links that look more like:
http://yourdomain.com/mc-events/title-of-your-event/?mc_id=24

**Comment by joedolson** [comment]
Neither of those sets of links in your initial issue are using pretty permalinks. Are you able to turn on pretty permalinks at all?

**Comment by paaljoachim** [comment]
Now it is working. Weird.

On:
https://wp-5-8.dev.cc/mc-events/a-new-event-2/?mc_id=4

Off:
https://wp-5-8.dev.cc/my-calendar/?mc_id=4

Closing this issue.
