### ISSUE TITLE
Settings -> (adding an) Advanced tab

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#220]
I am wondering if we should add an Advanced tab.

General.
Moving -->
"Get data (events, categories and locations) from a remote database."
"Enable external API."

Having some information about this aspect of it.

At the moment I am not sure (no idea) which other options that would be suitable to add into an Advanced tab.
I am adding the issue so that we can add additional ideas to it.

**Comment by joedolson** [comment]
I feel that with so few advanced settings, it doesn't make sense to go beyond breaking out an 'Advanced settings' section on the general settings tab. 

Still don't want to add anything more than the bare minimum of descriptive information to the settings.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue. We can always reopen when/if it becomes needed.
