### ISSUE TITLE
Permissions left column has a long vertical line.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#222]
I am right now taking screenshots for the docs posts and noticed that the left Permissions column has a longer right edge vertical line.

![Permissions left column extra long vertical line](https://user-images.githubusercontent.com/5323259/134087157-9c827649-4f56-4bf9-96eb-aaba8fa89c14.jpg)

In CSS removing bottom margin:
.mc-tabs.vertical .tabs {
    margin-top: 0;
    /* margin-bottom: 20px; */
}

The screen is seen like this:

![Screenshot 2021-09-21 at 00 58 21](https://user-images.githubusercontent.com/5323259/134087361-88efc1d6-4467-4a01-9de6-1c4b3a06aedf.jpg)

**Comment by joedolson** [comment]
I forgot about that - during one of the middle phases of restructuring this, there were some weird CSS things going on, and this is left over from that period.

**Comment by paaljoachim** [comment]
Fixed:
![Screenshot 2021-09-21 at 09 20 44](https://user-images.githubusercontent.com/5323259/134128427-943dbad5-64dd-4555-bde6-ef06cebee071.jpg)

One more thing....
Cursor does not change to a finger when hovering over the role list items.
Cursor does change to a finger when hovering over e.g. Add Events text link in the Spectator area.

**Comment by paaljoachim** [comment]
I fully removed bbPress and WooCommerce to not show so many none relevant to My Calendar user roles.
It now looks like this:

![Screenshot 2021-09-21 at 09 39 57](https://user-images.githubusercontent.com/5323259/134131192-75c5c628-372a-4d5b-8344-9a96297370a9.jpg)
