### ISSUE TITLE
Settings - General: Punctuation of sentences.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#226]
This screen...
![Screenshot 2021-09-21 at 02 09 36](https://user-images.githubusercontent.com/5323259/134093035-28bb2033-8dfe-4981-b3b1-21c1d74cffc5.jpg)

Some have a punctuation at the end of a sentence others do not. These sentences could all have a punctuation at the end of each sentence.

Use Pretty Permalinks for Events
Get data (events, categories and locations) from a remote database.
Enable external API.
Drop MySQL tables on uninstall
Delete plugin settings on uninstall

**Settings for other screens**

None of these have punctuation creating consistency in this area.

**Comment by joedolson** [comment]
I think, given that *no* other settings have punctuation, I'd rather remove those two periods, and have consistency across the board.
