### ISSUE TITLE
Cursor does not change when hovering these clickable items

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#227]
I happen to notice that when hovering over the User Roles in the Permissions Settings screen that the cursor did not change from the default arrow to a finger.

----

I also noticed that when hovering over the Settings tabs did not change the mouse cursor from arrow to finger.

**Comment by joedolson** [comment]
This is correct behavior. The tabs are buttons, and the native hover cursor for buttons is the default arrow. 

There's an ongoing debate between whether or not this *should* be correct, but that's a separate issue...
