### ISSUE TITLE
Testing out shortcodes - Categories need a frontend fix

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#228]
I am testing out shortcodes related to this documentation I am updating: https://docs.joedolson.com/my-calendar/quick-start-guide/

This is the shortcode I end up with testing out:
[`my_calendar above="toggle, nav" below="print, key" format="list" time="week"]`

I decided to add the key - categories to the bottom area. 
Checking the Frontend I noticed this:
![Screenshot 2021-09-21 at 11 11 46](https://user-images.githubusercontent.com/5323259/134145298-aa61cf4d-a9b2-498f-ac45-9d018c4981d2.jpg)

The display of Categories does not look good and need some brushing up.

**Comment by joedolson** [comment]
For anything related to styles, always specify which My Calendar stylesheet is in use in which WordPress theme. These can come from any number of places (e.g., may need to strengthen styling to override a theme); and some older My Calendar stylesheets just won't work particularly well anymore. There's just nothing actionable without specifics.

**Comment by paaljoachim** [comment]
What the above shows is just the default. Going to the Style Editor I see that the default is using twentytwenty.css.

I switched to various default themes as well as other themes. In general it looked like the above.
Here is an example from 2019 theme.

![Screenshot 2021-09-22 at 22 37 10](https://user-images.githubusercontent.com/5323259/134418120-728258da-85f0-408b-93ad-f5345efab723.jpg)

.my-calendar-header > div, .mc_bottomnav > div {
    display: inline-block;
}

Switching display to contents the category kinda aligns to the right of the word Categories.

I got to think about this some more. I just feel that in some way there is a need of a cleanup here.

**Comment by joedolson** [comment]
I think it's reasonable to convert the categories heading into a screen-reader only heading. That would make these much easier to align across different designs. The context should still be pretty easy to determine.

**Comment by joedolson** [comment]
FYI, `display: contents` is not yet a usable declaration for accessibility reasons. It's OK in Chrome & Firefox, but Safari still strips out the semantics, which breaks everything for screen readers.

Marking this as resolved per the referenced commit.
