### ISSUE TITLE
Shortcodes meta box - confused about "Search keyword"

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#229]
As I go through the various shortcode options. I notice a helpful note in relation to location filter values.
Below it we have Search keyword which I am not certain what actually does. It would be helpful to also add a note to the search keywords section. With a few sentences of what Search keyword is.

![My Calendar WordPress plugin default page Meta Box options](https://user-images.githubusercontent.com/5323259/134147773-70e76ba3-bec3-42cb-9431-b39c086b429f.jpg)

**Comment by joedolson** [comment]
Filters the calendar according to a text search. E.g., show all events containing a specific word.

**Comment by paaljoachim** [comment]
Adding a Search Keyword will then only show events that use the specific keyword in the title or description.

![Shortcodes](https://user-images.githubusercontent.com/5323259/134417549-c9878584-7ab5-4fa1-9c11-5f47633749d2.jpg)

I added the following note below the Search keyword field.
"Show only calendar events containing the search keyword."

**Comment by paaljoachim** [comment]
Great! This is very helpful!

![Screenshot 2021-09-22 at 23 43 23](https://user-images.githubusercontent.com/5323259/134426098-f5d92032-0506-48d0-9bba-f2b5a9de1463.jpg)
