### ISSUE TITLE
My Calendar Permissions: Removing plugins that add user roles does not change the border line.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#230]
I fully removed bbPress and WooCommerce to not show so many none relevant to My Calendar user roles.
It now looks like this:

![134131192-75c5c628-372a-4d5b-8344-9a96297370a9](https://user-images.githubusercontent.com/5323259/134420295-a505a1ee-a6e2-4061-a982-16b601619426.jpeg)

(Brought over from this closed issue: https://github.com/joedolson/my-calendar/issues/222#issuecomment-923721515)

**Comment by joedolson** [comment]
The left border I get; it's actually a border on the permissions container, not the roles container.  I'll have to look and see where the bottom border is coming from, however.
