### ISSUE TITLE
Settings > General > Default sort order for Admin Events List drop down

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#231]
The drop down:
![Screenshot 2021-09-22 at 23 55 40](https://user-images.githubusercontent.com/5323259/134427483-86bde5f3-2e3f-4353-b742-06935be02967.jpg)

Relates to the columns in the Event screen:
ID, Title, Location, Date/Time, Author and Category.
![Screenshot 2021-09-22 at 23 57 38](https://user-images.githubusercontent.com/5323259/134427630-7182bdc3-0233-4cf4-a63a-9c02b0abc5ac.jpg)

Let's use the same Admin Events List names both places.

**Comment by joedolson** [comment]
Boy, that points out some changes I've made over the years. Description hasn't been part of the table for a long time...

**Comment by paaljoachim** [comment]
The process of going through every option in the settings panel (for the documentation) really brings forth a lot of the dust. It feels like I am really going deep in the basement to clean every corner..:)

**Comment by joedolson** [comment]
Wanna come over to my house, too? It could use the same treatment. :D

**Comment by paaljoachim** [comment]
LOL! 
The next time I am in Minneapolis (no idea when) I will come on by with gloves and a bucket of water filled with a nice scented soap..:)
