### ISSUE TITLE
Settings > General > Get data

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#232]
I am looking at the My-Calendar-v3.2.0 pdf

In Settings I see. Clicking the checkbox for Get data and Enable external API.

![Screenshot 2021-09-23 at 00 13 42](https://user-images.githubusercontent.com/5323259/134429122-ab9225a4-6722-4fd7-956e-7e2efa1cd4a5.jpg)

In the pdf I see.
![Screenshot 2021-09-23 at 00 15 42](https://user-images.githubusercontent.com/5323259/134429232-c7de593f-e5d8-4e19-8aba-43297f6c46b6.jpg)

Does this mean that clicking the Get data checkbox will open information
"Add this code to your theme's functions.php file:"
--- then code --
and additional information below?

**Comment by joedolson** [comment]
That'll only be visible if you've actually enabled the function. (Checked & saved.)

**Comment by paaljoachim** [comment]
Ok. Thanks. Closing this issue.
