### ISSUE TITLE
Delete link missing in the Network Admin Installed Plugins screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#234]
I downloaded the multi-site tab fix latest update of My Calendar and was about to delete the last version I used in the multisite. This is what I saw.
![Screenshot 2021-09-23 at 00 59 50](https://user-images.githubusercontent.com/5323259/134432991-5cc61b7e-afb5-4987-9bbe-4fa035676cba.jpg)

There is no delete link to remove the plugin.

**Comment by joedolson** [comment]
Do you still have My Calendar active? You can't delete plugins in multisite if they're activated on any sites.

Best,
Joe

**Comment by paaljoachim** [comment]
Ahhh yes. It was active in the primary site. I turned it off there and now I can delete the plugin.
Thanks!
