### ISSUE TITLE
Adding new location directly in event deletes existing locations in location screen (or is not added).

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#235]
I was testing out the new Add a location toggle button in the event screen, and added a new location I called "House of Blues". 

![Screenshot 2021-09-24 at 11 33 47](https://user-images.githubusercontent.com/5323259/134653009-8abaf201-0ffc-4d28-9197-fa2c5437dfcd.jpg)

Went to another event and added another location I called "Waterworld theme park" by using the new toggle button.
Checked the All events screen and noticed that House of Blues had taken over the 3 events I had listed.
I checked the Locations screen and noticed that there was only the House of Blues location listed. Waterworld theme park and the other location I had from earlier had been removed.

![Screenshot 2021-09-24 at 11 31 33](https://user-images.githubusercontent.com/5323259/134652777-bc988cf5-6bac-4123-989b-81617fa7969c.jpg)

I am able to add a location through the Add New Location screen.

**Comment by joedolson** [comment]
With the extensive changes here, I expected some bugs. Pretty sure I know what this is.

**Comment by joedolson** [comment]
I actually haven't been able to reproduce this issue. It wasn't what I thought it might be. However, I just committed a change that *might* impact this - please re-test!

**Comment by paaljoachim** [comment]
It looks like it is working now!
I assume we can close this issue.

**Comment by joedolson** [comment]
If the same problem re-occurs, re-open this. But for now, yes, I think we can close.
