### ISSUE TITLE
Renaming and then removing Permalinks Events base and Locations base should bring back default name.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#236]
Let's say that I rename the My Calendar Events base but later on remove it and want to bring the default name (mc-events) back. 

![Screenshot 2021-09-24 at 11 41 35](https://user-images.githubusercontent.com/5323259/134654216-463c3df2-427a-4351-a4e6-9393ff3f8503.jpg)

Let's perhaps add a placeholder of the default Events base and the Locations base so the user can go back to using the default.

**Comment by paaljoachim** [comment]
Actually now that I also look at the Settings -> Text screen I wonder if we in general can use a placeholder when e.g. removing Posted by.

![Automatic-placeholder-blank-fields](https://user-images.githubusercontent.com/5323259/134657403-9bb483af-0303-4d87-87b9-484bff53d10d.jpg)

The reason why to add automatic placeholders is that the user might remove a default and keep it blank, and just seeing the ghost of the default the user can remember what the default was. For instance user renames a field but decides not to use it but wants to go back to default name.

**Comment by joedolson** [comment]
*technically*, there's no need to have a value in the permalink slug fields at all, as they will always fall back to mc-events/mc-locations when empty. But a placeholder could be useful for indicating the default value.

**Comment by joedolson** [comment]
Placeholders on permalink bases added in https://github.com/joedolson/my-calendar/commit/081527d7288a77ed8316e1644d38248397df8ab1

Placeholders on settings fields are harder; I'll have to review those.

**Comment by joedolson** [comment]
I'm closing this; the placeholders on settings fields is really a different issue from the title of this issue.
