### ISSUE TITLE
Text settings: Extended caption adjustment.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#239]
Text settings -> Extended caption

Extended caption: - fields - Follows month/year in list views.

![Screenshot 2021-09-24 at 13 10 10](https://user-images.githubusercontent.com/5323259/134666049-ac375905-ebcc-4b8e-8877-583aef9059d3.jpg)

Adjusting: Follows month/year in list views. ----> Follows month/year in list/grid views.

**Comment by joedolson** [comment]
But it doesn’t; it’s not used in grid views.

**Comment by paaljoachim** [comment]
Hmm... right now I have Twenty Nineteen theme activated.
In the Style Editor - twentyfourteen.css

Setting Text
![Screenshot 2021-09-24 at 16 26 54](https://user-images.githubusercontent.com/5323259/134691456-b13842f0-83d2-4bf4-b04c-d06382b4012b.jpg)

Grid
![Screenshot 2021-09-24 at 16 27 08](https://user-images.githubusercontent.com/5323259/134691496-307aeb30-cf45-48a5-be20-42fde61c336c.jpg)

List
![Screenshot 2021-09-24 at 16 27 17](https://user-images.githubusercontent.com/5323259/134691530-35c5d3fc-6682-4975-91e1-0f49377050b6.jpg)

**Comment by joedolson** [comment]
Huh. So it is. Now, did I change that at some point? Is that a mistake? Do I just misremember? Who knows. 12 years of development can involve a lot of different decisions... :shrug:

**Comment by paaljoachim** [comment]
I think it is a good idea that it is added to List and Grid views..:)

**Comment by paaljoachim** [comment]
This works.

"Follows month/year in calendar heading."

![Screenshot 2021-09-26 at 22 13 18](https://user-images.githubusercontent.com/5323259/134822675-4d7c8a33-61c8-40fe-bc76-b49ddb13ed86.jpg)
