### ISSUE TITLE
Text settings - not sure how Title element template works.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#240]
I am looking through Text settings and I have yet to figure out how Title element template works.
I have read the documentation and turned off the popup card view so that it goes straight from the calendar to single event view.

From the docs:
Title element template: If you're using My Calendar with a set-up that gives each event its own page view, this template provides a <title> element customized to that event, rather than the generic title for the calendar page itself. HTML will be stripped from this field, as the <title> element cannot con- tain HTML.

**Comment by joedolson** [comment]
The title element gives the current tab a name in the browser.

**Comment by paaljoachim** [comment]
Ahh. Can we change the name to Title browser tab element? Or something like that. As Title element template it fairly difficult name to guess.

I am not sure that I am "getting it".

Adding the word TEST
![Screenshot 2021-09-24 at 16 24 01](https://user-images.githubusercontent.com/5323259/134690824-ba5a4d16-bce0-4beb-9f56-a157516810bc.jpg)

Checking an event in the browser window.

![Screenshot 2021-09-24 at 16 24 12](https://user-images.githubusercontent.com/5323259/134690950-83eb6ed8-8872-46f9-a84a-f2a390383816.jpg)

**Comment by paaljoachim** [comment]
Yep! This is what I see now.
![Screenshot 2021-09-24 at 21 54 12](https://user-images.githubusercontent.com/5323259/134732523-b9ae19b4-f8c2-406b-b275-a9aa9271f7e3.jpg)
