### ISSUE TITLE
Settings Output - Adjust "Disable calendar links"

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#241]
Settings -> Output

The "Disable calendar links" is actually a "Disable calendar **event** links"
Let's rename it.

![Screenshot 2021-09-24 at 16 43 28](https://user-images.githubusercontent.com/5323259/134694082-614ffaff-d950-42d3-bac9-757b677fa063.jpg)

**Comment by joedolson** [comment]
That seems marginally more accurate. I'm still not sure it's super clear, but willing to go with it.

**Comment by joedolson** [comment]
Actually, I'm going to collapse these two options into a select with three choices: open in popup cards, open in single event view, and disable event links. I think that'll clarify better.

**Comment by paaljoachim** [comment]
(I was originally about to write this...:)
The "Disable calendar links" = could be any link in the calendar. Previous/Next or any other link.
A "Disable calendar event links" = says it will disable event links.

-----

Moving on to your next comment. Brainstorming...

Calendar event links will: -drop down-
open in popup cards
open single event view
are disabled

**Comment by joedolson** [comment]
What I meant was more that event "disable calendar event links" implies that it will disable all event links, which could suggest that it will not be possible to link to an event, e.g., disabled the target page. But I think that going to a single control is better, anyway. Gives more context, fewer settings, etc.

**Comment by paaljoachim** [comment]
A single control makes it a lot better.

**Comment by paaljoachim** [comment]
This is helpful.
![Screenshot 2021-09-24 at 21 52 20](https://user-images.githubusercontent.com/5323259/134732382-7d4db1eb-1168-443a-92b8-8e0329bafa3c.jpg)
