### ISSUE TITLE
Text Settings - Date/Time formats - capital/small letters

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#243]
There is here a mix of capital and small letters.
Based on the above Main Calendar View and Single Event View

Date/Time formats should be Date/Time Formats.

Time format should be Time Format
Month format should be Month Format

![Screenshot 2021-09-24 at 21 47 51](https://user-images.githubusercontent.com/5323259/134731900-550f2c35-429c-4b74-b999-425b2a1e09e3.jpg)

Date Format for multi-day events date) should be adjusted. It has a ) at the end but not in the beginning.

**Comment by joedolson** [comment]
That's a wrapping/layout error: the description string is wrapping under the label on the narrow screen.

**Comment by paaljoachim** [comment]
Ahhh yes this sentence "September 24-25, 2021 (Use %d to represent the end date.)" wraps below the text in front of the text field.

**Comment by paaljoachim** [comment]
This is what it looks like after the adjustment.
![Screenshot 2021-09-25 at 10 48 33](https://user-images.githubusercontent.com/5323259/134765618-602960ce-08c3-427d-95f4-a34cf290015f.jpg)

Interesting to see the ? to find out more about a specific option.
