### ISSUE TITLE
Setting Input - Location Controls

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#245]
I just tested the Location controls and I called out "cooool". Wow what a cool feature!
![Screenshot 2021-09-24 at 22 54 02](https://user-images.githubusercontent.com/5323259/134738589-4d79cd74-6c8a-44ee-9c5c-7483c95e2cc6.jpg)

I happen to click the Save Input Settings which is right above the Location Controls a few times and wondered why it did not save. Then I noticed the Update Location Controls just below the Location Controls.

I began testing out the various controls.

Can I add a none or something like that to hide specific location controls? For instance hiding country and region. Actually I would also like to hide Street Address (2).
If it is possible to hide specific controls then it would be helpful to add more information next to the current information under the Location Controls.

**Comment by joedolson** [comment]
Nope. Not currently possible to hide inputs.

**Comment by paaljoachim** [comment]
One more thing.
It was unclear what "Label" did until I noticed the field "Name of Location" suddenly had a drop down.

Should Location Controls reflect the names listed in the Locations screen?
I am also reordering the Location Controls to the same order seen in the Locations screen.

Label = Name of Location
City
State = State/Province
Postcode = Postal code 
Region
Country

**Comment by paaljoachim** [comment]
Great. It now uses the same field names as can be seen in the Add/Edit Location screen.

![Screenshot 2021-09-26 at 22 19 23](https://user-images.githubusercontent.com/5323259/134822837-bb974249-2fd0-4861-ac79-578073dd16fc.jpg)
