### ISSUE TITLE
Settings > Notifications - Message Body

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#246]
Email subject : New event added (I found it a bit strange with the : before the text)

![Screenshot 2021-09-24 at 23 45 56](https://user-images.githubusercontent.com/5323259/134743098-d84c2826-10c1-43c0-bc80-3969738562b6.jpg)

I am wondering if there should be additional tags/shortcodes listed below the Message Body field or perhaps an example showing what it could look like. Here I am working on getting the Message Body area as clear as possible making it easy for the user to understand how it should be used.

**Comment by joedolson** [comment]
Does your dev site not have a name set? The value before the colon should is `get_bloginfo( 'name' )`, which I generally don't consider as something that particularly needs a fallback. I could probably do something like "WordPress" as a fallback, if needed.

**Comment by paaljoachim** [comment]
Ahhh. The dev site did not have a name set. I set the name. I would think that most sites will automatically have the name set.
![Screenshot 2021-09-26 at 22 22 22](https://user-images.githubusercontent.com/5323259/134822892-786775da-652d-48e1-abd9-d5a57c540bdf.jpg)

I see the ? below the Message Body.

I assume we can close this issue.
