### ISSUE TITLE
Placeholders on Text Settings fields

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#247]
Actually now that I also look at the Settings -> Text screen I wonder if we in general can use a placeholder when e.g. removing Posted by.

![134657403-9bb483af-0303-4d87-87b9-484bff53d10d](https://user-images.githubusercontent.com/5323259/134820614-fc30da90-bffb-4a10-b7fa-1a31014be53e.jpeg)

The reason why to add automatic placeholders is that the user might remove a default and keep it blank, and just seeing the ghost of the default the user can remember what the default was. For instance user renames a field but decides not to use it but wants to go back to default name.

Brought over from: https://github.com/joedolson/my-calendar/issues/236#issuecomment-926507367

**Comment by joedolson** [comment]
After exploring this, it would require some surprisingly significant work to deal with. Mostly because the settings field function is used for both functions that must have a value set and functions where having a value is optional. Future release.

**Comment by joedolson** [comment]
Fixed when I refactored the settings field output.

**Comment by paaljoachim** [comment]
I really really like this! It is very helpful!
As it shows the default values if the user has not filled in anything.

![Screenshot 2023-01-04 at 15 37 04](https://user-images.githubusercontent.com/5323259/210578772-3b7f826b-302a-44e3-902c-ab3bc93b0190.jpg)
