### ISSUE TITLE
Clearing up a logic flow - Settings Input -> Event editing fields to show

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#249]
I am going through the logic flow. (Yes we have gone through this before, but I am looking into how to explain this in the documentation.)

1 test.
Settings -> Input
Event editing fields to show.
I turn off/uncheck Repetition Pattern.

Go to Add Event.
Notice that Repetition Pattern has been removed from the Add Event screen.

Add Event: I check Screen Options notice that Repetition Pattern is removed.

2 test.
I go back to Settings -> Input. Turn on/check Repetition Pattern.
Go back to Add Event and notice Repetition Pattern is again visible as one of the fields.
Go to Screen Options. Notice that Repetition Pattern is also seen there. I uncheck Repetition Pattern and click Apply. Notice that Repetition Pattern is not seen in the Add Event screen.

I check other events and also create a new Add Event and notice that Repetition Pattern is turned off.
I go to Settings -> Input and notice that Repetition Pattern is checked there.

--

Unchecking a field under Settings -> Input "Event editing fields to show" will remove it from Screen Options.
Unchecking a field under the Screen Options will just uncheck it.
Should unchecking in the Input screen leave the option in Screen Options but just uncheck it? I am not sure how to handle these two options - Event editing fields to show and Screen Options.

**Comment by joedolson** [comment]
Unchecking in the Settings means "this option is not available". Unchecking in the screen options means "I, personally, do not intend to use this field, though other users might". So yes, it's correct behavior for an option to go away if it's turned off in settings.

**Comment by paaljoachim** [comment]
Thanks for the clarification!

**Comment by paaljoachim** [comment]
I added to the documentation here: https://docs.joedolson.com/my-calendar/my-calendar-input-settings/
