### ISSUE TITLE
Editing the shortcode box

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#250]
Let's say that I go to the My Calendar -> Shortcodes screen and create a shortcode.
![Screenshot 2021-09-27 at 22 02 19](https://user-images.githubusercontent.com/5323259/134977085-ff1b3be9-fb26-4ad1-b178-0e19b56c74d7.jpg)

I select the shortcode and copy it.
Go to All Pages -> My Calendar and click the shortcode box and try to paste inn the shortcode by using ctrl+v. I then try to write in the box, but I am not able to do anything in it.

The grey shortcode boxes are not editable. I am not able to click into these to manually write a shortcode or to paste in a shortcode.

**Comment by joedolson** [comment]
True, although it can be edited anywhere you paste it into. I'm not sure there's a huge value to being able to edit it here.

**Comment by paaljoachim** [comment]
Having the area editable would also give the chance for a user manually going in to edit.
But we can just let it go for now and close the issue and if needed and more use cases show up then we can look at it again.

**Comment by joedolson** [comment]
Seems pretty nominal to me, but I'll think about it. Closing for now.
