### ISSUE TITLE
Scheduled dates for this event: adding additional dates.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#253]
I am working on this doc: https://docs.joedolson.com/my-calendar/my-calendar-add-events/

I noticed when clicking multiple dates to the "Scheduled dates for this event" area that it end up looking like this:
![Screenshot 2021-09-27 at 23 10 33](https://user-images.githubusercontent.com/5323259/134986120-028a7dc6-84b6-46a3-8e79-e52d63342d96.jpg)

Event 1. Shows a grey box.
Event 2 and 3 shows + and date in a bit weird way. (It seems like seconds are also being added to the time.)
Event 4 and 5 are below the Event 1 grey box. I assume that Event 4 and 5 should be straight under Event 2 and 3. Like so in this mockup:

![Scheduled-dates-for-this-event-dates-mockup](https://user-images.githubusercontent.com/5323259/134986736-f53caf07-306d-4e05-87e6-d34350ec7acf.jpg)

If there are additional dates then these would be below, and might end up pushing Add another date button further down.

![Scheduled-dates-for-this-event-dates-mockup2](https://user-images.githubusercontent.com/5323259/134986788-4fefe415-22ed-474c-90ea-ee79e0de58c9.jpg)

**Comment by joedolson** [comment]
Can you look at the CSS and make specific suggestions?

**Comment by paaljoachim** [comment]
Here is one suggestion. One I actually managed that looked alright.

#e_schedule .columns.instance-list li {
    padding: 10px;
    background: rgba( 0,0,0,.05 );
    height: 80px;
}

![Screenshot 2021-09-27 at 23 53 13](https://user-images.githubusercontent.com/5323259/134990898-035665cf-3d42-42ee-89ae-c650cfabbe8d.jpg)

**Comment by paaljoachim** [comment]
Another suggestion.

#e_schedule .columns.instance-list {
    grid-template-columns: repeat( 4, 1fr );
    grid-template-columns: auto auto auto auto;
}

![Screenshot 2021-09-27 at 23 53 13](https://user-images.githubusercontent.com/5323259/134992072-362e6595-f5c3-46b3-968c-43b877a42e9c.jpg)

**Comment by paaljoachim** [comment]
Yes that looks better.
![Screenshot 2021-09-28 at 12 09 10](https://user-images.githubusercontent.com/5323259/135067774-d3792588-a710-400a-8572-5dff7e126c38.jpg)
