### ISSUE TITLE
Checking Event Display Fields - Single Event, Calendar Popup, List View and Mini Calendar Popup

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#257]
Comment from: https://github.com/joedolson/my-calendar/issues/191#issuecomment-929662671
> Needs checking to verify that all options display as expected. This was a pretty major change.

I am using the theme Twenty Twenty One.
Stylesheet: twentytwenty.css

Output Settings:

Tabs for: Single Event, Calendar Popup, List View and Mini Calendar Popup.
![Screenshot 2021-10-01 at 11 38 42](https://user-images.githubusercontent.com/5323259/135599257-0028fe8f-4211-495d-957a-9f40c5e2d0e0.jpg)

Testing Single Event (checking all the checkboxes)
Author
Host
iCal Download
Share to Google Calendar
Link to Google Map 
Google Map 
Location Address
Excerpt
Description
Featured Image
Registration Settings
External Link (capital L)
Accessibility Information (capital I)

I added a Google Maps API Key

**Backend** in relation to Featured Image, Event Details, Event Location and Location Map (uses a bigger font)

![Screenshot 2021-10-01 at 12 04 44](https://user-images.githubusercontent.com/5323259/135602679-e52226db-1568-4648-9c91-6d5ea7dd1f7d.jpg)

---

**Frontend**

This is what I see:

![Single-Event](https://user-images.githubusercontent.com/5323259/135603537-eb2bd9e8-e164-4800-95ce-b4123a1cbc36.jpg)

---

Location Address shows up twice.
No Google map is seen.
The various fields are listed in a single column.
In general it needs to be prettified.

(Of course having a way to style where the fields go in relation to each other would be a wonderful feature. Which I will need to create a Github issue for.)

Associated: 
Setting Output: Event Display Fields - default preclicked checkboxes
https://github.com/joedolson/my-calendar/issues/256

**Comment by paaljoachim** [comment]
Calendar Popup.
All checkboxes have been checked.

![Calendar-popup](https://user-images.githubusercontent.com/5323259/135609476-7e974cc9-25ba-492f-b20b-a5887b6a9351.jpg)

**Comment by paaljoachim** [comment]
List View. 
List View tab. All checkboxes have been checked in the Output Settings List View.

Grid View (2 events are seen 1 October)
![Screenshot 2021-10-01 at 13 04 32](https://user-images.githubusercontent.com/5323259/135609962-ed7bc0d4-fbf8-4993-9dae-4a8f51c8072c.jpg)

Changing to List View. (The two events become almost merged into one.)


![List-View](https://user-images.githubusercontent.com/5323259/135610315-bad55b85-6d71-4973-bd45-2f1e819dc41d.jpg)

**Comment by paaljoachim** [comment]
Mini View.
All checkboxes have been checked in Output Settings in the Mini View tab. (It looks very similar to List view just above.
![Screenshot 2021-10-01 at 13 11 03](https://user-images.githubusercontent.com/5323259/135610792-c4e75af2-d2be-4cd8-ad5f-5eb0cdb5d039.jpg)
)

**Comment by joedolson** [comment]
It's a stylesheet thing; there's just no padding on `p` elements inside the details container.

**Comment by joedolson** [comment]
Resolved with a style change, though this will only propagate to some users.

**Comment by paaljoachim** [comment]
Fresh install of My Calendar.
Using Twenty Twenty One.
Chrome
Using default twentytwenty.css

Default views (with default output fields selected)

**Popup view.** (I am though not seeing the Event title. As I expected to see this in the top left area...:)
![Screenshot 2021-10-03 at 09 46 49](https://user-images.githubusercontent.com/5323259/135744977-7c62ce60-ecc1-4fba-9fc1-4a1323364145.jpg)

**List view.** (Here I see the title)

![Screenshot 2021-10-03 at 09 51 34](https://user-images.githubusercontent.com/5323259/135745069-79eb61ad-6e8a-44e0-8d94-8c0083820cb9.jpg)

Single view (50% zoom)
![Screenshot 2021-10-03 at 09 52 32](https://user-images.githubusercontent.com/5323259/135745086-e7e9ae96-9ab9-4d46-ac67-44bc0429c4be.jpg)

**Comment by joedolson** [comment]
Closing this in favor of subsequent issues.

FYI, the title in the grid output is a setting at Settings > Output > Grid Output. 

It's definitely a setting that could fairly be removed entirely; I'm not 100% sold on the idea of only sometimes showing the title.

**Comment by paaljoachim** [comment]
Hmm can we by default automatically show the title for all views?
If the user wants to turn it off they may.
Opening a new issue for this aspect.
