### ISSUE TITLE
Output Settings: Merge Calendar Popup and List View into one tab.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#258]
I am bringing this onward from:

https://github.com/joedolson/my-calendar/issues/256#issuecomment-932450124

> The List view and Calendar popup should be equivalent; I'm actually not totally sure I should even have separate settings for them - if they're different, that opens the possibility that users on mobile could see incomplete information, which is fuzzy.
> 
> However, since a user could disable one or the other view, as well, that makes things complicated. For now, I want the List and Popup defaults to be the same.

I added a new event and checked out the Popup vs List View and as you say these should likely be the same. As they are almost identical anyway.

The question comes up should Calendar Popup and List View be merged into one tab?
Another option is having changes in one also automatically change the other.
Not sure here....

**Comment by joedolson** [comment]
Continuing to think about this, I think they should be merged into a single tab. 

First, this doesn't totally prevent somebody from customizing them separately, using templates. So it's still possible to produce different content - it just requires more thought to do so.

Second, the primary usage is to either use only one of the two views *or* to have both available. In the latter case, they should be the same; in the former, it doesn't matter whether they're the same. In either case, everything works fine if they are the same. 

So I'm going to collapse those into a single set of settings. I don't see a benefit to having changes automatically propagate; I think that would be very confusing for users.

**Comment by paaljoachim** [comment]
I agree on collapsing into single set of settings because the popup and list view are almost identical views.

**Comment by paaljoachim** [comment]
Merging of Popup and List views now looks like this:
![Screenshot 2021-10-03 at 10 42 28](https://user-images.githubusercontent.com/5323259/135746315-c40a2f87-ddd7-4cbf-9fa8-811a326a11ee.jpg)
