### ISSUE TITLE
Export and Import events, locations, categories etc.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#259]
I am thinking it would be helpful to be able to export and import events, locations, categories etc from one calendar to another. It would also be a way to import demo content for the calendar.

**Comment by joedolson** [comment]
That's already possible in My Calendar Pro. It could use some love, but it does exist. You can use the My Calendar API endpoint (e.g.  https://demos.joedolson.com/?to=2021-10-02&from=2021-09-02&mc-api=csv) to import events, categories, and locations at My Calendar Pro > Importer > Import from URL. 

(To test, be sure to use the latest versions of both plug-ins; there are a couple of data shape changes that will make a difference.)

**Comment by paaljoachim** [comment]
I am moving the issue over to:
https://github.com/joedolson/my-calendar-pro/issues/16

Closing this issue.
