### ISSUE TITLE
Google/Outlook iCal feeds should include recurring events

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#26]
Problems to resolve: number of events could be very high. If included as unique events, this will becoming a very large export/import. Will need to parse recurrence patterns into iCal recurrence formats for this to work.

**Comment by joedolson** [comment]
Adding RRULE to ical output theoretically fixes this; needs testing.

**Comment by paaljoachim** [comment]
How would we go about testing?

**Comment by joedolson** [comment]
1. Create a recurring event.
2. Add the 'feeds' navigation item to the calendar display.
3. Download the ical output & verify whether the recurring events are present and accurate.

**Comment by paaljoachim** [comment]
-1- 
Added recurring events.

-2- 
(Had to look up what you meant with exports navigation item. Found it in the 3.2 PDF.) Went to the My Calendar page and in the Meta Boxes added "exports" to the Navigation below calendar item.  

Meta boxes:
![Screenshot 2021-12-12 at 22 46 31](https://user-images.githubusercontent.com/5323259/145730811-f64c3c55-d1ea-4fd1-8551-cca2c460e8ba.jpg)

Frontend:
![Screenshot 2021-12-12 at 22 45 03](https://user-images.githubusercontent.com/5323259/145730772-9441f325-6803-4293-97f5-3d6df93fb190.jpg)


-3-
Clicked Google download icon/text. Went to this page: 
https://my-calendar.dev.cc/feed/my-calendar-ics/?time=month&yr=2021&month=12&dy=1&nyr=2022&nmonth=1&export=google

Saw this:
![Screenshot 2021-12-12 at 22 48 42](https://user-images.githubusercontent.com/5323259/145730881-a427916c-57a6-4533-bc3f-f3248f107c43.jpg)


Clicked Outlook download icon/text. Went to this page: 
https://my-calendar.dev.cc/feed/my-calendar-ics/?time=month&yr=2021&month=12&dy=1&nyr=2022&nmonth=1&export=outlook

With the same result as clicking the Google download icon/text.

**Comment by paaljoachim** [comment]
Console error:
Failed to load resource: the server responded with a status of 404 (Not Found)  my-calendar.dev.cc/:1

![Screenshot 2021-12-12 at 22 50 51](https://user-images.githubusercontent.com/5323259/145730991-0e621b37-519a-4de6-b543-6e8f8c2cb0bf.jpg)

**Comment by joedolson** [comment]
Visit Settings > Permalinks, then re-check the link.

**Comment by paaljoachim** [comment]
I added a new Recurring event. 
Went to Settings > Permalink and resaved.
Frontend: clicked the download icon/Google. Downloaded the my-calendar-my-calendar-dev.ics

Double clicked the downloaded file. The Mac program Calendar opened. It begin Importing Calendar Data.

![Importing](https://user-images.githubusercontent.com/5323259/145735655-0a169c5d-1476-4b7b-9c76-3f1511af1261.jpg)

It is still importing these events (not many events). 
![Screenshot 2021-12-13 at 01 20 24](https://user-images.githubusercontent.com/5323259/145735685-a19f3277-b1e9-490f-9a98-fab52668c0f1.jpg)

It looks like it is on a loop. Atleast 4-5 minutes have now passed.

**Comment by paaljoachim** [comment]
Obs my mistake!
I had to click Adding a new event and select Work or Home before it was imported.
![Screenshot 2021-12-13 at 01 23 57](https://user-images.githubusercontent.com/5323259/145735895-1fd4b272-9398-4672-8034-a981a8b97dc0.jpg)

Clicking the Recurring event
![Screenshot 2021-12-13 at 01 25 03](https://user-images.githubusercontent.com/5323259/145735879-eabe0ac7-5556-4ad0-90de-552fecdd1faf.jpg)

**Comment by paaljoachim** [comment]
The Outlook download is also working.

**Comment by joedolson** [comment]
Whenever I test imports into Outlook, there's a dialog that pops up like that - but it pops up *behind* the browser, and I inevitably either wait for 5 minutes or I just click the link several times because I forget about that...

Looks good. My tests worked too. 👍

**Comment by paaljoachim** [comment]
Great!
