### ISSUE TITLE
Location drop down has a lot of space.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#261]
I noticed that after adding one location that the location drop down in Edit or Add Event looks like this in Chrome:

![Screenshot 2021-10-03 at 09 42 50](https://user-images.githubusercontent.com/5323259/135744808-a938ad1f-9cd3-4426-bbbc-6dd5d7017408.jpg)

**Comment by paaljoachim** [comment]
Weird stuff going on
![Screenshot 2021-10-03 at 15 06 33](https://user-images.githubusercontent.com/5323259/135754938-1988fa28-8cd8-4216-9f40-dd6e0f86185c.jpg)

**Comment by joedolson** [comment]
What it looks like is that you're getting a bunch of locations created with no location names. Are these visible in the Location manager?

**Comment by paaljoachim** [comment]
Yes. They are visible in the Locations screen.
![Screenshot 2021-10-03 at 17 27 36](https://user-images.githubusercontent.com/5323259/135760844-e312f18f-c185-4c32-9b36-8d98dd1f1b83.jpg)
![Screenshot 2021-10-03 at 17 27 57](https://user-images.githubusercontent.com/5323259/135760846-45b2e65c-1c02-46b8-aba2-bb5ed84a0975.jpg)

**Comment by joedolson** [comment]
I think it's a problem with inserting locations automatically when you create an event that has no location, with no default location set. E.g., none of the location fields have a value, and it injects an empty location. 

Will test; I have a default location set, so it would also choose a location for me - if you don't have a default (and it appears above that you don't), then that would happen for you. If so, should be easy to fix.

**Comment by paaljoachim** [comment]
Yes. That is correct. I have no default location set.

**Comment by paaljoachim** [comment]
Looks good.
![Screenshot 2021-10-03 at 23 24 08](https://user-images.githubusercontent.com/5323259/135771991-0aaf1d5c-f074-4a35-9492-663672ad0f2b.jpg)
