### ISSUE TITLE
Featured image size in Single Events

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#262]
Example from: https://github.com/joedolson/my-calendar/issues/257#issuecomment-932883448
Single view. 50% zoom

![Screenshot 2021-10-03 at 09 52 32](https://user-images.githubusercontent.com/5323259/135745395-773b765d-328c-4e48-b4ab-8d02ff1b9b68.jpg)

I am wondering how we might go about controlling the featured image size in the single view?

**Comment by paaljoachim** [comment]
There could perhaps be a featured image size setting in the Featured Image section in the backend events screen.
![Featured Image select size](https://user-images.githubusercontent.com/5323259/135754460-7e924c37-8505-46ad-bc41-f81c5f823779.jpg)

**Comment by joedolson** [comment]
Do you think that's really something people would do for an individual event? I'd think of that kind of setting as a design decision, done at the template/layout level.

**Comment by paaljoachim** [comment]
Adjusting the Featured image on a template/layout level sounds like a better route to go.

**Comment by joedolson** [comment]
Then I'm going to close this, as that's pretty much either going to be handled through custom templates or custom CSS; in the case of the single template, it's likely to be handled by the theme.
