### ISSUE TITLE
Smaller screen with horizontal scrollbar.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#263]
I noticed this when in the Help screen and doing a horizontal scroll.
Dev site
Chrome

https://user-images.githubusercontent.com/5323259/135753759-2cb4b2d8-f525-4d89-9e07-3222d9162507.mp4

**Comment by joedolson** [comment]
Looks like it's an issue anywhere between 1200px and the responsive breakpoint at 782px. The narrow container content is overflowing it's bounds, and I'll need to address that.

Best,
Joe

**Comment by paaljoachim** [comment]
I removed all traces of the last installation and installed the newest version.
Did a hard refresh and even installed Autoptimize to hard refresh.
I am still seeing the same thing.
![Screenshot 2021-10-03 at 23 28 06](https://user-images.githubusercontent.com/5323259/135772086-cf3ab6fd-b74f-4a44-9f1a-421e24272115.jpg)

**Comment by joedolson** [comment]
Ah, I bet it's the Twitter follower count display that's the problem. Tricky; I don't really have control over that, other than removing it. I had Pro active, so that wasn't showing.

**Comment by joedolson** [comment]
I can just hide the overflow. It's not exactly critical content, so while it's not *ideal*, it fixes more important problems.

**Comment by paaljoachim** [comment]
Ahhh yes. You are right. It is the Twitter follower popup causing trouble. When Pro is active Twitter is not present on the screen.  Twitter is present in the free version when Pro is not active.

Perhaps we can just hide the twitter followers popup with CSS?
![Screenshot 2021-10-03 at 23 39 42](https://user-images.githubusercontent.com/5323259/135772372-d46dcaa3-3f64-48b7-9c83-58b0c8c7abd8.jpg)
