### ISSUE TITLE
Help screen - Should it contain tabs?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#264]
I am wondering if the Help screen should contain tabs.

One reason I have it that we can add a longer and improved Getting Started area.

An example of using tabs.
![Help-How-to-use-My-Calendar-tabs](https://user-images.githubusercontent.com/5323259/135754200-0209ba5a-88ef-4355-9bf2-7529f8082632.jpg)

When people in the Plugins Installed screen click the Help link they will arrive at the Getting Started tab where I can add a more indepth tutorial.

**Comment by joedolson** [comment]
That's a good idea.

**Comment by paaljoachim** [comment]
Looks good!
![Screenshot 2021-10-03 at 23 30 56](https://user-images.githubusercontent.com/5323259/135772144-477f1966-0d54-4df1-9097-8cc034ce6e48.jpg)
