### ISSUE TITLE
Google map not rendering on frontend. Creating a duplicate of the location address being seen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#265]
This is a part of https://github.com/joedolson/my-calendar/issues/257#issuecomment-932883448
(I just decided to split it up into smaller issues.)

Location address is seen twice in the Single Event View.
![Screenshot 2021-10-03 at 15 04 54](https://user-images.githubusercontent.com/5323259/135754893-61a1eb36-23ee-4c52-99e9-2c9a24f06e81.jpg)

I believe this is also associated with:
Location drop down has a lot of space.
https://github.com/joedolson/my-calendar/issues/261

**Comment by joedolson** [comment]
I believe this is because your Google Map isn't rendering, and the second address block is the infowindow content for the Google Map. Check your console for Google Maps errors?

**Comment by paaljoachim** [comment]
I am not able to see any errors in the console. I only see this
![Screenshot 2021-10-03 at 18 17 15](https://user-images.githubusercontent.com/5323259/135762583-d8cd0a93-f721-4697-87af-54eaa424973d.jpg)
:

**Comment by joedolson** [comment]
In the source, is the second address wrapped in a 'mc-gmap-fupup' class? If so, it's definitely the one for Google Maps. 

Is the file /wp-content/my-calendar/js/gmaps.js loaded?

**Comment by paaljoachim** [comment]
How would I figure out if it is loaded or not?

**Comment by joedolson** [comment]
Simplest way is to view source, do a find in page for gmaps.js. Then check that link to verify that the src link is actually valid.

**Comment by paaljoachim** [comment]
Viewing source
![Screenshot 2021-10-03 at 18 41 38](https://user-images.githubusercontent.com/5323259/135763339-06dcc2e9-f9c7-4349-8692-d580afb133a2.jpg)

Clicking https://my-calendar.dev.cc/wp-content/plugins/My%20Calendar/js/gmaps.js?ver=5.8.1'

![Screenshot 2021-10-03 at 18 42 23](https://user-images.githubusercontent.com/5323259/135763367-b0e32341-93ca-4a1a-8751-03c8c9280e39.jpg)

**Comment by joedolson** [comment]
So, everything is fine in the admin; but the map is visible there, so that's expected. What about the frontend?

**Comment by paaljoachim** [comment]
It is not seen in the frontend
![Screenshot 2021-10-03 at 18 56 40](https://user-images.githubusercontent.com/5323259/135763895-b79ebbdc-87dc-4023-ad4a-396552cb5453.jpg)

**Comment by joedolson** [comment]
So you're saying that you do not see the gmaps.js script on the frontend? I am aware that you do not see the map; I'm trying to assess whether the script is present, but not functioning, or if the script is not present.

**Comment by paaljoachim** [comment]
In the page source for the frontend I am seeing this code:

<div class='time-block'>
--
  | <p><span class='mc-event-date dtstart' itemprop='startDate' title='2021-10-06T12:00:00+00:00' content='2021-10-06T12:00:00+00:00'>October 6, 2021</span> <span class='event-time dtstart'><time class='value-title' datetime='2021-10-06T12:00:00+00:00' title='2021-10-06T12:00:00+00:00'>12:00 pm</time></span> <span class='time-separator'> &ndash; </span><span class='end-time dtend'><time class='value-title' datetime='2021-10-06T16:00:00+00:00' title='2021-10-06T16:00:00+00:00'>4:00 pm</time></span></p><meta itemprop='startDate' content='2021-10-06T12:00:00' /><meta itemprop='endDate' content='2021-10-06T16:00:00'/><meta itemprop="duration" content="PT4H"/>
  | </div>
  | <meta itemprop='image' content='https://my-calendar.dev.cc/wp-content/uploads/Field-grass-wheat-sky-1024x682.jpg' />
  | <div class="location"><div id='mc_gmap_635432298' class='mc-gmap-fupup' style='width: 100%;height: 300px' data-zoom='16' ><div class='marker' data-address='Gullerås veien 15H  Oslo Norway 0779 ' data-title='Paal Joachim Romdahl' data-icon='//maps.google.com/mapfiles/marker_green.png' data-lat='' data-lng=''><strong>Paal Joachim Romdahl</strong><br>Gullerås veien 15H<br>Oslo, Norway  0779<br><br></div></div><div class="address location vcard" itemprop="location" itemscope itemtype="http://schema.org/Place"><div class="adr" itemprop="address" itemscope itemtype="http://schema.org/PostalAddress"><div><strong class="org fn" itemprop="name">Paal Joachim Romdahl</strong></div><div class='sub-address'><div class="street-address" itemprop="streetAddress">Gullerås veien 15H</div><div><span class="locality" itemprop="addressLocality">Oslo</span><span class="mc-sep">, </span><span class="region" itemprop="addressRegion">Norway</span>  <span class="postal-code" itemprop="postalCode">0779</span></div></div></div><meta itemprop="name" content="Paal Joachim Romdahl"/><meta itemprop="address" content="Gullerås veien 15H  Oslo Norway 0779 "/><div class='map'><a href='http://maps.google.com/maps?z=16&amp;daddr=Gullerås+veien+15H++Oslo+Norway+0779+' class='url external'>Map<span class='screen-reader-text fn'> Paal Joachim Romdahl</span></a></div></div></div>
  | <div class='longdesc description' itemprop='description'><p>Test event</p>
  | <p><img class="alignnone size-medium wp-image-17" src="https://my-calendar.dev.cc/wp-content/uploads/Blue-strips-300x212.jpg" alt="" width="300" height="212" /></p>
  | </div>

**Comment by joedolson** [comment]
That doesn't show me whether or not the script gmaps.js is present on the page; did you search for it and not find it?

**Comment by paaljoachim** [comment]
I just did a search and it is not present on the frontend.

**Comment by paaljoachim** [comment]
I also searched on the backend page source and gmaps.js is also not present there.

**Comment by joedolson** [comment]
Ah ha! The script enqueuing used the old version of the display settings, and didn't have a fallback for the new version. 

Fixing. Thanks!

**Comment by paaljoachim** [comment]
Great!

**Comment by paaljoachim** [comment]
Great! The map is now visible on the frontend.

![Single-Event-with-map](https://user-images.githubusercontent.com/5323259/135773102-69688ad3-cd7c-4490-8f5b-a67d2a27bb46.jpg)

Now we just need to figure out ways to improve the general look of the display of the event as it is seen on the frontend. (I assume that is a CSS concern we need to figure out.)
