### ISSUE TITLE
Remove or have Include event title in details pop-up prechecked by default

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#268]
I thought it was a bug when I in some views did not see the event title.

This setting could either be removed or prechecked by default.
![Screenshot 2021-10-03 at 23 52 32](https://user-images.githubusercontent.com/5323259/135772686-4f88aa5c-42ea-4623-8785-80e2cb24d592.jpg)

I would go with just removing it. If a user does not want to have the event title there they can always just use CSS with a display none.

**Comment by joedolson** [comment]
I agree. I don't think it's valuable to hide it.

**Comment by paaljoachim** [comment]
Great. The setting has been removed.
![Screenshot 2021-10-04 at 00 01 39](https://user-images.githubusercontent.com/5323259/135772904-ce9d6e88-ee25-4908-80cf-bd315997f8c8.jpg)
