### ISSUE TITLE
Looking at adding a category through the event screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#272]
I will do some brainstorming here as I am writing the getting started doc meant to help totally new users who for the first time use My Calendar.

I am doing a mini intro to adding an event.

In relation to clicking + Add a new category. User clicks it and it opens up to show:
![Screenshot 2021-10-10 at 09 38 33](https://user-images.githubusercontent.com/5323259/136687034-45697ac3-42d5-493d-91d7-1d1e82cb3819.jpg)

User fills in a new category. Clicks Add Category and will see something similar to this:
![Screenshot 2021-10-10 at 09 39 55](https://user-images.githubusercontent.com/5323259/136687054-253e8b1c-1592-4bd4-98b6-7638bac00c70.jpg)

I look at this and wonder why it still says Concert in Paris in the Category Name field when it has been added and one can see it above next to the other categories.

I wonder if we should automatically blank out the Category Name ___ field after having added a category. Or automatically close the Add Category disclosure toggle. This shows to the user that an action has been done and is finished. 

What can happen here is that the user will not automatically know that they can click + Add a new category to actually close the toggle again. Which means they will likely just leave the toggle open with the recent added category name and move on to the next field in the Event screen.

**Comment by joedolson** [comment]
Certainly wouldn't want somebody to add the same category twice by accident, so blanking the value makes sense. I don't think automatically closing the toggle is helpful though; it doesn't do any harm for it to be open, and it would be a pain if somebody was trying to add multiple categories at a time.

**Comment by paaljoachim** [comment]
It feels better when the Category name is blanked out after adding a category.
