### ISSUE TITLE
Event screen: Should Add occurrence have it's own section? (rethinking the UI of occurrence)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#275]
As I am creating documentation: https://docs.joedolson.com/my-calendar/my-calendar-add-events/

I suddenly wondered if Add occurrence should have its own section similar to how Repetition Pattern has its own section.

![Screenshot 2021-10-10 at 14 13 39](https://user-images.githubusercontent.com/5323259/136695073-29960aa9-feb3-4da1-8d2b-5be3c84fa7c8.jpg)

We would then move Add occurrence out from the standard Date and Time section.
Here I totally redid the occurrence screen.
I am working on repeating the existing Date and Time section creating familiarity for the user.

![Changing-occurrence-area](https://user-images.githubusercontent.com/5323259/136696154-01d089b7-ad87-4c79-b461-052b6f51070b.jpg)

The occurrences would just line up under each other.

**Comment by joedolson** [comment]
My gut feeling is "no, it shouldn't". My reasoning is that each grouping of information in the form is a set of characteristics about one event. The date/time panel is about "when the event happens"

Adding occurrences are not characteristics of the event; they're alternate dates for the same event. So they're variations on the date/time, and not unique information for the event. 

Adding another panel would take up a lot of space for a feature that only a small subset of users are likely to use, so I'm dubious about the value.

**Comment by joedolson** [comment]
Re: layout - you mean one group per row, rather than the flex layout currently in use?

Plausible.

**Comment by paaljoachim** [comment]
Yeah so that it looks more similar to the original Date and Time layout.
One sees the original layout.
![Screenshot 2021-10-10 at 17 18 47](https://user-images.githubusercontent.com/5323259/136702092-632222c5-a847-4e1a-aa3f-30e2ae94bfc2.jpg)

Adding an occurrence basically just copies the same layout one group per row.

**Comment by paaljoachim** [comment]
That does look better!
![Screenshot 2021-10-10 at 17 38 20](https://user-images.githubusercontent.com/5323259/136702918-9dee698f-ab80-45fe-85c3-6dcb8a0e46f7.jpg)
