### ISSUE TITLE
Hide/remove Location fields?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#276]
Here is an example of a Norwegian location.

![Screenshot 2021-10-10 at 15 25 22](https://user-images.githubusercontent.com/5323259/136697723-3a772dde-c8d3-47fa-910c-e1261afee9ad.jpg)

These fields will very likely not be used in Norway:
Street Address (2)
State/Province
Region

It would be nice to be able to hide/remove fields similar to how we hide/remove Event editing fields.
Perhaps something like this:

![Remove-hide-location-fields](https://user-images.githubusercontent.com/5323259/136698109-66a544a8-f179-4b12-a8a0-532caeb52b29.jpg)

**Comment by joedolson** [comment]
I'm feeling like this change is adding a bunch of extra UI complexity for something that's really pretty simple for users to ignore. In My Calendar Pro, you can customize the visible location fields, and that's where you can streamline things for low-access users, but I don't think the labor to add these toggles is a high enough value. Closing this issue as wontfix, for now.
