### ISSUE TITLE
Event screen: Excerpt placeholder?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#280]
I thought suddenly came to me...
What if we add a placeholder in the Excerpt field.

Original
![Screenshot 2021-10-10 at 19 55 11](https://user-images.githubusercontent.com/5323259/136707672-e9582424-e2fd-4310-9739-21437a2b9e86.jpg)

Adjusted:
![Excerpt-placeholder](https://user-images.githubusercontent.com/5323259/136707929-4bdf7034-0430-4c58-b316-4c13dc3f8056.jpg)

I believe the placeholder will also encourage people to add text to the Excerpt field.

**Comment by joedolson** [comment]
I think probably not. I'd only want to add a placeholder if it wasn't clear what type of content belonged in the field, and I don't think that applies.

From a practical standpoint, I have no way of knowing exactly how or where somebody is using the excerpt, so any comments about how it's used are of very limited value.
