### ISSUE TITLE
Long Settings screens also move the left WP menu.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#283]
Chrome
A local site.

This is kinda tricky and not straight forward, but it looks like I have been able to repeat the following a few times.

Steps.
1. Go to General Settings.
2. Resize the Chrome browser from perhaps 1500px or wider. Go up and down and end up at 1100px - 1050px wide. 
3. Go to Text Settings and Output Settings.
4. See if it looks like this:

![Screenshot 2021-10-11 at 09 01 41](https://user-images.githubusercontent.com/5323259/136746347-c5aa432c-7698-44b5-878a-3b5a577b3b6d.jpg)

What I did notice is that resizing the window while in one of the shorter Settings screen and then switching to one of the longer Settings screens such as Text and Output that the WP left menu seemed stuck to the screen content and scrolled with it.

**Comment by joedolson** [comment]
I haven't been able to reproduce this; following https://github.com/joedolson/my-calendar/commit/6d66c757cad1f22e9b0b916cc77133d259b4c0dc can you give it a re-test? Might be a Mac only bug.
