### ISSUE TITLE
Design screen: Clicking tabs makes the screen jump further down the page.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#284]
Chrome
Local site

I noticed when clicking the various tabs that the page jumps downward so one needs to scroll up to see the tabs.

https://user-images.githubusercontent.com/5323259/136912476-c9e7ca92-8a5a-4685-a8fd-6d8559b9f579.mp4

**Comment by joedolson** [comment]
OK. Tried another attempt. Worked in my tests, but I don't altogether trust that...

**Comment by paaljoachim** [comment]
Totally fresh install of My Calendar. (Before removing the earlier version  I clicked "Drop MySQL tables on uninstall" and "Delete plugin settings on uninstall".)

This is what I now see in Chrome.

https://user-images.githubusercontent.com/5323259/137590133-7f785cb3-07c4-44eb-b0e8-1ac153434986.mp4

**Comment by joedolson** [comment]
Just not going to get this done. It's been an issue for years, and I'm just not finding the direct cause. (I can find the indirect cause: it happens on tabs that are longer than the current screen), but that's not really a fixable option.

**Comment by paaljoachim** [comment]
Moving it to 3.4.0 (as you did) seems like the best solution at present time.

**Comment by joedolson** [comment]
This doesn't appear to still be happening; closing. Can be re-opened if it's still there, but I'm not seeing it anymore. May have been fixed upstream (Chrome.)

**Comment by paaljoachim** [comment]
Yeah. I just tested and what I reported back in 2021 is not occurring any longer.
