### ISSUE TITLE
Event: Accessibility Notes not seen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#285]
I am testing out what is seen on the frontend when clicking the various checkboxes and also writing into the Other: Notes text field.

Backend:
![Screenshot 2021-10-12 at 09 54 28](https://user-images.githubusercontent.com/5323259/136915178-3c10bdc7-4b17-4607-9669-90dfb53d12c7.jpg)

Frontend:
![Screenshot 2021-10-12 at 09 55 14](https://user-images.githubusercontent.com/5323259/136915302-7a573bff-83c5-40a4-8c19-1b807b431853.jpg)

Other is seen but not the notes I added into the text field associated with Other

**Comment by paaljoachim** [comment]
Adjustment suggestions:
![Event-Adjusting-Accessibility-section](https://user-images.githubusercontent.com/5323259/136916792-728bccd1-1b70-4573-b4bd-8274a7ef784a.jpg)

1- Adding a title for the Accessibility section. So the user can add a message above the accessibility section seen on the frontened.
2- Removing Other and only using Notes. What is inserted here will show up as Other showed up earlier on the frontend. (On the bottom of the list.)

**Comment by joedolson** [comment]
Notes can serve a variety of purposes; it *could be* additional features, but it could also be additional details about a provided feature. I know of groups using it to provide the name of the ASL interpreter or audio describer, for example. 

The fact that notes weren't shown is weird; I was unsetting the key, and I have *no memory at all* why.

**Comment by paaljoachim** [comment]
After the fix what one adds to the Notes field is seen on the frontend. I did also expect that one needs to check the checkboxes for Other to have it seen.

Right now it looks like this
Backend.
![Screenshot 2021-10-14 at 22 07 20](https://user-images.githubusercontent.com/5323259/137388032-b344f35d-db46-44e2-820f-193c9093ae3b.jpg)

Frontend.
![Screenshot 2021-10-14 at 22 07 30](https://user-images.githubusercontent.com/5323259/137388052-4e7e4820-8c0f-42b5-879f-235916d065d6.jpg)

**Comment by joedolson** [comment]
Maybe better as a text setting. I don't think it needs to be set on a per-event basis.
