### ISSUE TITLE
Option to set Primary Category

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#297]
The primary category is whichever category is saved in the main calendar DB; all other categories are secondary categories. Need a method to allow users to pick which category is primary. The implementation is trivial; needs a UI design.

See [Help Scout 6283](https://secure.helpscout.net/conversation/1656070425/6283?folderId=557254)

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar/commit/034087ef5d1598729db01b8afebfcc9fb620570f

**Comment by paaljoachim** [comment]
Is there a visible change here?

**Comment by joedolson** [comment]
Yes, but primary category is only relevant when an event has more than one category.

**Comment by paaljoachim** [comment]
Ahh...
It is in the Add Event screen.
This is what I see:
![Screenshot 2021-10-17 at 21 41 31](https://user-images.githubusercontent.com/5323259/137642510-120d37e8-17c4-43ad-8f53-3a278299965b.jpg)

![Screenshot 2021-10-17 at 21 41 35](https://user-images.githubusercontent.com/5323259/137642526-a972417c-aa41-41f7-afc0-bea5b7dc78cd.jpg)

It seems a bit weird.

**Comment by joedolson** [comment]
You might need to do a hard refresh; you shouldn't be seeing the General category. Is this editing an event or creating a new event?

**Comment by paaljoachim** [comment]
This is in Add Event.

It works better when I do not add a new category at the same time.
Selecting 3 categories that have already been added.
![Screenshot 2021-10-17 at 21 48 32](https://user-images.githubusercontent.com/5323259/137642723-89d33206-0457-4749-9020-c3838eef9268.jpg)

Adding another category.
![Screenshot 2021-10-17 at 21 49 23](https://user-images.githubusercontent.com/5323259/137642749-75ce0799-70f9-4e39-abdf-df8bb7e9c2ef.jpg)

Then right away going to select the Primary Category.
![Screenshot 2021-10-17 at 21 49 40](https://user-images.githubusercontent.com/5323259/137642769-8090a0f2-a675-41f8-8eeb-b5225cfc0bd5.jpg)

(A mental note for the doc. If one adds another category and then goes to select the new category as the Primary Category, it will not show up before one has updated the event.)

It looks like the Primary Category works and I will go ahead and close this issue.

**Comment by paaljoachim** [comment]
What affect does selecting Primary Category have?
