### ISSUE TITLE
Add New Template: - taking a closer look -

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#299]
Bringing comment over here from: https://github.com/joedolson/my-calendar/issues/292#issuecomment-943702806

We need a delete button. As if one clicks the Add New Template but changes ones mind. I thought that leaving the screen and then returning that the Add New Template - Template Description would be removed, but it is still there.

Adding the delete button will create enough visual change (I believe) to make it obvious that an Add New Template area has opened up after having Clicked the Add New Template button.

**Comment by joedolson** [comment]
I think these changes improve this significantly.

- Moved editor into first position
- Only display editor if either add new or an edit screen is selected
- Add 'Add New' link in header
- Show 'cancel' option in add new.

**Comment by joedolson** [comment]
Not sure you're seeing the complete updated CSS; the location of the upper Add New Template link is wrong.

I think that having two add new template links is needed; the other one is located so far down the page that it would be hard to notice. I'm going to stick with having two. But not showing 'Add New Template' while adding a new template definitely makes sense.

I'm not sure what you mean by "got stuck inside of it" - can you clarify that?

**Comment by paaljoachim** [comment]
First of all.
Even with a hard refresh and removing the old plugin I am seeing the Custom Template. I would of course assume that when clicking "Drop MySQL tables on uninstall" and "Delete plugin settings on uninstall" that anything regarding My Calendar plugin would be deleted when I delete the plugin, so that when I install and activate a new version that any remains from the old plugin would have been removed.

I am still seeing the Custom Template here:
![Screenshot 2021-10-16 at 16 14 56](https://user-images.githubusercontent.com/5323259/137590850-2e761d80-f6f0-4811-b299-5d33c4b4da10.jpg)
(As this Custom Template should have been removed when I deleted the former My Calendar plugin.)

---

Regarding Templates.
To me there are two main areas seen above the fold.
Core Templates
and
Custom Templates

Perhaps these should be two different sections similar to how we see sections in Add Event screen.
In the Add Event screen we see a visual difference between various features. As these are split into sections.
If I take this onward to Templates it could look something like this.

![Template-Editor-adjusted](https://user-images.githubusercontent.com/5323259/137591273-88d7f743-f435-4578-8231-c64d384cca3a.jpg)

**Comment by paaljoachim** [comment]
Here is a flow I notice for Adding a Custom Template.

1- Click Add New Template.
2- Fill inn the Template Description (title?)
3- Click Add Template again.
4- Edit Template is still active.

Going to another tab example Style Editor and back to Templates still shows the Edit Template active.

Clicking Delete. Suddenly it switches to the Core Template.

----

Needed flow.
1- Click Add New Template
2- Fill inn Template Description (title) and then fill in the code to be used in the Custom Template.
3- Click Add Template.
4- Template should now be seen in the Custom Template section.

**Comment by joedolson** [comment]
Fixed the deleting issue. Console error is not related; I know what that is, but it's not critical. 

If you can identify the deletion error, please open that as a separate issue.
