### ISSUE TITLE
Design -> Style Editor

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#300]
I am doing some brainstorming in relation to what I see in this screen. 

When I enter the Style Editor I see this:

![Screenshot 2021-10-16 at 14 35 10](https://user-images.githubusercontent.com/5323259/137587643-a7f6fe30-c2e8-45ba-a641-24b030f5f183.jpg)

----------

This is a totally fresh install where I earlier deleted the plugin by first going to Settings and checking 
"Drop MySQL tables on uninstall" and "Delete plugin settings on uninstall" and doing a few hard refreshes and then uploading the newest My Calendar plugin build from Github repo.

---------

I do not know why it says "There have been updates to the stylesheet. Compare Your Stylesheet with latest installed version of My Calendar." 

Compare your Stylesheet --> I do not have one as this is a fresh install.

I read through...
I notice Style Editor tab name is repeated in the screen with the heading Style Editor.
Then a "Select My Calendar Theme" where I can choose from various styles. I wonder what the default style looks like and wonder if I visually below the drop down would be able to visually see the differences of the styles I can choose from. (Obviously one can not view it below the drop down.) The idea here is to have a simple way to preview various themes.

Below I see CSS Style Options. I would assume that this screen has to do with styling through CSS. 
I wonder what "Apply CSS on these pages (comma separated IDs)" actually means. What does it do?

"Reset to default" What does this mean? What does this do?
"Disable My Calendar Stylesheet" --> Is actually "Disable default to activate your own Calendar stylesheet" 

"Edit the stylesheet for My Calendar" --> "Edit the stylesheet for the main My Calendar view"

**Comment by joedolson** [comment]
Re: previews: see https://github.com/joedolson/my-calendar/issues/166

**Comment by paaljoachim** [comment]
I will need to go through this issue for documentation and will go ahead and close it soon.

**Comment by paaljoachim** [comment]
Taking a closer look.
I selected the first theme in the drop down also seen as preselected. "dark.css"
I clicked Choose Style, and expected a link some place to preview the theme.
This is what I see:

![Screenshot 2021-10-18 at 15 53 04](https://user-images.githubusercontent.com/5323259/137744936-de6b13a7-c136-449c-8bf0-adca135effb5.jpg)


I see the comments in the theme in relation to the selected theme.

Ahhh. I noticed when switching theme that this happened:
![Screenshot 2021-10-18 at 15 53 41](https://user-images.githubusercontent.com/5323259/137745060-e79ef4e6-6f8e-47e9-b99c-f9fd764c18b7.jpg)
A Preview Stylesheet link is seen.

I am wondering if the Preview link should always be present to the theme that is currently active. Like so:
![Style-Editor-Preview-Style-Button](https://user-images.githubusercontent.com/5323259/137745633-14711aeb-714c-4deb-a28b-fb3a92754af3.jpg)

**Comment by joedolson** [comment]
Not going to make any major changes to theming in this release; happy to add one new stylesheet, but any major updates will happen in 3.4.0. 

I don't see a lot of value to a "preview" link that shows your current theme; that's just "view your site", and can be done at any time. This is about previewing changes.

> "Update stylesheet to match core version"

This works for me.

> I will use my own stylesheet

There's pretty much no other example of first-person language in the settings pages, so I think I'll stay away from that.

> Load CSS only on the selected pages

I can work with that. From a purely technical standpoint, the correct word would be 'post', but too many users would only understand that to mean blog posts. Any further improvements to this setting will be deferred to 3.4, however.

**Comment by paaljoachim** [comment]
> don't see a lot of value to a "preview" link that shows your current theme; that's just "view your site", and can be done at any time. This is about previewing changes.

Good point.

"I will use my own stylesheet." 
An option could be "User defined stylesheet" 
The purpose to change "Disable My Calendar Stylesheet" is to say what it is changing to. Mentioning disable then something else needs to take over. I am focusing on what it changes to.

I have this doc I am working on. As this screen will change in 3.4 I assume it does not matter so much what we call it as long as I "get it" and can write about it in a doc so users can get more information about the current screen.

**Comment by joedolson** [comment]
Pretty much, yes. This screen will probably change a *lot* in 3.4.0, so I don't want to put too much attention on it now. Making some minor changes, but otherwise only re-open for 3.4.
