### ISSUE TITLE
Overview of screens that use the icon ? help popups to give additional information.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#301]
Associated Documentation overview/tracking issue: https://github.com/joedolson/my-calendar/issues/199

----

This issue about all the popup tooltip icons that exist in various screens.

An example.

![Screenshot 2021-10-28 at 14 16 09](https://user-images.githubusercontent.com/5323259/139253512-2d56f1e8-ef1b-4c74-9fb0-d508622f2e15.jpg)

Clicking the ? brings up a modal:

![Screenshot 2021-10-28 at 14 16 18](https://user-images.githubusercontent.com/5323259/139253546-1478e959-ddf5-4046-83f9-4b44754287dd.jpg)

That means we need to add some key information that adds some quick understanding of what a specific section does. The user can then click the Documentation link that opens a new tab (should open a new tab so it does not take the user away from the site they are working on) to gain even more information.

Add Event:
**Add occurrence** 
**Repetition Pattern**

Events

Add New Location

Locations

Categories

Design:
Style Editor 
Templates: **Template Editor** 
Scripts

Settings
General
Text: Has different kinds of ? leading to Templating Help
Output 
Input 
Permissions 
Notifications: Had different kinds of ? leading to Templating Help

Shortcodes: Help ? icons in the Navigation area. 

Help: 
Getting Started
Custom Files
Privacy
Get Support

**Comment by joedolson** [comment]
Noting new popup: Categories > Category icon; displays available icons.

**Comment by joedolson** [comment]
The 'Documentation' link at the bottom of each modal takes users to a search query on the docs site using the modal title.

**Comment by paaljoachim** [comment]
This is what it looks like:

![Screenshot 2021-12-13 at 10 13 05](https://user-images.githubusercontent.com/5323259/145784086-1dccd557-fa2c-4b2d-9121-60f3b03a2564.jpg)

(The font size feels extra small when there is so much empty space. Anyhow that is something I can get back to at another time.)
