### ISSUE TITLE
Editing category - focus on "Search for an icon"

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#304]
I do not think there is anything for you to follow up on here Joe. I added this issue as a reminder to myself. Looking at one flow of editing categories.

I clicked to edit a category and see this:
![Screenshot 2021-10-18 at 09 17 42](https://user-images.githubusercontent.com/5323259/137685562-02bcf50b-356b-4b1e-bc6d-98b62cfc1b47.jpg)

What I am wondering about is the Category Icon: "Search for an icon"
I noticed that I could for instance write home and this would be seen.
![Screenshot 2021-10-18 at 09 19 03](https://user-images.githubusercontent.com/5323259/137685715-9f20afb2-e3aa-44d7-8119-1204db458cd7.jpg)

I wanted to bring some attention to it. As it is one aspect of editing categories to bring into the documentation. Which I will also need to take a closer look at.

"Search for an icon" - What it does is "Write a word and see possible icons show up."

**Comment by joedolson** [comment]
This actually got finished in 3.3.0; closing now.
