### ISSUE TITLE
Design - Scripts: Not able to save a checked option.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#315]
Clicking a checkbox and clicking Save automatically unchecks the checkbox.

![Screenshot 2021-10-19 at 00 06 02](https://user-images.githubusercontent.com/5323259/137813178-84ded1e3-f314-41e5-8f15-5c30ab692c1b.jpg)

**Comment by joedolson** [comment]
I should probably address the CodeMirror issue, or you'll just keep reporting it...it's not related to this; it's only happening because there's no codemirror region on the page when it loads.

**Comment by paaljoachim** [comment]
Heck yeah. I easily forget. Anyhow clicking to save a disabled state is somewhat weird. I can always let it rest for now anyway.

**Comment by paaljoachim** [comment]
Saving now works!
