### ISSUE TITLE
Main calendar page field shows page ID not page name

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#32]
Settings -> General

Where is your main calendar page? ---> shows Page ID and not page name.

https://user-images.githubusercontent.com/5323259/114263365-58b8d200-99e5-11eb-93d5-377d1c4d2d2c.mp4

**Comment by joedolson** [comment]
This came from a bunch of legacy settings that had a messy adaptation. But it's been long enough now that I don't think I still need to try to support the old settings. Fix also replaces jQuery Suggest with a more accessible & usable autocomplete solution.
