### ISSUE TITLE
Giving more space to an backend event title.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#331]
I noticed that the event title feels squashed between the edge above it and the menu below it. Like so:

![Screenshot 2021-10-28 at 14 04 39](https://user-images.githubusercontent.com/5323259/139252375-ab66b514-469e-4982-9e65-c064e459f205.jpg)

What about having a larger font size for the title, and more padding. Here is one example.
![Screenshot 2021-10-28 at 14 08 23](https://user-images.githubusercontent.com/5323259/139252521-ae43adb8-32bc-4637-8447-7b0a1a9dd828.jpg)

I also noticed that the .mc-controls have a -10px margin bringing it further up.

Another question comes up. Should the event title be below the menu area?

**Comment by joedolson** [comment]
Not going to move the event title below the menu; it should definitely be before the controls relevant to it. 

But the spacing is a bit compressed.

**Comment by paaljoachim** [comment]
There is now a little more space for the Event title:
![Screenshot 2021-10-29 at 22 47 16](https://user-images.githubusercontent.com/5323259/139499814-549f8b90-8050-4b1f-80e8-ebcfbcf5a9e5.jpg)
