### ISSUE TITLE
Categories - Adding category does not show up in the Category List

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#333]
I added a category and the icon home.svg, but it did not show up in the Category List.

![Screenshot 2021-10-28 at 15 19 16](https://user-images.githubusercontent.com/5323259/139263690-d5e26a02-4415-4fdd-8731-02b066c56d44.jpg)

**Comment by joedolson** [comment]
The category looks like it's present to me. The icon may not be visible; I need to massage those so that works better. They change appearance depending on color & icon settings.

**Comment by paaljoachim** [comment]
Yeah. The icon is not seen. Removing the Icon column works for now kinda works. It would be nice to at a later time have a column that shows which icons are used for which category.

**Comment by joedolson** [comment]
Note that the icon column is only removed if the option 'hide category icons' is checked.

**Comment by paaljoachim** [comment]
Ahhh. It was hidden by default.
