### ISSUE TITLE
Design > Template h2 vs h3

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#334]
I am looking at
Event Template Tags

.my-calendar-admin .metabox-holder .mc-postbox > h2 {
    padding: 8px 0;
    margin-top: 24 px;
    font-weight: 700;
}

vs

Location Template Tags

h2, h3 {
    color: #1d2327;
    font-size: 1.3em;
    margin: 1em 0;

![Screenshot 2021-10-28 at 22 36 24](https://user-images.githubusercontent.com/5323259/139331751-8bcf6c12-1bf1-4016-8100-8395332e5cca.jpg)

Here it looks like the Location Template Tags h3 uses a smaller font compared to Event Template Tags h2.

**Comment by joedolson** [comment]
Larger font, I think you mean. Not concerned about the size, but this is inconsistent; I'll make a change to improve the hierarchical consistency.
