### ISSUE TITLE
Testing out occurrences - Repetition Pattern

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#336]
I am right now working on documentation for adding occurrences. 
Going to Edit an event. We see this:

![Screenshot 2021-10-30 at 22 50 43](https://user-images.githubusercontent.com/5323259/139558047-891da918-a62a-4f39-a517-34a69c7bdaa1.jpg)

This seems like a bug:
Cancel event if it occurs on a date with an event in the category “” - I also find the sentence confusing.

**Comment by joedolson** [comment]
Do you have a holiday category set with an empty name field? 

This text should contain the name of your designated holiday category, and should only appear if that option is set. In that case, the text should be fairly clear; but I'm not sure why it's showing with no content.

**Comment by paaljoachim** [comment]
I do not know.
I installed the newest plugin version. Added a new event. Added a few occurrences and went to edit event and did not notice the second sentence.
