### ISSUE TITLE
Wondering about: Scheduled dates for this event vs + Add Occurrence

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#337]
I see this in the edit event screen.

![Screenshot 2021-10-30 at 23 03 24](https://user-images.githubusercontent.com/5323259/139558289-af2286f7-9f62-4a3e-bce2-e21e9585519b.jpg)

Which seems identical to this in the add event screen.

![Screenshot 2021-10-30 at 23 04 25](https://user-images.githubusercontent.com/5323259/139558318-c3763966-085d-4a3d-8e81-11864c8073e7.jpg)

I am wondering why these are not identical? As both add new events only one is through Add Event and the other in Edit Event.

**Comment by joedolson** [comment]
They are not the same feature, and they do *not* both add new events. 

The first 'Add Date', adds an additional date to a recurring event (which converts a single event to a recurring event, if it's not already recurring.)

The second, 'Add Occurrence', creates a duplicate of the event you're creating, including it's recurring pattern, if you're creating a recurring event. 

I'm open to suggestions that help clarify how and why these are different, but definitely *not* anything that would make them more similar, as that would only serve to increase confusion about how they work.

**Comment by paaljoachim** [comment]
This is really tricky. Because these as I see these as minor nuances.

Edit Event:
Add Date - adds an additional date. Would it matter for the user if the event is recurring or not? Or if it is a single event that changes later on to a recurring event. As all single events have the potential to become recurring events. What if all events are recurring events only that some of these do not have any additional dates. So in a sense it looks like a single event.

As a user adds an event. Notices later on that he/she wants to add an occurrence/Add date to a single event. They then open up the event and use the method that is there to add additional dates to the single event.

----

Add Event:
User adds multiple occurrences. Publishes. 

Edit Event:
Goes to edit one of the events to add an additional occurrence they forgot to add. Notices that instead of it saying + Add Occurrence it now says add dates. Assumes it is the same as adding an occurrence but that it is called differently in the Edit Event screen.

**Comment by joedolson** [comment]
It's a small nuance, but significant in its consequences because of the difference between how the information is saved & edited, so they should be kept separate. 

Clarification is good; but making them the same is not. 

But it's very hard to come up with language that makes the distinction clear.

**Comment by joedolson** [comment]
Calling these grouped dates would confuse it with Event Groups, don't you think? Related Events = Grouped Events, so that's a reasonable change to make. Probably better, for clarity. But 'Scheduled dates' is not the same thing as grouped events: it's the individual dates on which a recurring event occurs, and recurring events are just one event, not a group.

Definitely cannot merge these without a massive change to the underlying data model. They are completely different things.

**Comment by paaljoachim** [comment]
Remember I look at this from my limited view point.

> Calling these grouped dates would confuse it with Event Groups, don't you think? 

I thought these would be the same, but it seems from what you are saying that these are not the same.

I am working on understanding the various differences between Add Occurrence, Scheduled dates for this event, Related Events and Event Groups.

**Comment by paaljoachim** [comment]
Changed to Event Group.

![Screenshot 2021-11-01 at 16 58 06](https://user-images.githubusercontent.com/5323259/139701755-a887b729-c8ca-42a4-ba78-ed2c4005209e.jpg)

**Comment by joedolson** [comment]
I've just committed a change that switches the language "related" to 'grouped" - those are literally synonymous, and I can see the different language made things ambiguous. 

An "event" is a record in the events table. It may be a single event, or it could be a recurring event.

When you 'Add an occurrence', you're adding another event. 

Recurring events have stub records for each date of the event. Those are 'dates'. 

When you Add a Date, that's adding an additional stub record for the event. It is not represented in the events table, and only contains the date information.

Event groups group events - records in the events table. Each of those events could be single or recurring, and could have any number of dates associated with them.

Here's a quick chart that hopefully helps show the relationships.

![Event Relationships](https://user-images.githubusercontent.com/1686451/139701813-942ed1dc-30b0-4069-997b-f1b7412d314d.png)
.

**Comment by joedolson** [comment]
> Remember I look at this from my limited view point...

One of the reasons I'm having you go through this is so that I can get that viewpoint; and these questions are absolutely helpful in working towards making the interface clearer. If you don't understand that these are different, then neither will users!

**Comment by paaljoachim** [comment]
I just did some testing.
Added a few occurrences.

Went to edit one of the occurrences. Where I added additional dates. I wondered if the additional dates would show up in the Events screen (they did not). 

From your diagram and from what I saw while exploring.

Occurrence 1.
Occurrence 2.
Occurrence 3.

Occurrence 2 event 9:00pm - 11:00pm
I made additional events earlier in the day associated with only this event. At 12:00 - 13:30 and at 15:00 - 17:00.
So these would then be sub events for one event. The button Add Date feels misleading. As this is really about adding an event only associated with this peticular event. Instead of a button called "Add Date" I would call it "add sub events", "Add linked events" or something like so. 

I clicked the Update button and saw this message:
"Extra occurrences of this event have been added or modified. Updating the date or repetition pattern will reset its occurrences."

I find the above confusing as now it speaks about occurrences again. Also the second sentence updating the date will reset its occurrences. 

I went to the frontend. The additional added dates show up just like regular events.

![Screenshot 2021-11-01 at 18 00 55](https://user-images.githubusercontent.com/5323259/139710511-8d593a25-0657-42fb-ac79-160e03039a31.jpg)

But the additional events do not show up in the Events screen. These only show up when clicking to edit the Nov 17 event under scheduled events. So these become hidden but act just like any other event.

**Comment by joedolson** [comment]
Just added a set of changes to continue to try and clarify this. I'm not going to change form 'Add Date'; in my opinion 'Add Date' is a straightforward description of what you're doing: adding another date to your event. Adding a "sub date" would leave me puzzled. 

Major language change is moving from 'occurrence' to 'copy'.

**Comment by paaljoachim** [comment]
Going through this process again.

Adding the title "Concert in Paris". Date 8 Nov.
I see the + Add Copy. (Instead of + Add Occurrence in the standard Add Event screen. As you mentioned above.)
I add two events (copies) 10 Nov and 12 Nov.
Publish.

Notice the message:
Event added. It will now show on the calendar. View Event Edit Event
Event added. It will now show on the calendar. View Event Edit Event
Event added. It will now show on the calendar. View Event Edit Event

I suddenly remembered that I need to add an additional date (duplicate) of the event.
I randomly click an Edit Event. (Thinking it would not matter as I am just adding an additional event date.)

Scroll down to hmm it looks different. 
Now it says View scheduled dates (instead of + Add Copy)
Event Group

I am wondering where I should add the date I had earlier forgot to add.
Should I click View scheduled dates and then click + Add another date, or should I click the Event Group and click to Edit group.

Because of the difference from Adding Event to Editing Event. Just adding a duplicate of an event and switching the dates becomes tricker then expected.

**Comment by joedolson** [comment]
OK. So, my response to that workflow would be 'go to Events, click 'Copy' in the event actions'. As a user, what would make this clearer to you?

**Comment by paaljoachim** [comment]
Yes that would be helpful.
But I initially created the additional events by clicking the + Add Copy in the Add Event screen, and would expect that I could just follow the same procedure again by going to an existing event. 

So what we need to do it make it clear that the process is a little different from Add Event (adding a copy) to Edit Event (View scheduled dates + Add another date.)

But then again. I understand that it would say View scheduled dates (only I would expect to see all the dates that I made earlier, and not only the same event I am editing. This part is still a little confusing.)

Seeing the Event Group tells me that all the events that are associated are grouped together.

**Comment by joedolson** [comment]
The thing is that 'Add Copy' changes what you're doing from 'Adding one event' to 'Adding several events'; it's a way to create multiple events at once. But when you edit an event, you're always only editing *that* event. So they are fundamentally different.

What if there was a section heading that incremented each time you added a copy, e.g. "Creating 2 events", "Creating 3 events", etc., to clarify that you are creating more than one event in this action?

**Comment by paaljoachim** [comment]
I got to think out loud.... as I am not fully getting it.

Current approach in the Add event screen:

Clicking + Add Copy
Event Copy 1
Event Copy 2
Event Copy 3

Says that multiple copies are made of this event.

-----

Current approach in the Edit event screen:

Clicking View scheduled dates.
Clicking + Add another date.
Adds additional events (could be the same date just a different time slot)
Events are listed like so:

![Screenshot 2021-11-04 at 00 20 26](https://user-images.githubusercontent.com/5323259/140232123-2e278596-bf29-44be-86d6-7a9bce57ab04.jpg)

There is also a message that says: "Thanks! Your new date is saved to your calendar."

I would assume from earlier experiences of adding copies that these would be saved just like any other event, so that the above message kinda tells me that something is different without really telling me what is different.

**Comment by joedolson** [comment]
Would making the message "A new date has been added to this event" be more clear to you?

You haven't added an event; you've added an additional date to an event.

**Comment by paaljoachim** [comment]
I will go ahead and close this issue, as we will be moving the + Add another date UI into the Repetition Pattern UI.
Here is the issue for it: https://github.com/joedolson/my-calendar/issues/346
