### ISSUE TITLE
Add Event: Date and Time - End date is automatically added

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#341]
I noticed when creating an event (start) Date that the End Date (optional) is automatically filled in.
![Screenshot 2021-11-01 at 17 38 47](https://user-images.githubusercontent.com/5323259/139707571-b3389353-f4c5-480a-96e9-4e0a311d8d52.jpg)

Adding Event Occurrences Date the End Date is not automatically filled in similar to the original event.
![Screenshot 2021-11-01 at 17 39 42](https://user-images.githubusercontent.com/5323259/139707667-7faf4409-aaee-4765-974a-9c7c8800d368.jpg)

Should End Dates automatically be filled in also for occurrences?

**Comment by joedolson** [comment]
Yes, although it should happen when the copy is made in that case. Fixing.

**Comment by paaljoachim** [comment]
I assume the End Dates would be listed in the Event Copy 1 and Event Copy 2?

![Screenshot 2021-11-04 at 00 26 01](https://user-images.githubusercontent.com/5323259/140232637-29c9e5c1-ae59-4b06-9754-76c889d28e40.jpg)

**Comment by joedolson** [comment]
I can't tell what's happening in that screenshot; if there wasn't an end date in the original event, it wouldn't be added, so this could be correct. I have no way of knowing. 

End dates aren't required, so there's no particular reason to force them in most cases.

**Comment by paaljoachim** [comment]
My thinking is that an End Date is automatically added to the original event just after adding a date into the Date field.
So that the user can go ahead and change the End Date if needed. It would be nice to do the same thing when adding copies of the same event.

This is what I see:

https://user-images.githubusercontent.com/5323259/140431751-d672a6cc-98e7-4ba7-81d4-a45a8428db6b.mp4



Then adding copies the End Date would also be filled in automatically.

**Comment by joedolson** [comment]
I'm going to wontfix this for now. It's a very low priority, and this would open a lot of complexity. I'd have to make some assumptions - like monitoring the value of the original end date so I could assume the same length of event for every new copy, which might include changing the day. End dates are only required if they're different from the start date, and they aren't particularly difficult to enter, so it's just not going to happen.
