### ISSUE TITLE
Edit Event: Edit other events in the same event group. --> fatal error

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#344]
Here:

![Screenshot 2021-11-04 at 00 42 16](https://user-images.githubusercontent.com/5323259/140233809-872111cb-313b-4d53-8a63-6e647ce8aa5c.jpg)

Clicking: **Edit other events in the same event group.**

Leads to this error.

Fatal error: Uncaught Error: Call to undefined function mc_get_related() in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/My Calendar/my-calendar-group-manager.php on line 229

Error: Call to undefined function mc_get_related() in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/My Calendar/my-calendar-group-manager.php on line 229

--

Clicking the individual events in the Event Group list works fine.

**Comment by joedolson** [comment]
That looks like you've got some old files? The function mc_get_related was renamed in a previous commit, but if you still have an out of date copy of some files, there could be references to it. I don't see this function in the current version of the code, so I don't see anything to update.

**Comment by joedolson** [comment]
Found this, actually. I *had* made the change locally, but I somehow had failed to save the file, and hadn't touched it since then. So my code searches came out clean, but I had unsaved changes sitting there... 

I'm puzzled how I managed to get a changed file in my dev environments without having a saved version of it in the repository, but... :shrug:

**Comment by joedolson** [comment]
https://github.com/joedolson/my-calendar/commit/8988769b15ba440c767484e00e41c60575a0d7f2#diff-92e576b33caba3a5038914b54b4f5e16aefe8cf71433423394fec200b742b6cc

**Comment by paaljoachim** [comment]
Clicking: "Edit other events in the same event group." Now works!
