### ISSUE TITLE
Edit Event: Looking closer at View scheduled dates

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#345]
I go to Edit an event.
Click "View scheduled dates"

I click Add Date two times so that I see this:

![Screenshot 2021-11-04 at 00 36 25](https://user-images.githubusercontent.com/5323259/140233385-b20782bd-3619-4e06-8d27-18357cec791b.jpg)

-1-
I see no way to remove a date that has been added.

-2-
The message:
"Thanks! Your new date is saved to your calendar."

Does not help much. As this is expected behavior for adding a new event.

If it could tell me something like:
Dates are added uniquely to this event and will not be seen in the backend but are seen in the frontend calendar.

I would wonder why I would not see the events in the backend events screen. But it would atleast inform me of what is going on. I would not fully understand the connection between this event and the added events. As I would compare it to + Add Copy method of adding events. Even though Add date is different compared to + Add Copy. They are both about adding events.

**Comment by joedolson** [comment]
1) If you reload, you can remove them, although I don't think there's any reason I couldn't add the removal UI when I add the stub of the new date. Although the event bubbling might be nasty, since it isn't currently required. Not sure; I'd have to try it.

2) Would "A new date has been added to your event" help make the relationship more clear?

**Comment by paaljoachim** [comment]
1. Ahhh I just updated the event and then went back to the View scheduled dates, and there I would see the Delete and Edit buttons.

2. The initial select an event and then click View scheduled dates to see the Editing Now. There is a lack of direct information associated with this. As in what is the result of adding additional dates? What does it mean?

Adding a "A new date has been added to your event" well we need to make a clear differentiation between adding a copy of an event compared to adding another date.

**Tell me with a few sentences what the difference is.** 
---> As this is the information we need to inform the user of what adding another date actually means.

This is kinda like two twin brothers. To tell them a part one needs to look at both and figure out what the difference is.

**Comment by paaljoachim** [comment]
This is what it looks like right now:

![Screenshot 2021-11-05 at 00 13 37](https://user-images.githubusercontent.com/5323259/140433017-bfe9f249-2133-4194-a2f0-9a690ae6e5b2.jpg)

Btw no need to add the "Thanks!" I can bring it up in this issue: https://github.com/joedolson/my-calendar/issues/346
