### ISSUE TITLE
Moving + Add another date UI into Repetition Pattern.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#346]
As discussed on Slack.

Moving + Add another date UI into Repetition Pattern.

I will add the issue and then think about the UI.

I assume you are thinking something like this:

![Add-custom-dates-into-Repetition-Pattern](https://user-images.githubusercontent.com/5323259/140430873-004b8f0b-8842-477d-9f15-380fb91bbde2.jpg)

**Comment by paaljoachim** [comment]
Btw the message that shows up after adding a date:
![Screenshot 2021-11-05 at 00 15 40](https://user-images.githubusercontent.com/5323259/140433140-94e431e6-109a-4199-9bea-e70925018148.jpg)

**Thanks! A new date has been added to this event.**

I do not think it is needed (or we can think of another way to phrase it) when this has been added to the Repetition Pattern UI.

**Comment by joedolson** [comment]
I disagree; but if you have a specific suggestion for phrasing, let me know.

**Comment by paaljoachim** [comment]
We add a custom date. 

We can stick with the.
Message above that says: **A new date has been added to this event**

**Comment by paaljoachim** [comment]
The adjustment looks like this:

![Screenshot 2021-11-05 at 00 34 59](https://user-images.githubusercontent.com/5323259/140434584-0e93aaeb-ef07-4466-8443-7a5b9620eae4.jpg)

Here one needs to use the same event interface. One adds a date and in the same place adjusts what is needed and again clicks Add Date. 

Should we add a grey background or a border around each date to create a clear difference between each?
Perhaps something like so:

![Border-around-dates](https://user-images.githubusercontent.com/5323259/140434898-b5fe30cc-d7bd-482a-b355-ef52ace91539.jpg)

Btw there is no need to have the **Thanks!** in the **A new date has been added to this event** message.

**Comment by joedolson** [comment]
Noting that you're not seeing the current CSS in those screenshots; I didn't change what it looks like, but the CSS needed some updates to apply in the new location.

**Comment by paaljoachim** [comment]
I assume we also need to incorporate + Add another date into Repetition Pattern which is seen in the Add event screen?

It might mean something like + Add custom date where the user adds custom dates into the Repetition pattern section.

**Comment by joedolson** [comment]
> I assume we also need to incorporate + Add another date into Repetition Pattern which is seen in the Add event screen?

No. That's not possible, in fact, without pretty massive reconstruction of how new events are created. Maybe in some future release, but definitely not now.
