### ISSUE TITLE
Any ideas about this visual bug?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#347]
Hey Joe

Chrome.
Local site.

I see this on occasion. Top left. The grey above the left WP sidebar menu.

![Screenshot 2021-11-05 at 00 09 03](https://user-images.githubusercontent.com/5323259/140432610-b991e204-0860-4191-8dfa-2ccf28cedc4c.jpg)

![Screenshot 2021-11-05 at 00 08 54](https://user-images.githubusercontent.com/5323259/140432649-6ff63884-61f7-46f0-947d-eb7fbb84b9cb.jpg)

I wanted to mention it. This comes and goes. I am not sure if you can do anything about it. But I wanted to atleast mention it.

**Comment by joedolson** [comment]
It looks like something being echoed instead of returned, creating extra content on the page. Do a view content and look for something like 'selected=' or 'checked=', as those are the most probable strings. It'll be easier to find in a straight view source than in the inspector, in this case.

**Comment by paaljoachim** [comment]
I went to one of the pages (error is currently not seen). Did a view source.
Searched for selected= (found 17 mentions of it)
Searched for checked= (found 9 mentions of it)

What should I look for?

**Comment by joedolson** [comment]
Look for an example that is not contained within a logical HTML context. E.g., not an attribute of a checkbox, select option, or radio input.

**Comment by paaljoachim** [comment]
For selected. I am seeing a lot of option values.

I am adding in some of the codes that I see as they are all inside either checkboxes, options or radio inputs.

<option class='input' value='S'  selected="selected">Does not recur</option>

value='on' checked='checked' /> Host
id="mc_cat_2" value="2"  checked="checked" />

I do not believe the above helps. 
I do not think there is much we can do for this issue at the moment.

**Comment by joedolson** [comment]
Yeah, if I see it, I'll try and track it down, but I haven't seen this issue at all, which makes it hard to guess at.

**Comment by paaljoachim** [comment]
I went ahead and just moved it to the 3.4.0 milestone. (I am saying let's not spend any time on it now.)
I can always update the issue.

**Comment by joedolson** [comment]
It's been over a year, and I have still never seen this issue. So...closing. Can always reopen if needed.
