### ISSUE TITLE
Repetition daily by weekdays only not working correctly.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#350]
I did another test of Repetition Patterns. This time 10 Daily, weekdays only until 2021-11-20.

Starting Nov 8th.

![Screenshot 2021-11-05 at 11 27 54](https://user-images.githubusercontent.com/5323259/140496731-f1d4256a-e93a-4d9c-bdd2-0c0ff4bcf9f5.jpg)

**Comment by joedolson** [comment]
This issue is too general to be useful. Re-titling.

In general, avoid making large-sweeping generalizations in issues; they just make for issues that get extremely long and hard to close, because it's too difficult to tell whether they're finished.

**Comment by joedolson** [comment]
Technically, this is the same issue as #349. The only difference I can see is that the period is 10 days vs 5 days. If there's something else different about this that I'm missing, let me know.

**Comment by paaljoachim** [comment]
The reason for the broad issue is that I have checked multiple repetition patterns and there is just something not working there. I will create one issue for each patterns that does not work.

**Comment by joedolson** [comment]
That would be much preferred.

**Comment by paaljoachim** [comment]
Rechecking:
Repetition.
Frequency 10
Daily, Weekdays only.
Repeat Until: 2021-11-19

In the calendar I could only see it repeated twice.

![Screenshot 2021-11-05 at 17 32 27](https://user-images.githubusercontent.com/5323259/140545632-a0d6964b-0856-4017-be6e-351dc8638288.jpg)

**Comment by joedolson** [comment]
This is a duplicate issue; not needed.

Also, this looks right to me.
