### ISSUE TITLE
Repeat event - Daily for 7 days.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#352]
Repetition Pattern:
Frequency: 7
Period: Daily:
Repeat Until: (One week ahead 12 Nov 2021)

![Screenshot 2021-11-05 at 17 23 17](https://user-images.githubusercontent.com/5323259/140544322-97c4aa70-4d47-4265-9868-feb532ac6296.jpg)

Publish event.

View event in the calendar.
![Screenshot 2021-11-05 at 17 24 31](https://user-images.githubusercontent.com/5323259/140544470-71b4d92a-6893-4c24-a8fb-641908343bcf.jpg)

Shows only 1 event.

**Comment by joedolson** [comment]
Sounds like an off-by-one error. Expected: last event is on the 12th. Actual: event replication is stopped on the 12th.

**Comment by paaljoachim** [comment]
I expected to see the event repeated for each day from the 5th of November until the 12th of November, but only the one event is seen in the calendar.

**Comment by joedolson** [comment]
If you set a frequency of 'every 7 days', it won't happen every day...

**Comment by joedolson** [comment]
There is a valid issue here, and it's super weird. I'm testing, and repeat every 10 weekdays works (creates one event 10 weekdays later), but repeat every 5 weekdays (creates an event 5 *days* later, instead of 5 weekdays) doesn't. I'm not sure why, but it's going to require some exploration...

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar/commit/069d27dec721be3cb0c24e29cbac8088f1858edd#diff-6dd0488785a7eb05e57703415fd94735f4e913e7c5718ec77720bf51e7fc32c9
