### ISSUE TITLE
Repeat Weekly: Frequency 5

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#353]
Another.

Repetition Pattern.
Frequency: 5
Period: Weekly
Repeat Until 2021-11-26

This is what I see on the Frontend:
--> I see only one weekly event.

![Screenshot 2021-11-05 at 17 38 33](https://user-images.githubusercontent.com/5323259/140546387-c2811ae9-bc86-4f91-828c-94409ff2fc95.jpg)

Period weekly I might expect there to be one event per week until the 26th of November.
Which would mean one event on the 5th, 12th, 19th and 26th. Once a week until either 5 events are used or the end date/repeat until has been reached. So the repeat until was reached on the 26th of November making it 4 events instead of 5.

**Comment by joedolson** [comment]
Invalid issue; see comment on slack.
