### ISSUE TITLE
Edit Event: Clicking Edit Repetition Pattern not able to see the pattern

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#354]
I noticed when going to edit an event that clicking Edit Repetition pattern that the original repetition pattern does not show up. It resets itself.

![Screenshot 2021-11-05 at 18 03 43](https://user-images.githubusercontent.com/5323259/140550158-9652eb8e-a803-481e-89ab-7baa17fa03eb.jpg)

I expected that the original Frequency: 5. Period: Daily. Repeat Until 2021-11-19 would be seen.

**Comment by joedolson** [comment]
Hmm. I'm not seeing this; I'm seeing all the settings filled out as expected.

**Comment by paaljoachim** [comment]
I will retest using different examples and see if I get the same result.

**Comment by paaljoachim** [comment]
I tested two different Repetition Patterns and they show up as they should in the Event Edit screen. Closing issue.
