### ISSUE TITLE
Show human readable repetition pattern

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#355]
Two things:
1) Show the current pattern in human-readable format.
2) Show changes to the pattern to make output more predictable.

**Comment by paaljoachim** [comment]
Based on what I think this means.

![Screenshot 2021-11-05 at 21 24 03](https://user-images.githubusercontent.com/5323259/140574089-bf92dacb-01d5-4973-8a3e-6d73c7602f0d.jpg)


-1-
Show the current pattern in human-readable format.
**Daily until 2021-11-12**

-2-
Show changes to the pattern to make output more predictable.
----> Not sure what this means.

I did add another two dates:

![Screenshot 2021-11-05 at 21 27 04](https://user-images.githubusercontent.com/5323259/140574289-8c33518d-0cf9-45e0-bbbd-ed2dbbc10b88.jpg)

**Comment by joedolson** [comment]
> Show changes to the pattern to make output more predictable.

Did you try changing the pattern?

**Comment by paaljoachim** [comment]
Ahh. Yes I changed the pattern.
![Screenshot 2021-11-05 at 21 35 22](https://user-images.githubusercontent.com/5323259/140575278-66db77c9-8f09-406c-b008-7aaa153e2af4.jpg)

It showed the new output.
It is working nicely!
Thanks for adding that! It is very helpful information to have included!

**Comment by joedolson** [comment]
Note: you need to refresh your CSS cache.

**Comment by paaljoachim** [comment]
I just changed the pattern and clicked update, and it showed the new pattern and scheduled dates.

**Comment by joedolson** [comment]
Yes, and I can see in the screenshot that you aren't seeing the current version of the CSS.

**Comment by paaljoachim** [comment]
Ahhh. I used Autoptimize and refreshed. This came up.

![Screenshot 2021-11-05 at 21 42 59](https://user-images.githubusercontent.com/5323259/140576038-065057e3-1fa7-4264-9607-9ea4cf076923.jpg)

It looks like the CSS refreshed this time.
