### ISSUE TITLE
Add Event: Repetition Pattern - Strange message

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#356]
I made a new event. Did not fill in any information and went straight to Repetition Pattern.
Changed Period to Daily and this showed up:

![Screenshot 2021-11-05 at 21 44 29](https://user-images.githubusercontent.com/5323259/140576198-15f7c3da-c0cb-418b-b0bd-d56bd581020f.jpg)

**Comment by paaljoachim** [comment]
I went through the various options inside Period. Each had different notifications show up.
(I assume this is a one fix all situations.)

**Comment by joedolson** [comment]
What's the problem? That's telling somebody how many repetitions will happen if they omit the end date. (Which, granted, they can't do.)

**Comment by paaljoachim** [comment]
It looks like a notification bug. Or so it seems. As the user is not able to save/draft/publish/update an event without selecting a Repeat Until date.

**Comment by paaljoachim** [comment]
Especially went I go through and checked each option in the Period drop down and go back to Does not recur and see this:

![Screenshot 2021-11-05 at 21 52 04](https://user-images.githubusercontent.com/5323259/140577058-95846d30-24d5-42f6-9b7a-5badad7d7b64.jpg)

**Comment by paaljoachim** [comment]
I add in a date in the R"epeat Until" and I see:

![Screenshot 2021-11-05 at 21 57 53](https://user-images.githubusercontent.com/5323259/140577605-b93d0e17-76ac-4015-9572-cc7f3523a618.jpg)

That is a helpful message. Of course it could also mention:
Daily until 2021-11-12 (event repeated 7 times)

**Comment by joedolson** [comment]
There are some back-compat needs for that notification that I don't think I'll resolve now. Maybe later; but not for now. Will fix the empty notification field, however.

**Comment by paaljoachim** [comment]
Btw
This is very helpful! I really explains what frequency means.

![Screenshot 2021-11-05 at 22 19 43](https://user-images.githubusercontent.com/5323259/140579938-22e1c220-7f6c-4d94-a8bb-9bc7079bc162.jpg)
