### ISSUE TITLE
What to do with frontend event views?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#358]
Hey Joe

The following is the default view of the calendar. I have not touched any included stylesheets or adjusted any shortcodes. This is Twenty Twenty One in Chrome.

I assume this is one of the first things we will improve on for version 3.4. As this does look kinda like a list in one column. Somewhat messy list. Anyhow I do look forward to working on cleaning this up.

![Example-Frontend-Event-View](https://user-images.githubusercontent.com/5323259/141380090-20878844-8be9-4d93-ba03-faaab6fa5940.jpg)

**Comment by joedolson** [comment]
Can you send me a screenshot of the event address source code in there? I'm trying to figure out where that random period character is coming from.

**Comment by paaljoachim** [comment]
O the random . happened to be added to Street Address (2). It's a user simulated bug..:)

![Screenshot 2021-11-12 at 00 07 14](https://user-images.githubusercontent.com/5323259/141381717-0f674019-95ae-4506-a9b8-cae9a0b26199.jpg)

**Comment by joedolson** [comment]
Ah, great. Thanks - that's not something I'll be correcting for. ;)

Re: frontend views. Yes, a lot of revisions in 3.4.0. Not a thing to worry about right now.

**Comment by paaljoachim** [comment]
I'll go ahead and close this issue, as I do believe I have opened similar issues earlier.
