### ISSUE TITLE
Shortcode Generator: Comparing Main, Upcoming and Today.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#359]
I am comparing the three Main, Upcoming and Today screens.

Main
![Screenshot 2021-11-13 at 00 06 47](https://user-images.githubusercontent.com/5323259/141593788-a7a6d5bc-a24e-4167-a906-ef7fe6854252.jpg)

Main has these sections:
Content Filters.
Navigation
Author & Host Filters
Formatting & Timeframe
Initial Date Shown

Upcoming
![Screenshot 2021-11-13 at 00 07 01](https://user-images.githubusercontent.com/5323259/141593804-152f9eb9-5c9d-4f8c-a868-e7d9f4ea5d1c.jpg)

Upcoming has these sections:
Content Filters
Formatting & Timeframe

Does not have:
Navigation
Author & Host Filters
Initial Date Shown

Today
![Screenshot 2021-11-13 at 00 07 10](https://user-images.githubusercontent.com/5323259/141593811-6195a0bc-3274-4bbb-8c9c-0705ff759578.jpg)

Today has these sections:
Content Filters
Formatting & Timeframe

Does not have:
Navigation
Author & Host Filters
Initial Date Shown

I assume all three sections should be as similar to each other as logical possible to keep consistency.

**Comment by paaljoachim** [comment]
In the Main tab we have **Initial Date Shown**. 

![Screenshot 2021-11-15 at 13 09 51](https://user-images.githubusercontent.com/5323259/141779771-ae9993cd-7554-4d73-b09b-042571d4e9fb.jpg)

Having that in the Main seems a bit strange. As to me it looks like it focuses only on one date. 
Ahhh it actually means show from date going forward. Initial Date Shown = Start Date

**Comment by joedolson** [comment]
Yes, that language is probably a bit unclear...

**Comment by paaljoachim** [comment]
All three screens have now been adjusted.
This is what these look like after the fix:

**Main**
![Screenshot 2021-11-19 at 09 09 27](https://user-images.githubusercontent.com/5323259/142588258-4bb592ba-dc14-4db3-a888-b3c86d0a835a.jpg)

**Upcoming**
![Screenshot 2021-11-19 at 09 09 46](https://user-images.githubusercontent.com/5323259/142588318-50947f98-e988-494b-ab60-187a426b76a4.jpg)

**Today**
![Screenshot 2021-11-19 at 09 09 58](https://user-images.githubusercontent.com/5323259/142588340-9d99e0ca-20a8-4281-9670-00ea38b57eae.jpg)
