### ISSUE TITLE
Improving the Repetition Pattern message.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#360]
Hey Joe

I am wondering if we could/should improve the message seen even further.
An example.

Creating an event on the 18 of Nov.
Repetition daily until the 23 of Nov.

Looks like this:

![Screenshot 2021-11-13 at 00 16 30](https://user-images.githubusercontent.com/5323259/141594346-88313fef-09b0-4f19-bf76-bf082eb29753.jpg)

Here is a suggestion giving additional details. It creates an overview.

![Repetition-message-additional-details](https://user-images.githubusercontent.com/5323259/141594682-e3e93ee0-be3c-4c80-87b1-e3184a8947c7.jpg)

I believe this is associated with:
**Show projected scheduled dates when setting a repetition pattern.** 
https://github.com/joedolson/my-calendar/issues/351

If it seems like a doable issue then we can move it to 3.4.0

**Comment by joedolson** [comment]
May be in 3.4; I feel like it's a lot of redundant information, so I'm not sure it would be an improvement, but we can discuss later.

**Comment by paaljoachim** [comment]
Yeah. We can circle back again for 3.4, and take another look.

**Comment by joedolson** [comment]
I feel like this isn't necessary. Explaining the recurring pattern in basic terms makes sense to me; but repeating the dates & times that are already right there doesn't make sense.
