### ISSUE TITLE
Categories screen: Testing icons

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#363]
I just refreshed the My Calendar plugin.
Went to test out the icons list.
Checked out the list and decided on selecting anchor.

Made a new category called Anchor category with the anchor icon, but I see the house/home icon in the category screen instead.

---

I tested a few icons. Archway showed up. Writing ad or at into the Category Icon does not show a drop down. As it looks like the drop down that shows the icons first shows up after having written 3 characters or more. 

Here is an Anchor category where I initially added the anchor icon. On the first try the home/house icon showed up.

![Screenshot 2021-11-19 at 22 51 15](https://user-images.githubusercontent.com/5323259/142696032-ddcc0ba8-b54b-4945-b14b-7c533066f764.jpg)

Deleting the category and creating another anchor category. This time it showed up.

![Screenshot 2021-11-19 at 22 54 27](https://user-images.githubusercontent.com/5323259/142696409-36610e30-77dd-4162-b7a7-b0880f97ead0.jpg)

--------

Actionable items.
Have the drop down icons show up when the user writes Ad/ad or At/at.

Here is what it looks like when adding a Ad/ad icon.

![Screenshot 2021-11-19 at 22 57 12](https://user-images.githubusercontent.com/5323259/142696693-1d455fdc-6b50-4186-a1dd-5f9ea9ef3139.jpg)

**Comment by joedolson** [comment]
I think what you're saying is that the autocomplete should trigger after two characters, rather than three; is that right?

**Comment by paaljoachim** [comment]
Yes. That is correct. When the autocomplete triggers after two characters one will be able to click to select the Ad or At icons. Right now using these icons creates an error.

**Comment by joedolson** [comment]
Done.

**Comment by paaljoachim** [comment]
Great! I can now write ad and the drop down shows up.

![Screenshot 2021-11-23 at 11 22 05](https://user-images.githubusercontent.com/5323259/143007401-9e1e6325-5ab0-404a-a956-4e74ddbdd8e2.jpg)
