### ISSUE TITLE
Hide/Show places where a category icon shows up.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#364]
Adding an icon to a Category it will show up in these places.

The anchor icon example.

Categories screen:
![Screenshot 2021-11-19 at 23 04 20](https://user-images.githubusercontent.com/5323259/142697394-0487e634-ac69-4162-adb7-98c382450684.jpg)

We can choose to hide the icon so it is not seen in the Categories screen.

--

My Calendar frontend view:
![Screenshot 2021-11-19 at 23 00 53](https://user-images.githubusercontent.com/5323259/142697066-5c4f5cc1-7315-4b83-8780-33070bd8edc7.jpg)

Event view:
![Screenshot 2021-11-19 at 23 01 52](https://user-images.githubusercontent.com/5323259/142697235-162183ec-1450-439e-9920-599a2a2d1922.jpg)

In the My Calendar frontend view or in the event view. I see no way to hide the icon from appearing.
As one might want to show the icon in the Event view title but not in the calendar. Or the other way around.

Conclusion: Having a way to hide the icon in the calendar, categories seen below the calendar and the single event view.
As one might want to show the icon in one or more places but not all the above places.

I assume we can just push this to a later release.

**Comment by joedolson** [comment]
Not going to do this; in my opinion, it's trivial to do this with CSS, and I'm resistant to adding several additional settings to do this.
