### ISSUE TITLE
Affordance for event counts

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#367]
In the default view of the list and mini views, there's minimal affordance about how many events are on any date. Add event count to list view & add dot indicators to mini view.

**Comment by paaljoachim** [comment]
Hi Joe

I was working on understanding what you meant.

List view shows amount of events for each day.
![Screenshot 2021-11-23 at 11 16 32](https://user-images.githubusercontent.com/5323259/143006630-109e0c42-2401-4509-83d7-e85c55e3ff27.jpg)

Mini view shows a dot. Showing how many events there are each day.
![Screenshot 2021-11-23 at 11 18 08](https://user-images.githubusercontent.com/5323259/143006822-73bcc170-c777-4f90-85d6-c57acf10f4a8.jpg)

**Comment by joedolson** [comment]
That dot should be smaller, though...

**Comment by paaljoachim** [comment]
Yes. That is better!

(Same Twenty Twenty One theme as above only this time I changed the green background to become white.)
![Screenshot 2021-11-24 at 23 52 32](https://user-images.githubusercontent.com/5323259/143322751-12a5a913-49cd-498d-9183-f57031f34441.jpg)
