### ISSUE TITLE
Example on using the Upcoming shortcodes

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#368]
I am testing out the Upcoming shortcodes and I am about to write a separate documentation for showing how it works.

Shortcodes -> Upcoming.
![Screenshot 2021-11-23 at 12 18 50](https://user-images.githubusercontent.com/5323259/143015362-b4922b72-b1a3-4620-81bc-1d96c2a774ae.jpg)

Generated Shortcode

![Screenshot 2021-11-23 at 12 19 04](https://user-images.githubusercontent.com/5323259/143015421-f1b0ee77-e4b3-4ba6-9dc0-f6a38c956c62.jpg)

Adding the shortcode to the shortcode block in Gutenberg.

![Screenshot 2021-11-23 at 12 21 16](https://user-images.githubusercontent.com/5323259/143015910-2ce455ac-2b5a-45f3-a746-9a87a433ac4c.jpg)

Clicking to preview the result.

![Screenshot 2021-11-23 at 12 21 28](https://user-images.githubusercontent.com/5323259/143015683-794bfaf0-db7a-4cea-b655-6ecd2688d446.jpg)

Why is it showing the above as a list instead of showing the regular calendar?

**Comment by paaljoachim** [comment]
In the Shortcodes -> Upcoming I see this mention:
"Type of Upcoming Events List"

![Screenshot 2021-11-23 at 12 27 13](https://user-images.githubusercontent.com/5323259/143016385-8a738e99-4211-4910-8fd1-672b2628b91c.jpg)

It looks like I am not able to show as Grid view. As it looks like it only shows List view.

**Comment by joedolson** [comment]
The upcoming events list is a list of events. Only lists of dates can be displayed in grid view.

**Comment by paaljoachim** [comment]
So the Upcoming screen shows only lists. Is that correct? No possibility of grid view?
If I am mistaken which option would one pick in the "Type of Upcoming Events List"?

**Comment by joedolson** [comment]
From a front-end perspective, what would be the difference between the standard grid view and an upcoming events grid view? The point of an upcoming events list is to only show events that are coming up soon; the point of the grid view is to show events within the context of a grid. An upcoming events list that was in grid format would just be a normal grid, except that most of the events would be missing. That would be confusing, in my view.

**Comment by paaljoachim** [comment]
I expected to be able to select a grid (standard calendar view) based on the options I added.

Example. Based on the frontend list we see above starting November 25 and ending December 28. I was expecting to be able to select a calendar view where it started with Monday the Nov 22 and ending on Jan 2. Fairly close to the standard calendar view only filtering out all other categories expect category 2 (Concert in Paris).

**Comment by paaljoachim** [comment]
But then again. I could just use the Main screen and generate a shortcode that I need.

**Comment by joedolson** [comment]
What I should do is include brief notes on what each shortcode generation panel controls.

**Comment by paaljoachim** [comment]
Yes! That has also been in the back of my mind! It is a very good idea, as it gives a brief overview/introduction to the specific screen.

**Comment by joedolson** [comment]
Take a look at this change, let me know if that helps for you.

**Comment by paaljoachim** [comment]
Yes. This is very helpful! 

Main screen:

Generate the `[my_calendar] `shortcode. Generates the main grid, list, and mini calendar views.

![Screenshot 2021-11-23 at 19 23 30](https://user-images.githubusercontent.com/5323259/143082649-a87e2a7c-bc90-4863-b836-e917ca46fbf0.jpg)


Upcoming screen:

Generate the `[my_calendar_upcoming]` shortcode. Generates lists of upcoming events.

![Screenshot 2021-11-23 at 19 23 45](https://user-images.githubusercontent.com/5323259/143082607-63e339f2-a881-4b37-91e9-9e15618048d0.jpg)




Today screen:

Generate the `[my_calendar_today]` shortcode. Generates lists of events happening today.

![Screenshot 2021-11-23 at 19 23 58](https://user-images.githubusercontent.com/5323259/143082636-9e909c1e-8fea-4826-bc2e-96b79cf8e979.jpg)
