### ISSUE TITLE
Using Upcoming shortcode - clicking to edit this template.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#369]
This issue builds upon: 
Example on using the Upcoming shortcodes
https://github.com/joedolson/my-calendar/issues/368

After having generated the Upcoming shortcode I see this:

![Screenshot 2021-11-23 at 12 19 04](https://user-images.githubusercontent.com/5323259/143018632-9e67d5f5-6b7d-47de-a5d9-ff6041b803e7.jpg)

I click to edit this template, and I am lead to Design > Templates.
I see this:

![Screenshot 2021-11-23 at 12 48 00](https://user-images.githubusercontent.com/5323259/143018934-72790694-d6bf-46ba-b5f6-2a9c15dcbdb6.jpg)

I assume that there is meant to be more information in the Custom Template then what I can see there.

I am not sure where to go or what to do in relation to this screen. I will keep exploring this aspect of My Calendar.

----

The same thing happens with the Today screen.

**Comment by joedolson** [comment]
When you create a template in a shortcode, it's automatically saved as a custom template, and used by reference in the shortcode rather than directly. (Using them directly can create all sorts of problems with nested quotes.)

Not sure what information you're expecting.

**Comment by paaljoachim** [comment]
I was expecting to see the shortcode modifications brought over to the template. So that I could see a relation between the generated shortcode and the template.

**Comment by paaljoachim** [comment]
As I have yet to dabble into working with templates. I expected that options I added in the shortcode such as category 2, before 5 and after 18. Type event and order asc would in one way or another be addressed in the template.
Even though the shortcode is about what is to be seen (filtering) and the template is about what the output is (CSS) I expected somekind of overlap between filtering and CSS so to speak.

Perhaps just a simple /* A Custom Template is created from the generated Shortcode. Add HTML and CSS to modify the output of the layout. See documentation: -link url- on how to work with templates. */

**Comment by joedolson** [comment]
Templates don't have a relationship to shortcodes in any significant way; that template is used by the shortcode, but could be used anywhere. I'm not going to add any overlap between those; templates will only ever be about what's showing for an event, not about which events are shown.

I have some thoughts, will think about it.

**Comment by joedolson** [comment]
Added some minor changes; take a look.

**Comment by paaljoachim** [comment]
This is helpful!

Edit Custom Template ->
Is better than
Edit This Template ->

--

![Screenshot 2021-11-24 at 23 55 42](https://user-images.githubusercontent.com/5323259/143323121-862e8982-2e02-4e44-b588-d2a32fa8a54a.jpg)

---

I will go ahead and close this issue. Thanks for the adjustment! The wording going from **This** to **Custom** creates a better separation between the Generated Shortcode vs a template.
