### ISSUE TITLE
List view - clicking to open event - moving cursor away title dissapears. 

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#370]
I just now noticed the following.
In List view. Click a title once and move the cursor away. Notice that the title goes all white.

https://user-images.githubusercontent.com/5323259/143029885-3e9ad59b-9d29-405b-b97d-8746ae7ce304.mp4

**Comment by joedolson** [comment]
Is this in the admin or the front-end? If front-end, which stylesheet & theme?

**Comment by paaljoachim** [comment]
Frontend.
Theme: Twenty Twenty-One with a white background.
Style Editor: (default) twentytwenty.css

**Comment by joedolson** [comment]
What are your color variables set to? I'm not seeing the buttons as white on black background - in my dev site, they're black on a white background.

![image](https://user-images.githubusercontent.com/1686451/143069465-5eec6722-5195-4aa0-a1c3-5a2241e5ef43.png)

**Comment by paaljoachim** [comment]
Ahhh this might be creating the problem.

![Screenshot 2021-11-23 at 18 04 43](https://user-images.githubusercontent.com/5323259/143070515-02509d73-3751-427f-8ca6-609e72e0d07b.jpg)

**Comment by joedolson** [comment]
Hmm, no - that should be fine. Still not seeing it using similar settings. Could it be because of a Twenty Twenty One setting?

**Comment by paaljoachim** [comment]
I tested in another dev site. The colors are different. Which means I might have adjusted some colors or did something to affect these.

Bottom line is that it looks to be working as it should.
Closing this issue.
