### ISSUE TITLE
Text settings - Event title

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#371]
Event title (Grid) I added an on to the title, so it looks like this:
`{time} Event Title: {title}`

On the frontend I see this:

![Screenshot 2021-11-23 at 13 33 31](https://user-images.githubusercontent.com/5323259/143027307-ef1a2e7e-d86f-49ad-bda6-8106d3b9c114.jpg)

Changing Event title (Single) and Event title (List)

`Event Single Title:  {title}`
`Event List Title: {title}`

Event title (Single)has no change.

![Screenshot 2021-11-23 at 14 16 00](https://user-images.githubusercontent.com/5323259/143030844-9f3fe473-dae5-41c1-b0c7-07db49daa4ee.jpg)

Actually it does have a popup change (It just does not add the additional information to the Single view but only the popup view)
![Screenshot 2021-11-23 at 14 25 22](https://user-images.githubusercontent.com/5323259/143032153-9bb2322f-571c-4a7c-ac65-81894a85f64d.jpg)

**I assume that the Event title (Single) should instead say Event title (popup)....?**

--

Event title (List) I see this:

![My Calendar WordPress plugin Text Settings Frontend modifying Event title List](https://user-images.githubusercontent.com/5323259/143030812-8a3f04a6-cb48-44d5-b34d-2de9e82b9e7d.jpg)

**Comment by joedolson** [comment]
I could actually filter the title format in single view; there's already a filter on that, inserting the category icon - no reason it couldn't also change the title format, so that's more consistent.

**Comment by paaljoachim** [comment]
Great! The Event Single view is also changed when adding Event Single Title: {title} to the Event title (Single) field.

![Screenshot 2021-11-25 at 00 15 02](https://user-images.githubusercontent.com/5323259/143324451-757ed8ee-b848-456d-b2ea-70db6844f505.jpg)
