### ISSUE TITLE
Text Setting: ? popup tooltips are different vs Add Event tooltips

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#372]
Here is an example from Repetition Pattern.

![Screenshot 2021-11-23 at 17 10 41](https://user-images.githubusercontent.com/5323259/143061179-eff11139-e7e1-4ef7-bad7-ad30183e9380.jpg)

Here is an example from Text Settings.

![Screenshot 2021-11-23 at 17 12 33](https://user-images.githubusercontent.com/5323259/143061346-f83f4b93-4425-4a33-bccd-13ca1bf5a0f9.jpg)

The first example with Repetition Pattern seems to be focused on click to open a modul and get additional information.
The second example in Text Settings seems to be focused on inline info beside the ? icon.

**Comment by joedolson** [comment]
One of those is a tooltip; the other is just an icon indicating this text is informational. I'd consider this a non-issue, but if you want to suggest a different icon, please do.

**Comment by paaljoachim** [comment]
I think we will just leave it as it is. I might circle back to it at another time.
