### ISSUE TITLE
Display Settings: A very big My Calendar Icon.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#373]
I am seeing this very big My Calendar icon. I am not sure if it is meant to be so or not.
To me this row feels too big. I would assume it would be the same size as the rest but we could just keep the white background making it stand out from all the other background color grey rows.

![Screenshot 2021-11-25 at 00 03 02](https://user-images.githubusercontent.com/5323259/143323678-9727b751-8aad-4516-a487-f8a75b56e249.jpg)

**Comment by joedolson** [comment]
This is an intentional change; trying to make the calendar space stand out
more to better communicate that everything else is being organized around
it. Not sure about the look, but I do think the principle is viable. It's
had a white background for a long time, but I didn't feel that was strong
enough.

**Comment by paaljoachim** [comment]
The issue I have is the really big icon. 
Here is one with a smaller icon but it keeps the size of the row. 

![Smaller-My-Calendar-icon](https://user-images.githubusercontent.com/5323259/143325201-5d20f956-b5c5-4f94-a3a2-dcc8da0d06df.jpg)
(The icon is now just a tiny bit bigger than the other icons.)

The My Calendar text is the same size like the other texts in this section. It would be good to also keep the icon the same size as the other icons. Keep the size of the space as it is now.

**Comment by paaljoachim** [comment]
This is better. Keeping the consistency of the icons and titles.

![Screenshot 2021-11-25 at 15 25 55](https://user-images.githubusercontent.com/5323259/143458827-6cebb8a5-4e61-43a3-bc5d-6746f7aa3f09.jpg)
