### ISSUE TITLE
Twenty Twenty One: focus position jumps when opening popup

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#374]
Twenty Twenty One contains code that intercepts all anchor links containing a '#' and moves scroll position to that link. This causes an undesirable focus position movement for popups. 

```
		/**
		 * Close menu and scroll to anchor when an anchor link is clicked.
		 * Adapted from Twenty Twenty.
		 *
		 * @since Twenty Twenty-One 1.1
		 */
		document.addEventListener( 'click', function( event ) {
			// If target onclick is <a> with # within the href attribute
			if ( event.target.hash && event.target.hash.includes( '#' ) ) {
				wrapper.classList.remove( id + '-navigation-open', 'lock-scrolling' );
				twentytwentyoneToggleAriaExpanded( mobileButton );
				// Wait 550 and scroll to the anchor.
				setTimeout(function () {
					var anchor = document.getElementById(event.target.hash.slice(1));
					anchor.scrollIntoView();
				}, 550);
			}
		} );
```

Not sure there's a viable way around this other than switching the popup trigger to a button, which creates a significant new burden in formatting.

**Comment by paaljoachim** [comment]
Perhaps Twenty Twenty One could use a fix instead?

**Comment by joedolson** [comment]
That would be preferable, yes. They shouldn't really be capturing all links with this.

**Comment by paaljoachim** [comment]
I went ahead and added this Trac ticket:
https://core.trac.wordpress.org/ticket/55143#ticket

**Comment by joedolson** [comment]
Thanks!

**Comment by paaljoachim** [comment]
Hey Joe.

Carolina has left feedback in the Trac issue.
https://core.trac.wordpress.org/ticket/55143#comment:2
"Hi @paaljoachim & @joedolson, would you be able to add the steps to reproduce this issue?
Thank you."

https://core.trac.wordpress.org/ticket/55143#comment:3
Is this the same issue as reported in https://core.trac.wordpress.org/ticket/53331 ?

**Comment by joedolson** [comment]
Ticket updated at WordPress trac

**Comment by joedolson** [comment]
This is fixed in core JS using `e.stopImmediatePropgation()` - missed closing at the time.
