### ISSUE TITLE
Going through text settings: Extended caption

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#375]
I am going through the Text settings and in Main Calendar View the default Calendar heading is:

![Screenshot 2021-11-25 at 14 11 50](https://user-images.githubusercontent.com/5323259/143447690-0da2a81c-a8d0-44d3-8333-628753a77489.jpg)

**Events in November 2021.**

It is possible to extend the heading through the Extended Caption field but I see no field to actually change the current heading for the month view.

We are able to change the "Week view caption" like so:

![Screenshot 2021-11-25 at 14 16 52](https://user-images.githubusercontent.com/5323259/143448426-0d134c12-9566-4a9c-9d49-d2ea5a9deade.jpg)

We should be able to change the "Month view caption" in the same way.

**Comment by joedolson** [comment]
Closing; there is a field for the month view caption. 'Calendar month heading'

**Comment by paaljoachim** [comment]
Here is a screenshot:
![Screenshot 2022-12-22 at 20 45 59](https://user-images.githubusercontent.com/5323259/209254493-7553bc9b-25f6-4c37-a311-bbdd664e05f4.jpg)
