### ISSUE TITLE
Text settings: Week view caption missing placeholders

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#376]
Previous
Next
are listed inside the fields.

![Screenshot 2021-11-25 at 14 19 37](https://user-images.githubusercontent.com/5323259/143448824-ac7cfffc-b89c-4548-96a9-d9f30b212656.jpg)

I assume the Week view caption: (blank) should list the default seen on the frontend `Week of {date format="M j"}` (This is almost right.)

Almost correct code:

![Screenshot 2021-11-25 at 14 26 42](https://user-images.githubusercontent.com/5323259/143449778-76d5e5cb-7293-4241-ae96-65c157161dd1.jpg)

Adding the current Week view caption placeholder would also make it easier for the user to adjust what is already there compared to inserting a new caption.

**Comment by joedolson** [comment]
Fixed in some commit or another.

**Comment by paaljoachim** [comment]
Yep it is in place.

![Screenshot 2023-03-08 at 23 53 14](https://user-images.githubusercontent.com/5323259/223869803-05d7eb50-d3f7-4433-a20c-2ac4777cac24.jpg)

(Checking through some older issues I never did go through.)
