### ISSUE TITLE
Display Settings: Reset to default calendar layout

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#377]
I began moving various fields up and down and soon lost track of what the default layout was.

I am wondering if we should include a reset to default layout button?

![Screenshot 2021-11-25 at 15 25 55](https://user-images.githubusercontent.com/5323259/143459043-9664fbf7-6b63-4150-be87-6c6630266cba.jpg)

**Comment by joedolson** [comment]
I don't see a lot of value in that. What does it matter what the default is? Once people are manipulating this, they're presumably making decisions about what they want and what order it should be in.

**Comment by paaljoachim** [comment]
That is fair.
I usually like to be able to return various settings to the default to understand where it started from.
I can go ahead and close this issue. If I think of other "better" reasonings I can always reopen.
