### ISSUE TITLE
Design - Templates: Rename Core Templates details to single

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#378]
Renaming Core Templates.
Currently these are called: grid, list, mini and details.

1- Renaming details to single.

An alternative.
2- Should these be named: Grid view, List view, Mini view and Single view?
(Settings -> Text mentions Grid, Single and List.)

![My Calendar WordPress plugin Design Templates Core and Custom](https://user-images.githubusercontent.com/5323259/143495298-dbd3b275-a860-4016-bcf7-c35c90aedd02.jpg)

**Comment by paaljoachim** [comment]
Clicking grid brings one to:

![Screenshot 2021-11-25 at 21 25 04](https://user-images.githubusercontent.com/5323259/143497342-f30c03d8-af8a-4312-84d3-b1dcdac6e730.jpg)

"Core Template: used in the details pop-up in the main calendar view."

-------


Now that I think of it. Perhaps we should skip doing anything else with it, ss this is a section which will be reworked at a later time.

**Comment by joedolson** [comment]
Definitely not 3.3.0. That's not a trivial change to make, and could create a lot of breakages if it's rushed.

**Comment by joedolson** [comment]
In the next version of templating, this is called single. It won't be a breaking change, because it's a completely new templating system; but I won't be changing this in the existing templating, which will be moving to legacy status when the next version is done.
