### ISSUE TITLE
Question about creating a template file.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#379]
I just read this information in the My-Calendar-v3.2.0 pdf page 54.

"You can place a template file in your theme directory and reference it from the My Calendar shortcode. If you have a template file called “template.txt” in your theme directory, it would be referenced as `[my_calendar template=”template.txt”]` in your shortcode."

Should template.txt be placed in the root of the theme?

**Comment by joedolson** [comment]
It can be at the theme root, in a directory named 'css' in the theme, in the plugin directory `my-calendar-custom`, or in a subdirectory called 'styles' of `my-calendar-custom`. 

All of the possible locations are listed in the Help screen.

**Comment by paaljoachim** [comment]
Where and which Help screen are you thinking about?

**Comment by joedolson** [comment]
wp-admin/admin.php?page=my-calendar-help#my-calendar-files

**Comment by joedolson** [comment]
Or, as a path: `My Calendar > Help > Custom Files`

**Comment by paaljoachim** [comment]
So basically what we see here:
![Screenshot 2021-11-28 at 21 10 01](https://user-images.githubusercontent.com/5323259/143784201-fb276ec5-8291-44fa-ac9e-085104f819f6.jpg)

It lists the Custom Icons Location
.... My Calendar/my-calendar-custom/

Custom Styles Locations
..../plugins/my-calendar-custom/styles/
..../plugins/my-calendar-custom/
..../themes/twentytwentyone/css/
..../themes/twentytwentyone/

Custom print, mobile, and tablet stylesheet file names: mc-print.css, mc-mobile.css, and mc-tablet.css.

Perhaps we could have a mention above the last sentence with some information on where files should be located.
Something like.

We recommend adding a custom CSS stylesheet into (specific folder or folders) or a custom template file into (specific folder or folders).

**Comment by joedolson** [comment]
Any of these locations are equal; the only limitation with icons is that they're looked for in fewer places. Not going to address this now; this will be part of the large-scale templating changes in the future.

**Comment by paaljoachim** [comment]
Adding the 3.4 milestone to it.

I will just leave this text in place:
"You can place a template file in your theme directory  and reference it from the My Calendar shortcode."
https://docs.joedolson.com/my-calendar/my-calendar-design-templates/
