### ISSUE TITLE
Clicking to Hide end time should grey out or just remove the end date date bringing back the placeholder.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#38]
Clicking to Hide end time looks like this:

![Screen Shot 2021-04-18 at 20 52 15](https://user-images.githubusercontent.com/5323259/115157192-2748a200-a088-11eb-9363-6d7acb3bd238.png)

Some options to what it can do.
Reset the date so it goes back to the placeholder:
![Screen Shot 2021-04-18 at 20 53 09](https://user-images.githubusercontent.com/5323259/115157201-3c253580-a088-11eb-9305-c73d3fd282e3.png)

Or hide the text above and the field.

Or something else to show that the field is not active.

**Comment by joedolson** [comment]
I can see what you're seeing, but that's not what the control does; it only changes how the event will be displayed on the front-end. The end time is still set, it's just not displayed on the front end of the site. But the end time is still relevant for knowing when to display the event is other contexts, such as upcoming events lists. 

I could move this option to a global setting, but in practice I've learned that a lot of organizations only *sometimes* don't want to show this information. 

But I do appreciate that this can be confusing; do you have any thoughts about what might be clearer, given that?

**Comment by paaljoachim** [comment]
It is a minor thing, so I we can instead just close the issue.
