### ISSUE TITLE
Design - templates doc: converts code to calendar view.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#382]
I wrote this (copy and pasted from the v3.2.0 pdf page 54).

You can place a template file in your theme directory and reference it from the My Calendar shortcode. If you have a template file called "template.txt" in your theme directory, it would be referenced as `[my_calendar template=”template.txt”]` in your shortcode.

In the doc page here: https://docs.joedolson.com/my-calendar/my-calendar-design-templates/
The shortcode is converted to an image.

![Screenshot 2021-11-25 at 22 17 31](https://user-images.githubusercontent.com/5323259/143500588-656fe0e6-fa66-4ab4-baa7-4270c90fd255.jpg)

**Comment by joedolson** [comment]
Since I installed My Calendar on the docs site, that's causing shortcodes to render. I'll add a shortcode to render shortcodes as text. E.g. `[shortcode shortcode="[my_calendar]"]`.

**Comment by joedolson** [comment]
Done. Not quite what I'd planned, use like

`[shortcode shortcode="my_calendar format='list'"]`

Basically, use the shortcode but omit the square brackets. You'll have to use single quotes on all attributes for nesting purposes, but they'll be replaced with double quotes on display.

**Comment by paaljoachim** [comment]
Joe I am a bit confused. If you can go in here: https://docs.joedolson.com/my-calendar/my-calendar-design-templates/ and add the correct shortcode than I can see what you add. The main thing is being able to show the shortcode (which perhaps could also be done as text in a paragraph block) so the user can see the code used.

**Comment by joedolson** [comment]
Ah - you're using the shortcode inline, so I'll need to tweak it a bit. I was wrapping in `<pre>`, but I'll need to wrap in `<code>` instead.

**Comment by joedolson** [comment]
Done. You don't need to apply `code` to these shortcodes; it's done by the shortcode. If you want a shortcode to be block level, you can do `[shortcode shortcode="[my_calendar]" wrap="pre"]`

**Comment by paaljoachim** [comment]
I am now inserting the correct shortcode

If you have a template file called "template.txt" in your theme directory, it would be referenced as [my_calendar template=”template.txt”] in your shortcode.

**Comment by paaljoachim** [comment]
I have been trying variations of the [my_calendar template=”template.txt”] but it is not working yet.

**Comment by paaljoachim** [comment]
This is now working:
If you have a template file called "template.txt" in your theme directory, it would be referenced as [shortcode shortcode="my_calendar template='template.txt'"] in your shortcode. 

Thanks!
