### ISSUE TITLE
Minor change to Core template descriptions. Changing pop-up to popup.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#383]
Hey Joe

This is a minor change.
Core Template: used in the details pop-up in the main calendar view.
Core Template: used in pop-ups for the mini calendar.

![Screenshot 2021-11-28 at 13 02 53](https://user-images.githubusercontent.com/5323259/143766859-0d358e27-93aa-48f2-aeb1-4a8ba2326e3a.jpg)

+

![Screenshot 2021-11-28 at 13 01 46](https://user-images.githubusercontent.com/5323259/143766818-337d14a1-7ef9-4799-86b3-8d80a660d00f.jpg)

Changing "pop-up" and "pop-ups" to "popup".

Same as we use in Settings > Display.

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar/commit/2c15ea321a9d4fb729401372be31414660926819

**Comment by paaljoachim** [comment]
Thanks!
Fixed.
Here:
![Screenshot 2021-11-28 at 20 23 41](https://user-images.githubusercontent.com/5323259/143782809-d039e4d1-6f56-4cb1-9eda-0659f25fce4c.jpg)
and
in the templates.
![Screenshot 2021-11-28 at 20 23 52](https://user-images.githubusercontent.com/5323259/143782818-faca29e7-b586-4ee9-b601-c51c74e47066.jpg)

![Screenshot 2021-11-28 at 20 24 44](https://user-images.githubusercontent.com/5323259/143782832-b7b429b3-1ef2-4de6-a78e-9b1a159c9ae6.jpg)
