### ISSUE TITLE
Settings > General: Calendar Page Location drop down.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#384]
It is not obvious that the Calendar Page Location is actually a drop down.

![Screenshot 2021-11-28 at 21 32 18](https://user-images.githubusercontent.com/5323259/143784868-0b8eb7ba-c234-4c4b-b6a7-695692ad3131.jpg)

Should it look like a regular drop down?

Of course clicking on the My Calendar text (or into this area) one sees the area turn into a drop down.

![Screenshot 2021-11-28 at 21 33 00](https://user-images.githubusercontent.com/5323259/143784911-b639373e-4274-4c63-a52e-5cca52a2e77a.jpg)

After clicking into the area it becomes obvious one needs to go and create a new page if one wants the page to be named something else than My Calendar.

**Comment by joedolson** [comment]
Well, I'll look at this.

1) It's not a dropdown, it's an autocomplete search.
2) If you don't want your calendar to be called 'My Calendar', you should edit the page, not create a new one. I'd actively like to put a stop to people creating new pages just because they want the page title to be different.

**Comment by paaljoachim** [comment]
I am glad I mentioned creating a new page as I am now brainstorming an update to the text in the Help > Getting Started page which is outside the documentation and directly in the WP backend. I am in the process of creating the issue for it now.

**Comment by paaljoachim** [comment]
Now this is really helpful! A good way to direct people to just rename the current selected calendar page.

![Screenshot 2021-11-28 at 21 55 38](https://user-images.githubusercontent.com/5323259/143785730-8149a790-1ad0-4711-9364-f7fd7636cc9c.jpg)

What I miss with this is that I am not able to see all the pages on the site. It lists some of them that start with "My" but not all of them. As I have to know the name of it to have it show up in the "drop down".

**Comment by joedolson** [comment]
It searches everything; but the minimum search length is three characters. And if you just click on it, it's performing a search for 'My Calendar'.

**Comment by paaljoachim** [comment]
I selected another page. Clicked the "Save Management Settings" button. Refreshed the page. Clicked into the autocomplete and wrote My...

![Screenshot 2021-11-28 at 22 07 23](https://user-images.githubusercontent.com/5323259/143785998-f7e0b89d-2f1c-4227-95d7-c872a16554c7.jpg)

The My Calendar page is not showing up....

**Comment by joedolson** [comment]
And if you extend the search? It's searching every post on the site; it's only going to show so many results at a time. One thing I could do is tweak the results so that they're sorted in relevance order. WordPress doesn't do a great job of organizing by relevance, but it would improve things a bit, probably.

**Comment by paaljoachim** [comment]
This is the result.
![Screenshot 2021-11-28 at 22 11 41](https://user-images.githubusercontent.com/5323259/143786127-d9c8cf29-8e0e-49d6-b1f4-4f875a4df8c0.jpg)

**Comment by paaljoachim** [comment]
I will download the newest update and recheck.

**Comment by paaljoachim** [comment]
Great My Calendar page is now showing up.
![Screenshot 2021-11-28 at 22 17 33](https://user-images.githubusercontent.com/5323259/143786310-459ff028-132e-4b64-81c6-bb159d62d649.jpg)
