### ISSUE TITLE
How to use My Calendar - Getting Started 

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#385]
Today we have this text:

Getting Started
Add events by clicking on the Add Events link in the admin or on "Add Events" in the toolbar.
Select your preferred stylesheet in the Styles Editor
View your calendar
Build a custom shortcode: Shortcode Generator

![Screenshot 2021-11-28 at 22 39 04](https://user-images.githubusercontent.com/5323259/143787042-302f4683-d6d5-4283-96cc-66791a2353da.jpg)

----

Updating the above text.

Some brainstorming. (I just need to write it out, and we can figure out how to adjust the current text. As it just about giving users a soft start to getting started using the plugin.)

After installing My Calendar plugin go to Settings > General and notice the Calendar Page Location. Default is the "My Calendar" page. Clicking into this area opens an Autocomplete Search to where you can select another existing page by beginning to write the name of the page. 
You can also click "edit the current calendar page" and rename the page. Return to the General Settings and select the renamed page and click the button "Save Management Settings".

Go to your calendar page and view the page on the frontend. Notice the default event "Florence Price: Symphony No. 3 in c minor" is seen in the calendar view. Click the event and notice the popup show a preview of the event. Click the Read more text link which will open the single event view. Single event includes all the default event information.

Go to the backend. My Calendar > Events and notice the one event under My Events.
A new event can be added by clicking My Calendar > Add Event.

Check our documentation to learn more about how to use the My Calendar plugin.

**Comment by joedolson** [comment]
Is this text you're proposing to use to extend the intro or replace it? 

I'd keep the text as short as possible; e.g.

- View[link] or Edit[link] your calendar page
- [shown for new installs only] View the demo event[link] and the demo location[link]
- Read the documentation

In addition to the existing information.

**Comment by paaljoachim** [comment]
I am thinking we need to look at the goal for the Getting Started section.

I have shortened the information I added.


Go to Settings > General.
Use, select another page or rename My Calendar to become the default calendar page.

View your **calendar** (link).

Go to My Calendar > events to view the event in the backend. Click Add new to create a new event.

Visit the **documentation** (link).

------


Add events by clicking on the Add Events link in the admin or on "Add Events" in the toolbar. 
(Too much information on adding events at the Getting Started stage.)

Select your preferred stylesheet in the Styles Editor
(Too complex in a getting started section.)

View your calendar (-link-)
(added above.)

Build a custom shortcode: Shortcode Generator
(The user does not need this in the Getting Started section. As this is more for intermediate users, and not beginners.)

--------


I shorted the above but it could use some more space and more information to become more useful as a helpful getting started section.

**Comment by paaljoachim** [comment]
Changed to:

![Screenshot 2021-11-29 at 23 05 54](https://user-images.githubusercontent.com/5323259/143950567-9e007764-fc49-4678-8c1d-d994e6b6c6e1.jpg)

It gives the important links a new user can use. 

Should we link directly to the Quick Start Guide - Getting Started documentation?
https://docs.joedolson.com/my-calendar/my-calendar-quick-start-guide-getting-started/
The reason why I say this is that I think it might be useful with some more detailed information the user can be guided to.
