### ISSUE TITLE
Using current released plugin and than overwriting with new Github plugin version - produced fatal error -

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#386]
Usually when I use a plugin and manually upload a newer version of the same plugin I see the plugins information side by side and can then select to keep the current or upload the new. I think it is a fairly new feature in WordPress.

In this case using the current release plugin and uploading the latest plugin from Github an error showed up.

Fatal error: Cannot redeclare mc_plugin_activated() (previously declared in /Users/paaljoachimromdahl/Sites/hivepress.dev.cc/wp-content/plugins/my-calendar/my-calendar.php:54) in /Users/paaljoachimromdahl/Sites/hivepress.dev.cc/wp-content/plugins/My Calendar/my-calendar.php on line 71

![Screenshot 2021-11-29 at 22 12 31](https://user-images.githubusercontent.com/5323259/143943773-9b9b103d-ec97-44f1-a4d4-5d1957adbdf9.jpg)

**Comment by joedolson** [comment]
Well, those two plugins have different file paths, so you're technically uploading a duplicate of the plug-in - not sure why you'd have a different path name, but that would cause WordPress to assume they're two different plugins. (/my-calendar/ vs /My Calendar/).

**Comment by paaljoachim** [comment]
Ahhh yes. I am renaming the plugin from My Calendar to my-calendar.
After a bit of fidling I got it to work.

![Screenshot 2021-11-29 at 22 37 58](https://user-images.githubusercontent.com/5323259/143946902-d99cf83f-aaca-445d-8dc1-8dff2a5e3cb4.jpg)

The two events I added are both showing up. Using the correct Location and the correct category.
A good first test.

**Comment by paaljoachim** [comment]
I tested with yet another dev site. Using Blocksy theme and has various plugins installed.
Added the current my-calendar plugin. Added 1 event + 2 occurrences. Added also a repetition pattern that would repeat the se events 5 times.

Then installed the new my-calendar version and the events, occurrences, repetition pattern, category and location is in place.
