### ISSUE TITLE
Link to stylesheet diff does not work

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#391]
Design > Style Editor
Notification: There have been updates to the stylesheet. [Compare Your Stylesheet with latest installed version of My Calendar.](https://my-calendar.dev.cc/wp-admin/admin.php?page=my-calendar-design&diff)

Clicking the link does not lead one to the area below the CSS Variables but just refreshes the page, and removes the notification.
One has to scroll below the CSS Variables to actually see the Current (in use) and Latest (from plugin) comparison.

![Screenshot 2021-12-03 at 18 05 47](https://user-images.githubusercontent.com/5323259/144643368-ffb2d7fd-8363-4fb8-bfe5-04543966baca.jpg)

Clicking "Save Changes" the screen jumps to the top and I can see this:

![Screenshot 2021-12-03 at 18 07 08](https://user-images.githubusercontent.com/5323259/144643492-c88d25cb-8880-427b-97d3-d25db3453ff6.jpg)

I can refresh the page and the one save notification is removed but the "There have been updates to the stylesheet. Compare Your Stylesheet with latest installed version of My Calendar." Is still seen.

**Comment by joedolson** [comment]
The notice will continue until I updated the template store for stylesheets, which I won't do until the new stylesheet is locked. 

The link issue is legit, however, so I changed the name.
