### ISSUE TITLE
Design > Style Editor: CSS Variables do not change when changing Stylesheet.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#392]
Hey Joe

I just noticed that the CSS Variables do not change when changing Stylesheets. 
I assume the question comes up... Should the CSS Variables change when changing the Stylesheet or should these variables stay independent of the Stylesheet? It looks like one can set the overall defining colors of the calendar through CSS Variables and then adjust any CSS directly in the Stylesheet one wants to use. Keeping these separate from each other.

![CSS-Variables](https://user-images.githubusercontent.com/5323259/144645230-c3e73bb8-a706-4197-b4e0-5ffb4a73e656.jpg)

Ps
The above colors were meant for Twenty Twenty One Stylesheet to show where each color has an impact.

**Comment by joedolson** [comment]
No, CSS variables are general settings, not tied to a specific stylesheet.

I've considered adding sets of variables that can be tied to a stylesheet, but that would only  happen in the next major release.
