### ISSUE TITLE
Design > Style Editor: How to Reset a stylesheet?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#393]
At the bottom of Design > Style Editor I noticed:

"Resetting your stylesheet will set your stylesheet to the version currently distributed with the plugin."

![My Calendar WordPress plugin Design Style Editor CSS Variables](https://user-images.githubusercontent.com/5323259/144662336-9a23ec11-4819-4cbc-8583-33454bde35f5.jpg)

I am not seeing any reset button or a method to reset a stylesheet.

**Comment by joedolson** [comment]
It's the checkbox above the editing field: "Update stylesheet to match core version".

**Comment by paaljoachim** [comment]
Ahh...
Seems like the better sentence would be:
"Reset stylesheet to match core version". As it would use the same phrase "reset" as the sentence on the bottom.

"Resetting your stylesheet will set your stylesheet to the version currently distributed with the plugin."

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar/commit/41a89188ded4f85ab2b78b6b3a4c70d29c585a1b

**Comment by paaljoachim** [comment]
This feels a lot cleaner.

![My Calendar WordPress plugin Design Style Editor](https://user-images.githubusercontent.com/5323259/144713624-1a550cce-2e5c-47a4-8788-53094e9bad08.jpg)

Bottom. 
It removes:
"Resetting your stylesheet will set your stylesheet to the version currently distributed with the plugin."

Under the CSS Style Options area.
It removes:
-checkbox-  "Update stylesheet to match core version"

**Comment by joedolson** [comment]
You should also check out what it's like when the stylesheet is different.

**Comment by paaljoachim** [comment]
By removing the setting we are also saying that the user can not revert back to a default stylesheet. If they really want to revert then they will need to download the plugin and find the stylesheet they need and copy over the CSS.

I am not really sure what you mean here:

> You should also check out what it's like when the stylesheet is different.

--

"Use your own styles"

I am thinking it might need a **?** Add a custom stylesheet to ..... and it will be used instead of the default stylesheets that are included within the plugin.

What actually happens when the user clicks "Use your own styles"?
I assume the default stylesheets are deactivated. Which they are as I see the calendar on the frontend looks stripped of styles. Should the Choose Style drop down be deactivated when the user clicks to use their own styles?

**Comment by joedolson** [comment]
I haven't removed the control; it's only visible if the stylesheets don't
match. Based on that screenshot, yours matches.

Best,
Joe

**Comment by joedolson** [comment]
![image](https://user-images.githubusercontent.com/1686451/144718338-0ce07265-f475-42f6-9fbd-98b86ffb701a.png)

![image](https://user-images.githubusercontent.com/1686451/144718364-ff964342-6b3f-4036-9c5a-d1f6e77ff8a0.png)

**Comment by paaljoachim** [comment]
Yeah! I noticed when making a change to a stylesheet and clicking the **Save Changes** button, that the notification showed up. Clicking the text link "Compare Your Stylesheet with latest installed version of My Calendar." Will show a comparison between the original and the change made.

I am adding on to the doc.

**Comment by paaljoachim** [comment]
Btw
Update stylesheet to match core version. (dot)
If one clicks this the checkbox here and clicks **Update Styles** it reverts back to the original version.
I find the current phrase confusing. It would be better if it said: Revert back to original version.

**Comment by joedolson** [comment]
That's not technically accurate; it updates it to the current version of the styles that are shipped with the plug-in. Those may or may not be the "original" styles. Open to other ways of saying it, but not sure what that would be.
