### ISSUE TITLE
Design > Styl Editor: Selecting multiple CSS variables to delete only deletes one.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#394]
I am starting over with the create a stylesheet process and noticed that when selecting multiple Delete checkboxes that only the last variable will be deleted when clicking the "Save Changes" button.

![Screenshot 2021-12-04 at 15 35 04](https://user-images.githubusercontent.com/5323259/144713354-eb94c1fe-7adf-4277-b96c-7320b222e136.jpg)

Of course it actually might be a good idea to keep it as it is...:)
So that one can only delete one variable at a time even though multiple checkboxes are checked.

**Comment by joedolson** [comment]
No, I think it should delete everything that's checked. It's otherwise a very unexpected interaction.

**Comment by paaljoachim** [comment]
I agree. When the user clicks multiple CSS variable checkboxes then one is also expecting to delete the selected variables.

**Comment by paaljoachim** [comment]
Example selecting 3 Delete checkboxes and clicking Save Changes. Will automatically delete the selected checkboxes.

![Screenshot 2021-12-05 at 20 34 45](https://user-images.githubusercontent.com/5323259/144760927-0710ecc5-6353-4912-9568-d34e670cd0fc.jpg)
