### ISSUE TITLE
Show users which css variables make accessible color combinations

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#397]

**Comment by paaljoachim** [comment]
This is what I see:

![Screenshot 2021-12-05 at 23 46 55](https://user-images.githubusercontent.com/5323259/144766954-bcd50346-99d8-4c0a-bbf1-8e134316230e.jpg)

Could use a cleanup.

**Comment by joedolson** [comment]
Specifics?

**Comment by paaljoachim** [comment]
Right edge.
I removed the -- as these came on top some places and to the left other places.
I added a left and top line to create some differentiation between sections.

![Variables](https://user-images.githubusercontent.com/5323259/144767691-1e5501b1-5053-4aeb-b70a-809e35d3c106.jpg)

**Comment by paaljoachim** [comment]
Cleaning it up even further to create a symmetry making it easier to read.
![Color-order](https://user-images.githubusercontent.com/5323259/145058042-85b078fb-596f-4ba4-a588-2f88dac0e57d.jpg)

**Comment by joedolson** [comment]
What exactly are the changes? Do you think it's needed for the `with {varname}` to be visible in grid view? I feel like that's better only visible in mobile; the grid provides that correlating information when you're viewing it as a table. 

I feel like you may have viewed this without updating the CSS or cache, otherwise these changes don't make a lot of sense to me.

**Comment by paaljoachim** [comment]
I did some hard cache refreshing and it sure came out a lot better.
This looks good!

![Screenshot 2021-12-08 at 21 54 31](https://user-images.githubusercontent.com/5323259/145282954-c55587b0-07b9-4db2-93b1-7eec7a6e39fd.jpg)

Closing the issue!
