### ISSUE TITLE
Design > Style Editor: Reset stylesheet to match core version 

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#398]
Design > Style Editor.
1- I edited a core theme. Clicked Save Changes.
2- Noticed the notification

![My Calendar WordPress plugin Design Style Editor compare changes notification](https://user-images.githubusercontent.com/5323259/144763155-d92e6a1a-290b-4f24-8d32-a198d3a14e63.jpg)
 
Clicked to compare.

I am now seeing this:

![Screenshot 2021-12-05 at 21 42 12](https://user-images.githubusercontent.com/5323259/144763174-9768e310-b6e1-47b0-9b35-409fc9bd816d.jpg)

Checkbox to reset styles and a button to Reset Styles. 
Should Reset Style be Save (Styles)? As it seems that just clicking the button will reset the styles, so one is not able to keep the changes one made.

User clicks checkbox to reset the stylesheet to the latest version from the plugin. Then clicks the button.
User does not click the checkbox and only clicks the button to keep the current styles.

**Comment by paaljoachim** [comment]
Is the checkbox needed? Would it be good enough with just using the Reset Styles and the Return to editing (I assume Editing - capital E) ?

![Screenshot 2021-12-05 at 22 53 53](https://user-images.githubusercontent.com/5323259/144765396-a6b01852-25f5-4bd9-b42f-da50b37dc246.jpg)

**Comment by joedolson** [comment]
No, the checkbox is not - strictly speaking - needed. I thought about removing that, but I do think that it's a good thing that people have to take a little effort to reset their stylesheet. It's not a recoverable action, so it's good to have to think about it a bit...

**Comment by paaljoachim** [comment]
Gotcha!

**Comment by paaljoachim** [comment]
This is what I see:

![Screenshot 2021-12-05 at 23 31 03](https://user-images.githubusercontent.com/5323259/144766563-d34e4898-cf1f-464c-84db-7134e1e0a85f.jpg)

Looks good!
