### ISSUE TITLE
Design > Style Editor: Saving a change to a theme - Fatal error

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#399]
Design > Style Editor - Choosing a theme and making a change. I noticed this error.

Fatal error: Uncaught Error: Call to undefined function wpa_hex2rgb() in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/my-calendar/my-calendar-styles.php on line 630

Error: Call to undefined function wpa_hex2rgb() in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/my-calendar/my-calendar-styles.php on line 630

![Screenshot 2021-12-05 at 23 04 20](https://user-images.githubusercontent.com/5323259/144765715-8d4293ba-3dd7-4294-bad7-1c0c4fcb49d0.jpg)

**Comment by joedolson** [comment]
Puzzle to me why that error wasn't thrown for me...odd.

**Comment by paaljoachim** [comment]
It seems to be working after the fix.
