### ISSUE TITLE
Remove dashicons beside top/bottom bar actions text links.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#40]
I suddenly noticed the Dashicons beside the text links above the event title.

With dashicons:
![Screen Shot 2021-04-18 at 21 00 40](https://user-images.githubusercontent.com/5323259/115157398-4f84d080-a089-11eb-961a-fad1cd76d6a6.png)

Without dashicons:
![Screen Shot 2021-04-18 at 21 00 59](https://user-images.githubusercontent.com/5323259/115157411-5a3f6580-a089-11eb-8287-9483bcbdf406.png)

To me it looks better without the dashicons here.

**Comment by paaljoachim** [comment]
Experimenting with the action text links.

Here I removed the grey background, and added some more padding between the links.
.mc-controls li {
    display: inline-block;
    padding: 0 15px 0 0;
    margin: 0;
}

![Screen Shot 2021-04-18 at 21 04 09](https://user-images.githubusercontent.com/5323259/115157479-be622980-a089-11eb-88e4-0eddeca94575.png)

**Comment by joedolson** [comment]
The dashicons are there to offer affordance for people with learning and reading impairments; having both text & images can help make interfaces easier to understand. 

They aren't something that help me at all, as I *personally* struggle to understand what the icons mean - and if you have any suggestions about changing the icons to something that you think conveys the sense better, I'm open to that.

Note that the 'template' link is a new thing, and I'm not sure I'm going to keep it - it just links to a view of the output of the template tags for this event. 

Removing the background field is something I'm pretty open to, though; I don't think that's a particularly necessary part of the design.
