### ISSUE TITLE
Design > Style Editor - Adding change to theme - "Compare Your Stylesheet.." Notification does not go away

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#400]
Design > Style Editor
Adding a change to twentytwenty.css.
Clicking "Save Changes"

Clicking  "Compare Your Stylesheet with latest installed version of My Calendar."

Clicking "Return to editing"

This is still seen:

![Screenshot 2021-12-05 at 23 44 05](https://user-images.githubusercontent.com/5323259/144766862-01721ac0-4744-41de-a6d3-fd398e46c451.jpg)

The Compare Your Stylesheet notification message should go away after having looked at the Current vs Latest and clicked the Return to editing button.

**Comment by joedolson** [comment]
That's a wontfix. In my opinion, users need to be made aware that they are not using the core stylesheet as written. Open to text changes, but the notice will stay.

**Comment by paaljoachim** [comment]
I just jumped to another theme and back again. It is actually comforting seeing the notification telling me that I have changed the theme. So I will go ahead and close this issue.
