### ISSUE TITLE
Changing Featured Image in Event Group does not change it for all events in the group.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#401]
I made an event and 2 additional copies.
Added a featured image.
Checked the frontend and all use the same featured image.

Went to Events -> Edit Group -> Changed the featured image for all the events. (All events were checked so that these should be changed.) But only one event had the featured image changed.

![Screenshot 2021-12-07 at 16 41 10](https://user-images.githubusercontent.com/5323259/145060701-f77813cd-976f-405a-b290-6b9fa8415564.jpg)

--

I also tested with changing the contents information, and all the events where updated.
I changed the title and all events also had their title changed.

**Comment by joedolson** [comment]
This one was tricky...

**Comment by paaljoachim** [comment]
You got it working correctly!
Nicely done!
