### ISSUE TITLE
Going from old events -> new version events.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#403]
Former plugin version.
Added an event + 3 Occurrences. + repeated 5 times over a few weeks.
Added a category to it with a ball icon.

Output Settings. Clicking Calendar opened the event directly into the Single Event view.
I also added a Google map to it.

Updated the plugin to RC4.

Noticed this:

![Screenshot 2021-12-08 at 23 35 10](https://user-images.githubusercontent.com/5323259/145304717-29394b3e-884d-4d29-832b-892b99c3e62b.jpg)

See the Grid View and List View, Check all, and two events that are having problems.

Clicking to Edit the one yellow event.
I see this:
![Screenshot 2021-12-08 at 23 40 12](https://user-images.githubusercontent.com/5323259/145303054-07b1fc90-d767-43a9-a593-6ae4b76df73c.jpg)

![Screenshot 2021-12-08 at 23 40 25](https://user-images.githubusercontent.com/5323259/145303066-93ee5c49-0b51-4dfd-a083-43ad5e714286.jpg)

As well as additional layout problems.

Single Event view.
It is showing a huge icon in the top.

![Screenshot 2021-12-08 at 23 44 15](https://user-images.githubusercontent.com/5323259/145304822-62ecf584-5e14-4cc1-8906-a299ab136da5.jpg)

There are a lot of visual errors I see.

-----

I will go to another local site and retrace/retest various steps I did. I will add it into the next comment.

**Comment by paaljoachim** [comment]
Thanks for the reminder on doing a hard refresh!
I hard refreshed the backend and then the frontend and the visual weirdness went away.

For the events that had "There is a problem with this event." I edited and resaved the event. Then checked Events -> My Events again, and the error had gone away.

![Screenshot 2021-12-08 at 23 57 41](https://user-images.githubusercontent.com/5323259/145304889-88d7adfd-9d9a-40d8-a0e2-81d9c9e0d4ab.jpg)

Should we add a note telling the user to resave/update the event? As the error might go away.

**Comment by paaljoachim** [comment]
I have retested a couple of times. One time I had to do a hard refresh. Another time not.
For all the tests the warning message showed up.
Updating the event removed the warning message.

----

Actionable item is to add a message to the warning telling the user to **update the event**.

**Comment by joedolson** [comment]
Are these retests always with the same event, or have you done a wide variety of events and this is always happening?

If it's always the same event, please share with me the exact path to create the event, so I can explore that.

**Comment by joedolson** [comment]
What is your date formatting? Looking closely at your screenshots, I think that it's d/m/y in the management column, and y-m-d in the edit screen. If that's the case, why is the date in the event editing screen in November, but the management column is December? That seems odd to me...

**Comment by paaljoachim** [comment]
These are different events. I actually made a 8 minute video on the last test, so you can check it out here:
https://youtu.be/Smj7iO9Bc30 (Should be almost ready to be viewed...)

**Comment by joedolson** [comment]
Thanks - that's useful, although it misses one thing that I really needed to see to be able to figure this out; you always updated the event *before* scrolling down to a point where I could see the date information. So I don't know whether or not the date information showed any more details or indicated a change.

But I did see how you set up the events, so I can test that on my own. It is a slightly unusual event pattern, and somewhat unlikely in real life, but shouldn't actually throw an error. (December 8th at 22:00 - December 9th at 23:00, a 25 hour long event)

**Comment by paaljoachim** [comment]
Here is the overview:

![Screenshot 2021-12-09 at 01 23 18](https://user-images.githubusercontent.com/5323259/145312145-28ed4b7d-4387-4081-8ba7-91c0110d969c.jpg)

**Comment by joedolson** [comment]
I've reproduced it; exploring. I think the error is in the error message,
not in the event. (E.g., an incorrect flag set.)

**Comment by paaljoachim** [comment]
Great! I retested and this time it works nicely!
No error message!

I will go ahead and close this issue!
Nice job!
