### ISSUE TITLE
The new doc: View Locations

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#405]
I just noticed a View Locations doc.
https://docs.joedolson.com/my-calendar/view-locations/

Locations have two primary views: the single location view and a shortcode to display locations.

List of Locations
A list of locations is produced with the shortcode `[my_calendar_show_locations]`.

The list can sort by name, city, state, zip, country, or region; by default, it will sort by name.

I made a Locations List page.
Added the shortcode: `[my_calendar_show_locations]`.

![Screenshot 2021-12-11 at 19 57 04](https://user-images.githubusercontent.com/5323259/145688328-a4f77ccf-5125-4f97-88e2-0e2c82ada478.jpg)

Went to view the page on the frontend and noticed the shortcode not show. It was blank.
![Screenshot 2021-12-11 at 19 59 03](https://user-images.githubusercontent.com/5323259/145688383-354a4891-fb82-4090-adca-1313293efccb.jpg)

----

From what I see the purpose of the doc to "View Locations" is show how adding a location will also add the location to a map if one has added Google Maps API key.
+
That one with a shortcode can generate a "List of Locations". 

Both elements are nice to show. I am thinking of redoing the doc with additional text and screenshot information.

**Comment by paaljoachim** [comment]
This shortcode works:
`[my_calendar id="my-calendar"]`

Backend:
![Screenshot 2021-12-11 at 21 08 02](https://user-images.githubusercontent.com/5323259/145690164-cb3bc251-2323-445f-8624-f8eb16abbac6.jpg)

Frontend:

![Screenshot 2021-12-11 at 21 08 36](https://user-images.githubusercontent.com/5323259/145690184-93a5a3e8-d8f1-491b-b157-623606562018.jpg)

--------

This shortcode works:
`[my_calendar_show_locations template= '{label}, {state/province}']`

Backend:
![Screenshot 2021-12-11 at 21 09 44](https://user-images.githubusercontent.com/5323259/145690216-3245e5fa-a39d-468c-8f3f-5606390e1ab3.jpg)

Frontend:
![Screenshot 2021-12-11 at 21 10 14](https://user-images.githubusercontent.com/5323259/145690234-e51396f3-2f00-47f3-a926-2e5f26ac0eea.jpg)

--

The first shortcode shows all the information added to each location.
The second shortcode only shows the title of the location. I do not know what effect adding in state/province has.

**Comment by joedolson** [comment]
With that shortcode, none; state/province isn't a valid template key.

**Comment by paaljoachim** [comment]
Alrighty. I adjusted the shortcode.
![Screenshot 2021-12-11 at 21 39 01](https://user-images.githubusercontent.com/5323259/145690975-cae526f5-c147-4204-b66c-0ef719cb4d13.jpg)

Frontend.
![Screenshot 2021-12-11 at 21 39 10](https://user-images.githubusercontent.com/5323259/145690977-e4ab207a-8fd7-4c9b-86af-468876dc9f29.jpg)

It shows the same result on the frontend.
(I did a few hard refreshes just in case.)

**Comment by paaljoachim** [comment]
https://docs.joedolson.com/my-calendar/view-locations/

A list of locations is produced with the shortcode `[my_calendar_show_locations]`.

**The list can sort by name, city, state, zip, country, or region; by default, it will sort by name.** How?

How do the above shortcode compare to the below? As these are very different from each other.

`[my_calendar_show_locations template= '{label}, {city}']`

**Comment by joedolson** [comment]
The attribute is 'datatype', which is a legacy of a long past version...
I'll add an alias called 'sort', so that it's more intuitive...

**Comment by joedolson** [comment]
Add 'sort' as an alias for 'datatype'. You can effectively ignore the 'datatype' parameter in that shortcode and reference 'sort' instead. Valid sort fields:

name, city, state, zip, country, region.

**Comment by paaljoachim** [comment]
I need some more details I can add to the doc here, Joe.

**Comment by joedolson** [comment]
Sorry; what are you looking for?

**Comment by paaljoachim** [comment]
Somekind of update to: https://github.com/joedolson/my-calendar/issues/405#issuecomment-991782057

As it contains two shortcodes:

`[my_calendar_show_locations]`

and

`[my_calendar_show_locations template= '{label}, {city}']`

**Comment by joedolson** [comment]
For example, per https://github.com/joedolson/my-calendar/issues/405#issuecomment-991936650:

`[my_calendar_show_locations sort="city"]`

Sorts the list of locations by the city value.

**Comment by paaljoachim** [comment]
Ahh so this is the shortcode that we should use:
`[my_calendar_show_locations sort="city"]` (with these options: name, city, state, zip, country, region.)

The shortcode `[my_calendar_show_locations template= '{label}, {city}']` should I mention this as well?


I will likely merge this page: https://docs.joedolson.com/my-calendar/view-locations/
Into where I mention View here: https://docs.joedolson.com/my-calendar/my-calendar-locations/
(There are two screenshots I need to update in the doc.)

**Comment by joedolson** [comment]
It's the same shortcode, but yes, it's worth mentioning both attributes. The template changes what is displayed, and supports these template tags:

{id}, {label}, {street}, {street2}, {city}, {state}, {postcode}, {region}, {url}, {country}, {longitude}, {latitude}, {zoom}, {phone}, {phone2}

Though I'm noticing a logic error that means that templates won't ever be run in some cases; will review that.

**Comment by paaljoachim** [comment]
I have updated the doc here: https://docs.joedolson.com/my-calendar/my-calendar-locations/

Example adding this shortcode:
`[my_calendar_show_locations template= '{id},{label},{street},{city}']` or
`[my_calendar_show_locations template= '{id},{label},{street}']` or
`[my_calendar_show_locations template= '{id}']`

All show the same on the frontend:
![Screenshot 2021-12-13 at 23 17 43](https://user-images.githubusercontent.com/5323259/145897777-b8ef73fd-086f-4ea0-b413-f4ee715e07a1.jpg)

**Comment by joedolson** [comment]
Is that the exact shortcode you're using? If so, I think it's invalid, because there's a space between `=` and the value.

**Comment by paaljoachim** [comment]
Trying these shortcodes:
`[my_calendar_show_locations template='{id},{label},{street},{city}']` then
`[my_calendar_show_locations template='{id},{label},{street}']` then
`[my_calendar_show_locations template='{id}']`

Same result as last time.

**Comment by joedolson** [comment]
Well, it was worth checking.
