### ISSUE TITLE
Display Settings: Unchecking all Single Event display fields option and saving does not pick up the change - error -

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#407]
In the Settings > Display > Event Display Fields.
I wanted to experiment to see if totally deleting the My Calendar plugin and then uploading the plugin again would bring back the default "Single Event" Display fields options.

I unchecked all the Single Event options. 
Clicked Save.
Noticed a half second glimpse of an error before all the checkboxes reverted back to what they were before I clicked Save.

I tried again. Unchecking some of the checkboxes and saving. Unchecked some more and saved. Then unchecked the rest and noticed this:
![Screenshot 2021-12-11 at 21 49 05](https://user-images.githubusercontent.com/5323259/145691203-3b8e7076-fd03-4ebc-929f-78727664e3f6.jpg)

Notice: Undefined index: mc_display_single in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/my-calendar/my-calendar-settings.php on line 311

Warning: array_map(): Expected parameter 2 to be an array, null given in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/my-calendar/my-calendar-settings.php on line 311

**Comment by joedolson** [comment]
What version of PHP is this?

**Comment by joedolson** [comment]
Assuming you're still running locally in DesktopServer, it's probably 7.3. I'll test with that.

**Comment by joedolson** [comment]
Ah; it's because you unset *all* values. OK. I can handle that.

**Comment by joedolson** [comment]
FYI, unsetting all values will set the configuration back to default settings

**Comment by paaljoachim** [comment]
> FYI, unsetting all values will set the configuration back to default settings

That is actually a really interesting way of getting the default values back!

Unclicking all values in the Single Event, Main View, and Mini Calendar Popup Display Field and saving brought back the default values.
