### ISSUE TITLE
Manage Locations: View a location on the frontend?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#408]
I am wondering in the quick edit bar that shows up on hover if we should add in a View?

![Screenshot 2021-12-12 at 10 08 48](https://user-images.githubusercontent.com/5323259/145706650-fd596aac-eed4-44a2-a26f-f0f9442769ba.jpg)

Viewing the location information and map if there is one connected on the Frontend.

**Comment by joedolson** [comment]
This is already there, if the location has a location post reference & pretty permalinks are enabled. It won't always show, but in the cases it doesn't show, it also wouldn't work.
