### ISSUE TITLE
Preview Template Output error

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#409]
The following showed up as I was working on getting the correct address for the Sydney Opera House. (Using Google Maps to also show it.)

![Screenshot 2021-12-12 at 10 13 39](https://user-images.githubusercontent.com/5323259/145706766-ff13afa5-ea97-4f21-8bb2-a40f1d35ee9c.jpg)

 Warning: in_array() expects parameter 2 to be array, string given in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/my-calendar/my-calendar-output.php on line 866

**Comment by paaljoachim** [comment]
The same error is also seen on the frontend.

**Comment by joedolson** [comment]
This is the same issue as #407; closing. This is a problem fetching the setting that isn't being set properly in that issue, but it's really the same issue.

**Comment by paaljoachim** [comment]
It looks like it is working now.
