### ISSUE TITLE
Updating a location does not update the Google map

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#410]
I added a Sydney Opera House location. Found out that it showed the wrong place on the map and also noticed that I had made a mistake in the address. I updated the location address but the map did not update.

![Location-map-not-updating](https://user-images.githubusercontent.com/5323259/145706908-ac8417f2-e6c1-4b34-9a40-4a542f1acbbb.jpg)

I totally changed the address to something else. Saved the changes. Hard refreshed but the map did not change.

**Comment by joedolson** [comment]
This is because the map is derived from the latitude/longitude if those are set. Maybe I need to monitor for changes in the address settings and re-query the lat/lon values if the address is changed.

**Comment by joedolson** [comment]
Added a checkbox to refresh the GPS coordinates. I can't just auto update them on every change; Google isn't *always* right with GPS coordinates, so that would prevent people from fixing incorrect coordinates or adding extra precision.

**Comment by paaljoachim** [comment]
The "Update GPS Coordinates" option worked well!

I will update the Location doc....
