### ISSUE TITLE
Location: View Location and View

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#411]
I noticed the following:

![My Calendar WordPress plugin Location quick edit](https://user-images.githubusercontent.com/5323259/145728484-e7e623c2-4924-4613-91d3-46930b9fc635.jpg)

View Location and below it View.

Clicking View Location I see this:
![Screenshot 2021-12-12 at 21 31 00](https://user-images.githubusercontent.com/5323259/145728512-e3ec643c-df4c-4b86-8d45-3411983fdc68.jpg)

Adding events to the default location I see this:
![Screenshot 2021-12-12 at 22 01 17](https://user-images.githubusercontent.com/5323259/145729398-ec8ae3a5-4ebd-4d50-a89d-c6f103b52c65.jpg)

Clicking View shows the same thing.

The first and third location shows a View Location link.
The second location has no View Location or View option. (Shows the map when editing the location.)

![Screenshot 2021-12-12 at 21 32 14](https://user-images.githubusercontent.com/5323259/145728546-78c89a49-639c-4488-a6bf-b61e6eaa62b3.jpg)

**Comment by paaljoachim** [comment]
It would be nice to be able to view the map in addition to all the location information when clicking View Location.
I assume the View option to the left of Edit will be removed.

**Comment by joedolson** [comment]
You should see the map on the frontend; that looks like you might have a JS error, since the map HTML is rendering but not the map itself. Can you check the console?

**Comment by paaljoachim** [comment]
I edited my comment as I noticed a Map link instead of the map itself.

**Comment by paaljoachim** [comment]
There is no console error when I check the frontend.

**Comment by joedolson** [comment]
Hmm. Probably nothing I can do to address that, then, without being able to actually inspect it.

**Comment by paaljoachim** [comment]
Well this does look correct:

![Screenshot 2021-12-12 at 22 05 52](https://user-images.githubusercontent.com/5323259/145729536-106b7e3a-707b-42f2-b6c1-f923751734b9.jpg)

**Comment by paaljoachim** [comment]
Btw no error on the Locations screen backend.

**Comment by joedolson** [comment]
The map output is the part above that; the address that doesn't show the 'map' link. But I've found the case that triggers this; it's if the API key is entered, but 'show maps' isn't enabled in single event view; but that shouldn't apply to the locations view.

**Comment by paaljoachim** [comment]
Only the default location has a quick edit View option. The two other locations do not.

![Screenshot 2021-12-12 at 22 21 52](https://user-images.githubusercontent.com/5323259/145730009-75e8af25-c7f8-4fac-a787-919bdc6c5002.jpg)

![Screenshot 2021-12-12 at 22 24 51](https://user-images.githubusercontent.com/5323259/145730097-e650219e-8a27-4aea-ad61-b79c893ceb7b.jpg)

**Comment by paaljoachim** [comment]
I just noticed your comment here:
https://github.com/joedolson/my-calendar/issues/408#issuecomment-991971230

I assume we should close this issue. It seems that sometimes one can view the location and sometimes not.....

**Comment by joedolson** [comment]
How did you create those locations? Were they created in the location manager, or by adding with an event?

**Comment by paaljoachim** [comment]
Add New Location (Location Manager)

**Comment by joedolson** [comment]
Should be fixed now. Doesn't retroactively fix locations you already created, but fixes the process of creating new locations.

**Comment by paaljoachim** [comment]
I was able to see View on all the newly added locations.

![Screenshot 2021-12-13 at 00 55 48](https://user-images.githubusercontent.com/5323259/145734812-ed92e7ed-bac4-48f2-8a2a-8d930525e89d.jpg)

**Comment by paaljoachim** [comment]
Clicking View for Sydney's Opera House. I can see this frontend screen:

![Screenshot 2021-12-13 at 01 00 35](https://user-images.githubusercontent.com/5323259/145734970-31d1d290-2325-422d-a37a-d002b1d3e84f.jpg)

1- Quick edit: View is seen in all the new locations.
2- It shows a nice frontend view with a map (if there is one) the location information and events (if there are any).

Nice job! Closing issue!
