### ISSUE TITLE
Adding additional information to All Pages screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#415]
I am wondering if we should do as WooCommerce (and WP core) does.

![Screenshot 2021-12-13 at 10 57 48](https://user-images.githubusercontent.com/5323259/145790978-ca31a89f-d6e2-4bc0-9aad-f5ccd4f2272d.jpg)

Add in a - My Calendar Page

![All Pages My Calendar](https://user-images.githubusercontent.com/5323259/145791737-92c22074-b820-45fa-81cf-7dca1b99f846.jpg)

Something to perhaps look into at a later time.

**Comment by joedolson** [comment]
It's pretty easily done, so could do. Low priority, though.

**Comment by paaljoachim** [comment]
Great! I see this adjustment:

![Screenshot 2022-01-21 at 10 22 43](https://user-images.githubusercontent.com/5323259/150501346-3a973092-f151-44c7-91de-7ec98cf7c49b.jpg)
