### ISSUE TITLE
Map not rendering on front-end view for locations.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#417]
I am bringing this issue onward from the video I shared here:
https://github.com/joedolson/my-calendar/issues/416#issue-1078463790

From the latest my-calendar version I did not see any map rendered on the frontend.

**Comment by joedolson** [comment]
I need to know what type of issue this is. Can you check for console errors and verify whether the script 'gmaps.js' is enqueued?

**Comment by joedolson** [comment]
I've reproduced it. Very unclear issue so far; exploring.

**Comment by joedolson** [comment]
Ha, Found it. It was actually simple; caused by fixing some variable arguments that were wrong, but triggered something else to be correct.

**Comment by paaljoachim** [comment]
Great work Joe!

Both of these locations show a quick edit: View.
![Screenshot 2021-12-13 at 21 28 42](https://user-images.githubusercontent.com/5323259/145883873-2e29c507-033a-43be-8afe-62a3e4f8155e.jpg)

Both also show a map
![Screenshot 2021-12-13 at 21 27 46](https://user-images.githubusercontent.com/5323259/145883982-51cdefd9-4213-470e-96dc-df59e28e862f.jpg)
 on the frontend:
