### ISSUE TITLE
Deleting location used by event produces error.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#418]
1- Created a few events.
2- Selected an existing location. I had earlier made in Add New Location Manager.
3- Deleted the location in the Location Manager.
4- Went to one of the events that had used the deleted location and noticed an error.

![Screenshot 2021-12-13 at 21 45 49](https://user-images.githubusercontent.com/5323259/145886173-73740005-8ab2-41ee-848d-6f104ec817f8.jpg)

Warning: count(): Parameter must be an array or an object that implements Countable in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/my-calendar/my-calendar-templates.php on line 882

Warning: Invalid argument supplied for foreach() in /Users/paaljoachimromdahl/Sites/my-calendar.dev.cc/wp-content/plugins/my-calendar/my-calendar-templates.php on line 883

Location Map is seen like so:
![Screenshot 2021-12-13 at 21 47 14](https://user-images.githubusercontent.com/5323259/145886265-1b371f4d-e560-4329-ba58-a430e1723b06.jpg)

**Comment by joedolson** [comment]
This commit fixes this specific issue; there may be other consequences of a deleted location. Add them to this issue as well, as you find them.

**Comment by joedolson** [comment]
Closing; fixed everything I found as well, so at this point, anything more should be a new issue.

**Comment by paaljoachim** [comment]
The first issue: 
Don't run location map if no locations. - Has been fixed.
