### ISSUE TITLE
Locations: Check all - pressing Delete locations - nothing happens.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#419]
Clicked Check all.
Then clicked Delete locations. At first it said it was not able to delete location. I went to another screen and came back to Locations. Tried again to Delete locations. This time no message showed up. Nothing happened. (It loaded as if something was to happen but nothing did.) I do not see any errors in the Chrome console.

![Screenshot 2021-12-13 at 22 41 13](https://user-images.githubusercontent.com/5323259/145893494-0d348a5e-4228-4aa6-bedc-11f9215e27ed.jpg)

**Comment by joedolson** [comment]
Well, makes sense. There aren't any checkboxes, so 'check all' doesn't do anything. I'll have to see what's filtering those out; they're still in the code...

**Comment by paaljoachim** [comment]
Checkboxes are now added and it looks like this:
![Screenshot 2021-12-14 at 16 17 50](https://user-images.githubusercontent.com/5323259/146026219-595558ac-f9dd-451b-9441-a71578e4a7ba.jpg)

The deletion message also clearly mentions 1 location(s) deleted successfully out of 1 selected.
