### ISSUE TITLE
Remove grey background behind checkboxes.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#42]
As I was experimenting with the Categories area I looked at the grey area behind these checkboxes.

With and without:

![Screen Shot 2021-04-18 at 21 08 43](https://user-images.githubusercontent.com/5323259/115157677-d6867880-a08a-11eb-94e2-f100cfbda2a8.png)

![Screen Shot 2021-04-18 at 21 09 45](https://user-images.githubusercontent.com/5323259/115157679-d9816900-a08a-11eb-8be3-0849004ca589.png)

Other areas where there is a grey background is:
Add day event
Hide end time

Ahhh the grey is used as a clickable hover zone. Well it seems the grey areas should perhaps stay.

**Comment by joedolson** [comment]
Yes, I like to have visibility for the clickable area. I'm open to a design change, but it needs to retain the visible click regions.
