### ISSUE TITLE
My Calendar destroys the design (Is the theme sparkling the problem?)

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#424]
For me, MyCalendar has smashed the design.
I have archived this effect with screenshot:
https://1drv.ms/u/s!ApM3zNq3bOakiI0tj8sKkSFbAwddHQ?e=pbe38u

The error was accompanied with a system exit 400 bad request. An effect with all broser types Firefox, Crome, Opera, Edge.

After I uninstalled version 3.3.0 again, and work with 3.2.19 again, it looks like before:
https://www.klimabuendnis-hamm.de/info/kalender/

I suspect it is due to an incompatibility with the Sparkling theme.

I'm just wondering now which Pro version works well with version 3.2.19. Is it the old version 2.0.6 or better 2.1.2?
___
Translated from German with www.DeepL.com/Translator (free version)

**Comment by joedolson** [comment]
OK; I'm pretty confident that was a problem in 3.3.0 on sites that blocked remote access to images that I resolved in 3.3.1. Have you tried 3.3.1?

**Comment by UliMand** [comment]
We are cloning on a test server right now. I will test it there again and get back to you.

**Comment by joedolson** [comment]
That's great - thanks!

**Comment by UliMand** [comment]
A question in advance...
I am seeing some noticeable behavior starting with the update to 3.3.0 on 12/14/2021 at 10:14am:
We had an incredible amount of hits on the home page of our homepage on 12/14 and 12/15, and a lot of referrers from the wordpress dashboard to match.
Can this be related to the remote access to images?
With reset to the old version this behavior disappeared. (coincidence?)
See here: https://1drv.ms/u/s!ApM3zNq3bOakiI094bQy0ML7HMjX2Q?e=kGIlIx

**Comment by joedolson** [comment]
Yes, certainly possible. If your site is blocking remote access to images, it would instead pull up an alternate page (e.g., 404 page, home page, hard for me to know, depending on exactly what's happening), and so it would have done that roughly 1000 times.

**Comment by UliMand** [comment]
That's why also the smashed post editor? For example, different font style, incorrect field arrangements, code in MyCalendar form....  - In any case unusable and after call always with 400 Bad Request.
Or also missing scrollbars on the start page?
- Cause also remote access to images?

**Comment by joedolson** [comment]
Since I removed the remote calls to images in 3.3.1, I'm only really going to pursue issues you find with 3.3.1; let me know once you've got that installed. The remote accessing to images is completely gone already.

**Comment by joedolson** [comment]
Are there any continuing problems here? Please follow-up if there are continuing concerns! Otherwise, I'll be closing this issue.

**Comment by UliMand** [comment]
Hello,

Not pretty. A window of not even three days after announcing the closure 
of the issue. For a problem we are volunteering on the side to solve. 
Problem is still cloning the project.

-----
*Ulrich Mandel*
Redaktion Klimabündnis-Hamm.de

Am 02.01.2022 um 18:05 schrieb Joe Dolson:
>
> Closed #424 <https://github.com/joedolson/my-calendar/issues/424>.
>
> —
>
Am 30.12.2021 um 22:33 schrieb Joe Dolson:
>
> Are there any continuing problems here? Please follow-up if there are 
> continuing concerns! Otherwise, I'll be closing this issue.
>
Message ID: 
***@***.***>

**Comment by joedolson** [comment]
The issue can always be re-opened; but asking for basic information like confirming whether or not there is an issue and allowing three days is totally reasonable.

**Comment by UliMand** [comment]
Here the clone with MyCalendar 3.3.2 and Pro 2.1.3:
https://klimabuendnis-hamm.hpadm.de/info/kalender/

Looks better now than with version 3.3.0. - Some small things stand out:
1. in the directory "../wp-content/plugins/my-calendar/images/icons" we had our own icons. These are no longer visible. (Do we have to do without them?)
2. something has changed in the CSS (especially the navigation above the calendar). Compare here with the old version:
https://www.klimabuendnis-hamm.de/info/kalender/
Note the PDF document: https://1drv.ms/b/s!ApM3zNq3bOakiJcpJd8vfqFrlsNhRw?e=rphOKC
3. when entering new appointments, the field "Choose location:" is too small. The selection list after searching is too narrow.

Translated with www.DeepL.com/Translator (free version)

**Comment by joedolson** [comment]
- Custom icons should be placed in the directory /my-calendar-custom/, per the instructions on the Help screen. Placing your custom icons into the plug-in's own directory will cause them to be overwritten with every update. The original icons are still available; you can move them into the custom directory to use them. 
- Looks like your theme declares a small base font size; I'll have to look at that for the base styles. Practically, however, that probably needs to be customized for your site.  
- I'll look at the location search field.

**Comment by joedolson** [comment]
I can see you're using the My Calendar Pro responsive CSS; that's obsolete, as My Calendar Pro implements a different way of handling responsiveness in more recent versions. Have you tried switching to an alternate My Calendar stylesheet and disabling the responsive stylesheet? If you make sure you're using a recent & up to date My Calendar style, that may help with some of the styling issues.

**Comment by UliMand** [comment]
Thanks for the tips.
A lot of searching and trying for the layman.
- The new version is now running on the production system. 
- With the twentytwenty.css I did not have to adjust much.
- Adjustment CSS for the element "jump" is necessary. I haven't found the right CSS file yet. 
- Our icons are now in the plugins/my-calendar-custom/ directory.
- I still can not select them.

Look here: https://www.klimabuendnis-hamm.de/info/kalender/

**Comment by UliMand** [comment]
So now version 3.3.2 in use. Thanks for the support.

A new question: **What happens when I delete a category?**

My test:

1. I see in the category list 6 events without category.
2. I create an event with category "test" and save it.
3. I see the new category in the category list.
4. I delete this test category
5. event has no category now (default) 

==> So far, so correct.

BUT: In the category list I see (as before) 6 events.
So tried several times. Page cache is empty.
Is a refresh (or reindexing) of the category list possible?

___
Translated with www.DeepL.com/Translator (free version)

**Comment by joedolson** [comment]
At the moment, it looks like your category icons are disabled; so I'm going to assume that's intentional. 

I'm not sure I fully understand your questions about categories: 

"I see in the category list 6 events without category."

What list is this? I'm not following. I don't understand how you would see events without a category when viewing the category list. The category list shows the categories; it shows the number of events in that category, but I can't see a way it would ever show events that aren't associated with a category. 

If you can possibly provide some screenshots, maybe I'd follow what you're referring to.

**Comment by UliMand** [comment]
![grafik](https://user-images.githubusercontent.com/96249763/148618091-40be4492-312a-48d8-968b-fd1dd2926f6e.png)

**Comment by joedolson** [comment]
That looks like an inaccurate translation, to me - the english for that is "Untitled Category"; "without category" would be somewhat different. That simply means that those are events in a category that does not have a title.

**Comment by UliMand** [comment]
Sorry. I don't know the subtleties of the translation.
I rephrase the question:

- I had 6 events with categories WITHOUT title.
- The category with title "test" showed 1 event.
- I deleted this category with title "test".
- Now I should have 7 events with categories WITHOUT title.
- But I still have 6 in my list.
- Why has the number not increased to 7?

**Comment by joedolson** [comment]
Ah - I understand the question now. Will look.

**Comment by joedolson** [comment]
Got it; that's a bug, and I'll address it.

**Comment by joedolson** [comment]
Also identified the reason custom icons weren't showing up.

**Comment by UliMand** [comment]
Thank you! I just installed the version 3.3.3. It works now. When I delete a category, the related events are assigned to the category without title.
![grafik](https://user-images.githubusercontent.com/96249763/148626897-bf043286-d1fe-472a-9191-6a564dcc1e85.png)
![grafik](https://user-images.githubusercontent.com/96249763/148626908-38c500d6-2bad-4738-ab5b-6ac09591b619.png)

Still my numbers are not correct. My error description with 6+1=6 was just an example to explain the problem. 

In reality I deleted a category that had much more events. I see in the list of events 184 records with the category without title.
But the list of categories shows me only 9 events in the category without title.

The numbers need a refresh. They need to be recalculated. I am missing a button for this.

**Comment by UliMand** [comment]
A manual update of 175 events would fix the problem. I have successfully tested this with one event. Not a nice task. Can I please get a refresh button for this?

**Comment by joedolson** [comment]
So, I'm clear, the problem events are the result of a category you deleted *prior* to my making this fix, correct?

**Comment by UliMand** [comment]
No, I have already deleted the 175 uncounted events before the update to 3.3.3.

In order not to complicate my example unnecessarily, I have only written about one test event. But even this one test event did not increase the number of categories without titles. 

To test version 3.3.3, I created another test event and then deleted it. Only this one increased the number behind the categories without title.

So no recalculations are made for deletions **BEFORE** the update.

I hope I have expressed myself understandably.

Translated with www.DeepL.com/Translator (free version)

**Comment by joedolson** [comment]
Yes, that's what I was asking. I'll have to think about what the options are. It's non-trivial.

**Comment by UliMand** [comment]
I believe that. As as amends, I have already translated a lot and will continue to do so. ;)

**Comment by joedolson** [comment]
Thank you!

**Comment by joedolson** [comment]
I think this is basically resolved. There is a fix for the recalculations, although it's not a routine, per se; they're just recalculated on the fly when the admin events list is displayed.

**Comment by UliMand** [comment]
On January 9th I wrote:

> ... As as amends, I have already translated a lot and will continue to do so. ;)

The german translation of the last stable version is now complete. 
I hope the work was worth it and my translation will be released.

**Comment by joedolson** [comment]
I hope so, too. I dearly wish I had any control over getting those published.
