### ISSUE TITLE
No '+' symbol in time zone description of StartDate and endDate.

### ISSUE THREAD

**Issue by kitahiro** [joedolson/my-calendar#425]
Description of StartDate and endDate is in the event of My-Calendar of my site is
"startDate":"2022-01-09T17:00:0009:00","endDate":"2022-01-09T21:00:0009:00".

Isn't below right description according to ISO 8601?

"startDate":"2022-01-09T17:00:00+09:00","endDate":"2022-01-09T21:00:00+09:00"

It's unclear whether this is the cause, but you point out the error which has no timezone in "StartDate" by Google Site kit.

**Comment by joedolson** [comment]
Thanks - it looks like I'm returning the value before applying the symbols, so they don't end up in JSON_LD data.

**Comment by kitahiro** [comment]
There is a problem with my comment in the JSON_LD clearly.
When I do the following correction on probation, a problem has disappeared.
But I recognize that this is wrong correction.

before correction
  'startDate'   => $event['dtstart'] . $wp_time,
  'endDate'     => $event['dtend'] . $wp_time,

after correction
  'startDate'   => $event['dtstart'] . '+' . $wp_time,
  'endDate'     => $event['dtend'] . '+' . $wp_time,
