### ISSUE TITLE
Excessive quotes on the list view around the title

### ISSUE THREAD

**Issue by iedwebmaster** [joedolson/my-calendar#426]
![image](https://user-images.githubusercontent.com/97110902/148081000-60c4a80f-aed4-45a4-ab15-59372837ec3c.png)

**Comment by joedolson** [comment]
Can you share a link?

**Comment by iedwebmaster** [comment]
Yes, I am using Beaver Builder and the shortcut generator from MyCalendar. You may have to scroll down a little.

https://txsbdc.org/businessrecovery/trainings/

From: Joe Dolson ***@***.***>
Sent: Wednesday, January 5, 2022 12:59 PM
To: joedolson/my-calendar ***@***.***>
Cc: IED Webmasters ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [joedolson/my-calendar] Excessive quotes on the list view around the title (Issue #426)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Can you share a link?

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoedolson%2Fmy-calendar%2Fissues%2F426%23issuecomment-1005995209&data=04%7C01%7CMaria.Kelley%40utsa.edu%7Cc1b5562594384249f75c08d9d07d77e1%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770059579923180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=uLpdg85GOnQDjcYq%2FHslrRx%2BNIBV8voe0YO4lmrgZG8%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXE4W5QQPFUHQL5MIMLFNG3UUSIIFANCNFSM5LHWHFIA&data=04%7C01%7CMaria.Kelley%40utsa.edu%7Cc1b5562594384249f75c08d9d07d77e1%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770059579923180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=n%2BAWRC%2F4xpFETxt4%2B7JxslmVqvggmURbj1czXBbUp3Y%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMaria.Kelley%40utsa.edu%7Cc1b5562594384249f75c08d9d07d77e1%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770059579923180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1Wvhd5ZLlFcAP5Zueyl1twwt8qLhrhqgMn1fi7V8H1s%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMaria.Kelley%40utsa.edu%7Cc1b5562594384249f75c08d9d07d77e1%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770059579923180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3PW7D7UIp8MN7E9mR8O8fX7kq0wCp8dWC%2FgCtlKmEQc%3D&reserved=0>.

**Comment by joedolson** [comment]
OK. I took a look at your site, and it's definitely using a custom template for upcoming events. I'll need to see the code for the template to make any comments; if you can provide that, please do.

**Comment by iedwebmaster** [comment]
Here is the template code.......for Upcoming (Previous version I was able to change the font size and color. I am not able to do that in the new version)


<table style="width:100%">
<tr>
    <td><span style="font-family: helvetica, arial, sans-serif;font-size: 24px;color: #002244">{daterange}</span></td>
<td><span style="font-family: helvetica, arial, sans-serif;font-size: 24px;color: #ffffff"><strong>"
  "</strong></span></td>
    <td><span style="font-family: helvetica, arial, sans-serif;font-size: 16px;color: #1e1855"><strong> {linking_title}</strong></span> </td>
<td><span style="font-family: helvetica, arial, sans-serif;font-size: 16px;color: #ffffff"><strong>"
  "</strong></span></td>
<td><span style="font-family: helvetica, arial, sans-serif;font-size: 16px;color: #1e1855">{timerange }</span></td>
  </td>
</table>

Here is the Today's event ( it does it too)

<table style="width:100%">
<tr>
    <td><span style="font-family: helvetica, arial, sans-serif;font-size: 16px;color: #1e1855">{daterange}</span></td>
<td><span style="font-family: helvetica, arial, sans-serif;font-size: 16px;color: #ffffff"><strong>"
  "</strong></span></td>
    <td><span style="font-family: helvetica, arial, sans-serif;font-size: 16px;color: #1e1855"><strong> {linking_title}</strong></span> </td>
<td><span style="font-family: helvetica, arial, sans-serif;font-size: 16px;color: #ffffff"><strong>"
  "</strong></span></td>
<td><span style="font-family: helvetica, arial, sans-serif;font-size: 16px;color: #1e1855">{timerange }</span></td>
  </td>
</table>

From: Joe Dolson ***@***.***>
Sent: Wednesday, January 5, 2022 3:34 PM
To: joedolson/my-calendar ***@***.***>
Cc: IED Webmasters ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [joedolson/my-calendar] Excessive quotes on the list view around the title (Issue #426)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



OK. I took a look at your site, and it's definitely using a custom template for upcoming events. I'll need to see the code for the template to make any comments; if you can provide that, please do.

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoedolson%2Fmy-calendar%2Fissues%2F426%23issuecomment-1006095002&data=04%7C01%7CMaria.Kelley%40utsa.edu%7Cba4ec7b02ffa4628343608d9d093125c%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770152365297142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=teOcG3f2%2BV4VoBaPN3oyAM9TUe8V0qet8YzUZ7hL02c%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXE4W5SPGHH57ADGKHVS4GDUUS2L7ANCNFSM5LHWHFIA&data=04%7C01%7CMaria.Kelley%40utsa.edu%7Cba4ec7b02ffa4628343608d9d093125c%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770152365297142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oopDjuxqAPcT5jZAaCThNGsPSo8RuGBdikYU8lI%2FiOQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMaria.Kelley%40utsa.edu%7Cba4ec7b02ffa4628343608d9d093125c%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770152365297142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=49ceX7qDJSnvXa2fEyo8eG0hnkAKRGUF143qZzzBXi8%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMaria.Kelley%40utsa.edu%7Cba4ec7b02ffa4628343608d9d093125c%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770152365297142%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QA9puVEp%2FofBjnmM%2FY83fh72Ja1kh8Q6QF2V8tyX7oU%3D&reserved=0>.

**Comment by joedolson** [comment]
OK - got it. The 'style' attribute is not allowed in templates anymore; I strongly recommend using classes, e.g.

`<span class="upcoming-events-date">{daterange}</span>`

Then you'd specify your styles in your stylesheet.

**Comment by iedwebmaster** [comment]
Good Morning, How is the quote issues coming on the title?

From: Joe Dolson ***@***.***>
Sent: Wednesday, January 5, 2022 6:06 PM
To: joedolson/my-calendar ***@***.***>
Cc: IED Webmasters ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [joedolson/my-calendar] Excessive quotes on the list view around the title (Issue #426)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



OK - got it. The 'style' attribute is not allowed in templates anymore; I strongly recommend using classes, e.g.

<span class="upcoming-events-date">{daterange}</span>

Then you'd specify your styles in your stylesheet.

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoedolson%2Fmy-calendar%2Fissues%2F426%23issuecomment-1006175174&data=04%7C01%7CMaria.Kelley%40utsa.edu%7C5ff1a47d2fba4599946908d9d0a853b7%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770243668159279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=B3BVQImliUvoX9dxPefHCWo608i%2Bz4mOlNriF1vqBN0%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXE4W5X56TAOFHSQJ6HNUJDUUTMGTANCNFSM5LHWHFIA&data=04%7C01%7CMaria.Kelley%40utsa.edu%7C5ff1a47d2fba4599946908d9d0a853b7%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770243668159279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OaiEboOKz1BTwZ69FQgpyXHPw%2FSBD99RH1UD7ku%2BeVw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMaria.Kelley%40utsa.edu%7C5ff1a47d2fba4599946908d9d0a853b7%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770243668159279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zTIebyFVnduZZKpyPwHj%2Bp62N9LOd7pdNwd5tP%2FcRx4%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMaria.Kelley%40utsa.edu%7C5ff1a47d2fba4599946908d9d0a853b7%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770243668159279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QxGRE6Ff6eQCy8l27BIdN%2BY3BdWaW3nq7Jj7liZxMko%3D&reserved=0>.

**Comment by iedwebmaster** [comment]
I regenerated the shortcode and it looks better! Thanks for your time.

From: Maria Kelley
Sent: Wednesday, January 12, 2022 9:10 AM
To: joedolson/my-calendar ***@***.***>; joedolson/my-calendar ***@***.***>
Cc: IED Webmasters ***@***.***>; Author ***@***.***>
Subject: RE: [EXTERNAL] Re: [joedolson/my-calendar] Excessive quotes on the list view around the title (Issue #426)

Good Morning, How is the quote issues coming on the title?

From: Joe Dolson ***@***.******@***.***>>
Sent: Wednesday, January 5, 2022 6:06 PM
To: joedolson/my-calendar ***@***.******@***.***>>
Cc: IED Webmasters ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [EXTERNAL] Re: [joedolson/my-calendar] Excessive quotes on the list view around the title (Issue #426)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



OK - got it. The 'style' attribute is not allowed in templates anymore; I strongly recommend using classes, e.g.

<span class="upcoming-events-date">{daterange}</span>

Then you'd specify your styles in your stylesheet.

-
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjoedolson%2Fmy-calendar%2Fissues%2F426%23issuecomment-1006175174&data=04%7C01%7CMaria.Kelley%40utsa.edu%7C5ff1a47d2fba4599946908d9d0a853b7%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770243668159279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=B3BVQImliUvoX9dxPefHCWo608i%2Bz4mOlNriF1vqBN0%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXE4W5X56TAOFHSQJ6HNUJDUUTMGTANCNFSM5LHWHFIA&data=04%7C01%7CMaria.Kelley%40utsa.edu%7C5ff1a47d2fba4599946908d9d0a853b7%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770243668159279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OaiEboOKz1BTwZ69FQgpyXHPw%2FSBD99RH1UD7ku%2BeVw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMaria.Kelley%40utsa.edu%7C5ff1a47d2fba4599946908d9d0a853b7%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770243668159279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=zTIebyFVnduZZKpyPwHj%2Bp62N9LOd7pdNwd5tP%2FcRx4%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMaria.Kelley%40utsa.edu%7C5ff1a47d2fba4599946908d9d0a853b7%7C3a228dfbc64744cb88357b20617fc906%7C0%7C0%7C637770243668159279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QxGRE6Ff6eQCy8l27BIdN%2BY3BdWaW3nq7Jj7liZxMko%3D&reserved=0>.

**Comment by joedolson** [comment]
Glad to hear it!
