### ISSUE TITLE
Custom Templates Editor (cut and paste Bug?)

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#427]
### after paste:
![grafik](https://user-images.githubusercontent.com/96249763/148686613-bb275f8e-c493-42c1-940d-a6fc5943c462.png)

### after update:
![grafik](https://user-images.githubusercontent.com/96249763/148686608-0522583a-0984-449b-81d6-2b8e45b3464b.png)

**Comment by joedolson** [comment]
This is a bug; doesn't relate to cut and paste, but I'll get on it.

**Comment by UliMand** [comment]
Not new. I didn't want to believe it, but it happened again today: I have to set these fields and "Read more text" and "More Information text" again and again, because at some point they are empty again. 

Is there a connection to the bug described above?
## before:
![grafik](https://user-images.githubusercontent.com/96249763/149170994-346ffd2d-8233-463c-a592-417f65959133.png)
## sometime later:
![grafik](https://user-images.githubusercontent.com/96249763/149170757-ca63ef04-27c6-4c60-bf8d-ea445c9e4d26.png)

**Comment by joedolson** [comment]
This is the same issue, and is also fixed with the change made above.
