### ISSUE TITLE
Bug: Button incorrectly german-labeled

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#428]
## The buttons in the custom template editor:
![grafik](https://user-images.githubusercontent.com/96249763/148688851-0a9f879c-4137-4d66-a163-66c2e73e41c9.png)
In Englisch it would mean: "Update Template" | "Template"
Better german: `"Aktualisieren"` | `"Abbrechen und löschen"`

### resp.

![grafik](https://user-images.githubusercontent.com/96249763/148688792-95d4507c-40b4-4063-8638-1627e36cad8b.png)
Better german: `("Vorlage hinzufügen")` | `("Abbrechen")`

**Comment by UliMand** [comment]
The button `"cancel"` by Update not only cancels, it also deletes!

**Comment by joedolson** [comment]
All translations are handled at WordPress.org; I don't have access to or control over any of the translations. You can get involved in translations here: https://translate.wordpress.org/projects/wp-plugins/my-calendar/

**Comment by UliMand** [comment]
### The translator does not help here.

The HTML code is incorrect. As a result, the button is too short. The HTML code is:
`<input type="submit" name="delete" class="button-secondary" value="Vorlage" löschen"="">`

The syntax is incorrect. The correct code:
`<input type="submit" name="delete" class="button-secondary" value="Vorlage löschen">`

It will look correctly like this:
![grafik](https://user-images.githubusercontent.com/96249763/148696475-08fc4447-61ec-40e1-9439-9111128a30c7.png)

**Comment by joedolson** [comment]
OK. If I'm looking at the right place, there's a missing quote; but I can't tell for sure if I'm looking at the right spot.

**Comment by joedolson** [comment]
Hi, @UliMand!

I've touched base with Torsten Landsiedel, one of the Wordpress German editors, and he's reviewing your translations at WordPress.org; he's got some questions for, and wonders if you could join the German Slack community for WordPress so he could chat with you about them?

https://de.wordpress.org/slack/

Thanks!

**Comment by UliMand** [comment]
That's good. I'll sign up there right away. Thanks for the tip.
