### ISSUE TITLE
Bug: Translator not available

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#429]
## Is this an error or am I blocked there?
![grafik](https://user-images.githubusercontent.com/96249763/148689498-bf065a56-7a55-4816-bfe7-70f463e3fa8c.png)

**Comment by joedolson** [comment]
Can you tell me where you found that link? That's been out of use for years; but it's hard to find and get rid of all the links to it, so I could have missed one.

Translations are managed here: https://translate.wordpress.org/projects/wp-plugins/my-calendar/

**Comment by UliMand** [comment]
![grafik](https://user-images.githubusercontent.com/96249763/148690908-78ff767d-5313-4f3f-aca6-bbea1dd0a54e.png)

**Comment by joedolson** [comment]
Wow, can't believe I missed that one. And it's been at least five years...thanks!
