### ISSUE TITLE
Not able to preview a draft event...

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#43]
I made an event and saved it as a draft.
Then tried to Preview it.

1. Draft event.

![Screen Shot 2021-04-18 at 21 16 26](https://user-images.githubusercontent.com/5323259/115157781-5e6c8280-a08b-11eb-8d87-4f15a05d0411.png)

2. Previewing the event. Frontend.
![Screen Shot 2021-04-18 at 21 16 59](https://user-images.githubusercontent.com/5323259/115157790-717f5280-a08b-11eb-8421-47ded1e8f547.png)

This is a test site using Twenty Twenty One. WP 5.7.1. Only the My Calendar plugin active.
OSX 10.15.7
Chrome

**Comment by paaljoachim** [comment]
I also tried previewing from the Manage Events page.
Saw the same thing as I did above. Could not find event.

Then I published it. It could still not find the event.

**Comment by joedolson** [comment]
The 'preview' parameter is missing from the URL you shared; is that also missing from the link in the event manager?

The 404 error, however, looks like unrefreshed permalinks since installing My Calendar.

**Comment by paaljoachim** [comment]
> The 'preview' parameter is missing from the URL you shared; is that also missing from the link in the event manager?

That might be.

I went to Settings -> Permalinks and resaved them. The event can now be previewed on the frontend.

**Comment by joedolson** [comment]
Todo: need to work on ensuring that the permalink structure is reliably refreshed when activating the plug-in. This has been a problem in the past, and using this feature as a default depends on it.

**Comment by paaljoachim** [comment]
Retesting. Using WP 5.8.
Twenty Twenty One.
I have Autoptimize and My Calendar plugins activated.

Made a new event.
Went to Events page (All events) hovered the event and in the quick edit selected Preview.
I was able to see a preview of the event.

-------

I blanked out the database and started anew.
Made a draft event and was able to preview it.
It looks like it is working nicely.
