### ISSUE TITLE
Am I not allowed to change the core templates?

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#430]
Because Customer templates have a bug, I edit the core templates for grid and list. This is released. The update button is active.

I can adjust a lot and test for a long time. In the process I get closer to the goal and am happy.

Eventually my settings are gone and I see the default code you supplied again. I have tested this several times. Always with the same result.

**Comment by joedolson** [comment]
Do you mean that you edit the core template numerous times, and it saves normally, and then at some random point later it resets to the original? That's how I understand what you're saying, but I want to be clear on that.

**Comment by UliMand** [comment]
Yes, you got that right.

**Comment by UliMand** [comment]
The error happens after I touch the mini template.

**Comment by joedolson** [comment]
Does it a) only happen after editing the mini template and b) *always* happen after editing the mini template?

**Comment by UliMand** [comment]
One moment please, I will test this.

**Comment by UliMand** [comment]
### My test run:

- grid changed and saved. 
- Refresh of the browser page with grid - okay.
- grid changed again and saved.
- Refresh browser page with grid - okay
- This until test no. 5

Change to template list. ( (no change made there yet))

- Refresh browser page with grid ==> grid is still okay
- list changed and saved. 
- Back to grid
- Refresh of the browser page with grid **==> grid is standard again! <== Bug!**

I can test this as I like, also with change to template mini

![grafik](https://user-images.githubusercontent.com/96249763/148704667-07efb522-53c1-4a69-ba9b-8d58a6121703.png)

**Comment by UliMand** [comment]
### Conclusion: 
I can change and test a template as often as I want.
As soon as I change to the other template, the other one is set back to default.

**Comment by joedolson** [comment]
Hmm. That's really weird; I'll explore it.

**Comment by UliMand** [comment]
Also important:
The same happens exactly in the clone installation in a completely different system environment (different server, different provider)

Clone: https://klimabuendnis-hamm.hpadm.de/info/kalender/
Productive: https://klimabuendnis-hamm.de/kalender/
