### ISSUE TITLE
Template mini: Farbiger Balken mit Titel nicht günstig

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#431]
Where is the code for the colored bar with the title in the core template mini? 

I don't need it like this; would like to edit it or delete it.
- But where to find it?
![grafik](https://user-images.githubusercontent.com/96249763/148702535-acb0bf11-4aad-4c5f-b1b3-1476996fb995.png)

**Comment by joedolson** [comment]
My Calendar > Categories > Category colors > "title background color"

As a note, it looks like your theme is overriding the My Calendar setting for the heading text color, which would have made that much easier to read...
