### ISSUE TITLE
Incorrect assignment of category icons

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#432]
I choose
![grafik](https://user-images.githubusercontent.com/96249763/149384661-fdfbc19e-9cfd-4c6a-836c-3a07c5375f4a.png)

I see after saving
![grafik](https://user-images.githubusercontent.com/96249763/149384683-3ff652a6-0146-4bfa-886a-97f297e9507d.png)

I choose
![grafik](https://user-images.githubusercontent.com/96249763/149385272-41b0d29a-cf2d-469b-b450-d5ca21de33cb.png)

I see after saving
![grafik](https://user-images.githubusercontent.com/96249763/149385295-15dd5c60-6934-4d47-a2ca-8135d8ec4cb8.png)

**Comment by joedolson** [comment]
If you have custom icons, you should only be able to query the custom icons, and not see the default icons in your searches; I'm not sure why you're seeing those, or why you're getting something else. I'll explore; might have additional questions.

**Comment by UliMand** [comment]
**I only see these icons in the pulldown behind the help icon (question mark) and get the file names with cut and paste:**
 ![grafik](https://user-images.githubusercontent.com/96249763/149409794-671f04cb-4f32-494a-8f34-575731c9b5fc.png)

**Comment by joedolson** [comment]
If you're using custom icons, then you only have custom icons; you can see
the list at the bottom of the category screen, showing you all your custom
icons. You can always move other icons into your custom icon directory, but
it's one or the other.

**Comment by UliMand** [comment]
Okay. Now I understand. If I know it, it's not a problem. Thank you.

The help button should point that out. The text link "Documentation" 
`https://docs.joedolson.com/my-calendar/?s=Kategorie%20Icon `
in it points to a page with title "Nothing Found".

**Comment by joedolson** [comment]
Hmm. Yes, the links point to search queries, so those queries need to not be translated (since the docs site is only in English.) I'll need to check over those!
