### ISSUE TITLE
Add support for JPG & GIF icons

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#433]
## first Attempt
![grafik](https://user-images.githubusercontent.com/96249763/149388877-e5c977e7-a753-4ed1-85b1-3d3368cc1480.png)

## second Attempt
![grafik](https://user-images.githubusercontent.com/96249763/149388768-7ee97d21-2cd6-4999-b92b-f2c5ffa2c11e.png)

**Comment by joedolson** [comment]
Hmm. Icons currently only support PNG and SVG; looks like you have some JPGs? I should probably add support for those, but currently it's just PNG and SVG.

**Comment by UliMand** [comment]
Oops! There was a single jpg-image with it. This problem is fixed. Thank you.

**Comment by joedolson** [comment]
I'm leaving this open, because it is reasonable to support jpg and gig.
