### ISSUE TITLE
Shortcode generator submissions: Location Fields only visible if Location Fields is desired in the form

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#439]
The 'Enable Location Fields' should only be visible if I have selected something suitable in the 'Enable Location Options'.

This would fix one problem:
If I overlook to set the Location Options, my settings in the Location Fields will be lost.

**Comment by joedolson** [comment]
Thanks, @UliMand! As this is a My Calendar Pro issue, I'd appreciate it if you added it here: https://github.com/joedolson/my-calendar-pro/issues
