### ISSUE TITLE
Went to My Calendar page to view the frontend calendar

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#44]
I went to the My Calendar page to view the frontend calendar.

This is what I saw:

![Screen Shot 2021-04-18 at 21 22 39](https://user-images.githubusercontent.com/5323259/115157983-3f222500-a08c-11eb-9d50-cc9bd199d474.png)

I wondered if a fly had landed on the screen. For it kinda looks like a smudge mark on the 2021 year to the left of the Go button.

I assume that I can place the backend Classic block into a Group block to make it wider.
Like so:

![Screen Shot 2021-04-18 at 21 25 12](https://user-images.githubusercontent.com/5323259/115158049-97592700-a08c-11eb-8a53-b2f27d9a1785.png)

Checking the frontend the calendar has the same width. 
I also assume that I can add a background color to the calendar somewhere in the settings page.

It would be nice with different styles for the calendar. I can experiment with that.

**Comment by joedolson** [comment]
All design for the calendar, at this time, is via CSS editing. I haven't implemented any design tools at all, and - honestly - that's not something I'm sure I want to do, at all. 

That looks like a theme issue of some sort...

**Comment by paaljoachim** [comment]
So I am thinking here that I could actually create some designs for the calendar. I can later on add an issue for it. Then some of the designs could go into the documentation.

I do think we need a kind of quick start documentation that people can begin with. Then they can browse the "book" to get more in depth information.

**Comment by joedolson** [comment]
There are several different designs available for the calendar, selectable from the style page. Some of them are quite old, and look it, but I'm definitely open to additional designs being available.

**Comment by joedolson** [comment]
I think this is pretty much covered by other tickets; closing.
