### ISSUE TITLE
Creating a duplicate location on event editing.

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#441]
Reported from support request:

"I've created a location and set it as default. Then created a new event and the default location is set, event is published. Afterwards I edit the event and remove the location, set it to "--". Click again on publish and the default location is duplicated."

Sounds like removing the location isn't setting the location values to empty and the checkbox for adding the location to the database is remaining checked.

**Comment by paaljoachim** [comment]
Testing with
WP 5.9.
Twenty Twenty Two
Gutenberg plugin 12.5.4

Published an event. Linked to a location.
Went to location and made it into a default location.
Went back to event and changed from default location to "--"
Went to Locations and noticed the default location now has a duplicate location.

I believe this now closed issue is associated:
Locations: Clicking "Set as Default" the location is seen twice. - bug -
https://github.com/joedolson/my-calendar/issues/387

**Comment by joedolson** [comment]
#387 is unrelated.

**Comment by joedolson** [comment]
This should be fixed.

**Comment by paaljoachim** [comment]
I assume I need to delete the duplicates? As I am seeing this also after updating to 3.3.8.

![Screenshot 2022-02-16 at 14 55 48](https://user-images.githubusercontent.com/5323259/154281473-6bbaf6a1-a235-43f5-a63d-8a8673d3b9a2.jpg)

**Comment by joedolson** [comment]
In https://github.com/joedolson/my-calendar/commit/8f6bebb730c91d6e17391a955c3317c30057105b#diff-25978ecc98b4521340e67f00c5da6aec4f7d47547de340bc9930553d02dceda4, added mechanism for merging duplicated locations.

**Comment by paaljoachim** [comment]
Good idea!

**Comment by UliMand** [comment]
Actually happened to me 🙄: If by mistake the location that should be the only one left is in the selection, this location is also deleted. 

Example: ID 1 and 7 are selected. ID 1 should be left. 

Solution: ID 1 must be automatically excluded during deletion.

**Comment by joedolson** [comment]
Can you open this as a new issue, @UliMand?

**Comment by UliMand** [comment]
Okay. See here:
https://github.com/joedolson/my-calendar/issues/462#issue-1163786756
