### ISSUE TITLE
Twenty Twenty Two theme: does not prepend text to single title event

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#442]
**Describe the bug**
As I am going through the docs again I did some additional testing.
This time with the theme Twenty Twenty Two. 

Text Settings.
Event title (Grid) {time} Event Title: {title} ---> Is seen in the My Calendar grid.
Event title (Single) Event Single title: {title} ---> Is not seen in Single event screen with the theme Twenty Twenty Two.
Event title (List) Event List Title: {title} ---> Is seen in the My Calendar list.

**To Reproduce**
1. Activate Twenty Twenty Two.
2. Go to Settings -> General -> Text and add some text to the Event title (Single) field.
3. See if it shows up on the frontend in Single event views. 

**Expected behavior**
I expected the adjustment to be seen in single event views.

**Desktop (please complete the following information):**
OSX
Firefox
WP 5.9

**Comment by joedolson** [comment]
I assume that because Twenty Twenty Two is a block-based theme that the title is handled differently. Low priority for now.

**Comment by paaljoachim** [comment]
Twenty Twenty Two.
WordPress 6.1.1
Newest Github My Calendar version.

ehh hmm... not sure what to say here. 

I went to Settings -> Display.
Added text into Event title for Grid, List and Single. Like so.

![Screenshot 2023-01-04 at 23 29 37](https://user-images.githubusercontent.com/5323259/210662253-8b461a0b-f54e-4709-800a-0c1d65c856be.jpg)

Made an event. It looked a bit weird on the frontend, so I checked the default event. Demo: Florence Price:.....

Frontend single view.
![Screenshot 2023-01-04 at 23 33 14](https://user-images.githubusercontent.com/5323259/210662777-41c1325a-bfca-4f42-99c9-a97c77c3c99c.jpg)

As this can be a CSS error based on the error seen in the console:
`GET https://bluewinddesign.com/wp-content/plugins/my%20calendar/styles/?ver=3.4.0- net::ERR_ABORTED 403`

Went to Design and clicked Migrate CSS now.
That failed: "CSS migration failed. You may need to migrate your file via FTP."

I then clicked "Keep My Calendar's styles" button.
I received the message: "Thank you! Your site will be updated to the latest version of core CSS at every update."

Viewed the demo event single on the frontend and it looked the same as last time.

**Comment by joedolson** [comment]
You don't have a stylesheet selected.

**Comment by paaljoachim** [comment]
I have not had that problem before.
I was sure that latest default stylesheet was selected.

I noticed the twentyeighteen.css was selected and have now switched it over to twentytwentytwo.css.

Look what I noticed when scrolling to the bottom to save the new stylesheet.
![Screenshot 2023-01-04 at 23 44 14](https://user-images.githubusercontent.com/5323259/210664033-bf149b02-4339-4029-b024-507902969026.jpg)

**Comment by joedolson** [comment]
Please open a different issue; this is not the issue "Twenty Twenty Two theme: does not prepend text to single title event", regardless of other issues.

**Comment by joedolson** [comment]
Alternate fix committed in https://github.com/joedolson/my-calendar/commit/efd256d52803892b6e6028da4b4c0d716a4c186f

This fix checks whether the active post ID is the current singular post, and only replaces titles if it is. Seems to work.
