### ISSUE TITLE
Text settings: Week view caption: - Available tag.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#443]
Going to Text settings -> Text.
Main Calendar View
Tag {date} is seen with Previous events links, Next events link, Calendar month heading, 
but Week view caption uses {date format=""}. 
Should this be changed to {date} as these other options?

I assume that date format might hold additional values which date alone can not hold.
Making that the reason for the different date format for Week view caption.

Example. Something similar to:
https://www.w3schools.com/sql/func_mysql_date_format.asp

I believe it would be helpful if I add in various date format suggestions.

Right now I see I have the wrong information here:
Week view caption. https://docs.joedolson.com/my-calendar/my-calendar-text-settings/

**Comment by joedolson** [comment]
The week view supports custom formatting, the other views don't. I've added a placeholder showing the default for week view, which should help clarify this.
