### ISSUE TITLE
These are one multi-day event. Information.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#445]
The "These are one multi-day event." information.

![Screenshot 2022-02-14 at 13 15 40](https://user-images.githubusercontent.com/5323259/153862705-9ba9ccd6-518d-4ec7-a490-da220670f131.jpg)

I am missing a ? beside the multi-day event text to where I can get some more information on what that actually means.

**Comment by joedolson** [comment]
This should have been part of the help link on 'Add Copy', but that text was missing. Fixed.
