### ISSUE TITLE
Removing the "All day" event label from events screen brings it back on save/update.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#449]
I made a multi day event that went across 4 days. The first evening started at 19.00 and the last day ended at 16.00. 
I initially added the time but it showed up in the title of the event.
So I went back and edited for it to become All day events.

I went removed the All day label, as I did not and to have it added to the title.
Upon saving/updating the event the all day label was automatically added back in again.

**Removing the "All day" label and updating. The "All day" label should not come back.**

A work around:
Going to Settings -> Text and removing the label for all-day events: "All day" to blank.
This removed the label from the events.

![Screenshot 2022-02-14 at 14 07 12](https://user-images.githubusercontent.com/5323259/153869960-004b626e-5418-4df4-ab41-9488685b284e.jpg)

**Comment by joedolson** [comment]
This is probably because setting the value to blank triggered a fallback to the default. Removing the default resolved that. 

Tricky to fix that, since it's hard to distinguish between "All day text is not configured" and "All day text has been configured, and is empty". Arguably, what you've done is the most reasonable solution for your use case.

**Comment by paaljoachim** [comment]
Could/should there be a Hide "Time label" checkbox?

![Screenshot 2022-02-14 at 17 51 27](https://user-images.githubusercontent.com/5323259/153908903-9c243b11-e1d7-4740-9332-169f79200750.jpg)

**Comment by joedolson** [comment]
I'll consider it if I can't find a way to fix this. I'd prefer to fix without adding an additional option.

**Comment by UliMand** [comment]
I have also come across this and would like an option to hide it. I now choose the "~" character when I don't want a word for "all day".
