### ISSUE TITLE
Removing unneeded settings.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#45]
It would be helpful to go through Settings and see which options are not needed any longer, and perhaps add a note about it in this thread. So these can be looked at when there is time to do so.

Example:
Remove Use Pretty Permalinks for Events.

**Comment by joedolson** [comment]
Closing this. From a practical standpoint, we've been steadily collapsing options as necessary and haven't been updating this...so it's probably not necessary to keep it open.
