### ISSUE TITLE
An option to open (external) links in a new tab.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#450]
Clicking an event in the calendar opens the List view:

Here is the bottom portion.
![Screenshot 2022-02-14 at 14 13 37](https://user-images.githubusercontent.com/5323259/153871032-61c676a7-6757-443f-976a-16eddaa3dc1c.jpg)

If the user clicks the "More information" or "Buy tickets" they will be taken to these links.
What I miss is having a way to decide which links need to open in a new tab. In this case the "More information" links to an external site so they can easily lose where they came from.

**Comment by joedolson** [comment]
This is a won't fix. I will not add an option to open links in a new tab. If a user knows how to do that on their own, that's up to them, but there are significant accessibility issues around links that open in new tabs.
