### ISSUE TITLE
Choosing No Location option.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#453]
Adding a lot of events and a link to the external event location I might not want to add the address of the location of the event and instead choose -- as in no location selected.

Perhaps instead of selecting -- there could be an option to use "no location" or "blank location". Sometimes there might be digital events where there is no physical location in use.

Btw just ignore all the Dharma Mountain locations. There is a bug present.
![No-Location](https://user-images.githubusercontent.com/5323259/153886274-d76e0b3d-2d27-497f-8f5f-5281e215af6b.jpg)

**Comment by joedolson** [comment]
I think that what you're saying is "replace '--' with 'No location'" - is that right?

**Comment by paaljoachim** [comment]
Yes. That would be better then --

**Comment by paaljoachim** [comment]
Added to 3.3.8.
It works!
![Screenshot 2022-02-16 at 14 55 48](https://user-images.githubusercontent.com/5323259/154279221-8772bef2-f7e5-490c-a554-164bee5abf1c.jpg)

I still have multiple locations in the list. I assume I will need to delete all the duplicate locations that are made.

**Comment by joedolson** [comment]
Yes. I can't delete data from user's sites without very good reason...
