### ISSUE TITLE
Adding Tags to further classify events?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#454]
At the moment we can classify events into categories.
I am wondering if we should add tags as another way to give even more detail to how something is classified.

Let's say that I have the general category of Permaculture.
I might add tags for locations. So category Permaculture. Tag: Dharma Mountain. To get all permaculture events associated with Dharma Mountain into one tagged group.

Here is an example of the Permaculture events list and locations being mixed in together.
https://fragmentsofawalk.com/norske-okosamfunns-forening/aktiviteter/

![Screenshot 2022-02-16 at 16 29 16](https://user-images.githubusercontent.com/5323259/154298111-b72eeddf-9446-45b5-8a40-aef97be5b834.jpg)

For me to create a better overview I would probably create additional categories Permaculture - Dharma Mountain, Permaculture - Gaia and Permaculture - Opaker Gård (farm). Then create shortcodes for each category.

So the list would like something like this:

Permaculture courses held on Dharma Mountain.
(Shortcode that uses either category: Permaculture - Dharma Mountain or some other way to separate the specific courses.)
10/03/2022 – 13/03/2022 – Permaculture Design Course - Dharma Mountain
28/04/2022 – 01/05/2022 – Permaculture Design Course - Dharma Mountain
12/05/2022 – 16/05/2022 – Permaculture Design Course - Dharma Mountain

Permaculture courses held at the Gaia Center.
(Shortcode.....)
24/03/2022 – 27/03/2022 – Permaculture Design Course - Gaia
07/04/2022 – 10/04/2022 – Permaculture Design Course - Gaia
26/05/2022 – 29/05/2022 – Permaculture Design Course - Gaia

Permaculture courses held at the Opaker Gård.
(Shortcode.....)
31/03/2022 – 03/04/2022 – Permaculture Design Course - Opaker Gård
05/05/2022 – 08/05/2022 – Permaculture Design Course - Opaker Gård
16/06/2022 – 19/06/2022 – Permaculture Design Course - Opaker Gård

Btw I am seeing a dot infront of the list. Which is somewhat unexpected.

**Comment by paaljoachim** [comment]
That is a good idea.
I went ahead and went to Shortcodes -> Upcoming.
Selected category Permaculture.
Adjusted the Location filter type to Location Name and added in the name of a location.
Made the shortcode.

I noticed that this information was automatically added to the shortcode: 
`order="asc" template="abcd206b575b82d604522ca7bf01021f"`

This is the shortcode I used:
[my_calendar_upcoming category="2" ltype="event_label" lvalue="Gaia Senter"]

![Screenshot 2022-02-16 at 21 51 45](https://user-images.githubusercontent.com/5323259/154354954-55cc5fc0-d7c8-4e7a-9e18-3bd4b2187335.jpg)
https://fragmentsofawalk.com/norske-okosamfunns-forening/aktiviteter/

I made one and duplicated the shortcode and adjusted the location. Then duplicated it again.

The `lvalue="Gaia Senter"` is clear enough to understand, but what is the `ltype="event_label"` ?
Do the additional shortcode: `order="asc" template="abcd206b575b82d604522ca7bf01021f"` need to be added, or how much can we simplify the generated shortcode?

**Comment by joedolson** [comment]
Closing this; there really isn't a lot of simplification viable for these shortcodes. The template needs to be present, or it'll just fallback to the default template. I could eliminate values that are equal to the defaults, but it wouldn't accomplish a lot.
