### ISSUE TITLE
Edit Event Group - Choose location drop down does not show correct location.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#455]
**Describe the bug**
I went to Edit Event Group and noticed that the Choose location drop down is not showing the correct location.

**To Reproduce**
1. Add various events so they are grouped.
2. Add a location.
3. Go to Edit Event Group.
4. Notice the Choose location does not show the correct location.

This is what I see:

![Screenshot 2022-02-16 at 20 06 45](https://user-images.githubusercontent.com/5323259/154337821-35c553f5-d322-42ba-91d4-a68f8c9a3806.jpg)

Current location says Edit Gaia Senter.

Location Map
Gaia Senter

**Expected behavior**

I expected the Choose location to show the already selected location: Gaia Senter.
As I find it strange that another option is listed in the Choose location drop down.

**Comment by joedolson** [comment]
Hmm. That's definitely a case where changing '--' to 'No Location' makes the UI more confusing. The dropdown shouldn't show a value for events that already have a location. So this is correct, but the UI is confusing.

**Comment by paaljoachim** [comment]
Well I just think this would be natural:
![Screenshot 2022-02-16 at 20 15 48](https://user-images.githubusercontent.com/5323259/154338999-a7e1eaa5-27b8-4153-8bb2-6db9a6e5e4a1.jpg)

(Having it automatically reflect the current location.)
