### ISSUE TITLE
Not able to delete "General" category.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#456]
**Describe the bug**

I am trying to delete the General category but I see no quick edit option to delete it.
It first contained the default event which I then deleted so that no event was associated with the General category.
I also make the okosamfunn/Sustainable village a default category.

![Screenshot 2022-02-18 at 14 10 59](https://user-images.githubusercontent.com/5323259/154688911-a2c0e1fa-696e-405c-babc-27e12b6aac09.jpg)

**To Reproduce**
1. Be sure to add other categories.
2. Make sure that General has no events associated with it.
3. Quick edit does not show an option to delete the category.

**Expected behavior**
I expected that I would be able to delete the default General category.

**Comment by joedolson** [comment]
There's a lot in My Calendar that depends on a calendar with ID '1' existing; a lot of that is legacy, but I don't see any benefit to risking breakage on those issues so that this category can be deleted. I don't see any serious benefit to being able to delete it.

**Comment by paaljoachim** [comment]
It sounds like there is too much at risk in allowing the user to delete the initial "General" category.
So I understand the point in leaving it as it is.
