### ISSUE TITLE
Removing default words in Text Settings and clicking Save Custom Text brings back the default words.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#458]
**Describe the bug**

Settings -> Text.
Removing default words from example Single Event View (to make these blank). 

![Screenshot 2022-02-18 at 15 06 48](https://user-images.githubusercontent.com/5323259/154697536-792b0d8d-8833-4fa3-9cec-89446e368406.jpg)

Will automatically bring back the default words when clicking to save the changes (Save Custom Text).

![Screenshot 2022-02-18 at 15 03 47](https://user-images.githubusercontent.com/5323259/154697240-eeac0ddd-43ad-45e6-a642-033af0f58127.jpg)

**Expected behavior**
I expected the fields where I removed the default text to stay blank after having saved the changes.

**Comment by joedolson** [comment]
I'd consider this expected behavior. What would 'Hosted by' mean if there's no text? This isn't the mechanism for disabling features; just for setting the text.

**Comment by paaljoachim** [comment]
Ok. I will go ahead and close this for now, and if needed I will come back to it and give it more context.
