### ISSUE TITLE
Some links are underlined others are not.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#459]
I noticed that some links are underlined and others are not.
I do not know why this is so.

https://okosamfunn.no/mc-events/permaculture-design-course-gaia/?mc_id=10

![Screenshot 2022-02-18 at 15 10 30](https://user-images.githubusercontent.com/5323259/154698054-47a94ac9-eb9f-4846-bace-45fe5c2b2e98.jpg)

**Comment by joedolson** [comment]
The theme you're using has several different declarations for whether links are underlined or not, and they have variable specificity, so some of them override My Calendar's styles and others don't. Not a My Calendar problem, in my opinion.
