### ISSUE TITLE
List view: Please make title multiline possible

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#460]
**Is your feature request related to a problem? Please describe.**
If I have multiple events in one day, the list view is awkward. This is what these screenshots show. 
Example with two events on February 1:
grid view:
![grafik](https://user-images.githubusercontent.com/96249763/154843343-d2425221-d670-4ced-8f33-c3b6eb2cd14e.png)
List view:
![grafik](https://user-images.githubusercontent.com/96249763/154843379-d5f3d874-83a4-4ef9-ad4d-a9c07f3fa623.png)

**Describe the solution you'd like**
This montage shows my suggestion:
![grafik](https://user-images.githubusercontent.com/96249763/154844128-cef2dc7e-d124-4aca-b39e-c0b8d55cc9b9.png)
Ideally with {timerange] &": " & {title}

**Describe alternatives you've considered**
I can't think of any ad hoc solution for this

**Additional context**
I don't have any knowledge in PHP and don't know any solution here for customer CSS

**Comment by joedolson** [comment]
There is a filter for modifying the output format for event titles in the list format. The filter 'mc_titles_format' can be used to custom format the titles passed to the format. 

Just added an example here: https://github.com/joedolson/plugin-extensions/blob/master/my-calendar/mc-custom-list-titles.php
