### ISSUE TITLE
Make shortcodes for [my_calendar_search] possible?

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#461]
**Is your feature request related to a problem? Please describe.**
The search result with the shortcode [my_calendar_search] is displayed only limited, because only one month is visible

**Describe the solution you'd like**
When I search with [my_calendar_search], I want to see the search result in list view with events of the next x months. I want to configure the shortcode with keywords .

**Describe alternatives you've considered**
If I provide a special page for the search in list view, the search result is still in grid view because the default calendar has the grid view. Example: https://www.klimabuendnis-hamm.de/kalender/kalendersuche-im-test/ (search there for "fuge")

**Comment by joedolson** [comment]
There's an error in the current version that prevents this from working, but the shortcode `[my_calendar format="list" above="search" months="3"]` or something similar should give you what you need. 

The fix that allows the search form to render correctly is being released shortly.
