### ISSUE TITLE
Template code visible in the output

### ISSUE THREAD

**Issue by UliMand** [joedolson/my-calendar#463]
I see the Template-Code in the Output:
![grafik](https://user-images.githubusercontent.com/96249763/157436151-14202273-ad02-4a9f-810f-a4a45cb99282.png)

The Dates in the editor:
![grafik](https://user-images.githubusercontent.com/96249763/157435408-6a75098f-5a8a-4705-a3c1-12969d399bda.png)

The source code:
![grafik](https://user-images.githubusercontent.com/96249763/157436358-45a833a8-0e10-42d6-9a59-e56b00e6c85a.png)

what happened and how can I fix it?

**Comment by joedolson** [comment]
I haven't yet been able to reproduce this; but I'm looking.

**Comment by paaljoachim** [comment]
Hey @UliMand 

Could you just give me the steps to how you got this to show?
I would like to test it out following the procedure that you did. Thanks.

**Comment by UliMand** [comment]
I can no longer reproduce this. - Not even with a newly created date. When the error appears, the date did not yet have a location. This was only recorded later and can now no longer be deleted for the test. 

(The fact that the location can no longer be deleted seems to be another error).
