### ISSUE TITLE
Cursor does not change on clickable tabs from pointer to finger.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#464]
**Describe the bug**
Testing. Newest My Calendar plugin.

Hovering over the tabs In the Design, Settings and Shortcodes screen the cursor does not change to a finger signalling the typical clickable cursor type.

Example working cursor finger is seen in Events screen.

**To Reproduce**
1. Hover the tabs seen in Design, Settings and Shortcodes.
2. Notice that the cursor does not change from pointer to finger.

**Expected behavior**
Cursor change to finger.

**Screenshots**

Not working (Chrome)
![Cursor does not change on hover](https://user-images.githubusercontent.com/5323259/166150657-378bfc49-4a71-423f-8509-6b5f42a2b538.jpg)

Here it works:
![Cursor change on hover](https://user-images.githubusercontent.com/5323259/166150677-7b538460-7a39-48ce-ab20-41ce97230b23.jpg)

**Desktop (please complete the following information):**
 - OSX
 - Chrome
 - Newest version

**Comment by joedolson** [comment]
This is a won't fix. Pointer is not the correct cursor for a button; it is the correct cursor for a link.

**Comment by paaljoachim** [comment]
Alrighty! It has an hover effect and that gives a hint that something can be clicked.
