### ISSUE TITLE
Use default shortcode blocks?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#465]
**Is your feature request related to a problem? Please describe.**
The shortcodes from My Calendar (and Pro) used in Gutenberg shows the Classic block.

**Describe the solution you'd like**
I am wondering if by default that the shortcodes should be already be converted into shortcode blocks. So one would not need to convert when used with Gutenberg. If the Classic Editor plugin is activated the shortcode would automatically shows as the shortcode in TinyMCE.

**Describe alternatives you've considered**
Converting these myself.

**Comment by joedolson** [comment]
Could do that. I think I'd just need to wrap the inserted content in the appropriate comments. Will test.

**Comment by paaljoachim** [comment]
Great!
Pasting a shortcode automatically adds the Shortcode block when Gutenberg is used like so:

[my_calendar category="2" weekends="true"]


Pasting a shortcode into a page that uses the Classic editor shows the shortcode like so: 
<p>[my_calendar category="2" weekends="true"]</p>
