### ISSUE TITLE
Use `webcal` protocol for iCal feed links instead of `http/s`

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#466]
**Describe the bug**

Instead of using the webcal:// protocol they are linked via http(s) which is not working on any of the devices I tested.

Every browser just tries do download stuff instead of openind the default calendar application. Could this be fixed?

See: https://wordpress.org/support/topic/ical-subscription-links-broken/

**Comment by pattyland** [comment]
Thank you for fixing this problem so quickly! :)
