### ISSUE TITLE
Phone field to only accept numbers?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#473]
**Is your feature request related to a problem? Please describe.**

As I am filling out Location Contact Information  in the Add event screen I began filling out Phone.

**Describe the solution you'd like**

What about a phone field where one can only use numbers and not letters?

**Describe alternatives you've considered**

Just leaving it as it is and using numbers in the phone field.

Here I am using numbers and letters.

![Screenshot 2022-10-17 at 16 31 32](https://user-images.githubusercontent.com/5323259/196204684-02696c02-c516-49e5-9866-02e82c8fd0c2.jpg)

**Comment by joedolson** [comment]
This allows letters because of request to use vanity phone numbers, e.g. '1-800-GET-HELP'. These are increasingly rare, I suspect, but for historical reasons, it's may not be safe to change it.

**Comment by paaljoachim** [comment]
Ahh. Well that is a good reason.

Closing issue.
