### ISSUE TITLE
Adding event with additional copies and saving as draft. Clicking Events goes to Published.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#475]
**Describe the bug**
I made an event + 3 additional copies.
Saved as draft.
Clicked the sidebar: My Calendar -> Events. It went to Published like so:

![Screenshot 2022-10-17 at 16 41 17](https://user-images.githubusercontent.com/5323259/196207114-727b49b4-27f3-46bf-9fce-5b23234e34f2.jpg)

Notice that Published link is bold. It looks like one is in the Published screen that also includes Drafts.

**Expected behavior**

I expected that clicking the sidebar Events link just after saving events to drafts would go to the All screen. Having All and the number beside it in bold.

**Desktop (please complete the following information):**
OSX 12.6
Brave browser

----

Clicking All shows the same as the initial Published screen. Clicking Published I now only see the published events.
![Screenshot 2022-10-17 at 16 44 53](https://user-images.githubusercontent.com/5323259/196208047-8cb29fed-216b-4b92-a253-43bca61b1b25.jpg)

**Comment by paaljoachim** [comment]
One more thing.
In the Drafts screen should clicking to Publish a draft automatically take one over to the Published events screen, or should one remain in the Drafts screen? Currently one is automatically taken over to the Published events screen.

**Comment by joedolson** [comment]
This is definitely wrong; it *is* going to the all screen, but the Published screen is showing as current.

**Comment by joedolson** [comment]
Re: staying in drafts screen: should probably stay in the same screen you're currently in. Please make that a separate issue, however.

**Comment by paaljoachim** [comment]
Hey Joe

I am retesting on an online development site.
My Calendar plugin version 3.3.24.1

Using WordPress 6.1
Theme Twenty Twenty-Three
Gutenberg plugin 14.7.1
As well as a few other plugins are also active.
Such as WooCommerce.

After creating an event + adding a few copies and saving it as a Draft it still goes to the Published screen.
![Screenshot 2022-12-11 at 12 01 49](https://user-images.githubusercontent.com/5323259/206917644-ebdb83df-335e-421d-a33b-85b8b78e7358.jpg)

**Comment by paaljoachim** [comment]
Testing Github version. 3.4.0.

That works nicely as it should!
