### ISSUE TITLE
Going through what is seen in the main calendar view

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#476]
**Is your feature request related to a problem? Please describe.**
I am creating some events and then going to the Pro calendar.
I made some events and wondered where I would go to show more information in the main calendar view.
So I went to settings and to Display (as display would be the screen I decide what should be seen in the various views).
As it has been a while since I have looked at the calendar I notice a few new things...

Display Settings.
Begins with how Calendar Links should be opened. What about moving this option further down?
Reasoning is that going to Display I would like to be able to right away get a feel for what the various views are and how I can modify the views.

**Update calendar layout**

To me that would mean the main calendar layout. As seen when going to the My Calendar page here:
![Screenshot 2022-10-17 at 17 10 08](https://user-images.githubusercontent.com/5323259/196214725-386904e0-f186-4d6b-8e60-1d6f3cdabe15.jpg)

**Describe the solution you'd like**

Having a better definition of how I can modify what is seen in the main calendar view.
I go to Event Display Fields -> Main View (Popup or List). It seems like this is the view for the main calendar as well as the link Popup and the List views. Should this be split up into an additional tab? The reasoning is that I might want to see the excerpt in the main calendar view as well as a small image of the featured image.

I am thinking something like this:
![My Calendar main view with excerpt and featured image](https://user-images.githubusercontent.com/5323259/196217296-e8b59ad9-bdfb-4d91-8960-58b543a874e4.jpg)

Main calendar view which also includes an excerpt and featured image.

**Describe alternatives you've considered**

Using more time to figure out where the options are.

**Additional context**

Making the various views easier to modify.

**Comment by joedolson** [comment]
So, what you're looking for is how to modify the event title. The Event Display Fields is about displaying the event details; either in list or grid view - the title is a separate field, under Text settings. I could clarify this, though.
