### ISSUE TITLE
Events -> Drafts screen. Publishing a draft moves user to Published screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#478]
**Describe the bug**

I have noticed when clicking publish that the screen automatically redirects to the Published screen.
![Screenshot 2022-10-18 at 08 53 56](https://user-images.githubusercontent.com/5323259/196357434-98c92eef-d6a3-4341-b789-9e4e93edf114.jpg)

I believe it should stay in the Drafts screen.

**To Reproduce**
1. Create an event.
2. Save it as draft.
3. Go to Events -> Drafts screen.
4. Publish a draft.
5. Notice the screen goes from Drafts to the Published screen.

**Expected behavior**
That it would stay in the Drafts screen.

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar/commit/3d31f03c803bb4af713e2824e317f0876b214a22

**Comment by paaljoachim** [comment]
Great! This now works!
