### ISSUE TITLE
Add to settings remove My Calendar data when deleting plugin.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#48]
I am going through the manual.

1. INSTALLATION

Why not use the WordPress delete option?
 
My Calendar User's Guide : Calendar version 3.2.0 : June 2020 : 9
Using WordPress to delete a plug-in does more than just delete the files; it also deletes all of your set- tings for the plug-in. If you use that method to remove a plug-in, you will need to reconfigure any set- tings you've changed in the plug-in, including your stylesheets, unless you're using My Calendar's cus- tom files directory to store styles.

--------

Adding a remove My Calendar data on delete of plugin would give the option for the user. 
It would be added to the General settings page.

**Comment by paaljoachim** [comment]
Ok I just noticed the setting:

"Drop MySQL tables on uninstall"

Closing issue.

**Comment by joedolson** [comment]
Actually, I'm going to leave this open. Because the 'Drop MySQL tables' only relates to the plug-in data (events, locations, categories), and not to the plug-in settings, there is a benefit to adding an option that governs whether settings are deleted on uninstall.
