### ISSUE TITLE
Failure in Custom field callback for permalinks settings

### ISSUE THREAD

**Issue by borsti87** [joedolson/my-calendar#481]
https://github.com/joedolson/my-calendar/blob/1f7c546ed260a272445da21016b9f800c96947b8/src/my-calendar-core.php#L2140
Hi,
here are two failures in the code, in the both function calls of `get_option()` the parameter is misspelled.
In both cases the parameter must be `'mc_location_cpt_base'`.
Greetings
borsti87

**Comment by joedolson** [comment]
Thanks for calling these out! That's pretty egregiously wrong...
