### ISSUE TITLE
How to enable the My Calendar API for exporting and importing events.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#488]
Hey Joe

I began looking at how to import events: https://docs.joedolson.com/my-calendar-pro/2022/04/27/import-events-from-my-calendar/

This links to: My Calendar event export API - https://docs.joedolson.com/my-calendar/my-calendar-api/

"The API is not enabled by default. Once enabled, you can access it using URL parameters on your site:"

This means we need information on how to enable the API. I did not locate any information on how to enable it.

**Comment by joedolson** [comment]
Add note in that doc.

**Comment by paaljoachim** [comment]
What information did you add to the doc? Working on seeing a before and after.

**Comment by joedolson** [comment]
I added instructions for how to enable the api, and a screenshot showing
the option.

**Comment by paaljoachim** [comment]
Great!

Looking at: https://docs.joedolson.com/my-calendar-pro/2022/04/27/import-events-from-my-calendar/

Under the screenshot we have this text.
"Once the external API is enabled on the source site, you can use the normal My Calendar Pro imports to fetch events."

We should add something like this:
To import go to My Calendar Pro > Importer.
Below the heading Remote import we need to Import from URL.  

The URL you’ll need to use will follow a predictable pattern:
https://www.yourdomain.com/?mc-api=csv&from=YYYY-MM-DD&to=YYYY-MM-DD

All of the available parameters are documented in the My Calendar external API documents (**Link please**); you can import any set of events you choose from within those specifications, with a couple of exceptions:

---> I will need to test it out to see if there is anything else that should be added here.
