### ISSUE TITLE
Add Event - Clicking Add Categories adds an additional checkbox or -

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#489]
**Describe the bug**

This is in version 3.4.0.

Creating a new event and clicking Add Categories Adds a checkbox or - Just below Add Event. Deselecting the button also makes the additional checkbox or - go away.

**To Reproduce**
1. Create new event.
2. Click + Add Categories or - Categories.
3. Notice the additional checkbox or - seen above the Add event title just above the Event Title field.

**Expected behavior**
Not seeing the checkbox or - show up when clicking Add Categories.

**Screenshots**
![Screenshot 2022-12-11 at 21 02 47](https://user-images.githubusercontent.com/5323259/206945391-7f863cab-2c17-4d25-bfae-7c30a4de4548.jpg)

![Screenshot 2022-12-11 at 21 02 56](https://user-images.githubusercontent.com/5323259/206945393-47d549ba-138a-4a38-b373-a849c42e0111.jpg)

Clicking + Add Catgories / - Add Categories will add a checkbox or - just above the Event Title. Clicking outside the Add Categories button deselecting removes the added checkbox or -.
https://user-images.githubusercontent.com/5323259/206946159-67970a16-d962-4d04-b8af-2bbe1e28b14b.mp4

**Desktop (please complete the following information):**
 - OSX 12.6.1
 - Browser Brave

**Comment by joedolson** [comment]
I think this is either a plugin or your theme; that's something being applied to the class `.screen-reader-text` that's making it visible on selection. Can you inspect the code to see where that's coming from?

**Comment by paaljoachim** [comment]
Using default theme Twenty Twenty Three.
WP 6.1.1
Using only Gutenberg plugin 14.8 rc1 and My Calendar plugin.

AHA!! NB! It looks like it has to do with the Gutenberg plugin activated.
When the Gutenberg plugin is activated I see the following:

You are correct it has to do with the .screen-reader-text.

![Screenshot 2022-12-18 at 09 57 12](https://user-images.githubusercontent.com/5323259/208305482-055286f0-4a53-43dd-aa2e-6f13e6fdcbb1.jpg)

![Add new category My Calendar](https://user-images.githubusercontent.com/5323259/208305485-3f3541c7-929f-4cf0-8d26-24db8f8aa1ee.gif)

**Comment by paaljoachim** [comment]
Great! Now it is working correctly.
