### ISSUE TITLE
Settings - Text: Revert text fields to default

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#491]
**Is your feature request related to a problem? Please describe.**
Just a moment ago I changed and added text to all the fields in the Settings Text screen. (To test out 3.4.0)
I do not remember what the original names where.

**Describe the solution you'd like**
I would like to revert to default. Seeing the default placeholder fields. Getting the original names back.
Having a  "Revert to default" button next to "Save Custom Text" button.

**Describe alternatives you've considered**
Guessing what the default placeholders were.

**Comment by joedolson** [comment]
The default values for pretty much all fields is blank. These are customizations; no value is actually required.

**Comment by joedolson** [comment]
In https://github.com/joedolson/my-calendar/commit/ad77b71897d9583823f914a174cb5e5fd09e10e8, I changed all text settings to have no default values and show the defaults (that will be rendered with no data) as placeholders. Closing based on that, since I'm not going to add a feature to do this.
