### ISSUE TITLE
Design - The CSS editor will be removed in My Calendar 3.5. ....

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#495]
As I was testing the various settings screens I noticed this notification seen in the Design screen.

![Screenshot 2022-12-18 at 10 32 26](https://user-images.githubusercontent.com/5323259/208306715-eed84933-430f-4b95-8831-8a122055574a.jpg)

The CSS editor will be removed in My Calendar 3.5. You should migrate any custom CSS into the My Calendar custom directory at /wp-content/plugins/my-calendar-custom/.

Is the CSS editor the same as the Style Editor?
If so then it would be better to say: The CSS Style Editor will be removed....

**Comment by joedolson** [comment]
The style editor is the page, where you edit everything related to calendar styles. The CSS editor is the specific edit field where you edit the stylesheet. Only the CSS editor is going away. Happy to clarify that, but they are separate.

**Comment by paaljoachim** [comment]
Thank you! 
Btw I am not seeing the message in the newest version I downloaded from Github.
