### ISSUE TITLE
Categories - No visible icon list

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#496]
WordPress 6.1.1
Theme: Twenty Twenty Three
Plugin active: My Calendare
Brave browser

Clicking the ? beside the Category Icon. I see this screen.

![Screenshot 2022-12-18 at 10 35 13](https://user-images.githubusercontent.com/5323259/208306798-88a72a32-fa9e-48b0-819e-08aeda562203.jpg)

Clicking "Icons by Font Awsome" leads to this page:

https://fontawesome.com/license
Perhaps it instead should lead to: https://fontawesome.com/icons ?

Clicking Documentation leads to this page:
https://docs.joedolson.com/my-calendar/?s=Category%20Icons

I click the Category icons documentation.
https://docs.joedolson.com/my-calendar/my-calendar-category-icons/

I notice the second screenshot showing icons in an Icon List does not correspond to the modul which showed up as I clicked the ? beside the Category icon.

I also notice back in the Category Editor that beginning to write the word Anch or Anchor no drop down list is seen. (A loading gif is seen for a moment and then nothing happens.)

![No Icon List](https://user-images.githubusercontent.com/5323259/208307154-4b241161-8e49-4140-a900-9e452b01a1ef.gif)

**Comment by joedolson** [comment]
Fixed in https://github.com/joedolson/my-calendar/commit/8a58652b0c243fddd634c4b75be31890614c3393

**Comment by paaljoachim** [comment]
Great!
I now see the Icon list back in place.
