### ISSUE TITLE
Editing a category and adding Holiday - shows a notification in the top.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#500]
**Describe the bug**
I added the category "Spring" through the Categories screen.
Clicked the quick edit to "Edit" the category. Added "Holiday" and clicked "Save Changes".
The message: "Category was not changed. Holiday category changed." would be improved.
For instance just having "Holiday category changed." or "Holiday category added."

![Screenshot 2022-12-18 at 19 56 42](https://user-images.githubusercontent.com/5323259/208329140-0939a60c-fbfb-4fe1-bb0b-3416e6a5f24e.jpg)

**Comment by joedolson** [comment]
This is one of those awkward things where Holiday & Default are actually installation options, but edited as part of the category. So the category hasn't been changed, but the designated holiday category has been...

**Comment by paaljoachim** [comment]
Great! That looks better.
It now says: "Category edited successfully. Holiday category changed."

![Screenshot 2022-12-21 at 23 02 47](https://user-images.githubusercontent.com/5323259/209053057-5b71b760-544e-4dfb-8164-934c0aa10d3a.jpg)
