### ISSUE TITLE
Opening single event in new screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#502]
**Describe the bug**
The event opens in a single event screen.
There seems to be a black overlay. There is also an error.
![Screenshot 2022-12-18 at 20 19 35](https://user-images.githubusercontent.com/5323259/208330396-691d34dc-b1aa-4578-a7e1-e76e1b8ab5fa.jpg)

WordPress 6.1.1
Twenty Twenty Three
Only active plugin is My Calendar.
Brave browser.

**Comment by joedolson** [comment]
I don't know what the black overlay is; I don't think that's from My Calendar.

**Comment by paaljoachim** [comment]
I am not seeing the black overlay now. Hopefully it was just a glitch that now has passed.
