### ISSUE TITLE
Empty button in list view on 3.4.0 beta 1

### ISSUE THREAD

**Issue by amberhinds** [joedolson/my-calendar#504]
**Describe the bug**
This is the shortcode in use: [my_calendar format="list" time="month" months="2"]

Here's what I'm seeing on the front end:
<img width="547" alt="list view showing three bullet points with empty buttons" src="https://user-images.githubusercontent.com/13153456/208792515-d29a2e4d-1983-41a8-8f03-5f4e3a4c9393.png">

Here's the code I'm seeing:
`<li id="list-2022-12-21" aria-current="date" class="mc-events wednesday wed current-day has-events author1 mcat_general even"><strong class="event-date"><button type="button" class="mc-text-button"><span></span></button><span class="mc-list-details-separator"> – </span><span class="mc-list-details select-event">Demo: Florence Price: Symphony No. 3 in c minor</span></strong> `

**Additional context**
This is on a sandbox site running 2023 with no other plugins active - installed the zip from the beta at https://github.com/joedolson/my-calendar/releases/tag/v3.4.0-beta-1

**Comment by joedolson** [comment]
Does your sandbox WordPress installation have a date format set in the WordPress general settings? What's missing here is the date. While having no value in the My Calendar settings is normal, this should be falling back to the WordPress date format settings when that's empty.

**Comment by amberhinds** [comment]
Yes, date format is set to F j, Y.

For what it's worth, it does work if I deactivate the beta and reactivate Version 3.3.24.1. This is how that same shortcode looks on that version.
<img width="905" alt="Screen Shot showing shortcode output in version 3.3.24.1. " src="https://user-images.githubusercontent.com/13153456/209239821-cf19cea9-147c-40fd-bb36-3db8a625fc51.png">

**Comment by joedolson** [comment]
Tested my hypothesis and this happens if the option returns a boolean false, which was prevented in https://github.com/joedolson/my-calendar/commit/039e21008508201820fd030453f53685194f215e

So this should already be fixed.

**Comment by paaljoachim** [comment]
Testing.
WordPress 6.1.1
Theme: Twenty Twenty Three
Latest Github version.

Shortcode used:
`[my_calendar format="list" time="month" weekends="true" months="2"]`

This is what I see:
![Screenshot 2022-12-22 at 20 42 58](https://user-images.githubusercontent.com/5323259/209254180-93f447c7-b4ce-466e-9a21-02c9e980b3b7.jpg)
