### ISSUE TITLE
Missing Generate Shortcode button in the meta boxes in the My Calendar page

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#509]
**Describe the bug**
I am comparing the Shortcodes - My Calendar Shortcode Generator in relation to going to the My Calendar page and adjusting the shortcodes there.

Shortcodes screen:
![Screenshot 2022-12-22 at 19 57 01](https://user-images.githubusercontent.com/5323259/209250208-4f0501ce-bcc7-45f6-99e1-e29424b14b56.jpg)

My Calendar meta boxes Shortcodes:
![Screenshot 2022-12-22 at 19 57 47](https://user-images.githubusercontent.com/5323259/209250227-cc4b216c-c10d-42bc-bbd5-ea4a896758b1.jpg)

**The Generate Shortcodes button is missing from the meta boxes in the My Calendar page. I do not know how to generate a shortcode when the generate shortcode button is missing....**

**Comment by joedolson** [comment]
Closing as duplicate: https://github.com/joedolson/my-calendar/issues/362
