### ISSUE TITLE
Rephrasing: "Open calendar links to event details"

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#51]
In the Output settings.
The first option is:
"Open calendar links to event details"

Rephrasing to what I believe it does:

"Open events in single event view."

---> This should also be on/checked by default.

**Comment by joedolson** [comment]
Totally fine with changing the text; that does seem clearer. But I don't think I'll switch the default in this release; I'll keep the calendar modals for event details as the default.
