### ISSUE TITLE
Add modal view

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#511]
Added in https://github.com/joedolson/my-calendar/commit/ae01aa724ba213d25d544d8784bab80c9d15f61d; creating issue for documentation

**Comment by joedolson** [comment]
Enabled at My Calendar > Design > Scripts

**Comment by paaljoachim** [comment]
Let me know how you want me to this test, Joe.
This is what the Design > Scripts screen looks like now:
![Screenshot 2022-12-24 at 14 30 29](https://user-images.githubusercontent.com/5323259/209448971-2bffeaf9-ee6f-4c23-919e-71caabe14deb.jpg)

**Comment by joedolson** [comment]
This is a new popup style; test in all views on various themes.

**Comment by paaljoachim** [comment]
Hey Joe.
Can you give some more detail what this does? How I test it? Etc...
Thanks.

**Comment by joedolson** [comment]
Enable it; explore the pop ups on all main views. See
https://docs.joedolson.com/my-calendar/my-calendar-views-overview/

**Comment by paaljoachim** [comment]
I went ahead and explored the views in this issue: https://github.com/joedolson/my-calendar/issues/520
