### ISSUE TITLE
Event Accessibility heading level out of order

### ISSUE THREAD

**Issue by amberhinds** [joedolson/my-calendar#515]
**Describe the bug**
On a single event, if you select accessibility features for the event, the heading which outputs for that section on the event single is an H4. 

There are no other subheadings on the event single so this appears as a skipped heading level. I think this should be a heading 2.

**Comment by joedolson** [comment]
This isn't changeable until version 3.5, when I release the updated templating system, due to backwards compatibility issues. 

It can be filtered using the existing `mc_subheading_level` filter.
