### ISSUE TITLE
Display settings not saved - returning a non-array value

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#518]
**Describe the bug**
I am using the newest Github build. I made an event and published it. Then checked the frontend.
It shows this error:

![Screenshot 2023-01-04 at 15 56 40](https://user-images.githubusercontent.com/5323259/210582918-54402806-b864-42dd-8eb1-c4d233f9ceda.jpg)

WordPress 6.1.1
Theme: Twenty Twenty Two
My Calendar is the only active plugin.
Online test site

Activating Query Monitor. Refreshed the frontend and the error went away. 
Errors seen in Query Monitor.

![Screenshot 2023-01-04 at 15 59 00](https://user-images.githubusercontent.com/5323259/210583456-a6763c9d-4c45-4fac-be2c-fd5abaa55ff7.jpg)

```
wp-content/plugins/my calendar/my-calendar-output.php:1286
in_array()
wp-content/plugins/my calendar/my-calendar-output.php:1286
mc_output_is_visible()
wp-content/plugins/my calendar/my-calendar-output.php:447
my_calendar_draw_event()
wp-content/plugins/my calendar/my-calendar-events.php:732
mc_get_event()
wp-content/plugins/my calendar/my-calendar-output.php:1861
my_calendar()
wp-content/plugins/my calendar/my-calendar-shortcodes.php:97
my_calendar_insert()
wp-includes/shortcodes.php:355
do_shortcode_tag()
Unknown location
preg_replace_callback()
wp-includes/shortcodes.php:227
do_shortcode()
wp-includes/class-wp-hook.php:308
apply_filters('the_content')
wp-includes/blocks/post-content.php:55
render_block_core_post_content()
wp-includes/class-wp-block.php:256
WP_Block->render()
wp-includes/class-wp-block.php:242
WP_Block->render()
wp-includes/blocks.php:1051
render_block()
wp-includes/blocks.php:1089
do_blocks()
wp-includes/block-template.php:240
get_the_block_template_html()
wp-includes/template-canvas.php:12

```

**Comment by joedolson** [comment]
That's weird. The only way that could happen would be if your settings for the display view were not an array.  What are your settings if you go to My Calendar > Settings > Display for the view you were looking at? (Which I can't tell from your report.)

**Comment by paaljoachim** [comment]
I am not sure how to reply.
These were just default values.

Single Event
![Screenshot 2023-01-04 at 21 54 19](https://user-images.githubusercontent.com/5323259/210648317-0066c32f-9018-4629-8400-069a3458ec5a.jpg)

Mini Calendar Popup
![Screenshot 2023-01-04 at 21 56 39](https://user-images.githubusercontent.com/5323259/210648457-d681a516-edc7-4406-8bb7-40c4251d608b.jpg)

I will test the new build and see if the various errors still show up in Query Monitor.

**Comment by joedolson** [comment]
Which version of the build were you using when you had this issue? I had assumed you were already testing the most recent RC.

**Comment by joedolson** [comment]
Because this won't happen on the current master; but not because I've resolved the issue, just the symptom. I still would like to know how that happened, so knowing what version you were testing would be helpful.

**Comment by paaljoachim** [comment]
I tested with the version earlier today. Perhaps at 2pm my time. Making it 7am St. Paul time.

**Comment by paaljoachim** [comment]
If you'd like I can test that specific version again and check to see if I can repeat it.

**Comment by joedolson** [comment]
Was it a completely fresh install, or an environment that had other data already in it? This is a data issue, so it may not produce the same results if the data has changed since then.

**Comment by paaljoachim** [comment]
Earlier today I clicked to drop MySQL tables on uninstall and Delete plugin settings on uninstall and then deleted the plugin. Then went and got the newest version on Github. The one I downloaded at 2pm. So yes it was a fresh install.
The only data it had in it was Settings > Text to where I inserted various values something similar to this:
![Screenshot 2023-01-04 at 22 25 22](https://user-images.githubusercontent.com/5323259/210652858-4ff5aac0-18be-4b58-bbf1-2cf25cab9a5c.jpg)

**Comment by joedolson** [comment]
That's good; that increases the likelihood you'll be able to reproduce it. Let me know. Because with a fresh install you should be getting the default settings there, and those are arrays; if you're not, that's definitely something that needs exploring.

**Comment by paaljoachim** [comment]
Where do I find the version from earlier today?

**Comment by joedolson** [comment]
Probably need to use RC 3: https://github.com/joedolson/my-calendar/releases/tag/v3.4.0-RC-3

**Comment by paaljoachim** [comment]
I just tested with RC 3. 
I made a few events but I am not seeing the error I noticed in the first post.
I will let this go for now. I will create another issue if it shows up again.

**Comment by joedolson** [comment]
Weird. There were a few minor changes between the RC and early this morning, but none of them had any possibility of causing that issue. I guess I've resolved the consequence of this data issue, so we'll have to assume for now that it was some kind of fluke.
