### ISSUE TITLE
Not able to add new icon to existing category (or so I initially thought).

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#519]
**Describe the bug**
I added an event.
Added a category in the event.
Published the event.
Went to Categories and edit the Mountain event. Selected Category Icon mountain.svg. 
Clicked to Save Changes.
Noticed this:

![Screenshot 2023-01-04 at 16 17 25](https://user-images.githubusercontent.com/5323259/210587527-8951fa74-188a-49a6-930f-5876fb2f803b.jpg)

There is a black background where the icon should be. 

In Category Settings I tested.
Default: Hide category colors - Shows a black background instead of icon.
Title text color  - Shows a black background instead of icon.
Title background color - Shows the icon.

![Screenshot 2023-01-04 at 16 21 30](https://user-images.githubusercontent.com/5323259/210588369-f997a533-3682-428c-80f5-00a3d20381ab.jpg)

Also explored Hide Category icons and then selected Hide category colors (no black background is seen).
![Screenshot 2023-01-04 at 16 22 53](https://user-images.githubusercontent.com/5323259/210588661-abea214c-712c-4bc5-846b-27e0cbece81a.jpg)

**I found it weird to see a black background instead of the icon.**

WordPress 6.1.1
Theme: Twenty Twenty Two
Newest Github My Calendar build.
Active plugins: My Calendar and Query Monitor.

**Comment by joedolson** [comment]
It looks like there's no color defined for this category; does it become visible if you define a color?

**Comment by joedolson** [comment]
This was connected to the option 'hide category colors' - that sets the icon's color to 'inherit', but it didn't remove setting the background color, so they were the same color.

**Comment by paaljoachim** [comment]
Testing using the latest build.
Default Category Settings has changed (from what I see) from hide category colors to now: Title background color 

---

Hide category colors I  see this:
![Screenshot 2023-01-04 at 22 49 00](https://user-images.githubusercontent.com/5323259/210656467-178c4ff8-76a8-4878-b89b-4f8eb5b7a3bb.jpg)

Title text color I see this:
![Screenshot 2023-01-04 at 22 50 15](https://user-images.githubusercontent.com/5323259/210656629-880f4371-cd27-4049-9d9e-a366e934c544.jpg)

Title text color hides the icon underneath it.

**Comment by joedolson** [comment]
Default category settings have not changed.

**Comment by paaljoachim** [comment]
Should we do something with the hidden icon when "Title text color" is selected so that the icon is in some way still seen?

**Comment by joedolson** [comment]
I'm not sure I can readily solve that - if there's no category color set, but the settings are that the title should be in the category color, I don't know how I should guess what to use.

**Comment by paaljoachim** [comment]
Alrighty we just leave it as it is and move onward to other things.
