### ISSUE TITLE
What is this?    Target for Mini Calendar date links:

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#52]
As I am not very familiar with the calendar which is a good thing as I go through the guide..:)

I am right now in the Output Settings screen.

I do not understand what this is:

Target for Mini Calendar date links:
You can configure links in the mini calendar to point either to that date's events or to the place in the current calendar where that date is found. Although I could use the same URL for all possible settings, it gives more flexibility for you to specify a different URL – in case you want a different look or behavior. This URL is the destination you want links from the mini calendar to use.

Questions that come up....
What is the mini calendar? I have not seen a mention of this before now.
Where do I see it? 
What does it do?

![Screen Shot 2021-05-09 at 21 44 03](https://user-images.githubusercontent.com/5323259/117585534-3b297600-b113-11eb-801d-83c058bd837b.png)

Associated:
What is this? Mini calendar widget date links to:
https://github.com/joedolson/my-calendar/issues/53

**Comment by joedolson** [comment]
It's messy, that's what it is...it defines a url that arguments are added to as the target for date links in the mini calendar. It's a fairly obtuse setting, hard to communicate. Might be more clearly added in the widget rather than global settings.

**Comment by paaljoachim** [comment]
You mean here?

![Screen Shot 2021-07-16 at 14 01 08](https://user-images.githubusercontent.com/5323259/125944318-64eead1e-fd1e-4803-8edf-71b22b5906ac.png)

Hmm I will need to take a closer look at the mini calendar....

**Comment by paaljoachim** [comment]
This has been cleaned up so that I am closing this issue.
