### ISSUE TITLE
Category name by using Multibyte Language like Japanese,  Category class not output.

### ISSUE THREAD

**Issue by sutefu23** [joedolson/my-calendar#524]
**Describe the bug**
When Category name by multibyte language, there can not be output class name.
So even if there are several categories, display only one color.

**To Reproduce**
Create category names by Japanese language.

**Expected behavior**

**Screenshots**

![スクリーンショット 2023-02-03 112842](https://user-images.githubusercontent.com/16435468/216498724-2d0cbc46-751c-4783-b8e0-f663f14cdcf5.png)

**Desktop (please complete the following information):**
 - Windows10

**Additional context**
This causes the sanitize_html_class to return an empty string,  when that function's parameter is encoded in a multibyte language.
So I will send you a pull request.

**Comment by joedolson** [comment]
Closed in https://github.com/joedolson/my-calendar/commit/1290353ba15c3efeb43410432b8f3093e30dbc11#diff-d55b2099105cecc1c34b7a99d934cc8fa5f7c13921210a116995cff01ce25c3f; props @sutefu23
