### ISSUE TITLE
What is this?   Mini calendar widget date links to: 

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#53]
I am wondering what the below does.

**Mini calendar widget date links to:** 
Options.
jQuery pop-up view
daily view page (above)
in-page anchor on main calendar page (list)
In-page anchor on main calendar page (grid)

Associated: 
What is this? Target for Mini Calendar date links: 
https://github.com/joedolson/my-calendar/issues/52

**Comment by joedolson** [comment]
The mini calendar is a view option for the shortcode & the default view for the calendar widget. It eliminates the list of events on each day and instead (by default) just gives a single pop-up that shows all events for that day.

This option allows the user to alter the behavior of that link to go the the view of events for that day, or target a specific location in the list or the grid. 

Might be better to define this setting in the widget, so it's not global to all views of the mini calendar but only to the current view.

**Comment by joedolson** [comment]
This has been heavily updated since this issue was raised; I think it's reasonably clarified now. Closing for the time being.
