### ISSUE TITLE
MyCalendar ical API export has error in repetition pattern

### ISSUE THREAD

**Issue by masonwolf** [joedolson/my-calendar#532]
I have several recurring events in my calendar. The json feed exports them as each separate event, which is fine. But the ical feed exports them as singular events with a repetition pattern. The repetition pattern is incorrect.

See the example below:

SUMMARY:Monthly Potluck
DTSTAMP:20230308T180000
ORGANIZER;CN=Mason:MAILTO:REDACTED@gmail.com
DTSTART;TZID=America/Los_Angeles:20230308T180000
DTEND;TZID=America/Los_Angeles:20230308T210000
RRULE:FREQ=MONTHLY;BYDAY=1TU;UNTIL=20260311T000000Z

The first date is (correctly) on March 8, the second Wednesday of the month. And in the list of events on the event editor, it creates additional events on the second Wednesday. But in my ical reader, each event after March is on the first Tuesday of the month. I have 2 other events. One that should be on the last Wednesday of every month instead uses:

RRULE:FREQ=MONTHLY;BYDAY=4TU;UNTIL=20231025T000000Z

And another that should be on the first Saturday of every month is instead:

RRULE:FREQ=MONTHLY;BYDAY=5FR;UNTIL=20231202T000000Z

**Comment by masonwolf** [comment]
This happens both from making a direct API call, as well as in the navigation tools export for Google link.

**Comment by joedolson** [comment]
I think this commit should fix the issue; if you're comfortable applying the changes and testing for yourself, I'd appreciate the confirmation.

**Comment by joedolson** [comment]
This is committed and released, closing as fixed.
