### ISSUE TITLE
Hover over calendar icon + List text shows uneven underline.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#54]
Tested with Twenty Twenty One and Twenty Twenty themes.
Hovering over the main calendar icon + List text shows an uneven underline like so:

Twenty Twenty One
![Screen Shot 2021-05-09 at 22 19 54](https://user-images.githubusercontent.com/5323259/117585854-f1418f80-b114-11eb-9ce9-9afc3e75575f.png)

Twenty Twenty
![Screen Shot 2021-05-09 at 22 22 11](https://user-images.githubusercontent.com/5323259/117585875-133b1200-b115-11eb-9bf6-b82536315515.png)

I have also seen this in other locations as well.
For instance.

List view.
Hovering
![Screen Shot 2021-05-09 at 22 23 57](https://user-images.githubusercontent.com/5323259/117585911-585f4400-b115-11eb-8e36-5bbbe05f1eb4.png)

Btw Open a List view. Click the first event. Then close it again. Move the cursor away.
Notice the first clicked event has gone missing.
![Screen Shot 2021-05-09 at 22 25 46](https://user-images.githubusercontent.com/5323259/117585938-9492a480-b115-11eb-92ae-90408119036b.png)

**Comment by paaljoachim** [comment]
Another:

![Screen Shot 2021-05-09 at 22 38 26](https://user-images.githubusercontent.com/5323259/117586255-55fde980-b117-11eb-8e80-f9f9a420dc79.png)

**Comment by paaljoachim** [comment]
I am experimenting as I am styling the calendar.

Another example.

![Screen Shot 2021-07-31 at 23 18 02](https://user-images.githubusercontent.com/5323259/127752616-5a822a93-1c28-402a-8a30-244882e34957.jpg)



Commenting out or removing line-height will also bring the underline and icon a little bit up.

```
.mc-main .my-calendar-header span, .mc-main .my-calendar-header a, .mc-main .mc_bottomnav span, .mc-main .mc_bottomnav a, .mc-main .my-calendar-header select, .mc-main .my-calendar-header input, .mc-main .mc_bottomnav select, .mc-main .mc_bottomnav input, .mc-main .my-calendar-header input[type=submit], .mc-main .mc_bottomnav input[type=submit] {
    padding: 4px 6px !important;
    font-size: 16px;
 /*   line-height: 1.5; */
    font-weight: 400;
    text-decoration: none;
}
```


![Screen Shot 2021-07-31 at 23 18 45](https://user-images.githubusercontent.com/5323259/127752632-65ba1254-1563-4a3b-bd2a-87dc8a0ec25c.jpg)


Changing top from -2px to -3px in the below code.

```
.my-calendar-prev a:before, .my-calendar-next a:after, .mc-export a:before, .mc-main .time-block:before, .mc-main .sharing .ical a:before, .mc-main .sharing .gcal a:before, .mc-main .sharing .mc_details a:before, .mc-main .mc-format a:before, .mc-main .mc-format span:before, .mc-main .mc-print a:before, .mc-main .mc-list .event-date button:nth-of-type(1):before {
    font-family: 'dashicons';
    vertical-align: middle;
    position: relative;
    top: -2px;
    margin-right: 2px;
}
```

Will show the underline of the icon and text like so:

![Screen Shot 2021-07-31 at 23 23 14](https://user-images.githubusercontent.com/5323259/127752722-966766bc-ca7c-4f6a-9ba1-90b97c7d35e7.jpg)





An additional adjustment if wanted.

The following can be adjusted from 3px to 1px. As the line comes closer to the text. 

```
a {
    cursor: pointer;
    color: var(--wp--style--color--link, var(--global--color-primary));
    text-underline-offset: 3px;
}
```

**Comment by joedolson** [comment]
Just as a note, all of these changes will need to be tested with several different themes, especially if you're removing a declaration. 

One note: in the screenshots above, the only differentiation between the current view 'Month' and the other views is color; there needs to be something more than color alone to differentiate those.

**Comment by paaljoachim** [comment]
Instead of removing a declaration I followed what you mentioned in the other issue, and added a border bottom.

Regarding differentiation between current view "Month" etc.
I went from this:
![Screen Shot 2021-08-01 at 01 17 53](https://user-images.githubusercontent.com/5323259/127754495-3ec6d78d-eba7-4834-b2b1-184a2409ac10.jpg)

and added the kind of button seen above.

I will edit the styling issue https://github.com/joedolson/my-calendar/issues/173 and show a before and after what I have up to this point. Then we can later on talk through it.

**Comment by paaljoachim** [comment]
In Grid view I made this adjustment:

Before:
![Screen Shot 2021-08-01 at 01 45 39](https://user-images.githubusercontent.com/5323259/127754846-123a9254-3fc7-459a-b434-09e1fed18477.jpg)

After:
![Screen Shot 2021-08-01 at 01 44 56](https://user-images.githubusercontent.com/5323259/127754850-63f2e4d4-e0f1-4a7d-bc18-6772ff736b52.jpg)

CSS:

```
/* GRID view */

button.mc-text-button:hover, button .mc-text-button:focus {
    text-decoration: none; 
    border-bottom: 1px solid gray;
}

.mc-text-button  {
    border-bottom: 1px solid gray;
}
```

I first added all the CSS classes here:
```
.site .button:not(:hover):not(:active):not(.has-background), button:not(:hover):not(:active):not(.has-background), input[type=submit]:not(:hover):not(:active):not(.has-background), input[type=reset]:not(:hover):not(:active):not(.has-background), .wp-block-search .wp-block-search__button:not(:hover):not(:active):not(.has-background), .wp-block-button .wp-block-button__link:not(:hover):not(:active):not(.has-background), .wp-block-file a.wp-block-file__button:not(:hover):not(:active):not(.has-background) {
    background-color: var(--global--color-primary);
}
```

But it affected the X close button. So I decided to use the mc-text-button class. It does a little jumping, but I can always circle back to it at a later time.
