### ISSUE TITLE
Help wanted! 

### ISSUE THREAD

**Issue by LukasDanuser** [joedolson/my-calendar#540]
Hello, I want to use the My Calendar plugin for my website, however I can't seem to get the style working.

When selecting the colors, I got all black and gray, but it still displays blue.

I tried debugging with inspect elements, but couldn't seem to fix it.
What I saw is that the color blue is hard coded and the selected colors don't override it.

Color selection: https://prnt.sc/h38O9ABqlldH
Actual calendar: https://prnt.sc/kHRSSSTPc5l1

**Comment by joedolson** [comment]
Hi! Please make support requests at the WordPress support forums (https://wordpress.org/support/plugin/my-calendar/)

What you're seeing is the category color, as defined for the General category at My Calendar > Categories.
