### ISSUE TITLE
Use excerpt as event description in feed export

### ISSUE THREAD

**Issue by masonwolf** [joedolson/my-calendar#547]
When using the feed export, the event description is the exact description from the event, with all tags removed. This can lead to some strange formatting, since tags are displayed in the actual event page. A better solution would be to use the "excerpt" field for the event, if provided, as it's generally meant to be displayed without formatting.

**Comment by joedolson** [comment]
Closed in https://github.com/joedolson/my-calendar/commit/89c663fbe4dd1855d61633eec0deba72ad6f5f59
