### ISSUE TITLE
New control: Show all events.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#55]
Hey Joe

An example. I have used https://webnus.net/modern-events-calendar/
for a customer site.

I believe the site has various events in May, June and perhaps July. Let's say that there are 3-4 events a month.
Having a way to show all events independent of month would be helpful. A way to create an overview of all the events happening. I understand this can be done in List view. 

Maybe I should just close this issue. As I would like to see a general better design. Creating additional views on the frontend. To make the calendar feel more modern. I will likely get back to this at a later time.

**Comment by joedolson** [comment]
This can be done already using the upcoming events list, so I'm not sure how necessary this is.
