### ISSUE TITLE
Add card view

### ISSUE THREAD

**Issue by joedolson** [joedolson/my-calendar#551]
While I personally find card views next to useless, they're commonly requested. 

This should be a view of the main shortcode, but behave more like the upcoming events view, displaying a fixed number of events with navigation & filters available.

**Comment by paaljoachim** [comment]
Card views is just visual layout of how to separate events from each other. It can contain a nice visual.

**Comment by joedolson** [comment]
Reference: https://wordpress.org/support/topic/limit-number-of-events-shown-in-list-view-frustration/, https://wordpress.org/support/topic/feature-request-grid-view-of-individual-events/

**Comment by joedolson** [comment]
Card views are roughed in; need to make a decision about whether I'll adjust the pagination to have a fixed number of events per page. Would be a significant deviation from other views.

**Comment by joedolson** [comment]
Card views are supported in upcoming events widgets, and the widget now defaults to an exact number of events, so that helps with support ref 1. For #2, I think this is already possible, although the carousel interface would have to be set up by the user.

One thing I still want to add is pagination for the upcoming events list but a) that's proving to be really hard to do and b) is not really relevant to this issue, and should stop me from closing it.

Opening a new issue for that.

**Comment by joedolson** [comment]
Added feature to collapse recurring events in card view.
