### ISSUE TITLE
Update button not working on iPad

### ISSUE THREAD

**Issue by harmboschloo** [joedolson/my-calendar#558]
Thanks for the nice plugin. It has been really helpful.

**Describe the bug**
On an iPad when editing an existing event tapping the Update button does not work. Nothing happens when you tap the button, both at the top of the page and at the bottom of the page.

**To Reproduce**
1. On an iPad
2. Create an event and save it
3. Go to events and edit the existing event
4. Make a change and press the Update button

**Expected behavior**
The change in the event is saved.

**Actual behavior**
Nothing happens.

**Tablet**
 - iPad iOS
 - Tried in Safari and Chrome. Both didn't work.

**Comment by harmboschloo** [comment]
Seems to be working now for some reason... Sorry for the noise.

**Comment by joedolson** [comment]
Thanks for following up! I was wondering what this could possibly be, since there's really nothing unusual about that button...
