### ISSUE TITLE
There is no template tag for the Ticket URL field

### ISSUE THREAD

**Issue by harmboschloo** [joedolson/my-calendar#559]
Thanks for you nice plugin.

**Describe the bug**

When creating an event there is a Ticket URL field. But in the template editor there is no tag to select that field. At least I could not find it in the documented tags.

**Comment by joedolson** [comment]
It's `{event_tickets}` ; and it is [listed in the template tag docs](https://docs.joedolson.com/my-calendar/my-calendar-template-tag-index/). Is that the documentation you were looking at, or somewhere else?
