### ISSUE TITLE
Need more information: Process WordPress shortcodes in description fields

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#56]
I am looking at the Output Settings.

Regarding:
The option “Process WordPress shortcodes in description fields” refers to WordPress shortcodes like [my_calendar], not My Calendar’s own template tags like {title}. This enables you to insert forms, payment buttons, and similar items directly into your description fields and have them ren- dered appropriately.

The above should link to a section that mentions shortcodes.

**Comment by joedolson** [comment]
This *might* be an option I can remove. It was a performance problem at one point, but I rewrote the calendar display code a couple years ago, and largely eliminated that problem. It might need a little testing, however. But then things would pretty much work as expected.

If the shortcode was dependent on references to the $post global it wouldn't work right when rendered within the calendar, only on the single event view with pretty permalinks. Big question there is how much of a support burden that could create.

**Comment by joedolson** [comment]
Removed this option in https://github.com/joedolson/my-calendar/commit/5634d79f2354d9134fc6f13eae81ac109c57e6dc

I'm pretty confident that this is reasonable as a default now, given the number of changes I've made to how it's run.
