### ISSUE TITLE
List view: Calendar text is highlighted.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#57]
Hey Joe

I am wondering why all the text in List view is highlighted like so?

![Screen Shot 2021-05-30 at 14 00 50](https://user-images.githubusercontent.com/5323259/120103346-75ed5f80-c14f-11eb-88e3-a7cb82b5078f.png)

**Comment by joedolson** [comment]
Because Twenty Twenty One is overbearing about their styles, and the most recent stylesheet for My Calendar was released by the current default theme was. 

Will need to add an override for that.
