### ISSUE TITLE
The implemented Shortcode shows one Event everyday with the current date but this event is setup on one specific day 

### ISSUE THREAD

**Issue by slengemann** [joedolson/my-calendar#570]
Hello,

we are very happy with my calandar and we use it for Birthdays on our Intranet side to show others when colleagues have there Birthday. 

We have the problem that all events are in the future and not in the current month, attracted with today's date. If I set the date to the 30th of the current month, it will be displayed correctly. If I change the date to the 1st or 2nd of the following month, the entry is listed with today's date. Unfortunately, we are not getting anywhere here. It must be possible to display dates in the following months, or not?

Details to the events.
Every event is one day, allday long
for Example: 23. Januar 2023, 0:00 Yearly until 2033-08-17

We updated my calendar to the newest version last week but also the same problem. We chanded the shortcode 5 times also the still the same problem. We didn't reinstall the plugin only the update. 

Here the shortcode we use:

<strong>{date format="j. F"}</strong>{time} - {link_title}

**Screenshots**
WORKARROUND with Max Mustermann

![2023-09-19 08_45_56-Intranet](https://github.com/joedolson/my-calendar/assets/145427828/2f82dc1a-9ee8-4dd0-bf82-7a6ac4b106ef)

Thats the Problem what we have

![01_Intranet](https://github.com/joedolson/my-calendar/assets/145427828/e2bd0047-6b25-4d96-aa54-d870ea467390)

**Desktop (please complete the following information):**
 - OS: Win10/Win11
 - Browser Chrome/Firefox
 - Version newest

It would be awesome if you can help us with our issue.

**Comment by joedolson** [comment]
Can you tell me what the shortcode is that you're using?

**Comment by slengemann** [comment]
Hello,

thanks for your answer. We are using the following shortcode



Von: Joe Dolson ***@***.***>
Gesendet: Freitag, 22. September 2023 22:08
An: joedolson/my-calendar ***@***.***>
Cc: Lengemann, Stephan ***@***.***>; Author ***@***.***>
Betreff: [Externe Mail] Re: [joedolson/my-calendar] The implemented Shortcode shows one Event everyday with the current date but this event is setup on one specific day (Issue #570)


Can you tell me what the shortcode is that you're using?

**Comment by slengemann** [comment]
[my_calendar_upcoming category="1" before="3" after="2" type="event" order="desc" template="cef554e1f6937bb2be6a6d9a33beb736" weekends="false"]

I tried all options in the „Upcoming“ settings but nothing is working. It‘s shows only all events in the current month correctly. If the last event in the month is over all coming events in the next months will show with the date from the current day. It doesn’t matter how many days I set in the „after“ shortcode.

I hope I cold explain it that you understand what I mean.

BR,
Stephan

Von: Lengemann, Stephan
Gesendet: Samstag, 23. September 2023 17:17
An: 'joedolson/my-calendar' ***@***.***>
Betreff: AW: [Externe Mail] Re: [joedolson/my-calendar] The implemented Shortcode shows one Event everyday with the current date but this event is setup on one specific day (Issue #570)

Hello,

thanks for your answer. We are using the following shortcode



Von: Joe Dolson ***@***.******@***.***>>
Gesendet: Freitag, 22. September 2023 22:08
An: joedolson/my-calendar ***@***.******@***.***>>
Cc: Lengemann, Stephan ***@***.******@***.***>>; Author ***@***.******@***.***>>
Betreff: [Externe Mail] Re: [joedolson/my-calendar] The implemented Shortcode shows one Event everyday with the current date but this event is setup on one specific day (Issue #570)


Can you tell me what the shortcode is that you're using?

**Comment by joedolson** [comment]
Does the event have an end date set? The event you're describing (a birthday) should have a start date and an end date that are the same; what you're seeing could happen if the end date of the event is a different date from the start date.

**Comment by slengemann** [comment]
I tried everything what I can do in the calendar time options.

Setup Enddate at the same day and also on another day aswell. Not working.

Set date without „all day“ and took a time range from 8am. To 11pm. and set Enddate too. Not working

Hide Enddate in all constelations. Not working.

I don’t know what todo. I can only set 2 days in the future because I need a fake person for the last day in the current month so that I can display one real birthday person. If I took more birthdays then I have more birthday with the current day date.


Von: Joe Dolson ***@***.***>
Gesendet: Montag, 25. September 2023 04:28
An: joedolson/my-calendar ***@***.***>
Cc: Lengemann, Stephan ***@***.***>; Author ***@***.***>
Betreff: [Externe Mail] Re: [joedolson/my-calendar] The implemented Shortcode shows one Event everyday with the current date but this event is setup on one specific day (Issue #570)


Does the event have an end date set? The event you're describing (a birthday) should have a start date and an end date that are the same; what you're seeing could happen if the end date of the event is a different date from the start date.

**Comment by joedolson** [comment]
I just committed a change that might address this, although I'm not totally sure. I found some issues with counting events in the upcoming events widget, and cleaned that up a bit. However, the issue you're describing doesn't clearly match what I fixed.

My impression from what you're saying is that you have an event that's showing up with the wrong date, and I haven't been able to reproduce that.

**Comment by slengemann** [comment]
I don’t know. I deleted all birthdays  and created everything new to be sure that every event is correct but the same problem. My boss wants that I delete the app because everyone is thinking that we are stupid in the IT department but I really like the idea and your calendar plugin and don’t want to delete it. Maybe there is another solution to fix.


Von: Joe Dolson ***@***.***>
Gesendet: Mittwoch, 27. September 2023 01:19
An: joedolson/my-calendar ***@***.***>
Cc: Lengemann, Stephan ***@***.***>; Author ***@***.***>
Betreff: [Externe Mail] Re: [joedolson/my-calendar] The implemented Shortcode shows one Event everyday with the current date but this event is setup on one specific day (Issue #570)


I just committed a change that might address this, although I'm not totally sure. I found some issues with counting events in the upcoming events widget, and cleaned that up a bit. However, the issue you're describing doesn't clearly match what I fixed.

My impression from what you're saying is that you have an event that's showing up with the wrong date, and I haven't been able to reproduce that.

**Comment by joedolson** [comment]
Do you have a staging site or can you set up a clone of your site that you could give me access to? I think it would be helpful for me to try and explore what's going on, but I don't want access to your real site. If you can, send that info to plugins@joedolson.com

**Comment by slengemann** [comment]
I will try and will send it to you. I’m back in the Office next week and I will write you.

Von: Joe Dolson ***@***.***>
Gesendet: Donnerstag, 28. September 2023 11:46
An: joedolson/my-calendar ***@***.***>
Cc: Lengemann, Stephan ***@***.***>; Author ***@***.***>
Betreff: [Externe Mail] Re: [joedolson/my-calendar] The implemented Shortcode shows one Event everyday with the current date but this event is setup on one specific day (Issue #570)


Do you have a staging site or can you set up a clone of your site that you could give me access to? I think it would be helpful for me to try and explore what's going on, but I don't want access to your real site. If you can, send that info to ***@***.******@***.***>

**Comment by slengemann** [comment]
I fixed the problem on monday and I will give you this information for maybe other Germans they are having or get this problem. I changed the date format from „4. Oktober 2023“ to 10/04/2023 format. After this it works fine! Maybe your plugin cannot handle the Europe or German format. But thanks for your help the last days!

***@***.***


Von: Joe Dolson ***@***.***>
Gesendet: Donnerstag, 28. September 2023 11:46
An: joedolson/my-calendar ***@***.***>
Cc: Lengemann, Stephan ***@***.***>; Author ***@***.***>
Betreff: [Externe Mail] Re: [joedolson/my-calendar] The implemented Shortcode shows one Event everyday with the current date but this event is setup on one specific day (Issue #570)


Do you have a staging site or can you set up a clone of your site that you could give me access to? I think it would be helpful for me to try and explore what's going on, but I don't want access to your real site. If you can, send that info to ***@***.******@***.***>

**Comment by joedolson** [comment]
Thanks for following up! I have no idea how the date format could impact what's displayed here, but I'll keep my eyes open for this issue.
