### ISSUE TITLE
Suggestions to cleaning up the Input screen settings.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#58]
Hi Joe

Doing some brain storming.

I am wondering if the "Show in event manager" should be placed in a kind of vertical row with columns list.
+
Using less text in the "Event Scheduling Defaults" section.

"If a recurring event falls on a date that doesn't exist (like the 5th Wednesday in February), move it back one week."
= If a recurring event falls on a date that does not exist, move it back one week.

" If an event coincides with an event in the designated "Holiday" category, do not show the event."
Hmm this one is a bit tricky. It feels too detailed. Having a "Holiday Category" mentioned in the Categories page seems fine. The above option becomes too detailed. 

I believe it would be better to have an advanced customization page, to where less used option can be moved.

**Comment by joedolson** [comment]
An advanced settings page probably makes a lot of sense. It's also tempting to move some of these into pass-through filters - retain their existing values, but expose them through a filter. Especially these two settings, which don't actually do anything on their own; just set a default value in the event manager.
