### ISSUE TITLE
Search query is not clearing

### ISSUE THREAD

**Issue by sprngLf** [joedolson/my-calendar#581]
**Describe the bug**
Search query is not clearing, it is stuck to the first search query.

**To Reproduce**
1. Go to '/calendar' page
2. Input something into 'search input', click 'search events'
3. Replace the text in the 'search input', click 'search events' again
4. The search query is  still the same as the first search query, it is not replaced?

**Expected behavior**
4. The search query should be replaced with the latest input in the 'search input'

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Browser Chrome Version 121.0.6167.85 (Official Build) (64-bit)

**Additional context**
I think the problem is the GET request url when searching which is still stuck the first query string in the url,
maybe replace the GET request url or just use POST?

**Comment by joedolson** [comment]
Thanks for reporting! This is actually already fixed for the next release, see: https://github.com/joedolson/my-calendar/commit/a9aead58a56b782a114c9932d5383ea8dc0ee341
