### ISSUE TITLE
Design - Templates: Template Preview: Details shows image caption id info 

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#586]
I am using My Calendar v3.5.0-beta1.
Theme: Twenty Twenty Four is active.
Gutenberg, Akismet and Autoptimize are active on the site.
WordPress 6.5 beta1.

In the Design -> Templates section. In Template Preview: Details
I see this:

![Screenshot 2024-02-20 at 15 43 35](https://github.com/joedolson/my-calendar/assets/5323259/2f231be5-77c1-4b80-acf6-2b2eeb7dc66f)

I am not sure if it is meant to be that way or not but wanted to let you know about it.

**Comment by joedolson** [comment]
Because all of these templating previews are being replaced with PHP templates, I'm going to consider this a wontfix.
