### ISSUE TITLE
Creating custom templates and assigning these to overwrite a specific core template

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#587]
I am using My Calendar v3.5.0-beta1.
Theme: Twenty Twenty Four is active.
Gutenberg, Akismet and Autoptimize are active on the site.
WordPress 6.5 beta1.

Looking at template creation.

Clicking a Core Template.
Gives information about which template is clicked.
Then an option to: Use this template.

What I find strange here is that core templates are not Enabled by default. 

![Screenshot 2024-02-20 at 15 51 46](https://github.com/joedolson/my-calendar/assets/5323259/d857ffc0-6fba-4f2b-ab33-b183a11dd18f)

My thinking is then that core template should automatically be enabled to show the user which templates are currently in use. 

I also expect when clicking "Add Custom Template" 
![Screenshot 2024-02-20 at 15 55 44](https://github.com/joedolson/my-calendar/assets/5323259/f78efe19-7fe8-4d96-8aef-75fbc6db4beb)

That I should see the core template checkboxes above with their Template names. I should be able to click a checkbox to have the custom template overwrite the current default core template. Having the core template then become "Not Enabled" in the Core Templates list. Having the Custom Templates list show which core template it overwrites.

![Screenshot 2024-02-20 at 15 58 22](https://github.com/joedolson/my-calendar/assets/5323259/d4db19fb-dff4-43d8-ad78-363ea08b0eb0)

**Comment by joedolson** [comment]
Legacy core templates will never be enabled by default, because they don't support a lot of settings. This is all being replaced with the PHP templates, so I'm going to close this as #wontfix.
