### ISSUE TITLE
Moving Multisite mention in page 21 and 22 to later in the documentation?

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#59]
I am wondering if the Multisite information at page 21 Multisite Settings (Network Administrators only) and the mention of a widget page 22 should be moved into a later section of the documentation. 

I cut down on the information in the Google doc:
https://docs.google.com/document/d/1n0k2zRsggnLMMINrRJmq-XTprGHCoKhZsee-rWU5Vm4/edit#
Page 14-15.

**Comment by joedolson** [comment]
As far as I'm concerned, the goal here is complete restructuring of documentation, and since we're moving to a website, I think this is basically irrelevant at this point.
