### ISSUE TITLE
Bug or Feature?   Use of Event_added instead of event start in rss/ics feed

### ISSUE THREAD

**Issue by drjoeward** [joedolson/my-calendar#594]
Is there a reason the RSS/ICS feed is set up to only pull the date range based on event_added instead of the actual start of the event.

my organization schedules events several years in advance.   yet by default only the items added in the last 2 days will show in the ICS feed.  that is great if someone adds it when we are creating the events in the feed, but they will not appear if someone adds the feed the week after.

> Line 492 of my-calendar-events.php
		AND event_added > NOW() - INTERVAL $limit DAY 
		$exclude_categories
		ORDER BY event_added DESC"

**Comment by joedolson** [comment]
There are two separate iCal sources: one is a subscription feed, and that just shows recently added events. The other is an export, and exports whatever events are in the current view. 

I should probably expand that beyond the most recently couple of days, but the purpose is to be able to get information about recently added events.

**Comment by joedolson** [comment]
Closing this, as functionally it's necessary that the subscription link gets recent events; otherwise it would never update.
