### ISSUE TITLE
Google Calendar  single 1 day events show up as two days

### ISSUE THREAD

**Issue by drjoeward** [joedolson/my-calendar#595]
All of our single all day events are showing up as 2 day events.   i think it has to do with the code around line 745 in my-calendar-templates.php   there is 60 minutes being added to the end of the dtend and recur_end that is causing the the date to extend by 1 day.  if i take the + 60 out hte issue goes away.

**Comment by joedolson** [comment]
So, the entire iCal generation library has been replaced in My Calendar 3.5, so this will need to be tested in the pre-release version to see whether it's still an issue. That library change isn't in the 2nd beta, released last week, but I'm tagging the 3rd beta tomorrow.
