### ISSUE TITLE
Multiple calendars

### ISSUE THREAD

**Issue by mrscatlover** [joedolson/my-calendar#604]
Couldn't find a way to create more than one calendar (different calendars with different events on each).  Is it possible or is it only available at premium?

**Comment by joedolson** [comment]
You can create shortcodes at My Calendar > Shortcodes, and those shortcodes can be used to limit by category, location, search terms, authors, or hosts. You can then paste the new shortcode into any page to display a calendar with different events.

**Comment by mrscatlover** [comment]
Thank you! It worked like a charm.

**Comment by joedolson** [comment]
Thanks for following up!
