### ISSUE TITLE
Permissions: Some confusion as to what some of the options do.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#61]
I am wondering if some of these options should be removed?

<img width="283" alt="Screen Shot 2021-06-27 at 10 40 56" src="https://user-images.githubusercontent.com/5323259/123538237-31e08100-d734-11eb-8ff7-ab9ece7692ac.png">

For instance at this stage I do not know what "Edit Behaviors" is. "View Help" I also found confusing. Also after reading the description of View Help in page 24 I still found it confusing. 

**View Help:** User can see the Help screen and the My Calendar sidebars. Note: only administrators can submit the
support form, regardless of ability to view the Help screen. 

From looking through the various options I expect to see a kind of consistency (also order?) with the WP sidebar My Calendar links. So Permissions and the My Calendar links correspond with each other.

<img width="158" alt="Screen Shot 2021-06-27 at 10 47 39" src="https://user-images.githubusercontent.com/5323259/123538428-280b4d80-d735-11eb-810a-1a6074a9c0a4.png">

**Comment by joedolson** [comment]
This is a problem with changing labels. The menu item 'Script Manager' used to be 'Behavior Manager', and the permission corresponds to that. However, changing a menu item is easy; changing a permission breaks past permissions, so they're harder to change. I can make an exception and filter the name of that permission. It'll make it easier for people to understand these directly, but it'll still be a problem for code referencees

**Comment by joedolson** [comment]
Not sure what the confusion is about 'View Help', though. Can you clarify that?

**Comment by paaljoachim** [comment]
I just found it strange to have "View Help" in the Permission screen. I did not fully understand why it is listed there.

**Comment by joedolson** [comment]
The main reason 'View Help' is a permission is that it's also the means to 'white label' the plug-in for your users. With the sidebar gone, all of my branding, donation links, sales links, etc. also go away. 

But the re-ordering and re-labeling of permissions is doable.

**Comment by joedolson** [comment]
Closed with https://github.com/joedolson/my-calendar/commit/15ff00ef9734cf401d15c65da630d39bc0d515b8
