### ISSUE TITLE
My Events pagination not working

### ISSUE THREAD

**Issue by ejrobinson-uw** [joedolson/my-calendar#615]
**Describe the bug**
_A clear and concise description of what the bug is._
The dashboard My Event list view does not display the paginator.  The removal of 'SQL_CALC_FOUND_ROWS' in update v3.5.13 has caused the 'SELECT FOUND_ROWS();' query in my-calendar-event-manager.php, line 718 to return an incorrect value resulting in the $num_pages calculation to be incorrect, ultimately preventing the paginator from displaying on the My Events dashboard page.

**To Reproduce**
_Steps to reproduce the behavior:_
1. Create a number of events exceeding the events per page value in your screen options
2. Go to '/wp-admin/admin.php?page=my-calendar-manage&view=list'
3. See lack of paginator in upper-right

**Expected behavior**
_A clear and concise description of what you expected to happen._
The paginator to display when there is a number of events exceeding the events per page value.

**Desktop (please complete the following information):**
 - OS: Windows 11 Education 23H2
 - Browser: Chrome
 - Version: 128.0.6613.138

**Additional context**
_Add any other context about the problem here._
Adding '&paged=2' to url will produce paginator up to page 2, but not beyond.  It will properly display the paginator up to the page given in the url.

**Comment by joedolson** [comment]
Thanks for reporting this clearly. I had gotten a couple of other reports that I now realize were this problem, but were so unclear that I had not yet figured out what I was looking for...
