### ISSUE TITLE
Part 3: Display options - adjustments -

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#62]
**I am adding this issue here in addition to rewriting it in the Google doc because I believe this is an important subject to bring up.**

3. DISPLAY OPTIONS: SHOWING MY CALENDAR EVENTS.
(Page 26)

My Calendar has two primary methods for displaying events: Widgets and Shortcodes. Widgets are a convenient drag-and-drop method to add information to many themes' sidebars and footer areas. Using widgets, you can display a version of the calendar formatted for small spaces (the “mini” calendar), a list of upcoming events, a list of events happening today, or a specific single event.
“Shortcodes” are small pieces of code intended to be placed in posts or pages (or custom post types). Using shortcodes, you can add either a standard grid-format calendar or a list-formatted calendar, showing the events for the month, the week, or the day. You can also add any of the widgets through shortcodes, as well as a tool to filter your events by location, a tool to filter events by category, and a list of locations used.

-----------------

(How I see it)
My Calendar has two primary methods for displaying events. Using the main output to show events and using Shortcodes to customize how these events are seen. (I would perhaps call Widgets a secondary method.)
OR
There are two primary methods for displaying events: Shortcodes to customize how the events look like on the frontend in the main calendar and widgets usually seen in the sidebar or footer.
Or
There are two primary places for displaying events: In the main calendar and in widget areas such as sidebars and footers. Both of these methods can be customized with using shortcodes that can adjust which parts of the calendar that should be seen on the frontend.

**Comment by paaljoachim** [comment]
Since shortcodes are so important for customizing how the events are displayed on the frontend. I also expect a Shortcodes screen here. Perhaps under the Style Editor link.

<img width="158" alt="Screen Shot 2021-06-27 at 10 47 39" src="https://user-images.githubusercontent.com/5323259/123540727-c355f000-d740-11eb-8e41-b0fdcd184800.png">

**Comment by joedolson** [comment]
I'm not sure what's actionable on this issue; are you looking for any specific comments?

**Comment by paaljoachim** [comment]
I will look into it again, and let you know.

**Comment by paaljoachim** [comment]
Closing this issue.... It looks like there is no action to take here at the moment.
