### ISSUE TITLE
Shortcodes Generator screen: Removing Main, Upcoming and Today tabs and adding in boxes to show generated shortcodes.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#63]
I noticed that under Help there is a Shortcodes Generator screen.

<img width="738" alt="Screen Shot 2021-06-27 at 12 46 53" src="https://user-images.githubusercontent.com/5323259/123541657-e8992d00-d745-11eb-8f0e-979fe5cd5c5f.png">

Change: "My Calendar Shortcode Generator" -> "Shortcode Generator"

Clicking the tabs: Main, Upcoming and Today shows almost identical screens.
What about just having a shortcode option to where one selects Main, Upcoming or Today? (Removing the need for 3 tabs.) Then moves on down the list to select other options.

I will very likely have a lot more to say about this screen soon.

**Comment by paaljoachim** [comment]
I went ahead and made a video.

Here are the main points:
Remove the Main, Upcoming and Today tabs. Instead add in options where the user can select Main, Upcoming or Today.
The user continues through the list and at the end clicks the "Generate Shortcode" button.
The code generated could be seen in boxes below helping the user become aware of what the shortcodes look like as well as making it possible to copying the code into any page or widget area.

Example on boxes below the Shortcode Generator.
Showing shortcodes generated for Main, Upcoming or Today.

Main:
Shortcodes generated: - Code -

If user selects Upcoming then it could say.
Upcoming:
Shortcodes generated: - Code -

If user selects Today then it could say.
Today:
Shortcodes generated:  - Code -

One could end up with three boxes showing shortcodes for Main, Upcoming and Today.

Below each of the Shortcodes boxes could be a "Copy" button to copy the code as well as an "Edit" button where clicking edit would bring up the shortcodes in the shortcodes generator screen. One could adjust the shortcode and click "Generate Shortcode" button again to generate new code for Main, Upcoming or Today.

Here is the video:
https://youtu.be/FzVZLNxAup0

**Comment by paaljoachim** [comment]
In section 3b of the documentation. Page 30 - 35 shows a lot of shortcodes one can use.

There should be a section called Shortcodes in the Shortcodes Generator section. Where one can get an overview of the various shortcodes one can use.

This means:

- Shortcode Generator section -
- A section for Shortcode generated code. Code can be clicked into and modified.
- A section for shortcodes one can use.

I quickly went into Affinity Photo and mocked up this. To give a better overview of the Shortcode Generator, generated shortcodes, as well as an attribute list below. One can then go in and edit a shortcode in the Main, Upcoming or Today generated shortcode boxes. Copy the code and use it where it is needed. This ties in the various options in the shortcode system. It can also free up documentation pages having the attributes listed directly in this screen.

![My-Calendar-Shortcode-Generator-with-additional-screens](https://user-images.githubusercontent.com/5323259/123545665-76cade80-d759-11eb-8c8f-6330b2e27f6d.jpg)

**Comment by joedolson** [comment]
This is really two separate issues; the shortcodes info is here: http://docs.joedolson.com/my-calendar/2018/03/04/quick-start-guide/; it used to be in the plug-in, but I moved it out a few years ago.  I'd rather keep any significant documentation out of the plug-in, as it creates problems in getting translations finished. Since I have no means to actually get translations done, I want to avoid putting up barriers to their completion.

**Comment by paaljoachim** [comment]
> I'd rather keep any significant documentation out of the plug-in, as it creates problems in getting translations finished. 

Gotcha. I will focus on bringing the shortcodes back into the documentation, as it does contain a lot of text.
We could instead add a link in the Shortcode Generator screen saying something like: "Learn more about shortcodes used in My Calendar." People can click the link and it goes to an online Shortcodes documentation page.

**Comment by joedolson** [comment]
The goal is to move all of the documentation to a publicly accessible online manual, FYI.

**Comment by paaljoachim** [comment]
Updating this issue to focus on removing the tabs for Main, Today and Upcoming and instead adding in generated shortcode boxes below the Shortcode Generator. Updated the above title and comment.

**Comment by joedolson** [comment]
I've done as much on this as I intend to.

**Comment by paaljoachim** [comment]
Hey Joe. 
Can you let me know what you did. It is not fully clear for me as I check the code adjustments.
I would like to test it out. Thanks.

**Comment by joedolson** [comment]
Adding the copy to clipboard is the thing that impacts this issues. I don't intend to otherwise revamp the UI as described above.
