### ISSUE TITLE
Shortcodes Generator screen: Going through options.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#64]
I am going through the options in the Shortcodes Generator screen.

The option: "Location filter value:" is not well enough explained here:

"A location to filter to (two fields: a type of location field, and a value)"

**Categories (select to include):** Which Categories to display.
**Location filter type:** A location to filter to.
**Location filter value:** ?
**Limit by Author:** What author to limit by.
**Limit by Host:** What host to limit by.
**Format:** Grid or List
**Time Segment:** Month, Next Month, Week, Day. (NB. This says different in the original doc.)

Navigation above and below the calendar: your settings if this is left blank. Use none to hide all navigation.

**Navigation above calendar:** (EDIT) See the following options below.
**Navigation below calendar:** (EDIT) See the following options below.
**Months to show in list view:** Select the number of months to show. 
**Search keyword:** ? It says "Search term to list calendar results by." Not sure how that works.

The navigation part I find tricky. As it also ties in the Output settings option for the Nav.
It is not clear for me what one should add into the Navigation options.

Btw The Navigation options should perhaps be on the bottom of the Shortcode Generator screen. 

---> I am modifying the documentation.

**Comment by paaljoachim** [comment]
Btw this information is listed below:

### What shows up with “above” and “below” navigation?

The eight values available for these two attributes are key parts of My Calendar. 
nav – previous/next events navigation links.
toggle – toggle format between list and grid
jump – select box to jump quickly between different months and years
print – link to print version of the current view
timeframe – toggle between different time frames: month, week, day
key – show category key
feeds – show links to iCal formatted subscription links with the most recently added events.
exports – show links to RSS and iCal formatted calendar output with the events from the current view.
Which values you include in the attribute and the order they appear in will determine what shows up where above or below your calendar.
You can use “none” to remove all navigation. If you omit the above or below attributes entirely, My Calendar will show your defaults (as configured on the settings page.)

I am not sure the above has anything to do with the Shortcode Generator. As it does not clearly associate with the shortcodes.

**Comment by joedolson** [comment]
Clarification: Location filter type is the type of data to filter, e.g. State, City, Country, Region, etc. Location filter value is the value to filter to - e.g., Minnesota, Saint Paul, United States, Cherokee Heights.

Navigation has always been tricky. Practically speaking, it could use a better input mode; but I haven't had time for that. 

Search keyword is if you want to produce a calendar from search results. E.g., all events containing the term 'Festival'.

**Comment by paaljoachim** [comment]
> Navigation has always been tricky. Practically speaking, it could use a better input mode; but I haven't had time for that.

Thanks for the feedback! Should we focus this issue on improving the input mode for Navigation?

**Comment by joedolson** [comment]
At this point, the shortcode generator has been significantly tweaked.

Improving the input mode for navigation elements would be valuable, but I don't think it'll happen in this release.
