### ISSUE TITLE
Update widgets for WP 5.8 to show properly in the new Widgets screen.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#65]
I am running a local test site with WP 5.8 beta.
Twenty Twenty One
Deactivated Gutenberg plugin.

Going into the Appearance - Widget screen (the new widget screen) I notice the widgets look a little different now compared to earlier.

Here is an example with using the Mini Calendar.

![Widget-Mini-Calendar](https://user-images.githubusercontent.com/5323259/123547947-1b9de980-d763-11eb-8427-e019592c17c5.jpg)

There are a few things to fix for each Widget as some options are squashed and need more space.

**Comment by joedolson** [comment]
This is pretty annoying, honestly. I shouldn't have to add CSS to support basic UI components in the widget editor. It looks like core just doesn't implement styles for some basic elements.

**Comment by paaljoachim** [comment]
Should this be a Trac ticket instead?
Perhaps it would be helpful to just mention this issue in the feature-widgets-block-editor Slack channel?

**Comment by joedolson** [comment]
Yeah, I really do think this is a core issue. A plug-in shouldn't have to enqueue extra CSS just to have standard input elements match the core design; that just doesn't make any sense.

**Comment by paaljoachim** [comment]
Alrighty. I am sharing this issue in the widgets channel in Slack.

**Comment by joedolson** [comment]
So, this is fine in trunk for me (running from SVN). May have already been dealt with.

**Comment by joedolson** [comment]
The paragraph element isn't handled, but I'm OK with that; it's not a standard form element, so that's more reasonable.

**Comment by paaljoachim** [comment]
It sounds like we can check in again with this issue after 5.8 has been released.

**Comment by joedolson** [comment]
Yeah, I'll let it go for now.

**Comment by joedolson** [comment]
Nothing has changed as of RC4 as far as styling goes, so I'm guessing paragraph styles won't be handled in core.

**Comment by paaljoachim** [comment]
Rechecking with 5.8 RC4.

This is what I am seeing:

![Screen Shot 2021-07-16 at 13 54 38](https://user-images.githubusercontent.com/5323259/125943651-0de143ae-ee82-4634-9185-37bcf787ac10.jpg)

Location and Mini-Calendar Timespan is showing up nicer now then what it did earlier.

Should we close this issue? Or is there something else that needs to be followed up on here?
