### ISSUE TITLE
Bug: Not able to add location.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#66]
Hey Joe

This might be a simple thing but I am noticing that in my WP 5.8 beta site that clicking Location and add new location goes to a page that says "Sorry, you are not allowed to access this page."
It does not give me permission to add a location....

https://user-images.githubusercontent.com/5323259/123548784-88ff4980-d766-11eb-93a3-d7196b618509.mp4

**Comment by paaljoachim** [comment]
Actually the same error happened on a 5.7.2 test site as well.

**Comment by joedolson** [comment]
Are you still running the same version of My Calendar I sent you a month ago? If so, this is a fixed issue. https://github.com/joedolson/my-calendar/commit/a67dbc3989e6e48ca88bd9ea31c25334abb023ed

**Comment by paaljoachim** [comment]
That I am. I just now downloaded the zip from this repo and tried to install the plugin, but I am not getting that to work....

**Comment by joedolson** [comment]
You can't install that zip directly; you only need the contents of the 'src' directory, and the repo's zip is the whole repo.

**Comment by paaljoachim** [comment]
That worked! I am seeing the Add New Location and Location links.
