### ISSUE TITLE
Cleaning up the Add Events page.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#69]
The various areas in the Add Event page.

Main event.
Date and Time.
Repetition Pattern.
Short Description (could use some more information on how this is used.)

Add an image
Host
Event Link

<img width="615" alt="Screen Shot 2021-06-27 at 17 18 24" src="https://user-images.githubusercontent.com/5323259/123550067-02e60180-d76c-11eb-8839-b960736b124b.png">

An alternative mockup.

![Add-an-image-etc-Add-Event-area](https://user-images.githubusercontent.com/5323259/123550441-be5b6580-d76d-11eb-8bb2-7ead7ce27df6.jpg)

**Comment by joedolson** [comment]
I should probably just change the label on 'Short Description' to 'Excerpt', which I think would be clearer in the WordPress ecosystem. I can't make any broad statements on how it's used, really, since I don't have any way to know that.

**Comment by paaljoachim** [comment]
I went ahead and added an issue specifically for the "Add an image" option here: https://github.com/joedolson/my-calendar/issues/77 (In relation to it lacking a description.)

With the above mockup I adjusted the design (to create a more symmetrical layout), removed the description for Event link and instead added "External Event Link" text. I can of course make individual issues for each change if needed.
