### ISSUE TITLE
Move the Shortcodes Generator screen to become a stand alone WP menu item under My Calendar menu.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#72]
Today the Shortcodes Generator screen is located under Help.
My Calendar > Help > Shortcode Generator 
I find that a strange place to have the Shortcodes screen.

I believe the Shortcode Generator is such an important screen that it should have its own location.
My Calendar > Shortcodes 

Like so:
![WP-menu-My-Calendar-adding-in-Shortcodes-screen](https://user-images.githubusercontent.com/5323259/123558642-ab5d8b00-d797-11eb-8279-0ee831312e30.jpg)

**Comment by joedolson** [comment]
This was fixed in https://github.com/joedolson/my-calendar/commit/30f9a6557ba30660251758c6b2580d3326441e5d.

Closing.
