### ISSUE TITLE
Cleaning up the WP menu under My Calendar.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#73]
![My-Calendar-WP-menu](https://user-images.githubusercontent.com/5323259/123558764-47879200-d798-11eb-8904-72c836dd68cf.jpg)

Clicking **My Calendar** goes to the Add Event page.
Below we have the **Events** page.

(Skipping Event Groups for now.)

**Locations**
**Add New Location**

Going by the above logic for Locations and Add New Location we should rename My Calendar to Add New Event, so it becomes like so:

Events
Add New Event
Event Groups
Locations 
Add New Location

**Categories** (Contains the Category Editor to add a new category and it also contains a Category List that shows the categories. All on the same page.)

We then have:
**Style Editor
Script Manager
Template Editor
Settings
Help.**

Version 1.
 
![WP-menu-My-Calendar-ver2](https://user-images.githubusercontent.com/5323259/123558992-bfa28780-d799-11eb-810d-9b9381d28c24.jpg)

Version 2.

Now if we remove the "Add new" Events and Locations from this list and instead let the user go to Events and Locations to add new. (I also added the Shortcodes screen. Event Groups are still in the list.) We get this:

![WP-menu-My-Calendar-ver3](https://user-images.githubusercontent.com/5323259/123559160-9df5d000-d79a-11eb-812b-213c60b289bb.jpg)

**Comment by paaljoachim** [comment]
I just downloaded the newest version a few moments ago. I then noticed this WP menu:

<img width="158" alt="Screen Shot 2021-06-28 at 10 34 27" src="https://user-images.githubusercontent.com/5323259/123605808-864f3380-d7fc-11eb-9296-f02bb1f943f2.png">

Which is pretty similar to my version 1 above.

**Comment by joedolson** [comment]
Yes, I'd actually made a couple of those changes before you opened this issue. I'm in agreement with adding a Shortcodes menu item - I get more support requests about how to build a shortcode than I really need to. 

So this is on its way.

**Comment by joedolson** [comment]
Moved shortcodes to dedicated screen in https://github.com/joedolson/my-calendar/commit/30f9a6557ba30660251758c6b2580d3326441e5d

Closing.

**Comment by paaljoachim** [comment]
Great! That will be very helpful!
