### ISSUE TITLE
Repetition drop down: Remove extra explanation descriptions.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#75]
In the Repetition drop down there are two explanations.

Monthly by date (the 24th of each month)
Monthly by day (the 3rd Monday of each month)

![Screen Shot 2021-06-28 at 13 38 59](https://user-images.githubusercontent.com/5323259/123630789-3d0bdd80-d816-11eb-9c63-9599a9b575c8.png)

I believe it would be better to remove the added explanations.
Keeping the drop down cleaner. Like so:

![Repetition-pattern-drop-down](https://user-images.githubusercontent.com/5323259/123630966-76dce400-d816-11eb-9be2-0b5d50ed12a6.jpg)

**Comment by joedolson** [comment]
It may be cleaner, but does it make sense to a user? I added those explanations to defer support requests. I would get regular support requests asking what the difference between 'Monthly by date' and 'Monthly by day' was, so I added this to provide clarification. 

I'm open to other suggestions on the text in the dropdown, but I think it needs more than just the bare descriptor.

**Comment by paaljoachim** [comment]
Good point!
I think we will just leave it as it is for now. Closing this issue.
