### ISSUE TITLE
Add an image option: Lacks description on how it can be used.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#77]
Event Details section

![Event-Details-section](https://user-images.githubusercontent.com/5323259/123813427-2daf9180-d8f5-11eb-9e84-7551a3b7239a.jpg)

Focus here is on the "Add an image" (featured image?)
It is not clear how this will be used.
One can compare "Add an image" to adding an image directly into the Event content TinyMCE area.

I am not clearly seeing the difference between the two. Perhaps there is a setting to show a thumbnail version of the "featured image" directly in the calendar, and a setting to choose to show the "featured image" on the event page. 
I am thinking similar to how featured images can work with WP posts today. As one might see the featured image in the blog page, and not see the featured image on the post page. Or perhaps see the featured image in the top behind the title. Many options are possible. 

Circling back to My Calendar. 
"Add an image" is similar to featured image in the WP posts system.
What are the uses for this option? How can it be used?
What information should be added into a description for this option?

Thanks!

**Comment by joedolson** [comment]
It seems like it would make sense to just change the label to 'Featured Image', since that is how it's used. (Literally: the image is stored as the post featured image.) It can be used like a featured image; it has a programmatic relationship to the event and can be used anywhere the event appears, depending on the template.

**Comment by paaljoachim** [comment]
Ahhh yes! This is a lot cleaner!

![Screen Shot 2021-07-16 at 13 42 38](https://user-images.githubusercontent.com/5323259/125942396-110e22be-fa90-49a4-b9b7-7f94725df13c.png)
