### ISSUE TITLE
Manage Events screen: Title margins

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#79]
I just downloaded and tested the updated version. It feels cleaner to have Manage Events with My Events and Event Groups in the same screen.

I am wondering if the title Manage Events is to crammed into the corner surrounded by the Add New button and the My Events and Event Groups tabs.

![Screen Shot 2021-06-29 at 23 42 53](https://user-images.githubusercontent.com/5323259/123871449-0a580700-d934-11eb-9961-bd78ed9f5e87.png)

Making some comparisons.

Adding a margin right of 20px to the Locations tab.
![Locations-tab-adding-additional-margin-right](https://user-images.githubusercontent.com/5323259/123871812-7b97ba00-d934-11eb-939a-e48f42179d8a.jpg)

Adding margin bottom of 20px to the My Calendar Settings title to give margin space before we see the tabs.
![My-Calendar-Settings-title-margin-bottom-20px](https://user-images.githubusercontent.com/5323259/123872041-c87b9080-d934-11eb-9848-d71b8a8735d5.jpg)

Adding margin to the Manage Events title.
Margin right and bottom 20px.

![Manage-Events-title-margin-right-bottom](https://user-images.githubusercontent.com/5323259/123872216-12647680-d935-11eb-84a5-e4352a5c1074.jpg)

I believe the last screen that could perhaps also have the 20px right would be the Template Editor title.

Just something to be aware of.

**Comment by joedolson** [comment]
The right margin between title & Add New is a core standard, so I don't think I'll change that (see Posts, Pages, etc; it's in that location everywhere.)

Bottom margin makes sense.

**Comment by paaljoachim** [comment]
Yes this look better:

![Screen Shot 2021-07-16 at 13 40 45](https://user-images.githubusercontent.com/5323259/125942197-ddeb9456-8ee5-4a16-b24f-78a6b230beca.png)
