### ISSUE TITLE
Research issue: Thoughts on adding on another provider of maps.

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#80]
I am adding an issue for alternative Google maps providers.

Because of how Google maps have changed to a payment system after a certain amount of usage (I believe it is high) I am thinking it might be good to also check into other map providers.

https://supsystic.com/feature/best-google-maps-alternative/

https://elfsight.com/blog/2020/02/best-alternatives-to-google-maps-api/

https://valorouswebdesign.com/an-alternative-to-google-maps-embedding-an-open-street-map-on-your-website/

https://wordpress.org/plugins/stonehenge-em-osm/

**Comment by joedolson** [comment]
For the dynamic maps API, it works out to about 28.000 requests per month that will be free. It's true that most customers will never exceed that. 

It's always possible to plug-in other providers via plug-in; the templating is filtered, so anybody could do that. Might be something to consider in Pro, but not for the free plug-in.

**Comment by paaljoachim** [comment]
Additional note.

In the "Add New Location" page there is a link: "Add a Google Maps API Key to generate a location map". The link leads to Settings -> Output. User fills in the Google Maps API Key. 

I am wondering if the text: Google Maps API Key should be a link to: https://developers.google.com/maps/documentation/javascript/get-api-key

**Comment by joedolson** [comment]
Can't use a label as a link; it breaks UI by having two different behaviors attached to one string. (Clicking is both a link action and a checkbox action).

But moving the Google Maps API key into a separate setting probably makes sense, where it would be easier to provide it with an aria-describedby field.

**Comment by paaljoachim** [comment]
Ahh yes this is better!
![Screenshot 2021-09-27 at 00 02 12](https://user-images.githubusercontent.com/5323259/134825650-4716c30c-4c7b-4ba6-baf8-39a92621fcab.jpg)
