### ISSUE TITLE
Going through Output fields -> Single Event Details

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#83]
Today the calendar has these output options:

<img width="842" alt="Screen Shot 2021-07-03 at 15 45 26" src="https://user-images.githubusercontent.com/5323259/124356328-b68c3d00-dc15-11eb-9bca-293d64a16eaf.png">

Reordering:

![Single-Event-Details-reordering](https://user-images.githubusercontent.com/5323259/125165922-5fe4ad00-e199-11eb-8681-b55460e7ae39.jpg)

Frontend with notes:
![My-Calendar-Frontend-with-notes](https://user-images.githubusercontent.com/5323259/124360110-38856180-dc28-11eb-8e26-16422c45ef67.jpg)

Restructuring (I am not sure if I have enough explored to get these correctly.)
Move to Grid options below Single Event Details.

In Pop-up card view:
- Excerpt
- Full description
- More details link

**Comment by paaljoachim** [comment]
I am looking at reordering the Output Fields based on where these are located on the frontend.
Btw I am seeing somewhat similar names as it used in the Input Fields. With some differences..... Focusing now on order.
Do believe it would be nice to keep the same naming as is done for the Input fields to create a better consistency between Input and Output fields.

![Screenshot 2021-09-14 at 11 05 45](https://user-images.githubusercontent.com/5323259/133229264-746541e0-fb53-4c7c-8dab-af3f442d3308.jpg)

Image (rename to Featured Image)
Full description (rename to Description)
Event Address (rename to Location)
Excerpt
External link (The More information is actually "External link" which can be confused with "More details link.") 
Registration info (rename to Registration Settings)
Author
Host

Link to single event iCal download
Link to submit event to Google Calendar
Link to Google Map
Google Map (single view only)
Google Maps API Key

More details link (not sure about this name... As it is the Read more seen last in the card.)

**Comment by joedolson** [comment]
I think part of this is already done. The separation this proposes about splitting out a section that's "Card details/pop-up" vs. single event details page is something I don't really get, however. The layout options are used for both views, so there isn't really a distinction to be made here.
