### ISSUE TITLE
Rethinking the Re-order calendar layout

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#84]
I believe that we can really make some nice improvements to the Output screen.

Current Re-order calendar layout.

<img width="973" alt="Screen Shot 2021-07-10 at 20 07 49" src="https://user-images.githubusercontent.com/5323259/125172668-3dfc2200-e1bb-11eb-83a0-b8c84b9ee9b5.png">

I am looking at a UI/UX that might fit in.

Adding a Show/Hide button directly to each row. Having the row white which is seen, and greyed out the ones that are hidden. I used the current white background "The calendar" row as an example of a row that is seen. All other rows are hidden.

![Re-order-calendar-layout-new](https://user-images.githubusercontent.com/5323259/125172965-ce873200-e1bc-11eb-90f7-80f038dce244.jpg)

It makes it more obvious which rows are hidden and which are visible. 

What are good natural steps to renew the UI/UX of this section?
(Can we also followup on the Single Event Details? I added another [issue for the Single Event Details section](https://github.com/joedolson/my-calendar/issues/85).)

**Comment by joedolson** [comment]
From a UX standpoint, I'd want the Show/Hide toggle to be collected with the buttons on the left, rather than isolated on the right, but otherwise, this is a totally reasonable option.

**Comment by paaljoachim** [comment]
So perhaps something like this?

![Re-order-calendar-layout-show-hide-ver2](https://user-images.githubusercontent.com/5323259/125211809-5ba7b500-e2a9-11eb-870c-f4cb538d4327.jpg)

**Comment by joedolson** [comment]
Yes, exactly.

**Comment by paaljoachim** [comment]
Ahhh! I focused on using a word but using an eye icon toggle is even better. 

![Screen Shot 2021-07-16 at 13 13 30](https://user-images.githubusercontent.com/5323259/125939354-3ad996d9-420d-46a2-98a7-2fc5e3ef3a4a.png)

It looks really good! Now I know that it is alright to also use icons instead of a word..:)
