### ISSUE TITLE
Input: Calendar Input Fields

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#86]
I unchecked multiple fields and expected to not see these options when adding a new event.

![Screen Shot 2021-07-10 at 20 40 32](https://user-images.githubusercontent.com/5323259/125173369-3cccf400-e1bf-11eb-8f9a-880661e30abf.jpg)

Unchecked Location Dropdown Menu, Excerpt, Description and Category.

Did a hard refresh.

Went to create a new event (Add Event). Even as an administrator I expected to have turned off the above options.
But these were still all seen. Well Description I could not find when it was on or off.

**Comment by joedolson** [comment]
Those are the global settings; if your screen options are set differently, they'll override the global settings. What are the screen options configured for on the event manager screen?

**Comment by paaljoachim** [comment]
Ahhh. I went to add Event. Clicked the Screen Options and noticed that all of the "Event editing fields to show" are checked.

![Screen Shot 2021-07-12 at 00 17 09](https://user-images.githubusercontent.com/5323259/125211434-99570e80-e2a6-11eb-879a-a762dad00769.png)

From my understanding the Input fields are only related to the fields one might see when adding a new event.
So if all the options are automatically checked in the Screen Options tab of a new event. Then adjusting the Input fields will make no difference. Perhaps we need to remove the Screen Options so that these are not in the way when adjusting the fields in the Input screen?

**Comment by joedolson** [comment]
The behavior is different for an admin than for lower level users, so those settings are really about restricting the fields that other editors will see. So it does make a difference, just not necessarily for the current user.

It may make it clearer to label the section to be about editing the default input fields, with less implication that they'll have an immediate impact on the current user.

There's also some complicated logic to how the screen options interact with the default settings; I might need to review those and make sure they work appropriately. What I would expect is that all users would immediately inherit the default settings, and administrators would be able to turn on additional settings if they choose.

**Comment by paaljoachim** [comment]
I am circling back as I happen to come across this again yesterday.
A summary...
There is a Settings -> Input -> Show in event manager specific fields one can turn on and off. 
Even though turning these off the fields that are turned off will still be seen when creating an event.

Where it is currently at.
Making a change to the Input Fields in the calendar one also needs to go to a new Event and open the Screen Options. and click Apply to make the adjustment. --> This is information that we need to add to the Input setting screen.

Perhaps something like this (there is a bit much text).
![Input-Settings-Event-manager-fields-additional-info](https://user-images.githubusercontent.com/5323259/132816466-76b1cdcc-e046-4dec-a3a8-6582dc4ae19c.jpg)

A better way would be to perhaps have a ! instead of a ? inside a circle to give a signal that additional action is needed for the settings to actually be implemented. User hovers over the ! (inside a red circle) and sees the tooltip information.

**Comment by joedolson** [comment]
I'm wondering if I should completely re-map this feature so that it's more related to permissions. E.g., set up these input fields for admins, these for editors, etc. That would allow much more control over everything. It would be a big change, though. Break some backwards compatibility, for sure.

**Comment by paaljoachim** [comment]
This is what I see.

1- I go to Settings -> Input.
2- Turn off Categories, Location Fields and Location Selector.
3- Add Event. Notice the Categories, Location Fields and Location Selector is gone.
All without doing anything in the Screen Options.

So it seems that you have done something so that we do not need to any longer make adjustments in the Screen Options for it to take affect.

**Comment by joedolson** [comment]
For now, I'm going to call this closed. I find the idea of re-mapping input permissions to be role-based, but I'm not going to do that for this release.
