### ISSUE TITLE
Event Occurrence: Removing a specific occurrence

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#88]
Let's say I have added three occurrences.
I do not want to delete the last occurrence but I want to delete the first.

The way this is setup I have to delete Occurrence 3, and then Occurrence 2 to get to Occurrence 1.

![Screen Shot 2021-07-10 at 21 13 01](https://user-images.githubusercontent.com/5323259/125174185-d696a000-e1c3-11eb-8a6a-71e9dc81312d.png)

Here is an example of adding a method so the user can remove the exact occurrence they want.
I added the word Remove all the way to the right on the Event Occurrence title row.

![Event-Occurrence-Remove-button](https://user-images.githubusercontent.com/5323259/125174397-8a4c5f80-e1c5-11eb-80f3-e003a13716c1.jpg)

**Comment by paaljoachim** [comment]
Associated issue: 
Date and Time: Related Events: (Edit group)
https://github.com/joedolson/my-calendar/issues/89

From earlier times I noticed the word Delete was used. I will suggest we stick to using either Remove or Delete.
So my example above shows Remove. We could instead change the word to Delete.

**Comment by paaljoachim** [comment]
Associated issue: 
Date and Time: Related Events: (Edit group)
https://github.com/joedolson/my-calendar/issues/89

From earlier times I noticed the word Delete was used. I will suggest we stick to using either Remove or Delete.
So my example above shows Remove. We could instead change the word to Delete.

**Comment by joedolson** [comment]
That's a pretty reasonable change. Technically, you could just delete the last one and change the dates on the first one, but it's probably more user-friendly to be able to remove any of the set of new occurrences. This should be a pretty minor bit of JavaScript to change, so it's probably feasible in this release.

**Comment by paaljoachim** [comment]
This looks nice:

![Screen Shot 2021-07-16 at 13 21 57](https://user-images.githubusercontent.com/5323259/125940200-957ffe64-f70c-4242-b2c1-b877b09a858f.png)

It gives a lot more control over each Event Occurrence. I thought came up as to showing a square around each date for the dates.... I will add a new issue for this.
