### ISSUE TITLE
Date and Time: Related Events: (Edit group)

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#89]
From the documentation we see this:

![Screen Shot 2021-07-10 at 21 36 14](https://user-images.githubusercontent.com/5323259/125174623-fc717400-e1c6-11eb-92aa-875789ffa6cd.png)

Dates and times are aligned on top of each other. There is also a Delete button present.

Comparing to what it currently looks like:

![Related-Events-current](https://user-images.githubusercontent.com/5323259/125174656-3e021f00-e1c7-11eb-8461-c6211d2c1f09.jpg)

Even though there is a link to Edit group (My mistake I thought that clicking Edit group would do something else then clicking Related Events). Having some quick edit options here would be helpful.
Perhaps something like this:

![Related-Occurrence-Edit-Delete](https://user-images.githubusercontent.com/5323259/125174883-a0a7ea80-e1c8-11eb-8efe-7ef1d7ffc9d5.jpg)

**Comment by paaljoachim** [comment]
What is missing from my suggestion is a method to add a new occurrence.
Going to any of the Occurrences one should have a way to also add another occurrence. 
Perhaps something like this:

![Related-Occurrence-Edit-Delete-ver2](https://user-images.githubusercontent.com/5323259/125175218-ee255700-e1ca-11eb-80ed-d3da7669e91e.jpg)

**Comment by joedolson** [comment]
You're actually comparing two different features here; related events are about groups of events, each of which is a full event and can be edited independently; scheduled dates is about recurring events, where each date is an event stub, and cannot be edited independently of the full event.

**Comment by paaljoachim** [comment]
I suddenly noticed last night that I was mixing as one says apples and oranges....
I do have some ideas about Related Events and Scheduled events. Which I will get back to.
I am still looking at some of the logic used in both.

**Comment by paaljoachim** [comment]
I will close this and go through the Scheduled and Related Events etc a few more times and create a few new issues.
