### ISSUE TITLE
Taking a closer look at the Mini Widget Calendar

### ISSUE THREAD

**Issue by paaljoachim** [joedolson/my-calendar#94]
WP 5.8 RC 4.
Gutenberg plugin 11.0.0
Theme: Twenty Twenty One. 

Appearance -> (new) Widgets screen.

The Mini Widget Calendar has currently these options:

![Mini-Calendar-Widget](https://user-images.githubusercontent.com/5323259/125944899-7d50fd30-ecd6-453f-8aa4-026e107b6d96.jpg)

Listing these up:
Title
Widget Title Link (where would this go to?)
Category or categories to display? (Should there be a list of categories to choose from? Perhaps show the names below the text field in a row so the user can click a name and have it added into the text field box?)
Navigation above calendar
Navigation below calendar

Limit by Author (Should this be a drop down?)
Limit by Host (Should this also be a drop down?)

Location (Type) - drop down -
Location (Value) (What about listing locations below the text field? User clicks a location name and it is added to the text field.)
Mini-Calendar Timespan - drop down -
Months to show in list view: - number field -

Clicking outside of the calendar shows an automatic preview.
This is currently what I see.

![Screen Shot 2021-07-16 at 14 05 36](https://user-images.githubusercontent.com/5323259/125945914-9e4437e9-1322-4f23-9dc8-b483767e1780.png)

This is what it looks like on the frontend:

![Screen Shot 2021-07-16 at 14 24 41](https://user-images.githubusercontent.com/5323259/125947013-551f8a5f-fa8f-4a6e-bd61-fb9541ed84ce.png)

Jump and nav was added above the below the calendar as can be seen.
I am wondering how we can clean up Print, Categories, RSS, Google, Outlook, Google and Outlook.

-------

I assume we should move the options listed in the following issue directly into the Mini Calendar Widget.
Associated issue: 
What is this? Mini calendar widget date links to: 
https://github.com/joedolson/my-calendar/issues/53

<img width="794" alt="Screen Shot 2021-07-16 at 14 28 25" src="https://user-images.githubusercontent.com/5323259/125947696-230926b5-a493-4a6a-9ba3-4acd4e4d9b29.png">

**Comment by joedolson** [comment]
That's a lot of separate questions:

> Widget Title Link (where would this go to?)

Probably to the calendar, but it can point anywhere the user wants.

> Category or categories to display? (Should there be a list of categories to choose from? Perhaps show the names below the text field in a row so the user can click a name and have it added into the text field box?)

Generating a category list is reasonable, yes. For simplicity of initial implementation, I'd probably use a multiselect to start.

> Limit by Author (Should this be a drop down?)
> Limit by Host (Should this also be a drop down?)

Both of these are already dropdowns. 

> Location (Value) (What about listing locations below the text field? User clicks a location name and it is added to the text field.)

Not trivial. I have clients who have up to 40,000 locations in their databases. That would be fine with a small number of locations, but is not an option for larger sites. User lists have similar problems, but are controlled for users that have permissions, which helps cut that down.

**Comment by paaljoachim** [comment]
So the only actionable step in this issue (In addition to the drop down bug I just reported in #102 )
could be a multiselect for categories.

**Comment by paaljoachim** [comment]
From what I see Categories to display has been added.
It is very helpful to be able to click a checkbox which categories to include in the Mini Calendar.

This is what I see:
![Screen Shot 2021-07-31 at 14 09 09](https://user-images.githubusercontent.com/5323259/127739420-676ace7e-b599-4a03-8816-400e9cfbf0a9.jpg)
